Repository openshift/microshift, pull requests merged in 2021-06, with the labels that each got.

#116 Update OWNERS to be valid YAML
  OWNERS
Labels: needs-ok-to-test

#119 refactor containerized microshift build
  Makefile
  images/build/Dockerfile
Labels: approved, lgtm

#120 Get latest release version to download
  install.sh
Labels: approved

#115 add instructions to build all-in-one containerized microshift
  hack/all-in-one/.gitignore
  hack/all-in-one/Dockerfile
  hack/all-in-one/README.md
  hack/all-in-one/unit
Labels: approved

#121 Fix issue #117
  install.sh
Labels: approved

#124 clean up and address review feedback
  hack/all-in-one/Dockerfile
  hack/all-in-one/README.md
  pkg/config/kubelet.go
  pkg/node/kubelet.go
Labels: approved

#122 enable containerized microshift on MacOS
  hack/all-in-one/Dockerfile
  hack/all-in-one/README.md
  hack/all-in-one/kubelet-cgroups.conf
  pkg/config/kubelet.go
Labels: approved

#126 add macos host based command
  hack/all-in-one/README.md
Labels: approved

#128 initial entries
  install.sh
Labels: approved, lgtm

#130 Add v-level logging, pass to K8s components
  cmd/microshift/main.go
  pkg/cmd/controller.go
  pkg/config/config.go
  pkg/controllers/kube-api.go
  pkg/controllers/kube-controller-manager.go
  pkg/controllers/kube-scheduler.go
  pkg/controllers/ocp-controllers.go
  pkg/node/kubelet.go
Labels: approved, lgtm

#135 add windows instructions
  hack/all-in-one/README.md
Labels: approved
