Repository openshift/microshift, pull requests merged in 2021-12, with the labels that each got.

#435 fix aio build to support arm64 on rhel7 and Jetson
  hack/all-in-one/Dockerfile
  hack/all-in-one/build-images.sh
Labels: lgtm

#481 Add oc client binary to microshift-aio, set KUBECONFIG
  packaging/images/microshift-aio/Dockerfile
Labels: lgtm, approved

#484 fix for failed to get system container stats errors
  pkg/node/kubelet.go
Labels: lgtm, approved

#491 download path for cri-o repos has changed, update Dockerfile
  packaging/images/microshift-aio/Dockerfile
Labels: lgtm

#305 Embed git tags, commit ID and tree status in srpm
  Makefile
  packaging/rpm/make-rpm.sh
  packaging/rpm/microshift.spec
Labels: lgtm, needs-ok-to-test, approved

#497 Add debug flags when building MicroShift
  Makefile
Labels: lgtm, approved

#504 move service-ca volumes to cm,secret
  assets/apps/0000_60_service-ca_05_deploy.yaml
  assets/core/0000_60_service-ca_04_configmap.yaml
  assets/core/0000_60_service-ca_04_secret.yaml
  pkg/assets/apps/bindata.go
  pkg/assets/core.go
  pkg/assets/core/bindata.go
  pkg/components/controllers.go
  pkg/components/render.go
Labels: lgtm, approved

#503 move kuttl cmds to script for reuse in CI
  .github/workflows/ubuntu.yaml
  Makefile
  validate-microshift/.gitignore
  validate-microshift/kuttl-test.sh
Labels: lgtm, approved

#490 scc,clusterquota CRD remove 'nullable: true' fields from required and add shortNames
  assets/crd/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml
  assets/crd/0000_03_security-openshift_01_scc.crd.yaml
  pkg/assets/crd/bindata.go
Labels: lgtm, approved

#496 ocp components simplify,clarify names
  pkg/cmd/run.go
  pkg/components/controllers.go
  pkg/components/render.go
  pkg/controllers/apiservice.go
  pkg/controllers/infra-services-controller.go
  pkg/controllers/openshift-apiserver.go
  pkg/controllers/openshift-controller-manager.go
  pkg/controllers/openshift-crd-manager.go
  pkg/controllers/openshift-default-scc-manager.go
  pkg/mdns/controller.go
  pkg/mdns/routes.go
Labels: lgtm, approved

#506 adds GH Action + unit-tests
  .github/workflows/testing.yaml
  pkg/config/config_test.go
  test/config.yaml
Labels: lgtm, approved, ok-to-test

#510 Disable ubuntu ci job
  .github/workflows/ubuntu.yaml
Labels: lgtm, approved

#511 no longer require glibc-static
  packaging/rpm/microshift.spec
Labels: lgtm, approved

#456 Update OWNERS
  OWNERS
Labels: lgtm, approved

#512 microshift-aio image builds: bump oc download in aio image for aarch64 binary
  packaging/images/microshift-aio/Dockerfile
Labels: lgtm, approved

#514 Fix ocp cm namespace
  pkg/controllers/openshift-controller-manager.go
Labels: lgtm, approved

#507 Remove stray log messages
  pkg/controllers/kube-controller-manager.go
  pkg/controllers/kube-scheduler.go
  pkg/controllers/openshift-controller-manager.go
  pkg/controllers/openshift-oauth-server.go
  pkg/node/kube-proxy.go
  pkg/node/kubelet.go
Labels: lgtm, approved

#499 Reload existing CA from disk on restart
  pkg/cmd/init.go
  pkg/cmd/run.go
  pkg/util/cert.go
Labels: lgtm, approved

#525 spec req iptables
  packaging/crio.conf.d/microshift.conf
  packaging/rpm/microshift.spec
Labels: lgtm, approved

#524 Revert "Revert "Reload existing CA from disk on restart""
  pkg/cmd/init.go
  pkg/cmd/run.go
  pkg/util/cert.go
Labels: lgtm

#527 missing persistent volume mount
  packaging/systemd/microshift-containerized.service
Labels: lgtm, approved

#523 selinux create directories
  packaging/rpm/microshift.spec
Labels: lgtm, approved

#530 Support crio.networks in rhel8 properly
  packaging/crio.conf.d/microshift.conf
Labels: approved

#531 directory is required to exist
  packaging/systemd/microshift-containerized.service
Labels: lgtm, approved

#520 more testing
  validate-microshift/e2e/microshift/45-create-resources.sh
  validate-microshift/e2e/microshift/45-create-resources.yaml
  validate-microshift/e2e/microshift/50-assert-deployment.yaml
  validate-microshift/e2e/microshift/55-assert-svc.yaml
  validate-microshift/e2e/microshift/60-assert-pvc.yaml
Labels: lgtm, approved
