Repository openshift/microshift, pull requests merged in 2021-09, with the labels that each got.

#242 retrieve platform specific microshift binary from release repo
  hack/all-in-one/Dockerfile
Labels: lgtm

#246 Adds minimum requirements
  CONTRIBUTING.md
  README.md
Labels: lgtm, approved, ok-to-test

#248 fix crio sock deprecation warning
  pkg/node/kubelet.go
Labels: lgtm, needs-ok-to-test, approved

#228 set selinux always
  install.sh
Labels: lgtm, approved

#253 only verify project code
  Makefile
Labels: lgtm, approved

#251 Print base OKD version
  pkg/cmd/version.go
Labels: lgtm, approved

#255 Remove IPv6 CNI config
  install.sh
Labels: lgtm, approved

#234 Add script for rebasing onto later OKD version
  scripts/rebase.sh
Labels: lgtm, approved

#258 Add e2e demo video link to README
  README.md
Labels: lgtm, approved

#217 Refactor Kubelet to conform to the internal service manager
  pkg/cmd/run.go
  pkg/config/kubelet.go
  pkg/node/kubelet.go
Labels: lgtm

#241 kube-proxy conforms to internal service manager
  pkg/cmd/run.go
  pkg/node/kubelet.go
Labels: lgtm, approved

#265 Make hostname validation show warning and not stop installation
  install.sh
Labels: lgtm, approved, ok-to-test

#262 initial commit of selinux
  selinux/microshift.fc
  selinux/microshift.if
  selinux/microshift.te
Labels: lgtm, approved

#269 build and enable selinux
  install.sh
Labels: lgtm, approved, ok-to-test

#256 Tag latest
  scripts/release.sh
Labels: lgtm, approved

#267 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: lgtm, approved, ok-to-test

#271 Support Ubuntu for install.sh
  install.sh
Labels: approved, ok-to-test

#218 Add design documentation
  docs/design/design.md
Labels: approved

#274 Adds minimum requirements for README.md
  README.md
Labels: lgtm, needs-ok-to-test, approved

#275 Community info
  README.md
Labels: lgtm

#268 build both cuda and ubi aio images
  hack/all-in-one/Dockerfile
  hack/all-in-one/build-images.sh
Labels: lgtm, approved

#280 removal of selinux warning
  README.md
Labels: lgtm

#281 Remove CNI IPv6 configuration and use right conmon binary for AIO container images
  hack/all-in-one/Dockerfile
  hack/all-in-one/crio-bridge.conf
Labels: lgtm, approved

#282 add known issue doc for running on EC2 RHEL
  README.md
  docs/known-issues.md
Labels: lgtm, needs-ok-to-test, approved

#284 update install command to use bash
  README.md
Labels: lgtm, needs-ok-to-test, approved

#288 Create initial spec for RPM packaging
  Makefile
  microshift.spec
  systemd/microshift.service
Labels: lgtm, needs-ok-to-test, approved

#289 respect the config.Cluster.ServiceCIDR when signing certs
  pkg/cmd/init.go
Labels: approved, ok-to-test

#291 Create RPM SELinux sub-module
  microshift.spec
  selinux/Makefile
  selinux/microshift.fc
Labels: lgtm, needs-ok-to-test, approved

#292 add fully aio systemd unit file and script
  hack/all-in-one/README.md
  hack/all-in-one/microshift-aio-run
  hack/all-in-one/microshift-aio.service
Labels: lgtm

#294 typo-aio-readme
  hack/all-in-one/README.md
Labels: approved

#295 add sudo to podman to avoid rootless
  hack/all-in-one/README.md
  hack/all-in-one/microshift-aio-run
Labels: lgtm, approved

#297 update known issue for flannel issue on ec2
  docs/known-issues.md
Labels: needs-ok-to-test

#287 add arm64 support to the install script
  install.sh
Labels: lgtm, approved, ok-to-test

#301 Workaround rpmbuild with no --build-in-place support
  Makefile
  rpm/make-rpm.sh
  rpm/microshift.service
  rpm/microshift.spec
Labels: lgtm, needs-ok-to-test, approved

#299 typo in microshift-aio container name on ExecStop
  hack/all-in-one/README.md
  hack/all-in-one/microshift-aio
  hack/all-in-one/microshift-aio.service
Labels: lgtm, approved

#309 Legacy and nft-tables based images matrix
  hack/all-in-one/Dockerfile
  hack/all-in-one/build-images.sh
Labels: ok-to-test

#306 Remove the --broke(n) git describe flag
  Makefile
Labels: lgtm, approved, ok-to-test

#312 Updates storage requirement to more accurately reflect binary size
  README.md
Labels: lgtm, needs-ok-to-test, approved

#311 Continue support for RHEL7
  hack/all-in-one/Dockerfile
  hack/all-in-one/build-images.sh
Labels: needs-ok-to-test, approved

#260 Refactor OCPControllerManager to conform to the internal service manager
  pkg/cmd/run.go
  pkg/controllers/ocp-controllers.go
  pkg/util/net.go
Labels: lgtm, approved, ok-to-test

#314 Add github action: "release
  .github/workflows/release.yaml
  Makefile
  scripts/release.sh
Labels: lgtm, approved

#315 update all-in-one systemd, use podman generated ExecStart|Stop
  hack/all-in-one/microshift-aio
  hack/all-in-one/microshift-aio.service
Labels: lgtm, approved

#317 Enable install.sh to run on multiple Ubuntu versions #285
  install.sh
Labels: lgtm, needs-ok-to-test
