Repository openshift/microshift, pull requests merged in 2021-11, with the labels that each got.

#404 update docs Makefile
  Makefile
  docs/Makefile
Labels: lgtm, approved

#410 rename service file to match service purpose
  docs/microshift-containerized/README.md
  packaging/systemd/microshift-containerized.service
Labels: lgtm, approved

#408 typo-make-docs
  Makefile
Labels: lgtm

#416 docs moved to `microshift-documentation`, remove `make docs-build,serve` target
  Makefile
Labels: lgtm

#411 Move docs to different repo
  .github/workflows/jekyll.yml
  Gemfile
  docs/CNAME
  docs/Gemfile
  docs/README.md
  docs/_config.yaml
  docs/_includes/metas-ogp.html
  docs/_layouts/default.html
  docs/_layouts/page.html
  docs/_layouts/post.html
  docs/_sass/fonts.scss
  docs/_sass/premonition.scss
  docs/_sass/rouge-github.scss
  docs/assets/css/style.scss
  docs/assets/fonts/Noto-Sans-700/Noto-Sans-700.eot
  docs/assets/fonts/Noto-Sans-700/Noto-Sans-700.svg
  docs/assets/fonts/Noto-Sans-700/Noto-Sans-700.ttf
  docs/assets/fonts/Noto-Sans-700/Noto-Sans-700.woff
  docs/assets/fonts/Noto-Sans-700/Noto-Sans-700.woff2
  docs/assets/fonts/Noto-Sans-700italic/Noto-Sans-700italic.eot
  docs/assets/fonts/Noto-Sans-700italic/Noto-Sans-700italic.svg
  docs/assets/fonts/Noto-Sans-700italic/Noto-Sans-700italic.ttf
  docs/assets/fonts/Noto-Sans-700italic/Noto-Sans-700italic.woff
  docs/assets/fonts/Noto-Sans-700italic/Noto-Sans-700italic.woff2
  docs/assets/fonts/Noto-Sans-italic/Noto-Sans-italic.eot
  docs/assets/fonts/Noto-Sans-italic/Noto-Sans-italic.svg
  docs/assets/fonts/Noto-Sans-italic/Noto-Sans-italic.ttf
  docs/assets/fonts/Noto-Sans-italic/Noto-Sans-italic.woff
  docs/assets/fonts/Noto-Sans-italic/Noto-Sans-italic.woff2
  docs/assets/fonts/Noto-Sans-regular/Noto-Sans-regular.eot
  docs/assets/fonts/Noto-Sans-regular/Noto-Sans-regular.svg
  docs/assets/fonts/Noto-Sans-regular/Noto-Sans-regular.ttf
  docs/assets/fonts/Noto-Sans-regular/Noto-Sans-regular.woff
  docs/assets/fonts/Noto-Sans-regular/Noto-Sans-regular.woff2
  docs/assets/js/scale.fix.js
  docs/design/.gitkeep
  docs/design/design.md
  docs/index.md
  docs/known-issues.md
  docs/microshift-aio/README.md
  docs/microshift-containerized/README.md
  docs/pics/remote-ssh-dropdown.png
  docs/pics/vscode-remote-button.png
Labels: lgtm, ok-to-test

#324 Refactor OCPAPIServer to conform to the internal service manager
  pkg/cmd/run.go
  pkg/controllers/infra-services-controller.go
  pkg/controllers/openshift-api-components-controller.go
  pkg/controllers/openshift-apiserver.go
  pkg/controllers/openshift-oauth-server.go
  pkg/controllers/openshift-prepjob-manager.go
Labels: lgtm, needs-ok-to-test, approved

#415 Pre-checks into install.sh
  install.sh
Labels: lgtm, approved, ok-to-test

#421 Cleanup and add containerized systemd services as part of the rpm
  packaging/rpm/microshift.spec
  packaging/systemd/microshift-aio.service
  packaging/systemd/microshift-containerized.service
  packaging/systemd/microshift.service
Labels: approved

#427 quick fix of readme
  README.md
Labels: lgtm, approved

#428 add host network
  packaging/systemd/microshift-containerized.service
Labels: lgtm, approved

#431 issue restorecon
  install.sh
Labels: lgtm, approved

#439 git ignore rpm artifacts
  .gitignore
Labels: lgtm, approved

#443 Update release.yaml
  .github/workflows/release.yaml
Labels: lgtm, approved

#257 Adds SecurePort parameterization
  README.md
  pkg/config/config.go
  pkg/controllers/kube-apiserver.go
Labels: lgtm, approved, ok-to-test

#448 link fix
  README.md
Labels: approved

#450 Restore design documentation (#218)
  docs/design/design.md
Labels: lgtm, approved

#447 Fix some nits on various scripts
  hack/all-in-one/build-aio-dev.sh
  hack/all-in-one/build-images.sh
  hack/verify.sh
  packaging/images/components/build.sh
  packaging/images/components/components/coredns/build_binaries
  packaging/images/components/components/flannel/build_binaries
  packaging/images/components/components/haproxy-router/build_binaries
  packaging/images/components/components/hostpath-provisioner/build_binaries
  packaging/images/components/components/kube-rbac-proxy/build_binaries
  packaging/images/components/components/pause/build_binaries
  packaging/images/components/components/service-ca-operator/build_binaries
  packaging/systemd/microshift-aio
  packaging/systemd/microshift-containerized
  scripts/bindata.sh
  scripts/release.sh
  scripts/tools.go
Labels: lgtm, ok-to-test

#462 fix flannel
  assets/apps/0000_00_flannel-daemonset.yaml
  assets/core/0000_00_flannel-configmap.yaml
  packaging/images/components/build.sh
  packaging/images/components/components/flannel-cni/Dockerfile
  packaging/images/components/components/flannel-cni/Dockerfile.riscv64
  packaging/images/components/components/flannel-cni/build_binaries
  packaging/images/components/components/flannel-cni/commit
  packaging/images/components/components/flannel-cni/repo
  pkg/assets/apps/bindata.go
  pkg/assets/core/bindata.go
  pkg/release/release.go
  pkg/release/release_amd64.go
Labels: lgtm, approved

#465 Add log directory to MicroShift config
  pkg/config/config.go
Labels: lgtm, approved

#464 resolves #454
  README.md
Labels: lgtm, approved

#468 Sometimes the cleanup script won't clean /var/lib/microshift
  hack/cleanup.sh
Labels: lgtm

#429 mDNS responder for microshift
  go.mod
  pkg/cmd/init.go
  pkg/cmd/run.go
  pkg/mdns/controller.go
  pkg/mdns/routes.go
  pkg/mdns/routes_test.go
  pkg/mdns/server/resolver.go
  pkg/mdns/server/resolver_test.go
  pkg/mdns/server/server.go
  pkg/mdns/server/server_test.go
  vendor/k8s.io/client-go/dynamic/dynamicinformer/informer.go
  vendor/k8s.io/client-go/dynamic/dynamicinformer/interface.go
  vendor/k8s.io/client-go/dynamic/dynamiclister/interface.go
  vendor/k8s.io/client-go/dynamic/dynamiclister/lister.go
  vendor/k8s.io/client-go/dynamic/dynamiclister/shim.go
  vendor/modules.txt
Labels: approved

#470 Aio image push
  Makefile
  scripts/release.sh
Labels: lgtm, approved

#467 fix: set cri-o version to 1.21
  install.sh
Labels: lgtm, ok-to-test

#452 update contributing doc
  CONTRIBUTING.md
Labels: lgtm, needs-ok-to-test, approved
