Repository openshift/microshift, pull requests merged in 2021-10, with the labels that each got.

#321 Remove usage of deprecated apt-key in install.sh #286
  install.sh
Labels: lgtm, needs-ok-to-test, approved

#318 drop static-build flags
  Makefile
Labels: lgtm, approved

#403 Updating K8s version to show the right one
  Makefile
Labels: lgtm, needs-ok-to-test
