Repository openshift/microshift, pull requests merged in 2021-07, with the labels that each got.

#143 Use ubi8-minimal instead of regular ubi8
  Dockerfile
  hack/all-in-one/Dockerfile
  images/build/Dockerfile
Labels: approved, lgtm, ok-to-test

#139 Enabling firewall requires sudo
  install.sh
Labels: approved, lgtm, needs-ok-to-test

#136 add release target and script
  Makefile
  hack/generate-versioninfo.sh
  images/build/Dockerfile
  scripts/release.sh
  scripts/release_config/rhel-ubi-minimal-8-4-arch-digests
Labels: approved, lgtm

#147 Check if subscribed and proper repos
  install.sh
Labels: approved, ok-to-test

#150 Handle podman divergence in cli commands, add checksum
  Makefile
  images/build/Dockerfile
  scripts/release.sh
Labels: approved, lgtm

#149 Update README.md
  README.md
Labels: approved

#154 Fix retrieval of VERSION
  install.sh
Labels: approved, lgtm

#153 Add framework for managing startup dependencies and shutdown
  pkg/cmd/controller.go
  pkg/cmd/init.go
  pkg/cmd/run.go
  pkg/controllers/etcd.go
  pkg/controllers/kube-api.go
  pkg/servicemanager/manager.go
  pkg/servicemanager/service.go
  pkg/servicemanager/type.go
  pkg/util/sigchannel/sigchannel.go
  pkg/util/util.go
Labels: approved, lgtm

#165 Improve test coverage
  pkg/servicemanager/manager.go
  pkg/servicemanager/manager_test.go
  pkg/util/sigchannel/sigchannel.go
  pkg/util/sigchannel/sigchannel_test.go
Labels: approved, lgtm

#169 Fix high CPU load issue
  pkg/util/sigchannel/sigchannel.go
Labels: approved, lgtm

#173 Simplify CPU load fix
  pkg/util/sigchannel/sigchannel.go
Labels: approved, lgtm

#177 adding validation check function for hostname
  install.sh
Labels: approved, lgtm, needs-ok-to-test

#178 Use k8s compliant build date
  Makefile
  images/build/Dockerfile
Labels: approved, lgtm

#183 fix version scheme
  Makefile
Labels: approved, lgtm

#180 unify service account key and signing keys
  pkg/cmd/init.go
  pkg/controllers/kube-api.go
Labels: approved, lgtm

#182 rule for cidr
  install.sh
Labels: approved
