Repository openshift/microshift, pull requests merged in 2021-08, with the labels that each got.

#157 add PR and issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement-tracking.md
  .github/PULL_REQUEST_TEMPLATE.md
  docs/design/.gitkeep
Labels: approved, lgtm

#190 Initialize also with pre-existing data dir
  pkg/cmd/run.go
Labels: approved, lgtm

#187 Add env config script for use in CI
  README.md
  install.sh
Labels: approved

#194 release tag should not have git-dirty data
  Makefile
Labels: approved, lgtm

#195 fix release.sh bug
  Makefile
  scripts/release.sh
Labels: approved, lgtm

#193 set hostpath version
  assets/apps/000_80_hostpath-provisioner-daemonset.yaml
Labels: lgtm

#197 fixed git org naming
  scripts/release.sh
Labels: lgtm

#202 Add service to apply kustomizations
  pkg/cmd/run.go
  pkg/kustomize/apply.go
  vendor/github.com/chai2010/gettext-go/LICENSE
  vendor/github.com/chai2010/gettext-go/gettext/caller.go
  vendor/github.com/chai2010/gettext-go/gettext/doc.go
  vendor/github.com/chai2010/gettext-go/gettext/domain.go
  vendor/github.com/chai2010/gettext-go/gettext/domain_helper.go
  vendor/github.com/chai2010/gettext-go/gettext/fs.go
  vendor/github.com/chai2010/gettext-go/gettext/gettext.go
  vendor/github.com/chai2010/gettext-go/gettext/local.go
  vendor/github.com/chai2010/gettext-go/gettext/mo/doc.go
  vendor/github.com/chai2010/gettext-go/gettext/mo/encoder.go
  vendor/github.com/chai2010/gettext-go/gettext/mo/file.go
  vendor/github.com/chai2010/gettext-go/gettext/mo/header.go
  vendor/github.com/chai2010/gettext-go/gettext/mo/message.go
  vendor/github.com/chai2010/gettext-go/gettext/mo/util.go
  vendor/github.com/chai2010/gettext-go/gettext/plural/doc.go
  vendor/github.com/chai2010/gettext-go/gettext/plural/formula.go
  vendor/github.com/chai2010/gettext-go/gettext/plural/table.go
  vendor/github.com/chai2010/gettext-go/gettext/po/comment.go
  vendor/github.com/chai2010/gettext-go/gettext/po/doc.go
  vendor/github.com/chai2010/gettext-go/gettext/po/file.go
  vendor/github.com/chai2010/gettext-go/gettext/po/header.go
  vendor/github.com/chai2010/gettext-go/gettext/po/line_reader.go
  vendor/github.com/chai2010/gettext-go/gettext/po/message.go
  vendor/github.com/chai2010/gettext-go/gettext/po/re.go
  vendor/github.com/chai2010/gettext-go/gettext/po/util.go
  vendor/github.com/chai2010/gettext-go/gettext/tr.go
  vendor/k8s.io/apimachinery/pkg/util/jsonmergepatch/patch.go
  vendor/k8s.io/kubectl/pkg/cmd/apply/apply.go
  vendor/k8s.io/kubectl/pkg/cmd/apply/apply_edit_last_applied.go
  vendor/k8s.io/kubectl/pkg/cmd/apply/apply_set_last_applied.go
  vendor/k8s.io/kubectl/pkg/cmd/apply/apply_view_last_applied.go
  vendor/k8s.io/kubectl/pkg/cmd/apply/patcher.go
  vendor/k8s.io/kubectl/pkg/cmd/apply/prune.go
  vendor/k8s.io/kubectl/pkg/cmd/delete/delete.go
  vendor/k8s.io/kubectl/pkg/cmd/delete/delete_flags.go
  vendor/k8s.io/kubectl/pkg/cmd/util/editor/crlf/crlf.go
  vendor/k8s.io/kubectl/pkg/cmd/util/editor/editoptions.go
  vendor/k8s.io/kubectl/pkg/cmd/util/editor/editor.go
  vendor/k8s.io/kubectl/pkg/cmd/wait/wait.go
  vendor/k8s.io/kubectl/pkg/generated/bindata.go
  vendor/k8s.io/kubectl/pkg/rawhttp/raw.go
  vendor/k8s.io/kubectl/pkg/util/apply.go
  vendor/k8s.io/kubectl/pkg/util/i18n/i18n.go
  vendor/k8s.io/kubectl/pkg/util/pod_port.go
  vendor/k8s.io/kubectl/pkg/util/service_port.go
  vendor/k8s.io/kubectl/pkg/util/umask.go
  vendor/k8s.io/kubectl/pkg/util/umask_windows.go
  vendor/k8s.io/kubectl/pkg/util/util.go
Labels: lgtm, approved

#206 fixes binary checksum validation and binary naming in releases
  install.sh
  scripts/release.sh
Labels: lgtm, approved

#207 Kube-scheduler porting to the service manager framework
  hack/patches/0003_d8e4c.patch
  hack/patches/0004_ccdbe.patch
  pkg/cmd/run.go
  pkg/controllers/kube-scheduler.go
  pkg/util/net.go
  vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go
Labels: lgtm, approved

#214 check CTR_CMD in containerized build
  Makefile
Labels: lgtm, approved

#215 Add crio dependency on systemd services
  hack/all-in-one/unit
  install.sh
Labels: lgtm, approved, ok-to-test

#216 Rename Host.* variables to Node.*
  pkg/cmd/init.go
  pkg/config/config.go
  pkg/config/kubelet.go
  pkg/controllers/etcd.go
  pkg/controllers/kube-controller-manager.go
  pkg/node/kubelet.go
Labels: approved, ok-to-test

#220 Use systemd resolv.conf in case it exists
  pkg/config/kubelet.go
Labels: approved, ok-to-test

#231 delete orphaned dockerfile
  Dockerfile
  images/build/Dockerfile
Labels: lgtm, approved

#235 patch build dockerfile
  images/build/Dockerfile
Labels: lgtm, approved
