Repository openshift/microshift, pull requests merged in 2022-10, with the labels that each got.

#986 Fix wait-for-pods command in performance test scripts
  ansible/roles/common/tasks/readinesscheck.yml
Labels: lgtm, approved

#987 Document error messages generated when unsupported APIs are used in the oc CLI
  README.md
  docs/enable_apis.md
  docs/enabled_apis.md
Labels: lgtm, approved

#991 USHIFT-328: Fix and document automatic manifest apply on startup
  docs/howto_config.md
  pkg/config/config.go
  pkg/kustomize/apply.go
Labels: lgtm, approved

#990 USHIFT-445: Add prometheus exporter for RHEL4EDGE
  scripts/image-builder/build.sh
Labels: lgtm, approved

#993 Reorg rebase scripts into subdir
  Makefile
  docs/rebase.md
  scripts/auto-rebase/create_pr.py
  scripts/auto-rebase/rebase.sh
  scripts/auto-rebase/rebase_patches/.gitkeep
  scripts/auto-rebase/rebase_patches/0001-Fix-CSI-initialization-conflict.patch
  scripts/auto-rebase/rebase_patches/0002-disable-APIrequestcount-controller.patch
  scripts/auto-rebase/rebase_patches/0010-kube-apiserver-command-context.patch
  scripts/auto-rebase/rebase_patches/0020-klog-component-names.patch
Labels: lgtm, approved

#994 USHIFT-442: Refactor logging exporters installation and update docs
  ansible/README.md
  ansible/inventory/inventory
  ansible/roles/common/tasks/readinesscheck.yml
  ansible/roles/install-logging-exporters/defaults/main.yml
  ansible/roles/install-logging-exporters/tasks/main.yml
  ansible/roles/install-logging-exporters/templates/cadvisor.service.j2
  ansible/roles/install-microshift/tasks/main.yml
  ansible/roles/manage-repos/tasks/main.yml
  ansible/roles/microshift-start/tasks/main.yml
  ansible/roles/setup-microshift-host/defaults/main.yml
  ansible/roles/setup-microshift-host/tasks/main.yml
  ansible/run-perf.yml
  ansible/setup-node.yml
  ansible/vars/all.yml
Labels: lgtm, approved

#997 USHIFT-449: Fix auto-apply for manifests to run in a non-default namespace
  docs/howto_config.md
Labels: lgtm, approved

#998 USHIFT-450: Fix namespace deletion
  assets/crd/authorizationv1-local-apiservice.yaml
  pkg/assets/bindata.go
  pkg/assets/crd.go
Labels: lgtm, approved

#1000 upgrade topolvm
  pkg/release/release_amd64.go
Labels: lgtm, approved

#995 API-1437: Enable kube-apiserver option send-retry-after-while-not-ready-once
  pkg/controllers/kube-apiserver.go
Labels: lgtm, approved

#1003 Fix 4.12 nightly rebase
  go.mod
  vendor/modules.txt
Labels: lgtm, approved

#1001 USHIFT-327: Update documentation with the supported configuration options
  docs/howto_config.md
  pkg/config/config_test.go
Labels: lgtm, approved

#883 Add csi node user-facing configuration
  assets/components/odf-lvm/topolvm-lvmd-config_configmap_v1.yaml
  assets/components/odf-lvm/topolvm-node_daemonset.yaml
  docs/default_csi_plugin.md
  pkg/assets/bindata.go
  pkg/components/components.go
  pkg/components/render.go
  pkg/components/render_test.go
  pkg/components/storage.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/lvmd/lvmd.go
  pkg/config/lvmd/lvmd_test.go
  pkg/config/lvmd/test/lvmd.yaml
  pkg/config/lvmd/types.go
Labels: kind/feature, lgtm, approved

#967 Switch to ovnk local gateway mode
  assets/components/ovn/configmap.yaml
  assets/components/ovn/master/daemonset.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#1013 USHIFT-461: Add PSA clusterrole and clusterrolebinding
  assets/core/podsecurity-admission-label-syncer-controller-clusterrole.yaml
  assets/core/podsecurity-admission-label-syncer-controller-clusterrolebinding.yaml
  pkg/assets/bindata.go
  pkg/controllers/infra-services-controller.go
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved

#1009 Improve create_pr.py with branch-off commit logic
  scripts/auto-rebase/create_pr.py
Labels: lgtm, approved

#1015 scripts/image-builder/configure.sh: Add rpm-build to package list
  scripts/image-builder/configure.sh
Labels: lgtm, approved

#1006 USHIFT-452: Update docs to 4.12 pre
  docs/devenv_rhel8.md
  docs/rhel4edge_iso.md
  scripts/devenv-builder/configure-vm.sh
  scripts/image-builder/build.sh
Labels: lgtm, approved

#1002 USHIFT-457: use cli.Run for executing boilerplate and initializing logs
  cmd/microshift/main.go
  pkg/config/config.go
  pkg/config/config_test.go
  vendor/k8s.io/component-base/cli/OWNERS
  vendor/k8s.io/component-base/cli/run.go
  vendor/modules.txt
Labels: lgtm, approved

#996 USHIFT-313: Refactor microshift-start standalone role
  ansible/README.md
  ansible/roles/common/tasks/disk.yml
  ansible/roles/common/tasks/readinesscheck.yml
  ansible/roles/install-logging/defaults/main.yml
  ansible/roles/install-logging/tasks/main.yml
  ansible/roles/install-microshift/tasks/main.yml
  ansible/roles/microshift-start/defaults/main.yml
  ansible/roles/microshift-start/tasks/main.yml
  ansible/run-perf.yml
  ansible/vars/all.yml
Labels: lgtm, approved

#1017 Revert "microshift: compact ovn databases periodically"
  assets/components/ovn/master/daemonset.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#1014 USHIFT-459: Add hostport to ingress
  assets/components/openshift-router/deployment.yaml
  assets/core/0000_50_cluster-openshift-controller-manager_00_namespace.yaml
  pkg/assets/bindata.go
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved

#1022 Fix iso image path in rhel4edge doc
  docs/rhel4edge_iso.md
Labels: lgtm, approved

#1024 docs/devenv_rhel8.md: fix typo (PRM => RPM)
  docs/devenv_rhel8.md
Labels: lgtm, approved

#1020 USHIFT-484: Fix template data ref
  assets/components/odf-lvm/topolvm-node_daemonset.yaml
  pkg/assets/bindata.go
  pkg/components/render.go
  pkg/components/render_test.go
Labels: lgtm, approved

#1034 USHIFT-494: go1.18
  ansible/roles/setup-microshift-host/defaults/main.yml
  ansible/roles/setup-microshift-host/tasks/main.yml
  docs/devenv_rhel8.md
  go.mod
  packaging/rpm/microshift.spec
  scripts/devenv-builder/configure-vm.sh
  scripts/devenv-builder/create-vm.sh
Labels: lgtm, approved

#1027 USHIFT-497: update pause image to registry.k8s.io
  docs/howto_config.md
  pkg/release/release_amd64.go
  pkg/release/release_arm64.go
Labels: lgtm, approved

#1045 USHIFT-492: Document getting-started procedure from microshift-testing copr repo
  README.md
  docs/config/microshift-starter.ks
  docs/getting_started.md
Labels: lgtm, approved

#1042 USHIFT-205: Add an option for embedding containers using Image Builder
  docs/rhel4edge_iso.md
  hack/osbuild2copr.sh
  scripts/image-builder/build.sh
  scripts/image-builder/config/ostree-copr.toml
  scripts/image-builder/configure.sh
Labels: lgtm, approved

#1039 Update pause image to registry.k8s.io
  docs/howto_config.md
  pkg/release/release_amd64.go
  pkg/release/release_arm64.go
Labels: approved

#1044 update create-vm.sh to support shared systems
  scripts/devenv-builder/create-vm.sh
Labels: lgtm, approved

#1047 USHIFT-492: Use openshift-client-linux-4.12.0-ec.4 for getting started environment
  docs/config/microshift-starter.ks
Labels: lgtm, approved

#1049 Fix connectivity issue to NodePorts and router hostPort
  assets/components/ovn/master/daemonset.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#1048 Fix connectivity issue to NodePorts and router hostPort
  assets/components/ovn/master/daemonset.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#1010 go-bindata -> go:embed
  Makefile
  assets/bindata_timestamp.txt
  assets/embed.go
  go.mod
  go.sum
  pkg/assets/apps.go
  pkg/assets/core.go
  pkg/assets/crd.go
  pkg/assets/rbac.go
  pkg/assets/scc.go
  pkg/assets/storage.go
  pkg/components/controllers.go
  pkg/components/networking.go
  pkg/components/storage.go
  pkg/controllers/infra-services-controller.go
  pkg/controllers/kube-apiserver.go
  pkg/controllers/kube-controller-manager.go
  pkg/controllers/openshift-default-scc-manager.go
  pkg/controllers/openshift-route-controller-manager.go
  pkg/controllers/version.go
  scripts/auto-rebase/rebase.sh
  scripts/bindata.sh
  scripts/tools.go
  scripts/verify_bindata.sh
  vendor/github.com/go-bindata/go-bindata/.gitignore
  vendor/github.com/go-bindata/go-bindata/CONTRIBUTING.md
  vendor/github.com/go-bindata/go-bindata/LICENSE
  vendor/github.com/go-bindata/go-bindata/Makefile
  vendor/github.com/go-bindata/go-bindata/README.md
  vendor/github.com/go-bindata/go-bindata/_config.yml
  vendor/github.com/go-bindata/go-bindata/asset.go
  vendor/github.com/go-bindata/go-bindata/bytewriter.go
  vendor/github.com/go-bindata/go-bindata/config.go
  vendor/github.com/go-bindata/go-bindata/convert.go
  vendor/github.com/go-bindata/go-bindata/debug.go
  vendor/github.com/go-bindata/go-bindata/doc.go
  vendor/github.com/go-bindata/go-bindata/file.go
  vendor/github.com/go-bindata/go-bindata/go-bindata/.gitignore
  vendor/github.com/go-bindata/go-bindata/go-bindata/AppendSliceValue.go
  vendor/github.com/go-bindata/go-bindata/go-bindata/main.go
  vendor/github.com/go-bindata/go-bindata/go-bindata/version.go
  vendor/github.com/go-bindata/go-bindata/release.go
  vendor/github.com/go-bindata/go-bindata/restore.go
  vendor/github.com/go-bindata/go-bindata/stringwriter.go
  vendor/github.com/go-bindata/go-bindata/toc.go
  vendor/modules.txt
Labels: lgtm, approved

#981 AUTH-296: generate kubelet certs properly
  pkg/cmd/init.go
  pkg/cmd/run.go
  pkg/controllers/kube-apiserver.go
  pkg/node/kubelet.go
  pkg/util/cryptomaterial/certpaths.go
Labels: lgtm, approved

#1018 packaging/systemd/configure-ovs.sh: Add tun device support
  packaging/systemd/configure-ovs.sh
Labels: lgtm, approved

#1046 USHIFT-499: Replace k8s pause image with openshift pod image
  packaging/crio.conf.d/microshift_amd64.conf
  packaging/crio.conf.d/microshift_arm64.conf
  packaging/rpm/microshift.spec
  pkg/release/release.go
  pkg/release/release_amd64.go
  pkg/release/release_arm64.go
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved

#1052 USHIFT-205: Clean osbuild-composer cache when switching versions
  hack/osbuild2copr.sh
  scripts/image-builder/configure.sh
Labels: lgtm, approved

#1053 USHIFT-506: Remove pkg/assets/bindata.go
  pkg/assets/bindata.go
  pkg/components/render_test.go
Labels: lgtm, approved

#975 AUTH-296: work out etcd certificates
  .image_references
  pkg/cmd/init.go
  pkg/controllers/etcd.go
  pkg/controllers/kube-apiserver.go
  pkg/util/cryptomaterial/certpaths.go
  pkg/util/cryptomaterial/signers.go
Labels: lgtm, approved

#1051 API-1449: Enable kube-apiserver audit logging.
  pkg/cmd/run.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/controllers/kube-apiserver.go
Labels: lgtm, approved

#1056 USHIFT-510: Clean up references to removed auditLogDir option.
  docs/howto_config.md
  packaging/microshift/config.yaml
  test/config.yaml
Labels: lgtm, approved

#1057 fixes link from Getting Started doc to r4e install doc
  docs/getting_started.md
Labels: lgtm, approved

#1026 USHIFT-500: Remove ConfigFile, DataDir and Manifests fields off MicroShift config
  docs/howto_config.md
  pkg/cmd/init.go
  pkg/cmd/run.go
  pkg/cmd/showConfig.go
  pkg/components/components.go
  pkg/components/controllers.go
  pkg/components/networking.go
  pkg/components/storage.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/controllers/etcd.go
  pkg/controllers/kube-apiserver.go
  pkg/controllers/kube-controller-manager.go
  pkg/controllers/kube-scheduler.go
  pkg/controllers/openshift-route-controller-manager.go
  pkg/kustomize/apply.go
  pkg/node/kubelet.go
  test/config.yaml
Labels: lgtm, approved

#1059 USHIFT-521: Fix ART builds; bring back golang in microshift.spec
  packaging/rpm/microshift.spec
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved

#1025 USHIFT-363: Use route CRD from cluster-ingress-operator repo in rebase script
  assets/crd/route.crd.yaml
  pkg/assets/crd.go
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved

#1060 USHIFT-529: fix(storage): correct lvmd file path
  pkg/components/storage.go
Labels: lgtm, approved

#1062 USHIFT-532: Remove pprof flag.
  docs/devenv_rhel8.md
  docs/images/devenv_pprof.png
  pkg/cmd/run.go
  pkg/config/config.go
  pkg/config/config_test.go
Labels: lgtm, approved

#1067 Fix missing remote in rebase script
  scripts/auto-rebase/create_pr.py
Labels: lgtm, approved

#1038 Some minor fixes for configure scripts and add arm64 image mapping
  pkg/release/get.sh
  scripts/image-builder/configure.sh
Labels: lgtm, approved

#1041 USHIFT-384: ovsdb compaction
  assets/components/ovn/master/daemonset.yaml
Labels: lgtm, approved, tide/merge-method-squash

#1070 Use formatting infof when logging variable
  pkg/config/lvmd/lvmd.go
Labels: lgtm, approved

#1072 Add support for vnstat metrics to ansible playbooks & slight cleanup
  ansible/roles/configure-firewall/defaults/main.yml
  ansible/roles/install-logging-exporters/templates/cadvisor.service.j2
  ansible/roles/install-logging/defaults/main.yml
  ansible/roles/install-logging/tasks/main.yml
  ansible/roles/install-logging/templates/prometheus.yml.j2
  ansible/roles/install-microshift/defaults/main.yml
  ansible/roles/microshift-start/defaults/main.yml
  ansible/roles/microshift-start/tasks/main.yml
  ansible/roles/setup-microshift-host/defaults/main.yml
  ansible/roles/setup-microshift-host/templates/cadvisor.service.j2
Labels: lgtm, approved

#1043 add verify job step for image locations
  Makefile
  pkg/release/get.sh
  scripts/verify_images.sh
Labels: lgtm, approved, tide/merge-method-squash

#1066 USHIFT-428: Update change history in microshift.spec file
  Makefile
  packaging/rpm/microshift.spec
Labels: lgtm, approved

#1031 AUTH-296: Finish the removal of the root CA
  assets/components/openshift-router/service-internal.yaml
  assets/components/openshift-router/serving-certificate.yaml
  pkg/cmd/init.go
  pkg/cmd/run.go
  pkg/components/controllers.go
  pkg/config/config.go
  pkg/controllers/kube-apiserver.go
  pkg/controllers/kube-controller-manager.go
  pkg/util/cert.go
  pkg/util/cryptomaterial/certpaths.go
  pkg/util/cryptomaterial/trustupdates.go
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved

#1058 disable ingress-ip controller as we are not allowing configuration of IngressIPNetworkCIDR
  pkg/controllers/openshift-route-controller-manager.go
Labels: lgtm, approved

#1065 USHIFT-533: Remove role (controlplane/node) config.
  docs/design.md
  pkg/cmd/run.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/node/kubelet.go
  test/config.yaml
Labels: lgtm, approved
