Repository openshift/microshift, pull requests merged in 2022-03, with the labels that each got.

#568 Pre-loading container images into CRI-O
  packaging/rpm/make-microshift-app-images-rpm.sh
  packaging/rpm/make-microshift-images-rpm.sh
  packaging/rpm/microshift-images.spec
  pkg/release/get.sh
Labels: lgtm, approved

#611 Specify the right pause image used by cri-o
  pkg/release/release_amd64.go
Labels: lgtm, approved

#616 Set Default Audit Log Retention
  pkg/controllers/kube-apiserver.go
Labels: approved, ok-to-test

#615 Pack containers into GitHub CI
  .github/workflows/release.yaml
  Makefile
  packaging/images/components/archive.sh
  scripts/release.sh
Labels: lgtm, approved

#621 Use default GOMAXPROCS behavior
  cmd/microshift/main.go
Labels: lgtm, approved, ok-to-test

#623 fix typo in reference
  scripts/release.sh
Labels: approved

#628 Fix AIO image to properly configure crio for MicroShift networking
  packaging/images/microshift-aio/Dockerfile
  packaging/images/microshift-aio/crio-bridge.conf
Labels: lgtm, approved

#625 update LICENSE
  LICENSE
Labels: lgtm, approved

#637 Equalise service stop or failures
  pkg/controllers/openshift-apiserver.go
  pkg/controllers/openshift-controller-manager.go
  pkg/controllers/openshift-oauth-server.go
  pkg/kustomize/apply.go
  pkg/node/kube-proxy.go
Labels: lgtm, approved

#644 Format value of error for stopped services
  pkg/cmd/run.go
Labels: lgtm, approved
