Repository openshift/microshift, pull requests merged in 2022-12, with the labels that each got.

#1155 pass log level to KCM
  pkg/controllers/kube-controller-manager.go
  pkg/controllers/kube-controller-manager_test.go
Labels: lgtm, approved

#1152 USHIFT-194: Add kubeconfig to Scheduler's authz and authn
  pkg/controllers/kube-scheduler.go
Labels: lgtm, approved

#1144 USHIFT-631: Rearrangement of assets directory
  assets/controllers/cluster-policy-controller/namespace-security-allocation-controller-clusterrole.yaml
  assets/controllers/cluster-policy-controller/namespace-security-allocation-controller-clusterrolebinding.yaml
  assets/controllers/cluster-policy-controller/podsecurity-admission-label-syncer-controller-clusterrole.yaml
  assets/controllers/cluster-policy-controller/podsecurity-admission-label-syncer-controller-clusterrolebinding.yaml
  assets/controllers/kube-apiserver/config-overrides.yaml
  assets/controllers/kube-apiserver/defaultconfig.yaml
  assets/controllers/kube-controller-manager/csr_approver_clusterrole.yaml
  assets/controllers/kube-controller-manager/csr_approver_clusterrolebinding.yaml
  assets/controllers/kube-controller-manager/defaultconfig.yaml
  assets/controllers/kube-controller-manager/namespace-openshift-kube-controller-manager.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_cr-scc-anyuid.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_cr-scc-hostaccess.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_cr-scc-hostmount-anyuid.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_cr-scc-hostnetwork-v2.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_cr-scc-hostnetwork.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_cr-scc-nonroot-v2.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_cr-scc-nonroot.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_cr-scc-privileged.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_cr-scc-restricted-v2.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_cr-scc-restricted.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_crb-systemauthenticated-scc-restricted-v2.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_scc-anyuid.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_scc-hostaccess.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_scc-hostmount-anyuid.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_scc-hostnetwork-v2.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_scc-hostnetwork.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_scc-nonroot-v2.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_scc-nonroot.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_scc-privileged.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_scc-restricted-v2.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_scc-restricted.yaml
  assets/controllers/route-controller-manager/0000_50_cluster-openshift-route-controller-manager_00_namespace.yaml
  assets/controllers/route-controller-manager/ingress-to-route-controller-clusterrole.yaml
  assets/controllers/route-controller-manager/ingress-to-route-controller-clusterrolebinding.yaml
  assets/controllers/route-controller-manager/route-controller-informer-clusterrole.yaml
  assets/controllers/route-controller-manager/route-controller-informer-clusterrolebinding.yaml
  assets/controllers/route-controller-manager/route-controller-leader-role.yaml
  assets/controllers/route-controller-manager/route-controller-leader-rolebinding.yaml
  assets/controllers/route-controller-manager/route-controller-sa.yaml
  assets/controllers/route-controller-manager/route-controller-separate-sa-role.yaml
  assets/controllers/route-controller-manager/route-controller-separate-sa-rolebinding.yaml
  assets/controllers/route-controller-manager/route-controller-tokenreview-clusterrole.yaml
  assets/controllers/route-controller-manager/route-controller-tokenreview-clusterrolebinding.yaml
  assets/core/securityv1-local-apiservice.yaml
  assets/embed.go
  pkg/assets/crd.go
  pkg/controllers/infra-services-controller.go
  pkg/controllers/kube-apiserver.go
  pkg/controllers/kube-controller-manager.go
  pkg/controllers/openshift-default-scc-manager.go
  pkg/controllers/openshift-route-controller-manager.go
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved

#1164 Add wait option to virt-install to make sure VMs are restarted
  scripts/devenv-builder/create-vm.sh
  scripts/image-builder/create-vm.sh
Labels: lgtm, approved

#1149 USHIFT-573 avoid NodeName changes in running systems
  pkg/config/config.go
  pkg/config/config_test.go
Labels: lgtm, approved

#1167 Better cleanup of MicroShift resources for developers
  hack/cleanup.sh
Labels: lgtm, approved

#1162 USHIFT-447: Add os_id label to kubelet node registration
  pkg/node/kubelet.go
Labels: lgtm, approved

#1170 USHIFT-666: Add %{commit} and embed it into binary
  packaging/rpm/make-rpm.sh
  packaging/rpm/microshift.spec
Labels: lgtm, approved

#1172 USHIFT-660: extract CI cluster fail debug info to separate file
  validate-microshift/cluster-debug-info.sh
  validate-microshift/kuttl-test.sh
Labels: lgtm, approved

#1160 [BUG] USHIFT-657 MicroShift does not find lvmd config if no microshift config file exists.
  pkg/components/render_test.go
  pkg/components/storage.go
  pkg/config/config.go
  pkg/config/lvmd/lvmd.go
  pkg/config/lvmd/lvmd_test.go
Labels: kind/bug, lgtm, approved

#1174 Change %{X} to 'X macro' in spec changelog
  packaging/rpm/microshift.spec
Labels: lgtm, approved

#1175 USHIFT-660: yet another cluster debug info improvement
  validate-microshift/cluster-debug-info.sh
Labels: lgtm, approved

#1030 USHIFT-607: Introduce a new config format for microshift config
  docs/howto_config.md
  pkg/config/config.go
  test/config.yaml
Labels: lgtm, approved

#1173 USHIFT-632: Update MicroShift description in RPM
  README.md
  packaging/rpm/microshift.spec
Labels: lgtm, approved

#1182 USHIFT-503: Document unidle service known limitation
  README.md
  docs/known_limitations.md
Labels: lgtm, approved

#1176 Re-introduce PR#1030 baseDomain patch and add backend logic
  assets/components/openshift-router/deployment.yaml
  docs/howto_config.md
  pkg/cmd/init.go
  pkg/cmd/run.go
  pkg/components/render.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/controllers/kube-apiserver.go
  pkg/node/kubelet.go
  test/config.yaml
Labels: lgtm, approved, tide/merge-method-squash

#1186 Fix missing change of router manifest
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved

#1179 OCPBUGS-4577: Fix default router domain in GenericAPIServerConfig
  pkg/controllers/kube-apiserver.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#1188 USHIFT-674: Fix show-config command
  pkg/cmd/showConfig.go
Labels: lgtm, approved

#1191 USHIFT-677: Remove _output on successful rebase
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved

#1194 NOISSUE: squash rebase pull requests
  scripts/auto-rebase/create_pr.py
Labels: lgtm, approved

#1187 USHIFT-673: Clean up config file format
  assets/components/openshift-router/deployment.yaml
  docs/howto_config.md
  packaging/microshift/config.yaml
  pkg/cmd/init.go
  pkg/cmd/run.go
  pkg/cmd/showConfig.go
  pkg/components/render.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/controllers/kube-apiserver.go
  pkg/controllers/kube-controller-manager_test.go
  scripts/auto-rebase/rebase.sh
  test/config.yaml
  test/config_bad_subjectaltnames.yaml
Labels: lgtm, approved

#1197 NOISSUE: save last image references so it is easy to reproduce the rebase
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved

#1196 USHIFT-247: Generate release-info
  Makefile
  README.md
  assets/embed.go
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  docs/devenv_rhel8.md
  docs/howto_offline_containers.md
  docs/rhel4edge_iso.md
  packaging/rpm/microshift.spec
  pkg/release/get.sh
  pkg/release/release.go
  pkg/release/release_amd64.go
  pkg/release/release_arm64.go
  scripts/auto-rebase/rebase.sh
  scripts/image-builder/build.sh
  scripts/verify_images.sh
Labels: lgtm, approved

#1199 USHIFT-606: Remove cert validity time warnings
  pkg/util/cryptomaterial/certchains/chainsbuilder.go
Labels: lgtm, approved

#1171 Add host networking doc
  README.md
  docs/network/host_networking.md
Labels: lgtm, approved

#1204 USHIFT-673: Minor fixes in offline container docs
  README.md
  docs/howto_offline_containers.md
  docs/rhel4edge_iso.md
Labels: lgtm, approved

#1205 USHIFT-721: Rename ODF-LVM to LVMS in MicroShift
  assets/components/lvms/csi-driver.yaml
  assets/components/lvms/topolvm-controller_deployment.yaml
  assets/components/lvms/topolvm-controller_rbac.authorization.k8s.io_v1_clusterrole.yaml
  assets/components/lvms/topolvm-controller_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  assets/components/lvms/topolvm-controller_rbac.authorization.k8s.io_v1_role.yaml
  assets/components/lvms/topolvm-controller_rbac.authorization.k8s.io_v1_rolebinding.yaml
  assets/components/lvms/topolvm-controller_v1_serviceaccount.yaml
  assets/components/lvms/topolvm-csi-provisioner_rbac.authorization.k8s.io_v1_clusterrole.yaml
  assets/components/lvms/topolvm-csi-provisioner_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  assets/components/lvms/topolvm-csi-provisioner_rbac.authorization.k8s.io_v1_role.yaml
  assets/components/lvms/topolvm-csi-provisioner_rbac.authorization.k8s.io_v1_rolebinding.yaml
  assets/components/lvms/topolvm-csi-resizer_rbac.authorization.k8s.io_v1_clusterrole.yaml
  assets/components/lvms/topolvm-csi-resizer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  assets/components/lvms/topolvm-csi-resizer_rbac.authorization.k8s.io_v1_role.yaml
  assets/components/lvms/topolvm-csi-resizer_rbac.authorization.k8s.io_v1_rolebinding.yaml
  assets/components/lvms/topolvm-csi-snapshotter_rbac.authorization.k8s.io_v1_clusterrole.yaml
  assets/components/lvms/topolvm-csi-snapshotter_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  assets/components/lvms/topolvm-leader-election_rbac.authorization.k8s.io_v1_role.yaml
  assets/components/lvms/topolvm-leader-election_rbac.authorization.k8s.io_v1_rolebinding.yaml
  assets/components/lvms/topolvm-lvmd-config_configmap_v1.yaml
  assets/components/lvms/topolvm-metrics_rbac.authorization.k8s.io_v1_role.yaml
  assets/components/lvms/topolvm-metrics_rbac.authorization.k8s.io_v1_rolebinding.yaml
  assets/components/lvms/topolvm-node-metrics_v1_service.yaml
  assets/components/lvms/topolvm-node-scc_rbac.authorization.k8s.io_v1_clusterrole.yaml
  assets/components/lvms/topolvm-node-scc_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  assets/components/lvms/topolvm-node-securitycontextconstraint.yaml
  assets/components/lvms/topolvm-node_daemonset.yaml
  assets/components/lvms/topolvm-node_rbac.authorization.k8s.io_v1_clusterrole.yaml
  assets/components/lvms/topolvm-node_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  assets/components/lvms/topolvm-node_v1_serviceaccount.yaml
  assets/components/lvms/topolvm-openshift-storage_namespace.yaml
  assets/components/lvms/topolvm.io_logicalvolumes.yaml
  assets/components/lvms/topolvm_default-storage-class.yaml
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  docs/default_csi_plugin.md
  docs/design.md
  pkg/assets/crd.go
  pkg/components/render_test.go
  pkg/components/storage.go
Labels: lgtm, approved

#1200 USHIFT-667: Avoid regenerating keypair for Service Account tokens
  pkg/cmd/init.go
  pkg/controllers/kube-apiserver.go
  pkg/util/cert.go
Labels: lgtm, approved

#1208 rebase.sh: remove previous last_rebase.sh
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, tide/merge-method-squash

#1165 USHIFT-640: Add ovn-kubernetes traffic flows doc
  README.md
  docs/network/ovn_kubernetes_traffic_flows.md
  docs/network/ovn_topology.svg
Labels: lgtm, approved

#1213 fix broken link
  docs/design.md
Labels: lgtm, approved

#1215 USHIFT-732: forbid IP addresses as hostname
  pkg/config/config.go
  pkg/config/config_test.go
Labels: lgtm, approved

#1218 rebase.sh: don't fail if last_rebase.sh didn't change
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved

#1219 Fix hostport iptable owner in network doc
  docs/network/host_networking.md
Labels: lgtm, approved

#1224 Delete openshift-tests' static analysis code
  hack/tests-static-analysis/README
  hack/tests-static-analysis/go.mod
  hack/tests-static-analysis/go.sum
  hack/tests-static-analysis/main.go
Labels: lgtm, approved
