Repository openshift/microshift, pull requests merged in 2022-09, with the labels that each got.

#914 USHIFT-19: add example config file to rpm
  packaging/microshift/microshift.yaml
  packaging/rpm/microshift.spec
  packaging/rpm/microshift.yaml
Labels: lgtm, approved

#915 USHIFT-140: remove experimental comments from RPM description
  packaging/rpm/microshift.spec
Labels: lgtm, approved

#876 Get node IP through ovn gateway interface when no default route
  pkg/config/config.go
  pkg/controllers/kube-apiserver.go
  pkg/util/net.go
Labels: kind/bug, lgtm, approved

#917 Wait for default route to become available after boot
  packaging/systemd/configure-ovs.sh
  packaging/systemd/microshift-ovs-init.service
Labels: lgtm, approved

#919 USHIFT-19: fix location of example configuration file in RPM
  packaging/microshift/config.yaml
  packaging/rpm/example-user-containers.yaml
  packaging/rpm/microshift.spec
Labels: lgtm, approved

#916 USHIFT-336: Inject embedded component names into klog headers.
  Makefile
  pkg/servicemanager/manager.go
  scripts/rebase_patches/0020-klog-component-names.patch
  vendor/k8s.io/klog/v2/goroutine_labels.go
  vendor/k8s.io/klog/v2/klog.go
Labels: lgtm, approved

#896 Make nodeport range configurable
  assets/components/openshift-router/service-cloud.yaml
  pkg/assets/bindata.go
  pkg/controllers/kube-apiserver.go
  scripts/rebase.sh
Labels: lgtm, approved

#918 USHIFT-256 OpenShift tests static analysis
  hack/tests-static-analysis/README
  hack/tests-static-analysis/go.mod
  hack/tests-static-analysis/go.sum
  hack/tests-static-analysis/main.go
Labels: lgtm, approved

#921 Use lorax outside of container during iso creation
  scripts/image-builder/build.sh
  scripts/image-builder/configure.sh
Labels: lgtm, approved, kind/cleanup

#922 USHIFT-367: add OPC to rebase script and update go.mod
  go.mod
  go.sum
  scripts/rebase.sh
  vendor/modules.txt
Labels: lgtm, approved

#920 USHIFT-333: update validation for tls in route crd
  assets/crd/0000_01_route.crd.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#913 USHIFT-364: add command to show default configuration
  cmd/microshift/main.go
  pkg/cmd/run.go
  pkg/cmd/showConfig.go
  pkg/config/config.go
Labels: lgtm, approved

#926 USHIFT-367: apply rebase.sh to service-ca manifests
  assets/components/service-ca/clusterrole.yaml
  assets/components/service-ca/deployment.yaml
  assets/components/service-ca/ns.yaml
  assets/components/service-ca/role.yaml
  assets/components/service-ca/rolebinding.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#898 AUTH-296: Separate kubelet client trust
  pkg/cmd/init.go
  pkg/controllers/kube-apiserver.go
  pkg/node/kubelet.go
  pkg/util/cryptomaterial/certpaths.go
  pkg/util/cryptomaterial/trustupdates.go
Labels: lgtm, approved

#884 Reconcile ovnk in case node IP changes
  assets/components/ovn/master/daemonset.yaml
  assets/components/ovn/node/daemonset.yaml
  pkg/assets/bindata.go
Labels: kind/feature, lgtm, approved

#929 expand configuration section of design guidelines
  docs/design.md
Labels: lgtm, approved

#923 USHIFT-318: Create local APIServices for formerly-openshift-apiserver CRDs.
  assets/crd/authorizationv1-local-apiservice.yaml
  assets/crd/securityv1-local-apiservice.yaml
  pkg/assets/bindata.go
  pkg/assets/crd.go
Labels: lgtm, approved

#931 USHIFT-362: consolidate all build output directories
  .gitignore
  Makefile
  docs/devenv_rhel8.md
  docs/rhel4edge_iso.md
  packaging/rpm/make-rpm.sh
  scripts/devenv-builder/configure-vm.sh
  scripts/image-builder/build.sh
  scripts/image-builder/cleanup.sh
Labels: lgtm, approved

#928 USHIFT-368: Generalize asset templating
  pkg/assets/applier.go
  pkg/components/components.go
  pkg/components/controllers.go
  pkg/components/networking.go
  pkg/components/render.go
  pkg/components/storage.go
Labels: lgtm, approved

#932 add mtu config option
  assets/components/ovn/configmap.yaml
  pkg/assets/bindata.go
  pkg/components/render.go
  pkg/config/config.go
  pkg/config/config_test.go
Labels: lgtm, approved

#925 USHIFT-367: apply rebase.sh to openshift-dns manifests
  assets/bindata_timestamp.txt
  assets/components/openshift-dns/dns/daemonset.yaml
  assets/components/openshift-dns/dns/namespace.yaml
  assets/components/openshift-dns/dns/service.yaml
  pkg/assets/bindata.go
  scripts/rebase.sh
Labels: lgtm, approved

#942 Do not try to rebase OVNk manifests
  scripts/rebase.sh
Labels: lgtm, approved

#944 USHIFT-362: toml.template url updates.
  scripts/image-builder/build.sh
  scripts/image-builder/config/custom-rpms.toml.template
  scripts/image-builder/config/microshift-local.toml.template
  scripts/image-builder/config/openshift-local.toml.template
Labels: lgtm, approved

#941 update ovnk image from release payload
  assets/components/ovn/master/daemonset.yaml
  assets/components/ovn/node/daemonset.yaml
  pkg/assets/bindata.go
  pkg/release/release.go
  pkg/release/release_amd64.go
  pkg/release/release_arm64.go
  scripts/rebase.sh
Labels: lgtm, approved

#933 USHIFT-251: Sync more core and CRD manifests
  assets/core/0000_50_cluster-openshift-controller-manager_00_namespace.yaml
  assets/crd/0000_03_securityinternal-openshift_02_rangeallocation.crd.yaml
  pkg/assets/bindata.go
  scripts/rebase.sh
Labels: lgtm, approved

#927 USHIFT-367: apply rebase.sh to router manifests and align with OCP
  assets/components/openshift-router/deployment.yaml
  assets/components/openshift-router/namespace.yaml
  assets/components/openshift-router/service-cloud.yaml
  assets/components/openshift-router/service-internal.yaml
  pkg/assets/bindata.go
  scripts/rebase.sh
Labels: lgtm, approved

#946 Fix config params and tests
  pkg/cmd/run.go
  pkg/config/config.go
  pkg/config/config_test.go
  test/config.yaml
Labels: lgtm, approved

#943 USHIFT-375: fix capitalization in show-config output
  packaging/microshift/config.yaml
  pkg/config/config.go
Labels: lgtm, approved

#940 USHIFT-381: Support for running performance tests against devenv VM
  ansible/README.md
  ansible/inventory/inventory
  ansible/roles/configure-firewall/defaults/main.yml
  ansible/roles/configure-firewall/tasks/main.yml
  ansible/roles/install-microshift/defaults/main.yml
  ansible/roles/install-microshift/tasks/disk.yml
  ansible/roles/install-microshift/tasks/main.yml
  ansible/roles/manage-repos/defaults/main.yml
  ansible/roles/manage-repos/tasks/main.yml
  ansible/roles/setup-microshift-host/defaults/main.yml
  ansible/roles/setup-microshift-host/handlers/main.yml
  ansible/roles/setup-microshift-host/tasks/main.yml
  ansible/run-perf.yml
  ansible/setup-node.yml
  ansible/vars/all.yml
Labels: lgtm, approved

#936 USHIFT-373: add priorityClassName to topoLVM
  assets/components/odf-lvm/topolvm-controller_deployment.yaml
  assets/components/odf-lvm/topolvm-node_daemonset.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#938 USHIFT-362: Fix microshift executable location in the devenv docs
  docs/devenv_rhel8.md
  packaging/rpm/make-rpm.sh
Labels: lgtm, approved

#950 Some clean-ups for the rebase script
  scripts/rebase.sh
Labels: lgtm, approved

#939 AUTH-296: certificate chains init refactoring
  pkg/cmd/init.go
  pkg/util/cryptomaterial/certpaths.go
  pkg/util/cryptomaterial/signers.go
  pkg/util/cryptomaterial/signers_test.go
Labels: lgtm, approved

#948 USHIFT-278: util: write kubeconfigs using the upstream code
  pkg/util/kubeconfig.go
Labels: lgtm, approved

#952 USHIFT-399: update list of enabled APIs
  docs/enable_apis.md
Labels: lgtm, approved

#947 AUTH-296: split out the service-ca trust chain
  pkg/cmd/init.go
  pkg/components/controllers.go
  pkg/util/cert.go
  pkg/util/cryptomaterial/certpaths.go
Labels: lgtm, approved

#954 USHIFT-261: clean up path handling for kubeconfig files
  pkg/assets/crd.go
  pkg/cmd/init.go
  pkg/components/components.go
  pkg/config/config.go
  pkg/controllers/cluster-policy-controller.go
  pkg/controllers/infra-services-controller.go
  pkg/controllers/kube-controller-manager.go
  pkg/controllers/kube-scheduler.go
  pkg/controllers/openshift-controller-manager.go
  pkg/controllers/openshift-default-scc-manager.go
  pkg/controllers/version.go
  pkg/kustomize/apply.go
  pkg/mdns/controller.go
  pkg/node/kubelet.go
Labels: lgtm, approved

#937 USHIFT-365: support ipv4.ignore-auto-dns on ovs-interface br-ex
  packaging/systemd/configure-ovs.sh
Labels: lgtm, approved

#953 USHIFT-400: remove unused fields in configuration data structure
  pkg/config/config.go
Labels: lgtm, approved

#957 Fix spelling
  pkg/servicemanager/manager.go
  scripts/rebase_patches/0020-klog-component-names.patch
  vendor/k8s.io/klog/v2/goroutine_labels.go
Labels: lgtm, approved

#949 AUTH-296: Cut off the root CA from the cluster-distributed client CA
  pkg/cmd/init.go
  pkg/controllers/kube-apiserver.go
  pkg/controllers/kube-controller-manager.go
  pkg/controllers/openshift-controller-manager.go
  pkg/util/cryptomaterial/signers.go
Labels: lgtm, approved

#959 Set UBI version to latest UBI minor version
  hack/all-in-one/Dockerfile
  hack/all-in-one/build-aio-dev.sh
  hack/all-in-one/build-images.sh
  packaging/images/components/components/base-image/Dockerfile
  packaging/images/microshift-aio/Dockerfile
  packaging/images/microshift/Dockerfile
Labels: lgtm, approved, ok-to-test

#951 AUTH-296: Cut off the root CA from the cluster-distributed requestheader-client-ca
  pkg/cmd/init.go
  pkg/controllers/kube-apiserver.go
  pkg/util/cryptomaterial/certpaths.go
Labels: lgtm, approved

#962 Update OCM and CPC requirements
  scripts/rebase.sh
Labels: lgtm, approved

#964 USHIFT-416: Clean up unused cert management code
  pkg/cmd/init.go
Labels: lgtm, approved

#966 USHIFT-362: Fix output directories for container RPM builds
  docs/rhel4edge_iso.md
  packaging/rpm/make-microshift-images-rpm.sh
  packaging/rpm/paack.py
Labels: lgtm, approved

#955 USHIFT-401: Carried out patch to disable APIrequestcount controller
  scripts/rebase_patches/0002-disable-APIrequestcount-controller.patch
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
Labels: lgtm, approved

#963 USHIFT-415: Remove scripts and files for unsupported procedures
  .copr/Makefile
  .image-references.
  Makefile
  _site/CNAME
  hack/all-in-one/.gitignore
  hack/all-in-one/Dockerfile
  hack/all-in-one/README.md
  hack/all-in-one/build-aio-dev.sh
  hack/all-in-one/build-images.sh
  hack/all-in-one/nvidia-config.toml
  hack/install.sh
  packaging/images/components/.gitignore
  packaging/images/components/README.md
  packaging/images/components/archive.sh
  packaging/images/components/build.sh
  packaging/images/components/components/.gitignore
  packaging/images/components/components/base-image/Dockerfile
  packaging/images/components/components/base-image/Dockerfile.arm
  packaging/images/components/components/base-image/Dockerfile.riscv64
  packaging/images/components/components/cli/Dockerfile
  packaging/images/components/components/cli/ImageSource.amd64
  packaging/images/components/components/coredns/Dockerfile
  packaging/images/components/components/coredns/Dockerfile.riscv64
  packaging/images/components/components/coredns/ImageSource.amd64
  packaging/images/components/components/coredns/build_binaries
  packaging/images/components/components/haproxy-router/Dockerfile
  packaging/images/components/components/haproxy-router/Dockerfile.riscv64
  packaging/images/components/components/haproxy-router/ImageSource.amd64
  packaging/images/components/components/haproxy-router/build_binaries
  packaging/images/components/components/kube-rbac-proxy/0001-workaround-riscv64.patch
  packaging/images/components/components/kube-rbac-proxy/Dockerfile
  packaging/images/components/components/kube-rbac-proxy/ImageSource.amd64
  packaging/images/components/components/kube-rbac-proxy/build_binaries
  packaging/images/components/components/pause/Dockerfile.riscv64
  packaging/images/components/components/pause/ImageSource.amd64
  packaging/images/components/components/pause/ImageSource.arm
  packaging/images/components/components/pause/ImageSource.arm64
  packaging/images/components/components/pause/ImageSource.ppc64le
  packaging/images/components/components/pause/build_binaries
  packaging/images/components/components/pause/commit
  packaging/images/components/components/pause/repo
  packaging/images/components/components/service-ca-operator/Dockerfile
  packaging/images/components/components/service-ca-operator/ImageSource.amd64
  packaging/images/components/components/service-ca-operator/build_binaries
  packaging/images/microshift-aio/Dockerfile
  packaging/images/microshift-aio/kubelet-cgroups.conf
  packaging/images/microshift-aio/unit
  packaging/images/microshift/Dockerfile
  packaging/images/microshift/entrypoint.sh
  packaging/systemd/microshift-aio.service
  scripts/release.sh
Labels: lgtm, approved

#961 Rebase to 4.10.33
  assets/bindata_timestamp.txt
  assets/components/openshift-router/deployment.yaml
  go.mod
  go.sum
  pkg/assets/bindata.go
  pkg/release/release.go
  pkg/release/release_amd64.go
  pkg/release/release_arm64.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/filters/deprecatedapirequest/deprecated.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/containermap/container_map.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/cpu_manager.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/memorymanager/memory_manager.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go
  vendor/modules.txt
Labels: lgtm, approved

#971 Add microshift config doc
  README.md
  docs/howto_config.md
Labels: lgtm, approved

#974 USHIFT-179: PR creator
  scripts/create_pr.py
Labels: lgtm, approved

#969 Update dns comments in config.yaml
  packaging/microshift/config.yaml
Labels: lgtm, approved

#980 USHIFT-179 Create PR script improvements & doc
  docs/openshift_ci.md
  scripts/create_pr.py
Labels: lgtm, approved

#972 USHIFT-429: Remove RoleBindingRestriction CRD
  assets/crd/0000_03_authorization-openshift_01_rolebindingrestriction.crd.yaml
  docs/enable_apis.md
  pkg/assets/bindata.go
  pkg/assets/crd.go
  scripts/rebase.sh
Labels: lgtm, approved

#970 AUTH-296: Certificate-related fixes
  pkg/cmd/init.go
  pkg/controllers/openshift-controller-manager.go
  pkg/util/cryptomaterial/certpaths.go
  pkg/util/cryptomaterial/signers.go
Labels: lgtm, approved

#979 rebase.sh: Use shallow clone
  scripts/rebase.sh
Labels: lgtm, approved

#960 Add support for process-exporter
  ansible/inventory/inventory
  ansible/roles/configure-firewall/defaults/main.yml
  ansible/roles/install-logging/handlers/main.yml
  ansible/roles/install-logging/tasks/main.yml
  ansible/roles/install-logging/templates/prometheus.yml.j2
  ansible/roles/setup-microshift-host/defaults/main.yml
  ansible/roles/setup-microshift-host/tasks/main.yml
  ansible/roles/setup-microshift-host/templates/cadvisor.service.j2
  ansible/run-perf.yml
  ansible/setup-node.yml
Labels: lgtm, approved

#983 Run go fmt after updating release images
  scripts/rebase.sh
Labels: lgtm, approved
