Repository openshift/microshift, pull requests merged in 2022-01, with the labels that each got.

#534 hack to temp fix releases
  .github/workflows/temp-release.yaml
  Makefile
  hack/temp-release.sh
Labels: lgtm, approved

#537 Update temp-release.yaml
  .github/workflows/temp-release.yaml
Labels: lgtm, approved

#543 matching service name with docs
  packaging/rpm/microshift.spec
Labels: lgtm, approved

#542 fix release.sh
  scripts/release.sh
Labels: lgtm, approved

#545 Revert "Update temp-release.yaml"
  .github/workflows/temp-release.yaml
Labels: lgtm, approved

#536 Revert "hack to temp fix releases"
  .github/workflows/temp-release.yaml
  Makefile
  hack/temp-release.sh
Labels: lgtm, approved

#547 Fix of mirrors for release.sh
  .github/workflows/release.yaml
Labels: lgtm, approved

#548 fixes the systemd files
  packaging/rpm/microshift.spec
Labels: lgtm, approved

#494 Do not modify default logging parameters
  assets/apps/0000_70_dns_01-dns-daemonset.yaml
  pkg/assets/apps/bindata.go
  pkg/cmd/run.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/controllers/kube-apiserver.go
  pkg/controllers/kube-controller-manager.go
  pkg/controllers/kube-scheduler.go
  pkg/controllers/openshift-apiserver.go
  pkg/node/kube-proxy.go
  pkg/node/kubelet.go
  test/config.yaml
Labels: approved

#549 fix broken OCM link
  README.md
Labels: lgtm, approved

#546 fix for microshift-containerized with volume mount
  packaging/systemd/microshift-containerized
Labels: lgtm, approved

#488 Switch to microshift.io
  CONTRIBUTING.md
  README.md
  docs/README.md
  hack/all-in-one/README.md
Labels: lgtm, approved

#554 fix microshift-aio unit file
  packaging/systemd/microshift-aio
  packaging/systemd/microshift-aio.service
Labels: lgtm, approved, ok-to-test

#457 selinux configs and volume for microshift-containerized
  packaging/systemd/microshift-containerized.service
Labels: lgtm, approved, ok-to-test

#555 Wait for crd established
  pkg/assets/crd.go
  pkg/controllers/openshift-crd-manager.go
Labels: lgtm, approved

#561 Populate the the NO_PROXY environment
  pkg/cmd/run.go
  pkg/util/net.go
  pkg/util/net_test.go
Labels: lgtm, approved

#560 Use 127.0.0.1 as HostIP if no IP is available
  pkg/config/config.go
  pkg/util/net.go
Labels: lgtm, approved

#188 logrus -> klog
  pkg/assets/apps.go
  pkg/assets/core.go
  pkg/assets/crd.go
  pkg/assets/rbac.go
  pkg/assets/scc.go
  pkg/assets/storage.go
  pkg/cmd/run.go
  pkg/components/components.go
  pkg/components/controllers.go
  pkg/components/networking.go
  pkg/components/storage.go
  pkg/config/config.go
  pkg/controllers/apiservice.go
  pkg/controllers/etcd.go
  pkg/controllers/infra-services-controller.go
  pkg/controllers/kube-apiserver.go
  pkg/controllers/kube-controller-manager.go
  pkg/controllers/kube-scheduler.go
  pkg/controllers/openshift-apiserver.go
  pkg/controllers/openshift-controller-manager.go
  pkg/controllers/openshift-crd-manager.go
  pkg/controllers/openshift-default-scc-manager.go
  pkg/controllers/openshift-oauth-server.go
  pkg/kustomize/apply.go
  pkg/mdns/controller.go
  pkg/mdns/routes.go
  pkg/node/kube-proxy.go
  pkg/node/kubelet.go
  pkg/servicemanager/manager.go
  pkg/util/cert.go
  pkg/util/net.go
Labels: lgtm, approved

#487 Deprecate install.sh
  hack/install.sh
Labels: lgtm

#578 Exit MicroShift if scc apply fails
  pkg/controllers/openshift-default-scc-manager.go
Labels: lgtm, approved

#586 allow hpvolumes to be created at runtime and tagged accordingly
  packaging/systemd/microshift-containerized.service
Labels: lgtm, approved

#575 If a service stops with error request all the other services to stop
  pkg/servicemanager/manager.go
  pkg/servicemanager/manager_test.go
Labels: lgtm, approved
