Repository openshift/microshift, pull requests merged in 2022-08, with the labels that each got.

#819 USHIFT-238: Set type of microshift.service to "notify".
  packaging/systemd/microshift.service
  pkg/cmd/run.go
Labels: lgtm, approved

#811 Skip non-yaml files when generating bindata
  scripts/bindata.sh
Labels: lgtm, approved

#816 Fix openvswitch issues when MicroShift service is disabled
  hack/cleanup.sh
  packaging/rpm/microshift.spec
  packaging/systemd/configure-ovs.sh
Labels: approved

#810 ovnk: get kubeconfig dir from microshift config
  assets/components/ovn/master/daemonset.yaml
  pkg/assets/bindata.go
  pkg/components/networking.go
  pkg/components/render.go
Labels: lgtm, approved

#824 USHIFT-241: Asset permissions
  pkg/assets/bindata.go
  scripts/bindata.sh
Labels: lgtm, approved

#825 USHIFT-240: fix verify-bindata target
  Makefile
  pkg/assets/bindata.go
  scripts/bindata.sh
  scripts/verify_bindata.sh
Labels: lgtm, approved

#821 Switch to ovn standalone mode
  assets/components/ovn/master/daemonset.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#831 Proposing Zenghui Shi as reviewer/approver
  OWNERS
Labels: lgtm, approved

#826 Streamline devenv configuration with OVN-K and TopoLVM drivers
  README.md
  docs/devenv_rhel8.md
  docs/howto_firewall.md
  hack/cleanup.sh
  packaging/systemd/configure-ovs-microshift.sh
Labels: lgtm, approved

#834 Copy explicit list of CRDs
  scripts/rebase.sh
Labels: lgtm, approved

#829 USHIFT-126: Minimal CSI Plugin documentation
  README.md
  docs/default_csi_plugin.md
Labels: lgtm, approved

#835 Fix kube-proxy dependency in go.mod
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved

#822 pkg/sysconfwatch: add non-linux variant to allow microshift binary to build
  pkg/sysconfwatch/sysconfwatch.go
  pkg/sysconfwatch/sysconfwatch_linux.go
Labels: lgtm, approved

#833 fix mdns unqulified name
  pkg/mdns/controller.go
Labels: lgtm, approved

#830 Ushift-230: CSI image templating
  assets/components/odf-lvm/topolvm-controller_deployment.yaml
  assets/components/odf-lvm/topolvm-node_daemonset.yaml
  assets/components/odf-lvm/topolvm.cybozu.com_logicalvolumes.yaml
  index.db
  pkg/assets/bindata.go
  pkg/assets/crd.go
  pkg/release/release.go
  pkg/release/release_amd64.go
Labels: lgtm, approved

#838 Update firewall settings to reflect the requirements imposed by OVN-k
  docs/devenv_rhel8.md
  docs/howto_firewall.md
  scripts/image-builder/config/kickstart.ks.template
Labels: lgtm, approved

#839 Pull the ovn-kubernetes image by sha256 hash
  pkg/release/release_amd64.go
Labels: lgtm, approved

#840 Use the arm64 image for OVNk in release_arm64.go
  pkg/release/release_arm64.go
Labels: lgtm, approved

#836 cmd: add debug.pprof option to serve pprof on local port 29500
  pkg/cmd/run.go
  pkg/config/config.go
Labels: lgtm, approved

#746 Hack scripts to help us debug scc
  hack/nginx-scc-test.yaml
  hack/scc-prep.sh
Labels: lgtm, approved

#815 Disable CGO when building MicroShift binary
  Makefile
Labels: lgtm, approved

#842 Fix ISO kickstart to check if firewall is active, not enabled
  scripts/image-builder/config/kickstart.ks.template
Labels: lgtm, approved

#841 Update the devenv documentation with pprof instructions
  docs/devenv_rhel8.md
  docs/images/devenv_pprof.png
  pkg/cmd/run.go
Labels: lgtm, approved

#844 Remove firewall rules reload command from kickstart
  scripts/image-builder/config/kickstart.ks.template
Labels: lgtm, approved

#805 Add staging directive to rebase script
  scripts/rebase.sh
Labels: lgtm, approved

#843 Tolerate any taints in ovnkube-master daemonset
  assets/components/ovn/master/daemonset.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#845 docs: fix command name in rebase instructions
  docs/rebase.md
Labels: lgtm, approved

#846 kube-apiserver: don't setup the oauth endpoint
  pkg/controllers/kube-apiserver.go
Labels: lgtm, approved

#850 mDNS: Avoid listening on internal interfaces and reduce footprint
  pkg/mdns/controller.go
  pkg/mdns/server/server.go
Labels: lgtm, approved

#856 USHIFT-269: Carry patch for CSI plugin initialization conflicts between kubelet and kube-controller-manager.
  scripts/rebase.sh
  scripts/rebase_patches/0001-Fix-CSI-initialization-conflict.patch
  vendor/k8s.io/kubernetes/pkg/volume/csi/csi_plugin.go
Labels: lgtm, approved

#855 Store host IPs for mDNS routes even if hostname is not .local
  pkg/mdns/controller.go
Labels: lgtm, approved

#849 Fix mDNS package logging
  pkg/mdns/controller.go
  pkg/mdns/routes.go
Labels: lgtm, approved

#857 USHIFT-272: start debugging tips doc with version information
  README.md
  docs/debugging_tips.md
Labels: lgtm, approved

#858 USHIFT-231: Use UBI8 image to perform init ops
  assets/components/odf-lvm/topolvm-controller_deployment.yaml
  assets/components/odf-lvm/topolvm-node_daemonset.yaml
  pkg/assets/bindata.go
  pkg/release/release.go
  pkg/release/release_amd64.go
  pkg/release/release_arm64.go
Labels: lgtm, approved

#865 update storage notes in design docs
  docs/design.md
Labels: lgtm, approved

#847 PERFSCALE-1818: Initial commit of ansible-microshift automation
  ansible/README.md
  ansible/inventory/inventory
  ansible/roles/install-logging/defaults/main.yml
  ansible/roles/install-logging/handlers/main.yml
  ansible/roles/install-logging/tasks/main.yml
  ansible/roles/install-logging/templates/prometheus.yml.j2
  ansible/roles/install-microshift/defaults/main.yml
  ansible/roles/install-microshift/files/pull-secret.txt
  ansible/roles/install-microshift/handlers/main.yml
  ansible/roles/install-microshift/tasks/disk.yml
  ansible/roles/install-microshift/tasks/main.yml
  ansible/roles/install-microshift/templates/cadvisor.service.j2
  ansible/roles/manage-repos/defaults/main.yml
  ansible/roles/manage-repos/tasks/main.yml
  ansible/roles/manage-repos/templates/kubernetes.repo.j2
  ansible/roles/microshift-start/defaults/main.yml
  ansible/roles/microshift-start/tasks/main.yml
  ansible/roles/setup-localhost/defaults/main.yml
  ansible/roles/setup-localhost/tasks/main.yml
  ansible/setup-node.yml
  ansible/vars/all.yml
Labels: lgtm, approved

#868 USHIFT-197: Enable resource accounting in MicroShift systemd service
  packaging/systemd/microshift.service
Labels: lgtm, approved

#862 USHIFT-275: Use "apply" semantics for static resource appliers.
  go.mod
  go.sum
  pkg/assets/applier.go
  pkg/assets/apps.go
  pkg/assets/core.go
  pkg/assets/crd.go
  pkg/assets/rbac.go
  pkg/assets/scc.go
  pkg/assets/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/credentialsrequest.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/event_helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/json_patch_helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/migration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/policy.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/resource_cache.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/volumesnapshotclass.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcehelper/resource_helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/generic_config_merger.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/object_merger.go
  vendor/modules.txt
  vendor/sigs.k8s.io/kube-storage-version-migrator/LICENSE
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1/doc.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1/register.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1/types.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/clientset.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/doc.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/scheme/doc.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/scheme/register.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/doc.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/generated_expansion.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/migration_client.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/storagestate.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/storageversionmigration.go
Labels: lgtm, approved

#803 USHIFT-213: Enable OpenShift flavor of kube-apiserver.
  assets/components/kube-apiserver/config-overrides.yaml
  assets/components/kube-apiserver/defaultconfig.yaml
  assets/components/odf-lvm/topolvm-node-securitycontextconstraint.yaml
  pkg/assets/bindata.go
  pkg/components/storage.go
  pkg/controllers/kube-apiserver.go
  scripts/rebase_patches/0010-kube-apiserver-command-context.patch
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
Labels: lgtm, approved

#871 Proposing Ben Luddy as reviewer/approver
  OWNERS
Labels: lgtm, approved

#861 Fix selinux rules by explicit type declaration
  .gitignore
  packaging/selinux/Makefile
  packaging/selinux/microshift.te
Labels: lgtm, approved

#866 update networking notes in design docs
  docs/design.md
Labels: lgtm, approved, kind/documentation, tide/merge-method-squash

#877 cleanup ovn kubernetes CNI binary and config file
  hack/cleanup.sh
Labels: lgtm, approved

#875 Implement AMQ Broker message persistency
  docs/config/amq-broker.yaml
  docs/howto_amq_broker.md
Labels: lgtm, approved, kind/documentation

#864 Fix early systemd readiness
  packaging/systemd/microshift.service
  pkg/cmd/run.go
  pkg/sysconfwatch/sysconfwatch_linux.go
Labels: kind/bug, lgtm, approved

#869 Set node-role.kubernetes.io based on MicroShift roles
  pkg/node/kubelet.go
Labels: kind/bug, lgtm, approved

#852 USHIFT-266: Don't send second SIGTERM on context.Canceled.
  pkg/servicemanager/manager.go
Labels: kind/bug, lgtm, approved

#872 USHIFT-286: Run Service CA component as non root
  assets/components/service-ca/clusterrolebinding.yaml
  assets/components/service-ca/deployment.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#878 USHIFT-293: Ansible GCP Compatibility Update
  ansible/README.md
  ansible/roles/common/tasks/readinesscheck.yml
  ansible/roles/install-microshift/defaults/main.yml
  ansible/roles/install-microshift/tasks/main.yml
  ansible/roles/manage-repos/tasks/main.yml
  ansible/roles/microshift-start/tasks/main.yml
  ansible/setup-node.yml
Labels: lgtm, approved

#879 Use first available route interface
  packaging/systemd/configure-ovs.sh
Labels: lgtm, approved

#870 API-1438: Split the global trust with kube-control-plane client certs
  pkg/cmd/init.go
  pkg/components/controllers.go
  pkg/controllers/etcd.go
  pkg/controllers/kube-apiserver.go
  pkg/controllers/kube-controller-manager.go
  pkg/controllers/openshift-controller-manager.go
  pkg/node/kubelet.go
  pkg/util/cert.go
  pkg/util/cryptomaterial/certpaths.go
  pkg/util/cryptomaterial/trustupdates.go
  pkg/util/kubeconfig.go
Labels: lgtm, approved, kind/cleanup

#882 USHIFT-315: Automate RHEL8 devenv creation and configuration
  docs/devenv_rhel8.md
  docs/devenv_rhel8_auto.md
  docs/howto_firewall.md
  scripts/devenv-builder/config/kickstart.ks.template
  scripts/devenv-builder/configure-vm.sh
  scripts/devenv-builder/create-vm.sh
Labels: lgtm, approved

#886 compact ovn databases periodically
  assets/components/ovn/master/daemonset.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#887 USHIFT-332: Cleanup TopoLVM webhook labels
  assets/components/odf-lvm/topolvm-openshift-storage_namespace.yaml
  assets/components/openshift-dns/dns/namespace.yaml
  assets/components/openshift-router/namespace.yaml
  assets/components/service-ca/ns.yaml
  assets/core/0000_50_cluster-openshift-controller-manager_00_namespace.yaml
  assets/core/namespace-openshift-infra.yaml
  pkg/assets/bindata.go
Labels: lgtm, approved

#889 Always do force cleanup
  hack/cleanup.sh
Labels: lgtm, approved

#891 remove os-type argument to eliminate warning message when creating VM
  scripts/devenv-builder/create-vm.sh
Labels: lgtm, approved, kind/cleanup

#888 USHIFT-136: Replace Microshift by MicroShift
  .github/ISSUE_TEMPLATE/bug-report.md
  docs/howto_sysconf_watch.md
  pkg/cmd/init.go
  pkg/cmd/run.go
  pkg/config/config_test.go
  pkg/controllers/cluster-policy-controller.go
  pkg/controllers/etcd.go
  pkg/controllers/infra-services-controller.go
  pkg/controllers/kube-apiserver.go
  pkg/controllers/kube-controller-manager.go
  pkg/controllers/kube-scheduler.go
  pkg/controllers/openshift-controller-manager.go
  pkg/controllers/openshift-crd-manager.go
  pkg/controllers/openshift-default-scc-manager.go
  pkg/mdns/server/resolver.go
  pkg/mdns/server/server.go
  pkg/node/kubelet.go
  pkg/release/release.go
  pkg/release/release_amd64.go
  pkg/release/release_arm64.go
  pkg/sysconfwatch/sysconfwatch_linux.go
  pkg/util/cert.go
  pkg/util/kubeconfig.go
  pkg/util/net.go
  scripts/release.sh
Labels: lgtm, approved, kind/cleanup

#893 skip extra make step in dev environment automation
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, kind/cleanup

#894 USHIFT-315: Add swap space to the development environment setup
  docs/devenv_rhel8_auto.md
  scripts/devenv-builder/config/kickstart.ks.template
  scripts/devenv-builder/create-vm.sh
Labels: lgtm, approved

#895 update create-vm.sh to support taking inputs via environment variables
  docs/devenv_rhel8_auto.md
  scripts/devenv-builder/create-vm.sh
Labels: lgtm, approved

#901 add new member to owners list
  OWNERS
Labels: lgtm, approved

#881 rm unused code, smaller simplifications
  pkg/mdns/controller.go
  pkg/mdns/server/server.go
  pkg/mdns/server/server_test.go
Labels: lgtm, approved, kind/cleanup

#902 USHIFT-337: Support topolvm disk, building external etcd, etc
  ansible/roles/install-microshift/defaults/main.yml
  ansible/roles/install-microshift/files/etcd.service
  ansible/roles/install-microshift/tasks/main.yml
  ansible/roles/manage-repos/defaults/main.yml
  ansible/vars/all.yml
Labels: lgtm, approved

#905 align dev install with prod and simplify
  docs/devenv_rhel8.md
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved

#897 Update issue templates for bugs and ERs
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement-tracking.md
Labels: lgtm, approved

#906 Fix devenv configuration procedure
  docs/devenv_rhel8.md
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved

#903 USHIFT-333: add ingress-to-route-controller RBAC
  assets/components/openshift-router/ingress-to-route-controller-clusterrole.yaml
  assets/components/openshift-router/ingress-to-route-controller-clusterrolebinding.yaml
  pkg/assets/bindata.go
  pkg/components/controllers.go
  scripts/rebase.sh
Labels: lgtm, approved

#910 USHIFT-270: Remove remaining references to hostpath-provisioner
  docs/rhel4edge_iso.md
  packaging/images/components/README.md
  packaging/images/components/build.sh
  packaging/images/components/components/hostpath-provisioner/Dockerfile
  packaging/images/components/components/hostpath-provisioner/ImageSource.amd64
  packaging/images/components/components/hostpath-provisioner/arm32.patch
  packaging/images/components/components/hostpath-provisioner/build_binaries
  packaging/images/components/components/hostpath-provisioner/commit
  packaging/images/components/components/hostpath-provisioner/repo
  packaging/rpm/microshift.spec
  packaging/systemd/hostpath-provisioner.service
Labels: lgtm, approved

#911 USHIFT-361: Fix RPM post install script not to return error when crio is not running
  packaging/rpm/microshift.spec
Labels: lgtm, approved

#907 Set application/json content-type for OCM clients.
  pkg/controllers/openshift-controller-manager.go
Labels: lgtm, approved

#890 Use OpenShift Infra NS from KCM operator
  assets/core/namespace-openshift-infra.yaml
  pkg/assets/bindata.go
  scripts/rebase.sh
Labels: lgtm, approved, kind/cleanup

#912 ignore rpm build location
  .gitignore
Labels: lgtm, approved

#904 USHIFT-325: Update MetalLB howto with the instructions on how to work with the latest software
  docs/howto_load_balancer.md
Labels: lgtm, approved
