Repository openshift/microshift, pull requests merged in 2023-03, with the labels that each got.

#1395 ETCD-352: Adding etcd defrag goroutine
  etcd/cmd/microshift-etcd/run.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
  pkg/config/config.go
  pkg/config/config_test.go
Labels: lgtm, approved, jira/valid-reference

#1403 NO-ISSUE: add developer review dashboard tools
  scripts/review-dashboard/README.md
  scripts/review-dashboard/dinghy.yaml
  scripts/review-dashboard/setup.sh
Labels: lgtm, approved, jira/valid-reference

#1426 Add lvmd.yaml and ovn.yaml default configuration files
  packaging/microshift/lvmd.yaml
  packaging/microshift/ovn.yaml
  packaging/rpm/microshift.spec
Labels: lgtm, approved

#1421 OCPBUGS-2869: patch out unused components in openshift-kube-apiserver
  scripts/auto-rebase/rebase_patches/0003-disable-clusterQuotaMapping-controller.patch
  scripts/auto-rebase/rebase_patches/0004-remove-config-informer.patch
  scripts/auto-rebase/rebase_patches/0005-remove-user-informer.patch
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1429 USHIFT-915: Add wait flag when creating VMs to make sure they are restarted
  docs/devenv_setup.md
  docs/rhel4edge_iso.md
Labels: lgtm, approved, jira/valid-reference

#1412 NO-ISSUE: add developer tool for getting CI pull secret
  scripts/auto-rebase/get-ci-token.sh
Labels: lgtm, approved, jira/valid-reference

#1424 OCPBUGS-7874: set the pause exec path for openshift pod image
  packaging/crio.conf.d/microshift_amd64.conf
  packaging/crio.conf.d/microshift_arm64.conf
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1241 NP-604: Add loadbalancer service controller
  go.mod
  pkg/cmd/run.go
  pkg/loadbalancerservice/controller.go
Labels: lgtm, approved

#1434 NO-ISSUE: [MANUAL REBASE] 4.13 amd64:2023-02-27 arm64:2023-02-28
  Makefile.kube_git.var
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_scc-anyuid.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_scc-hostaccess.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_scc-hostmount-anyuid.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_scc-hostnetwork-v2.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_scc-hostnetwork.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_scc-nonroot-v2.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_scc-nonroot.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_scc-restricted-v2.yaml
  assets/controllers/openshift-default-scc-manager/0000_20_kube-apiserver-operator_00_scc-restricted.yaml
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  etcd/go.mod
  etcd/go.sum
  etcd/vendor/modules.txt
  go.mod
  go.sum
  packaging/crio.conf.d/microshift_amd64.conf
  packaging/crio.conf.d/microshift_arm64.conf
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/commits.txt
  scripts/auto-rebase/last_rebase.sh
  scripts/auto-rebase/rebase.sh
  scripts/auto-rebase/rebase_patches/0004-remove-config-informer-and-cpu-partitioning-admission-plugin.patch
  scripts/auto-rebase/rebase_patches/0005-remove-user-informer.patch
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/autoscaling/managednode/admission.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/autoscaling/managednode/initializers.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/autoscaling/managementcpusoverride/admission.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#1435 ETCD-401: Adding etcd config to user-facing config
  docs/howto_config.md
  packaging/microshift/config.yaml
  pkg/config/config.go
  pkg/config/config_test.go
Labels: lgtm, approved, jira/valid-reference

#1446 USHIFT-938: Ansible RHEL9 & 4.13 changes
  ansible/roles/install-logging/defaults/main.yml
  ansible/roles/install-logging/tasks/main.yml
  ansible/roles/manage-repos/defaults/main.yml
  ansible/roles/manage-repos/tasks/main.yml
  ansible/roles/manage-repos/templates/ocpbeta.repo.j2
  ansible/roles/setup-microshift-host/defaults/main.yml
  ansible/roles/setup-microshift-host/tasks/main.yml
Labels: lgtm, approved, jira/valid-reference

#1453 OCPBUGS-8411: Use lower case node names only
  pkg/config/config.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-important, jira/valid-reference

#1447 USHIFT-737: Add user workload health check docs to Greenboot procedures
  docs/config/busybox_running_check.sh
  docs/greenboot_dev.md
  packaging/greenboot/functions.sh
  packaging/greenboot/microshift-pre-rollback.sh
  packaging/greenboot/microshift-running-check.sh
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#1455 NO-ISSUE: proper order of rebase patches & logging rejected hunks
  Makefile
Labels: lgtm, approved, jira/valid-reference

#1456 USHIFT-901: change names of rebase image configmaps
  scripts/auto-rebase/rebase_job_entrypoint.sh
Labels: lgtm, approved, jira/valid-reference

#1397 USHIFT-907: Remove unsupported topolvm manifests
  assets/components/lvms/topolvm-csi-resizer_rbac.authorization.k8s.io_v1_clusterrole.yaml
  assets/components/lvms/topolvm-csi-resizer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  assets/components/lvms/topolvm-csi-resizer_rbac.authorization.k8s.io_v1_role.yaml
  assets/components/lvms/topolvm-csi-resizer_rbac.authorization.k8s.io_v1_rolebinding.yaml
  assets/components/lvms/topolvm-csi-snapshotter_rbac.authorization.k8s.io_v1_clusterrole.yaml
  assets/components/lvms/topolvm-csi-snapshotter_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  assets/components/lvms/topolvm-leader-election_rbac.authorization.k8s.io_v1_role.yaml
  assets/components/lvms/topolvm-leader-election_rbac.authorization.k8s.io_v1_rolebinding.yaml
  assets/components/lvms/topolvm-metrics_rbac.authorization.k8s.io_v1_role.yaml
  assets/components/lvms/topolvm-metrics_rbac.authorization.k8s.io_v1_rolebinding.yaml
  assets/components/lvms/topolvm-node-metrics_v1_service.yaml
  pkg/components/storage.go
  scripts/auto-rebase/assets.yaml
Labels: lgtm, approved, kind/cleanup, jira/valid-reference

#1378 OCPBUGS-6861: Allow TopoLVM initial grace period while service-ca attempts to start
  assets/components/lvms/topolvm-controller_deployment.yaml
  assets/components/lvms/topolvm-node_daemonset.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1467 OCPBUGS-7791 Fix `microshift-etcd version` to show correct info
  Makefile
Labels: lgtm, approved

#1474 NO-ISSUE: Correct markdown link error in Getting Started doc
  docs/getting_started.md
Labels: lgtm, approved, jira/valid-reference

#1445 OCPBUGS-8329: update sysconfwatch-controller logging
  pkg/util/net.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1479 USHIFT-289 Add env var to create RPM for specific target
  packaging/rpm/make-rpm.sh
Labels: lgtm, approved

#1480 USHIFT-737: Fix user workload greenboot verification to check for 1 pod
  docs/config/busybox_running_check.sh
  docs/greenboot_dev.md
Labels: lgtm, approved, jira/valid-reference

#1439 NO-ISSUE: add more changelog details to PR descriptions
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/rebase.py
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#1487 USHIFT-949: cache getAllHostnames
  etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
  etcd/vendor/github.com/openshift/microshift/pkg/util/net.go
  pkg/config/config.go
Labels: lgtm, approved, jira/valid-reference

#1463 OCPBUGS-8425: Fix the kustomization procedure not to exit with fatal error
  pkg/kustomize/apply.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1494 USHIFT-952 Fix rebase of topolvm manifests
  scripts/auto-rebase/assets.yaml
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved

#1478 OCPBUGS-8277: Use a different internal IP for apiserver connectivity
  docs/howto_firewall.md
  docs/network/host_networking.md
  docs/network/ovn_kubernetes_traffic_flows.md
  pkg/config/config.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1440 OCPBUGS-8301: Use correct CAs in kubeconfig files
  docs/openshift_ci.md
  pkg/cmd/init.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1486 USHIFT-289 Changes to microshift-validate/ for ARM CI
  validate-microshift/cluster-debug-info.sh
  validate-microshift/kuttl-test.sh
Labels: lgtm, approved

#1432 NP-604: Loadbalancer Service document update
  docs/config/nginx-IP-header.yaml
  docs/howto_load_balancer.md
Labels: lgtm, approved, jira/valid-reference

#1471 USHIFT-940: New ansible role to streamline devenv vm creation
  ansible/roles/create-vm/defaults/main.yml
  ansible/roles/create-vm/handlers/main.yml
  ansible/roles/create-vm/tasks/main.yml
  ansible/roles/setup-localhost/defaults/main.yml
  ansible/roles/setup-localhost/tasks/main.yml
  ansible/run-perf.yml
  ansible/setup-node.yml
  ansible/vars/all.yml
Labels: lgtm, approved, jira/valid-reference

#1502 [release-4.13] USHIFT-289: Changes to microshift-validate/ for ARM CI
  validate-microshift/cluster-debug-info.sh
  validate-microshift/kuttl-test.sh
Labels: lgtm, approved, cherry-pick-approved, bugzilla/valid-bug, backport-risk-assessed, jira/valid-reference

#1503 USHIFT-956: optimize rpm build time
  packaging/rpm/make-rpm.sh
Labels: lgtm, approved, jira/valid-reference

#1497 USHIFT-289: Add env to allow building RPM for different arch
  packaging/rpm/make-rpm.sh
Labels: lgtm, approved, cherry-pick-approved, bugzilla/valid-bug, backport-risk-assessed, jira/valid-reference

#1496 USHIFT-955: MicroShift Cockpit plugin PoC
  cockpit-plugin/.babelrc.json
  cockpit-plugin/.cirrus.yml
  cockpit-plugin/.eslintignore
  cockpit-plugin/.eslintrc.json
  cockpit-plugin/.fmf/version
  cockpit-plugin/.github/workflows/npm-update-pf.yml
  cockpit-plugin/.github/workflows/npm-update.yml
  cockpit-plugin/.github/workflows/release.yml.disabled
  cockpit-plugin/.gitignore
  cockpit-plugin/.stylelintrc.json
  cockpit-plugin/Makefile
  cockpit-plugin/README.md
  cockpit-plugin/package.json
  cockpit-plugin/packaging/cockpit-starter-kit.spec.in
  cockpit-plugin/packit.yaml
  cockpit-plugin/plans/all.fmf
  cockpit-plugin/po/de.po
  cockpit-plugin/src/YamlFile.jsx
  cockpit-plugin/src/app.jsx
  cockpit-plugin/src/app.scss
  cockpit-plugin/src/index.html
  cockpit-plugin/src/index.js
  cockpit-plugin/src/manifest.json
  cockpit-plugin/test/browser/browser.sh
  cockpit-plugin/test/browser/main.fmf
  cockpit-plugin/test/browser/run-test.sh
  cockpit-plugin/test/check-application
  cockpit-plugin/test/reference-image
  cockpit-plugin/test/run
  cockpit-plugin/test/vm.install
  cockpit-plugin/webpack.config.js
Labels: lgtm, approved, jira/valid-reference

#1510 USHIFT-960: Replace RHEL 8 references by RHEL 9 references
  README.md
  docs/devenv_cloud.md
  docs/devenv_setup.md
  docs/greenboot_dev.md
  docs/network/ovn_kubernetes_traffic_flows.md
Labels: lgtm, approved, jira/valid-reference

#1505 OCPBUGS-10347: Fix KAS' config templating during rebase
  scripts/auto-rebase/create_pr.py
  scripts/auto-rebase/rebase.py
  scripts/auto-rebase/rebase.sh
  scripts/auto-rebase/rebase_job_entrypoint.sh
Labels: lgtm, approved, cherry-pick-approved, bugzilla/valid-bug, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1513 NOISSUE: Add jira auto clone tool to scripts
  scripts/jira/cloner.py
Labels: lgtm, approved

#1518 USHIFT-976: Override journald configuration rather than editing the system files
  docs/config/microshift-starter.ks
  docs/greenboot.md
  scripts/image-builder/config/kickstart.ks.template
Labels: lgtm, approved, jira/valid-reference

#1526 USHIFT-979: Sanitize the values of wait timeout and max boots from greenboot.conf
  packaging/greenboot/functions.sh
Labels: lgtm, approved, jira/valid-reference

#1528 NO-ISSUE: update the release note generator script for RHEL 9
  scripts/release-notes/gen-ec-release-notes.py
Labels: lgtm, approved, jira/valid-reference

#1489 OCPBUGS-9996: make lvms configuration more robust
  docs/default_csi_plugin.md
  pkg/components/render.go
  pkg/components/storage.go
  pkg/config/lvmd/lvmd.go
  pkg/config/lvmd/lvmd_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1517 USHIFT-290: update ovn-kubernetes to rhel9 based image
  assets/components/ovn/master/daemonset.yaml
  assets/components/ovn/node/daemonset.yaml
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#1534 NOISSUE: Fix output directory name in devenv docs
  docs/devenv_setup.md
Labels: lgtm, approved

#1535 NO-ISSUE: Use busybox image with AMD and ARM
  docs/howto_config.md
Labels: lgtm, approved, jira/valid-reference

#1533 [release-4.13] OCPBUGS-10532: update ovn-kubernetes to rhel9 based image
  assets/components/ovn/master/daemonset.yaml
  assets/components/ovn/node/daemonset.yaml
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, cherry-pick-approved, bugzilla/valid-bug, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1521 NO-ISSUE: add sshpass to dnf install on hypervisor
  docs/devenv_setup.md
  scripts/devenv-builder/create-vm.sh
  scripts/image-builder/create-vm.sh
Labels: lgtm, approved, jira/valid-reference

#1516 PERFSCALE-2109: Bugfix wait for vnstat db to populate before recording output
  ansible/roles/microshift-start/tasks/main.yml
Labels: lgtm, approved, jira/valid-reference

#1515 USHIFT-978 Building RPMs in container
  Makefile
  packaging/images/Containerfile.rpm-builder
Labels: lgtm, approved

#1541 NOISSUE: Improve JIRA cloner
  scripts/jira/cloner.py
Labels: lgtm, approved

#1547 Fix greenboot script errors when variables are specified in /etc/greenboot/greenboot.conf file
  packaging/greenboot/functions.sh
  packaging/greenboot/microshift-pre-rollback.sh
  packaging/greenboot/microshift-running-check.sh
Labels: lgtm, approved

#1548 NOISSUE: Add user filtering and sprint handling to jira script
  scripts/jira/cloner.py
Labels: lgtm, approved

#1520 NOISSUE: Add kubeconfig management docs
  README.md
  docs/howto_kubeconfig.md
Labels: lgtm, approved

#1509 PERFSCALE-2108: Enable logging for Microshift built-in kubelet metrics
  ansible/README.md
  ansible/inventory/inventory
  ansible/roles/add-kubelet-logging/defaults/main.yml
  ansible/roles/add-kubelet-logging/files/metrics-sa.yaml
  ansible/roles/add-kubelet-logging/tasks/main.yml
  ansible/roles/configure-firewall/defaults/main.yml
  ansible/roles/create-service-account/defaults/main.yml
  ansible/roles/create-service-account/tasks/main.yml
  ansible/roles/create-service-account/tasks/metrics-sa.yaml
  ansible/roles/install-logging-exporters/defaults/main.yml
  ansible/roles/install-logging-exporters/tasks/main.yml
  ansible/roles/install-logging/templates/prometheus.yml.j2
  ansible/roles/microshift-start/tasks/main.yml
  ansible/setup-node.yml
Labels: lgtm, approved, jira/valid-reference

#1566 USHIFT-953: Dockerfile for CI's test runtime
  packaging/images/openshift-ci/Dockerfile.test-runtime
Labels: lgtm, approved, jira/valid-reference

#1556 NO-ISSUE: update release notes script to handle RC builds
  scripts/release-notes/gen-ec-release-notes.py
Labels: lgtm, approved, jira/valid-reference

#1573 OCPBUGS-10766: Stop using .local domain suffix in the MicroShift VMs
  docs/config/microshift-starter.ks
  docs/devenv_setup.md
  scripts/devenv-builder/config/kickstart.ks.template
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1565 configure-vm: add option to not install build deps
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved

#1576 USHIFT-1008: Justify why healthz endpoints are not TLS verified
  pkg/controllers/kube-controller-manager.go
  pkg/controllers/kube-scheduler.go
  pkg/node/kubelet.go
  pkg/util/net.go
Labels: lgtm, approved, jira/valid-reference

#1567 USHIFT-1011: Fix the usage of predictable file names in /tmp
  docs/devenv_setup.md
  docs/rhel4edge_iso.md
  packaging/images/openshift-ci/Dockerfile.test-runtime
  scripts/auto-rebase/get-ci-token.sh
  scripts/auto-rebase/rebase.sh
  scripts/devenv-builder/configure-vm.sh
  scripts/devenv-builder/create-vm.sh
  scripts/image-builder/configure.sh
Labels: lgtm, approved, jira/valid-reference

#1581 NO-ISSUE: rebase - remove hardcoded reviewers
  scripts/auto-rebase/rebase.py
Labels: lgtm, approved, jira/valid-reference

#1572 USHIFT-1010: Restrict created files permissions
  pkg/controllers/kube-apiserver.go
  pkg/controllers/kube-scheduler.go
  pkg/node/kubelet.go
  pkg/util/cert.go
  pkg/util/cryptomaterial/certchains/signers.go
Labels: lgtm, approved, jira/valid-reference

#1558 USHIFT-642: Static analysis for .go, .sh, and .py
  .golangci.yaml
  Makefile
  scripts/fetch_tools.sh
Labels: lgtm, approved, jira/valid-reference

#1575 OCPBUGS-10766: Change apiserver preferred addresses
  pkg/cmd/init.go
  pkg/controllers/kube-apiserver.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1591 OCPBUGS-10533: unfreeze ovn-k images
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1590 NO-ISSUE: Modify OWNERS
  OWNERS
Labels: lgtm, approved, jira/valid-reference

#1559 add storage config documentation
  docs/howto_config.md
  docs/storage/configuration.md
  docs/storage/default_csi_plugin.md
Labels: lgtm, approved

#1588 : NOISSUE: Update the LB service document by using a free host port
  docs/config/nginx-IP-header.yaml
  docs/howto_load_balancer.md
Labels: lgtm, approved

#1596 Allow password-less sudo in the R4E images
  scripts/image-builder/config/kickstart.ks.template
Labels: lgtm, approved

#1523 USHIFT-591: log when exiting due to certificate rotation
  pkg/cmd/run.go
Labels: lgtm, approved, jira/valid-reference

#1598 Fix LVM-not-detected log rendering
  pkg/components/storage.go
Labels: lgtm, approved

#1584 Start using RHEL 9.2 in the devenv and edge
  docs/devenv_setup.md
  packaging/rpm/microshift.spec
  scripts/devenv-builder/configure-vm.sh
  scripts/image-builder/configure.sh
Labels: lgtm, approved

#1600 USHIFT-950: add verification step to ensure etcd/vendor is kept up to date
  Makefile
  etcd/vendor/github.com/openshift/microshift/pkg/util/cert.go
  hack/verify-vendor-etcd.sh
Labels: lgtm, approved, jira/valid-reference

#1506 ETCD-403: Revert user configuration for etcd and change default max quota
  docs/howto_config.md
  etcd/cmd/microshift-etcd/run.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
  packaging/microshift/config.yaml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/controllers/etcd.go
Labels: lgtm, approved, jira/valid-reference
