Repository openshift/microshift, pull requests merged in 2023-06, with the labels that each got.

#1819 USHIFT-1083 `microshift admin data backup` command
  cmd/microshift/main.go
  go.mod
  pkg/admin/data/data_manager.go
  pkg/admin/data/run_check.go
  pkg/admin/data/types.go
  pkg/cmd/admin.go
  pkg/cmd/run.go
  pkg/config/files.go
  pkg/util/util.go
Labels: lgtm, approved, tide/merge-method-squash

#1861 NO-ISSUE: Add jerpeter1 to owners
  OWNERS
Labels: lgtm, approved, jira/valid-reference

#1735 USHIFT-1199: add automated tests for etcd memory limit management
  test/resources/YAML.py
  test/resources/microshift-config.resource
  test/resources/microshift-process.resource
  test/resources/systemd.resource
  test/suites/etcd.robot
Labels: lgtm, approved, jira/valid-reference

#1868 NOISSUE: [release-4.13] Fix configure-vm.sh script to use release-4.13 branch by default
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1860 USHIFT-788: Add AdvertiseAddress to kube-apiserver-service-network-signer SANs to fix OI…
  pkg/cmd/init.go
Labels: lgtm, approved, jira/valid-reference

#1855 USHIFT-1287: update image references to 4.14 EC 1 build
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  packaging/crio.conf.d/microshift_amd64.conf
  packaging/crio.conf.d/microshift_arm64.conf
Labels: lgtm, approved, jira/valid-reference

#1862 USHIFT-1292: Install GCC in dev VM
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#1873 USHIFT-1299 make SSH re-connect after reboot more robust
  e2e/tests/0040-reboot.sh
Labels: lgtm, approved

#1721 USHIFT-1049 QE: regression case failure [sig-storage] STORAGE MicroShiftOnly-Author:rdeore-Critical-59660-[MicroShift] Volumes resize on-line
  assets/components/lvms/topolvm-controller-resizer_rbac.authorization.k8s.io_v1_clusterrole.yaml
  assets/components/lvms/topolvm-controller-resizer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  docs/storage/default_csi_plugin.md
  e2e/tests/0050-pvc-resize.sh
  pkg/components/storage.go
  scripts/auto-rebase/assets.yaml
Labels: lgtm, approved

#1859 USHIFT-1291: fix gofmt for go 1.20
  pkg/controllers/kube-apiserver.go
Labels: lgtm, approved, jira/valid-reference

#1730 chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`
  go.mod
  pkg/config/lvmd/lvmd.go
  pkg/controllers/kube-controller-manager.go
Labels: lgtm, approved, ok-to-test

#1806 OCPBUGS-13221: show the effective config by default
  pkg/cmd/showConfig.go
  test/suites/show-config.robot
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1879 NO-ISSUE: make sure bash e2e tests are executable
  e2e/main.sh
Labels: lgtm, approved, jira/valid-reference

#1698 USHIFT-1123: add manifests.d support
  Makefile
  cmd/generate-config/config/config-openapi-spec.json
  docs/howto_config.md
  etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/manifests.go
  packaging/microshift/config.yaml
  packaging/rpm/microshift.spec
  pkg/config/config.go
  pkg/config/manifests.go
  pkg/config/manifests_test.go
  pkg/kustomize/apply.go
  test/resources/common.resource
  test/resources/kubeconfig.resource
  test/resources/microshift-config.resource
  test/suites/kustomize.robot
Labels: lgtm, approved, jira/valid-reference

#1884 update asset verification script to look for redundant instructions
  scripts/auto-rebase/presubmit.py
Labels: lgtm, approved

#1869 USHIFT-1298: enable cgo to support loading local libraries
  Makefile
  e2e/main.sh
  e2e/tests/0050-pvc-resize.sh
  etcd/Makefile
Labels: lgtm, approved, jira/valid-reference

#1882 USHIFT-1267: Allow for keeping container images when cleaning MicroShift data
  e2e/main.sh
  e2e/tests/assets/greenboot-test.sh
  scripts/microshift-cleanup-data.sh
Labels: lgtm, approved, jira/valid-reference

#1889 USHIFT-1296: Fix privileges to download caddy in iso builds
  scripts/image-builder/build.sh
Labels: lgtm, approved, jira/valid-reference

#1893 [USHIFT-1316] add lvms volume cloning documentation
  docs/storage/default_csi_plugin.md
Labels: documentation, lgtm, approved

#1898 NO-ISSUE: load-balancer.robot: change logging of `curl`'s `result`
  test/suites/load-balancer.robot
Labels: lgtm, approved, jira/valid-reference

#1892 USHIFT-1287, USHIFT-1315: prepare EC 1 build
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  packaging/crio.conf.d/microshift_amd64.conf
  packaging/crio.conf.d/microshift_arm64.conf
  packaging/rpm/microshift.spec
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#1900 USHIFT-1086: Refuse to start if versions of data and executable are different, refuse migration if data version > exec version
  pkg/admin/prerun/prerun.go
  pkg/admin/prerun/version.go
  pkg/admin/prerun/version_test.go
  pkg/cmd/run.go
Labels: lgtm, approved, jira/valid-reference

#1906 USHIFT-1297: Create image-builder VM as foreground process
  scripts/image-builder/create-vm.sh
Labels: lgtm, approved, jira/valid-reference

#1907 USHIFT-1327: correct instructions for using ssh-agent with RF tests
  test/README.md
Labels: lgtm, approved, jira/valid-reference

#1844 USHIFT-1280: Document multinode environment setup and runtime
  README.md
  docs/config/microshift-starter.ks
  docs/getting_started.md
  docs/multinode/config_r4e.md
  docs/multinode/config_rpm.md
  docs/multinode/setup.md
  scripts/configure-multinode.sh
  scripts/image-builder/build.sh
  scripts/multinode/configure-pri.sh
  scripts/multinode/configure-sec.sh
Labels: lgtm, approved, jira/valid-reference

#1888 OCPBUGS-13078: Remove externalGatewayInterface from configure-ovs.sh
  packaging/systemd/configure-ovs.sh
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#1905 NOISSUE: Enhance devenv docs my merging manual and automation steps
  docs/devenv_cloud.md
  docs/devenv_setup.md
  docs/devenv_setup_auto.md
Labels: lgtm, approved

#1918 NO-ISSUE: verify-gofmt
  Makefile
Labels: lgtm, approved, jira/valid-reference

#1914 USHIFT-1328: document how to pass options to the test runner
  test/README.md
Labels: lgtm, approved, jira/valid-reference

#1919 SHIFTWEEK: feat: add spec dir and move cp openapi spec file
  packaging/rpm/microshift.spec
Labels: lgtm, approved

#1866 USHIFT-1312 Test: Rebooting healthy system should result in backing up the data
  test/resources/DataFormats.py
  test/resources/microshift-config.resource
  test/resources/microshift-host.resource
  test/resources/microshift-process.resource
  test/resources/oc.resource
  test/resources/ostree.resource
  test/suites-ostree/upgrade-ostree.robot
  test/suites/show-config.robot
  test/suites/version.robot
Labels: lgtm, approved

#1913 OCPBUGS-12744: support all kustomization base filenames
  cmd/generate-config/config/config-openapi-spec.json
  docs/howto_config.md
  etcd/vendor/github.com/openshift/microshift/pkg/config/manifests.go
  packaging/microshift/config.yaml
  pkg/config/manifests.go
  pkg/config/manifests_test.go
  pkg/kustomize/apply.go
  test/suites/kustomize.robot
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1945 NO-ISSUE: make the path to a file consist
  docs/rhel4edge_iso.md
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#1944 USHIFT-1088 Refuse to start if existing data is older than 1 y-stream
  pkg/admin/prerun/version.go
  pkg/admin/prerun/version_test.go
Labels: lgtm, approved

#1940 USHIFT-1359 Change source from where release image tag is obtained from for rebase
  scripts/auto-rebase/rebase_job_entrypoint.sh
Labels: lgtm, approved

#1947 USHIFT-1357: Persist patch version along major and minor
  Makefile
  assets/version/microshift-version.yaml
  etcd/cmd/microshift-etcd/version.go
  pkg/admin/prerun/version.go
  pkg/controllers/version.go
  pkg/version/version.go
  test/suites/version.robot
Labels: lgtm, approved, jira/valid-reference

#1891 USHIFT-1313 Test: Rebooting unhealthy system results in restoring data from a backup
  test/resources/ostree.resource
  test/suites-ostree/upgrade-ostree.robot
Labels: lgtm, approved

#1954 USHIFT-1359: Rebase: write cluster registry credentials to custom path
  scripts/auto-rebase/rebase_job_entrypoint.sh
Labels: lgtm, approved, jira/valid-reference

#1949 USHIFT-1087 Simple list of blocked upgrades
  pkg/admin/prerun/upgrade_blocking.go
  pkg/admin/prerun/upgrade_blocking_test.go
  pkg/admin/prerun/version.go
Labels: lgtm, approved

#1948 USHIFT-1303: Separate libvirt installation and startup into manage-vm.sh script
  docs/devenv_cloud.md
  docs/devenv_setup.md
  docs/getting_started.md
  docs/rhel4edge_iso.md
  scripts/devenv-builder/create-vm.sh
  scripts/devenv-builder/manage-vm.sh
  scripts/image-builder/create-vm.sh
Labels: lgtm, approved, jira/valid-reference

#1941 Increase retries and backoff of loadbalancer service smoke test
  e2e/tests/0031-loadbalancer-smoke-test.sh
  test/suites/load-balancer.robot
Labels: lgtm, approved

#1958 NOISSUE: Add explicit environment requirements to the RHEL for Edge document
  docs/rhel4edge_iso.md
Labels: lgtm, approved

#1955 USHIFT-1361: Test happy ostree upgrade
  test/resources/libostree.py
  test/resources/microshift-process.resource
  test/resources/ostree.resource
  test/resources/systemd.resource
  test/suites-ostree/backup-restore.robot
  test/suites-ostree/healthy-upgrade.robot
Labels: lgtm, approved, jira/valid-reference

#1957 USHIFT-1091 USHIFT-1095: Handle upgrade from 4.13
  pkg/admin/data/data_manager.go
  pkg/admin/prerun/prerun.go
  pkg/admin/prerun/version.go
Labels: lgtm, approved, jira/valid-reference

#1692 NP-764: Enable no uplink OVN-K gateway bridge mode
  assets/components/ovn/common/clusterrole.yaml
  assets/components/ovn/single-node/master/daemonset.yaml
  docs/network/default_cni_plugin.md
  etcd/vendor/github.com/openshift/microshift/pkg/config/ovn/ovn.go
  etcd/vendor/github.com/openshift/microshift/pkg/util/net.go
  etcd/vendor/modules.txt
  packaging/microshift/ovn.yaml
  packaging/systemd/configure-ovs.sh
  packaging/systemd/microshift-ovs-init.service
  pkg/config/ovn/ovn.go
  pkg/config/ovn/test/ovn.yaml
  pkg/mdns/controller.go
  pkg/node/netconfig.go
  pkg/util/net.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#1970 NO-ISSUE: Refactor the docs into user and contributor directories
  README.md
  docs/contributor/design.md
  docs/contributor/devenv_cloud.md
  docs/contributor/devenv_setup.md
  docs/contributor/enabled_apis.md
  docs/contributor/greenboot.md
  docs/contributor/howto_quay_mirror.md
  docs/contributor/multinode/config_r4e.md
  docs/contributor/multinode/config_rpm.md
  docs/contributor/multinode/setup.md
  docs/contributor/network/default_cni_plugin.md
  docs/contributor/network/host_networking.md
  docs/contributor/network/ovn_kubernetes_traffic_flows.md
  docs/contributor/openshift_ci.md
  docs/contributor/rebase.md
  docs/contributor/rhel4edge_iso.md
  docs/contributor/rpm_packages.md
  docs/contributor/storage/configuration.md
  docs/contributor/storage/default_csi_plugin.md
  docs/images/ovn_topology.svg
  docs/user/debugging_tips.md
  docs/user/getting_started.md
  docs/user/greenboot.md
  docs/user/howto_amq_broker.md
  docs/user/howto_config.md
  docs/user/howto_firewall.md
  docs/user/howto_http_proxy.md
  docs/user/howto_kubeconfig.md
  docs/user/howto_load_balancer.md
  docs/user/howto_mirror_images.md
  docs/user/howto_offline_containers.md
  docs/user/howto_sysconf_watch.md
  docs/user/known_limitations.md
  etcd/vendor/github.com/openshift/microshift/pkg/config/manifests.go
  scripts/generate-config.sh
  scripts/verify/verify-config.sh
Labels: lgtm, approved, jira/valid-reference

#1974 Rebase 4.14.0 0.nightly 2023 06 27 233015 amd64 2023 06 27 arm64 2023 06 29
  Makefile.kube_git.var
  Makefile.version.aarch64.var
  Makefile.version.x86_64.var
  assets/components/openshift-router/service-internal.yaml
  assets/controllers/kube-apiserver/defaultconfig.yaml
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  etcd/go.mod
  etcd/go.sum
  etcd/vendor/modules.txt
  go.mod
  go.sum
  packaging/crio.conf.d/microshift_amd64.conf
  packaging/crio.conf.d/microshift_arm64.conf
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/commits.txt
  scripts/auto-rebase/last_rebase.sh
  scripts/auto-rebase/rebase_patches/0002-disable-APIrequestcount-controller.patch
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/aggregator.go
  vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/sdn_readyz_wait.go
  vendor/k8s.io/kubernetes/pkg/kubelet/preemption/preemption.go
  vendor/k8s.io/kubernetes/pkg/proxy/node.go
  vendor/k8s.io/kubernetes/plugin/pkg/admission/imagepolicy/admission.go
  vendor/k8s.io/kubernetes/plugin/pkg/admission/serviceaccount/admission.go
  vendor/modules.txt
Labels: lgtm, approved

#1975 NO-ISSUE: OSTree backup test: use full name
  test/suites-ostree/backup-restore.robot
Labels: lgtm, approved, jira/valid-reference

#1978 USHIFT-1085: feat: support prerun with minimal services
  pkg/admin/prerun/prerun.go
  pkg/admin/prerun/run_minimal.go
  pkg/cmd/run.go
Labels: lgtm, approved, jira/valid-reference

#1976 NO-ISSUE: Fix configure-vm.sh script to work on CentOS 9 Stream
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#1982 USHIFT-1380: Consider filepath as not existing even if exists but is empty
  pkg/admin/prerun/prerun.go
  pkg/admin/prerun/version.go
  pkg/util/util.go
Labels: lgtm, approved, jira/valid-reference

#1971 USHIFT-1371: Test agent for testing ostree upgrade failures
  test/agent/build.sh
  test/agent/microshift-test-agent.service
  test/agent/microshift-test-agent.sh
  test/agent/microshift-test-agent.spec
Labels: lgtm, approved, jira/valid-reference
