Repository openshift/microshift, pull requests merged in 2023-07, with the labels that each got.

#1985 NO-ISSUE: fix usage of Catenate keyword
  test/resources/ostree.resource
Labels: lgtm, approved, jira/valid-reference

#1951 USHIFT-1363: tools to build multiple images for ci
  .gitignore
  scripts/devenv-builder/manage-vm.sh
  scripts/image-builder/configure.sh
  scripts/verify/verify-shell.sh
  test/README.md
  test/bin/build_images.sh
  test/bin/ci_phase_iso_boot.sh
  test/bin/ci_phase_iso_build.sh
  test/bin/cleanup.sh
  test/bin/common.sh
  test/bin/composer_cleanup.sh
  test/bin/configure_hypervisor_firewall.sh
  test/bin/create_local_repo.sh
  test/bin/download_images.sh
  test/bin/force_vm_settings.sh
  test/bin/manage_vm_connections.sh
  test/bin/scenario.sh
  test/bin/start_osbuild_workers.sh
  test/bin/start_webserver.sh
  test/bin/wait_images.py
  test/image-blueprints/rhel92-microshift413.toml
  test/image-blueprints/rhel92-source.toml
  test/image-blueprints/rhel92.toml
  test/kickstart-templates/kickstart.ks.template
  test/package-sources/fast-datapath-rhel9.toml
  test/package-sources/microshift-local.toml
  test/package-sources/rhocp-4.13.toml
  test/resources/DataFormats.py
  test/resources/kubeconfig.resource
  test/scenario_settings.sh.example
  test/scenarios/rhel-9.2-microshift-source-backup-restore.sh
  test/scenarios/rhel-9.2-microshift-source-standard-suite.sh
  test/suites/kustomize.robot
  test/suites/load-balancer.robot
  test/variables.yaml.example
Labels: lgtm, approved, jira/valid-reference

#1983 USHIFT-1370 E2E RF Test: FIDO Device Onboarding
  test/resources/libostree.py
  test/resources/ostree.resource
  test/suites-ostree/fdo.robot
Labels: lgtm, approved

#1991 chore: pkg imported more than once
  pkg/assets/crd.go
Labels: lgtm, approved, ok-to-test

#2002 USHIFT-704: fix rebase asset.yaml for aggregate-route
  scripts/auto-rebase/assets.yaml
Labels: lgtm, approved, jira/valid-reference

#1994 USHIFT-1364: Don't overwrite health if backup wasn't created
  packaging/greenboot/microshift_set_unhealthy.sh
Labels: lgtm, approved, jira/valid-reference

#2007 [NO-ISSUE] LVMS snapshot rbac fix
  assets/components/csi-snapshot-controller/05_operand_rbac.yaml
  assets/components/lvms/topolvm-controller_rbac.authorization.k8s.io_v1_clusterrole.yaml
  assets/components/lvms/topolvm-csi-snapshotter_rbac.authorization.k8s.io_v1_clusterrole.yaml
  assets/components/lvms/topolvm-csi-snapshotter_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  pkg/components/storage.go
  scripts/auto-rebase/assets.yaml
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved

#1990 USHIFT-1388: provide a tool for quickly rebuilding source images for scenario tests
  test/bin/build_images.sh
  test/bin/rebuild_source_images.sh
  test/bin/setup_local.sh
Labels: lgtm, approved, jira/valid-reference

#2004 USHIFT-1401: rebase should only clean up files it creates
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#2009 USHIFT-1409: extend scenario.sh to make it easy to login to test vms
  test/README.md
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2018 USHIFT-1412: run virt-install in the foreground
  scripts/devenv-builder/create-vm.sh
Labels: lgtm, approved, jira/valid-reference

#2020 NO-ISSUE: Fix lichen error due to go shim usage in CI
  Makefile
  scripts/verify/verify-licenses.sh
Labels: lgtm, approved, jira/valid-reference

#1987 USHIFT-1385: boot CI VMs in parallel
  test/bin/ci_phase_iso_boot.sh
Labels: lgtm, approved, jira/valid-reference

#2013 OCPBUGS-15740: Fix show-config command output
  pkg/cmd/showConfig.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2026 Revert "feat: support prerun with minimal services"
  pkg/admin/prerun/prerun.go
  pkg/admin/prerun/run_minimal.go
  pkg/cmd/run.go
Labels: lgtm, approved

#2031 USHIFT-1411: Fix openvswitch3.1 version comparison not to use exact pattern
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#2017 [USHIFT-1398] Snapshotting config and usage documentation
  docs/contributor/storage/configuration.md
  docs/contributor/storage/default_csi_plugin.md
Labels: lgtm, approved

#2032 USHIFT-1367: Reword comment and log when health file does not exist
  pkg/admin/prerun/prerun.go
Labels: lgtm, approved, jira/valid-reference

#2036 USHIFT-1387: Add scenario test run script
  test/bin/ci_phase_test.sh
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2039 USHIFT-1395: Use file protocol for local ostree updates instead of Caddy HTTP server
  docs/contributor/rhel4edge_iso.md
  scripts/image-builder/build.sh
  scripts/image-builder/config/kickstart.ks.template
Labels: lgtm, approved, jira/valid-reference

#2033 USHIFT-1366: 4.13 upgrade logic even if health.json exists
  pkg/admin/prerun/prerun.go
Labels: lgtm, approved, jira/valid-reference

#2041 USHIFT-1428: add "rerun" command to scenario script
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2043 USHIFT-1429: set port values for new VMs by default
  test/bin/ci_phase_iso_boot.sh
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2027 USHIFT-1421 pin ovs 4.13
  packaging/rpm/microshift.spec
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#2028 USHIFT-1422: use the regular RPM repositories for dependencies in image-builder script
  scripts/image-builder/build.sh
  scripts/image-builder/cleanup.sh
  scripts/image-builder/config/blueprint_v0.0.1.toml
  scripts/image-builder/config/fast-datapath.toml.template
  scripts/image-builder/config/openshift-local.toml.template
  scripts/image-builder/config/rhocp-4.13.toml.template
Labels: lgtm, approved, jira/valid-reference

#2050 USHIFT-1387: Re-enable ssh agent in scenario testing
  test/bin/ci_phase_test.sh
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2051 USHIFT-1433: pass repo to ostree refs command
  test/bin/download_images.sh
Labels: lgtm, approved, jira/valid-reference

#2037 USHIFT-1413: Update prerun after storage migration design changes
  pkg/admin/prerun/health.go
  pkg/admin/prerun/prerun.go
  pkg/admin/prerun/upgrade_blocking.go
  pkg/admin/prerun/upgrade_blocking_test.go
  pkg/admin/prerun/version.go
  pkg/admin/prerun/version_test.go
  pkg/cmd/run.go
Labels: lgtm, approved, jira/valid-reference

#2052 USHIFT-1434: Add csi-snapshot pods to greenboot
  packaging/greenboot/microshift-running-check.sh
Labels: lgtm, approved, jira/valid-reference

#2047 USHIFT-1319: Add a message to the greenboot pod count check when it fails
  packaging/greenboot/microshift-running-check.sh
Labels: lgtm, approved, jira/valid-reference

#2055 NO-ISSUE: add __pycache__ to .gitignore
  .gitignore
Labels: lgtm, approved, jira/valid-reference

#2040 USHIFT-1391: Restore on rollback
  pkg/admin/prerun/prerun.go
Labels: lgtm, approved, jira/valid-reference

#2056 USHIFT-1395: Fix custom-rpm failure in build.sh
  scripts/image-builder/build.sh
Labels: lgtm, approved, jira/valid-reference

#1998 USHIFT-1390: Handle FDO scenario
  pkg/admin/data/data_manager.go
  pkg/admin/data/types.go
  pkg/admin/prerun/health.go
  pkg/admin/prerun/health_test.go
  pkg/admin/prerun/prerun.go
  test/resources/libostree.py
  test/resources/ostree.resource
  test/suites-ostree/fdo.robot
Labels: lgtm, approved, jira/valid-reference

#2042 USHIFT-1387: Use storage pool for scenario VM creation
  test/README.md
  test/bin/ci_phase_iso_boot.sh
  test/bin/common.sh
  test/bin/manage_vm_storage_pool.sh
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2034 USHIFT-1365: Handle missing data, but existing health
  pkg/admin/prerun/prerun.go
Labels: lgtm, approved, jira/valid-reference

#2025 USHIFT-1396: Add sos reports to scenario testing
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2061 NO-ISSUE: Add retries for dnf commands in configure-vm.sh script
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#2053 USHIFT-1382: feat: add e2e test for storage migration
  test/assets/storage-version-migration/cr.yaml
  test/assets/storage-version-migration/crd.beta.yaml
  test/assets/storage-version-migration/crd.stable.yaml
  test/suites/storage-version-migration.robot
Labels: lgtm, approved, jira/valid-reference

#2063 USHIFT-1438: Temporarily skip csi snapshot test
  test/suites/snapshot.robot
Labels: lgtm, approved, jira/valid-reference

#2049 USHIFT-1225: Remove backups for no longer existing deploys
  pkg/admin/prerun/backups.go
  pkg/admin/prerun/prerun.go
  pkg/admin/prerun/system.go
Labels: lgtm, approved, jira/valid-reference

#2062 USHIFT-1425: Fix ostree url update and user configuration in kickstart files
  docs/config/microshift-starter.ks
  scripts/image-builder/config/kickstart.ks.template
  test/kickstart-templates/kickstart.ks.template
Labels: lgtm, approved, jira/valid-reference

#2065 USHIFT-1439: manually update image references to EC3
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  packaging/crio.conf.d/microshift_amd64.conf
  packaging/crio.conf.d/microshift_arm64.conf
Labels: lgtm, approved, jira/valid-reference

#2064 USHIFT-1432: E2E RF "Rollback" test
  Makefile
  scripts/verify/verify-rf.sh
  test/Makefile
  test/bin/build_images.sh
  test/bin/ci_phase_iso_build.sh
  test/bin/ci_phase_test.sh
  test/image-blueprints/rhel92-source-fake-next-minor.toml
  test/resources/libostree.py
  test/scenarios/rhel-9.2-microshift-source-rollback.sh
  test/suites-ostree/rollback.robot
Labels: lgtm, approved, jira/valid-reference

#2058 USHIFT-1436: capture composer logs when building images
  test/bin/build_images.sh
  test/bin/download_images.sh
Labels: lgtm, approved, jira/valid-reference

#2014 USHIFT-1410: add tool to auto-transition tickets when PRs merge
  scripts/jira/README.md
  scripts/jira/manage_ticket.py
  scripts/jira/manage_ticket.sh
  scripts/jira/requirements.txt
  scripts/jira/start_ticket.sh
Labels: lgtm, approved, jira/valid-reference

#2057 USHIFT-1435: add script to report on go dependencies
  scripts/dependency_report.sh
Labels: lgtm, approved, jira/valid-reference

#2070 USHIFT-1448: remove redundant ostree setup in kickstart
  test/kickstart-templates/kickstart.ks.template
Labels: lgtm, approved, jira/valid-reference

#2071 USHIFT-1449: make storage pool manager script handle repeated calls
  test/bin/manage_vm_storage_pool.sh
Labels: lgtm, approved, jira/valid-reference

#1989 USHIFT-1098: add minor-version upgrade scenario
  packaging/rpm/make-rpm.sh
  test/Makefile
  test/bin/build_images.sh
  test/bin/ci_phase_iso_build.sh
  test/bin/common.sh
  test/bin/create_local_repo.sh
  test/bin/get_latest_rpm_version.sh
  test/bin/manage_vm_connections.sh
  test/bin/scenario.sh
  test/image-blueprints/rhel92-microshift-previous-minor.toml
  test/image-blueprints/rhel92-microshift413.toml
  test/image-blueprints/rhel92-source-fake-next-minor.toml
  test/package-sources/microshift-fake-next-minor.toml
  test/scenarios/upgrade-minor-version-healthy.sh
Labels: lgtm, approved, jira/valid-reference

#2072 NO-ISSUE: MicroShift release info RPM should be queried from the local directory
  scripts/image-builder/build.sh
Labels: lgtm, approved, jira/valid-reference

#2066 USHIFT-1320 USHIFT-1431: E2E RF Test: "block downgrade"
  test/bin/rebuild_source_images.sh
  test/resources/microshift-host.resource
  test/resources/ostree.resource
  test/scenarios/rhel-9.2-microshift-source-block-downgrade.sh
  test/suites-ostree/block-downgrade.robot
Labels: lgtm, approved, jira/valid-reference

#2074 USHIFT-1451: install all dependencies for jira tools
  scripts/jira/manage_ticket.sh
Labels: lgtm, approved, jira/valid-reference

#2075 USHIFT-1450: move firewall settings to blueprint
  test/bin/composer_cleanup.sh
  test/bin/force_vm_settings.sh
  test/bin/scenario.sh
  test/image-blueprints/rhel92-microshift-previous-minor.toml
  test/image-blueprints/rhel92-source-fake-next-minor.toml
  test/image-blueprints/rhel92-source.toml
  test/image-blueprints/rhel92.toml
  test/kickstart-templates/kickstart.ks.template
Labels: lgtm, approved, jira/valid-reference

#2076 USHIFT-1089: microshift writes version metadata file
  test/suites/version.robot
Labels: lgtm, approved, jira/valid-reference

#2081 USHIFT-1457: copy entire rpm source to local repo
  scripts/image-builder/build.sh
Labels: lgtm, approved, jira/valid-reference

#2082 USHIFT-1458: update build scripts to make rpm builds consistent
  test/README.md
  test/bin/build_images.sh
  test/bin/build_rpms.sh
  test/bin/ci_phase_iso_build.sh
  test/bin/common.sh
  test/bin/create_local_repo.sh
  test/bin/download_images.sh
  test/bin/rebuild_source_images.sh
Labels: lgtm, approved, jira/valid-reference

#2073 NO-ISSUE: Review non-ostree test harness code and docs
  Makefile
  scripts/verify/verify-shell.sh
  test/Makefile
  test/README.md
  test/bin/build_images.sh
  test/bin/build_rpms.sh
  test/bin/ci_phase_iso_boot.sh
  test/bin/ci_phase_test.sh
  test/bin/cleanup.sh
  test/bin/configure_hypervisor_firewall.sh
  test/bin/create_local_repo.sh
  test/bin/download_images.sh
  test/bin/get_latest_rpm_version.sh
  test/bin/manage_vm_connections.sh
  test/bin/manage_vm_storage_pool.sh
  test/bin/rebuild_source_images.sh
  test/bin/scenario.sh
  test/bin/setup_local.sh
  test/bin/start_osbuild_workers.sh
  test/bin/start_webserver.sh
  test/format.sh
  test/run.sh
  test/suites/version.robot
  test/variables.yaml.example
Labels: lgtm, approved, jira/valid-reference

#2090 NO-ISSUE: Simplify makefile clean target to remove the top-level directory
  Makefile
Labels: lgtm, approved, jira/valid-reference

#2088 Added clarification that pull secret has to be in composer configurat…
  docs/user/howto_offline_containers.md
Labels: lgtm, approved

#2095 OCPBUGS-16192: Use no uplink br-ex in mutlinode mode
  assets/components/ovn/multi-node/node/daemonset.yaml
  scripts/multinode/configure-pri.sh
  scripts/multinode/configure-sec.sh
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2102 OCPBUGS-16658: Fix build.sh due to the openvswitch version pinning
  scripts/image-builder/build.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2084 USHIFT-1399: Pre run filelogger
  packaging/greenboot/functions.sh
  packaging/greenboot/microshift-running-check.sh
  pkg/admin/prerun/health.go
  pkg/cmd/run.go
  pkg/util/util.go
Labels: lgtm, approved, jira/valid-reference

#2035 USHIFT-1419: Openvswitch user group workaround
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#2106 Rebase 4.14 + renaming Route Controller Manager assets
  Makefile.version.aarch64.var
  Makefile.version.x86_64.var
  assets/controllers/route-controller-manager/informer-clusterrole.yaml
  assets/controllers/route-controller-manager/informer-clusterrolebinding.yaml
  assets/controllers/route-controller-manager/route-controller-informer-clusterrole.yaml
  assets/controllers/route-controller-manager/route-controller-informer-clusterrolebinding.yaml
  assets/controllers/route-controller-manager/route-controller-manager-ingress-to-route-controller-clusterrole.yaml
  assets/controllers/route-controller-manager/route-controller-manager-ingress-to-route-controller-clusterrolebinding.yaml
  assets/controllers/route-controller-manager/route-controller-manager-leader-role.yaml
  assets/controllers/route-controller-manager/route-controller-manager-leader-rolebinding.yaml
  assets/controllers/route-controller-manager/route-controller-manager-ns.yaml
  assets/controllers/route-controller-manager/route-controller-manager-sa.yaml
  assets/controllers/route-controller-manager/route-controller-manager-separate-sa-role.yaml
  assets/controllers/route-controller-manager/route-controller-manager-separate-sa-rolebinding.yaml
  assets/controllers/route-controller-manager/route-controller-manager-tokenreview-clusterrole.yaml
  assets/controllers/route-controller-manager/route-controller-manager-tokenreview-clusterrolebinding.yaml
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  go.mod
  go.sum
  pkg/controllers/openshift-route-controller-manager.go
  scripts/auto-rebase/assets.yaml
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/commits.txt
  scripts/auto-rebase/last_rebase.sh
  vendor/github.com/openshift/cluster-policy-controller/pkg/quota/clusterquotareconciliation/reconciliation_controller.go
  vendor/github.com/openshift/cluster-policy-controller/pkg/quota/clusterquotareconciliation/workqueuebucket.go
  vendor/github.com/openshift/route-controller-manager/pkg/cmd/route-controller-manager/cmd.go
  vendor/modules.txt
Labels: lgtm, approved

#2107 USHIFT-1059: fix: rbac generator for topolvm from lvms bundle starting with 4.13
  assets/components/lvms/topolvm-controller-resizer_rbac.authorization.k8s.io_v1_clusterrole.yaml
  assets/components/lvms/topolvm-controller-resizer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  assets/components/lvms/topolvm-controller_rbac.authorization.k8s.io_v1_clusterrole.yaml
  assets/components/lvms/topolvm-controller_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  assets/components/lvms/topolvm-controller_rbac.authorization.k8s.io_v1_role.yaml
  assets/components/lvms/topolvm-controller_rbac.authorization.k8s.io_v1_rolebinding.yaml
  assets/components/lvms/topolvm-csi-provisioner_rbac.authorization.k8s.io_v1_clusterrole.yaml
  assets/components/lvms/topolvm-csi-provisioner_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  assets/components/lvms/topolvm-csi-provisioner_rbac.authorization.k8s.io_v1_role.yaml
  assets/components/lvms/topolvm-csi-provisioner_rbac.authorization.k8s.io_v1_rolebinding.yaml
  assets/components/lvms/topolvm-csi-snapshotter_rbac.authorization.k8s.io_v1_clusterrole.yaml
  assets/components/lvms/topolvm-csi-snapshotter_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  assets/components/lvms/topolvm-node_rbac.authorization.k8s.io_v1_clusterrole.yaml
  assets/components/lvms/topolvm-node_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  pkg/components/storage.go
  scripts/auto-rebase/assets.yaml
  scripts/auto-rebase/last_rebase.sh
  scripts/auto-rebase/rebase.sh
  scripts/auto-rebase/rebase_job_entrypoint.sh
Labels: lgtm, approved, jira/valid-reference

#2117 USHIFT-1490: update test image reference table
  test/README.md
  test/image-blueprints/group1/rhel92.toml
  test/image-blueprints/group2/rhel92-microshift-previous-minor.toml
  test/image-blueprints/group2/rhel92-source-fake-next-minor.toml
  test/image-blueprints/group2/rhel92-source.toml
Labels: lgtm, approved, jira/valid-reference

#2118 USHIFT-1445: feat: add e2e test for backup pruning and unknown directories
  test/resources/libostree.py
  test/scenarios/rhel-9.2-microshift-source-backup-prune.sh
  test/suites-ostree/backup-prune.robot
Labels: lgtm, approved, jira/valid-reference

#2080 USHIFT-1456: use more complete version numbers in release tagging
  scripts/release-notes/gen_ec_release_notes.py
Labels: lgtm, approved, jira/valid-reference

#2113 USHIFT-1460: Disable grub-boot-success.timer for ostree-based systems
  scripts/image-builder/config/kickstart.ks.template
  test/kickstart-templates/kickstart.ks.template
  test/resources/ostree.resource
  test/suites-ostree/fdo.robot
Labels: lgtm, approved, jira/valid-reference

#2124 OCPBUGS-16339: Add explicit version dependencies among MicroShift RPM packages
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2123 USHIFT-1445: fix: prune test
  test/resources/libostree.py
  test/suites-ostree/backup-prune.robot
Labels: lgtm, approved, jira/valid-reference

#2122 rebase 4.14.0 + fix for router assets' source path
  Makefile.version.aarch64.var
  Makefile.version.x86_64.var
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  go.mod
  go.sum
  packaging/crio.conf.d/microshift_amd64.conf
  packaging/crio.conf.d/microshift_arm64.conf
  scripts/auto-rebase/assets.yaml
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/commits.txt
  scripts/auto-rebase/last_rebase.sh
  vendor/github.com/openshift/cluster-policy-controller/pkg/quota/clusterquotareconciliation/reconciliation_controller.go
  vendor/modules.txt
Labels: lgtm, approved

#2128 USHIFT-1493: The microshift-greenboot package is no longer optional
  docs/contributor/greenboot.md
  docs/user/greenboot.md
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#2132 USHIFT-1511: add scc example
  docs/user/debugging_tips.md
  docs/user/howto_config.md
  docs/user/howto_pod_security.md
Labels: lgtm, approved, jira/valid-reference

#2114 USHIFT-1426: unpin openvswitch 4.13
  packaging/rpm/microshift.spec
  scripts/image-builder/build.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2137 Rebase 4.14.0 + sync changes to cluster-dns-operator
  Makefile.version.aarch64.var
  Makefile.version.x86_64.var
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  scripts/auto-rebase/assets.yaml
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/commits.txt
  scripts/auto-rebase/last_rebase.sh
Labels: lgtm, approved

#2133 USHIFT-1513: update rebase to work with kube-storage-version-migrator
  docs/contributor/rebase.md
  etcd/go.mod
  etcd/go.sum
  etcd/vendor/github.com/openshift/microshift/pkg/util/util.go
  etcd/vendor/modules.txt
  go.mod
  go.sum
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/commits.txt
  scripts/auto-rebase/rebase.sh
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#2099 USHIFT-1467: Upgradeability contributor's doc
  docs/contributor/updateability.md
Labels: lgtm, approved, jira/valid-reference

#2141 USHIFT-1518: deal with potential race condition in storage migration test
  test/suites/storage-version-migration.robot
Labels: lgtm, approved, jira/valid-reference

#2142 USHIFT-1520: show LVMS bundle source in rebase output for debugging
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#2143 USHIFT-1519: hard-code source of LVMS manifests
  scripts/auto-rebase/last_rebase.sh
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#2139 USHIFT-1516: Fix build.sh to properly pick up embedded container references
  Makefile
  scripts/image-builder/build.sh
Labels: lgtm, approved, jira/valid-reference
