Repository openshift/microshift, pull requests merged in 2023-10, with the labels that each got.

#2284 USHIFT-1685: Ansible Improvements Catch-up
  ansible/roles/add-kubelet-logging/defaults/main.yml
  ansible/roles/add-kubelet-logging/tasks/main.yml
  ansible/roles/common/tasks/boot.yml
  ansible/roles/create-service-account/tasks/main.yml
  ansible/roles/create-vm/defaults/main.yml
  ansible/roles/install-logging/defaults/main.yml
  ansible/roles/install-logging/tasks/main.yml
  ansible/roles/install-microshift/defaults/main.yml
  ansible/roles/install-microshift/tasks/main.yml
  ansible/roles/manage-repos/defaults/main.yml
  ansible/roles/manage-repos/tasks/main.yml
  ansible/roles/microshift-start/files/ready.sh
  ansible/roles/microshift-start/tasks/main.yml
  ansible/setup-node.yml
  ansible/vars/all.yml
Labels: lgtm, approved, jira/valid-reference

#2418 NO-ISSUE: Retrieve osbuild worker logs from iso build
  test/bin/build_images.sh
Labels: lgtm, approved, jira/valid-reference

#2412 USHIFT-1737: fix: add wait for microshift serice to make sure health check succeeds
  test/resources/microshift-process.resource
Labels: lgtm, approved, jira/valid-reference

#2425 USHIFT-1733: 1733 reenable after cleanup
  test/resources/microshift-process.resource
  test/suites/greenboot/greenboot.robot
  test/suites/standard/hostname.robot
Labels: lgtm, approved, jira/valid-reference

#2424 OCPBUGS-19632: Rework automated backup and restore
  packaging/greenboot/microshift-pre-rollback.sh
  packaging/greenboot/microshift_set_healthy.sh
  packaging/greenboot/microshift_set_unhealthy.sh
  packaging/rpm/microshift.spec
  pkg/admin/prerun/backups.go
  pkg/admin/prerun/health.go
  pkg/admin/prerun/health_test.go
  pkg/admin/prerun/prerun.go
  pkg/admin/prerun/system.go
  pkg/admin/prerun/version.go
  test/resources/ostree-data.resource
  test/resources/ostree-health.resource
  test/resources/ostree.resource
  test/scenarios-periodics/el92-src@fdo.sh
  test/scenarios-periodics/el92-src@manual-rollback.sh
  test/suites/backup/backup-prune-old.robot
  test/suites/backup/backup-restore-on-reboot.robot
  test/suites/network/isolated-network.robot
  test/suites/network/multi-nic.robot
  test/suites/upgrade/downgrade-block.robot
  test/suites/upgrade/fdo.robot
  test/suites/upgrade/rollback-manual.robot
  test/suites/upgrade/upgrade-block-2-minor.robot
  test/suites/upgrade/upgrade-fails-and-rolls-back.robot
  test/suites/upgrade/upgrade-fails-on-1st-boot-but-recovers-on-2nd.robot
  test/suites/upgrade/upgrade-successful.robot
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2411 USHIFT-1726: Pull busybox from quay.io to avoid rate limit
  test/assets/hello-microshift.yaml
Labels: lgtm, approved, jira/valid-reference

#2431 [release-4.14] OCPBUGS-20044: Cherry pick 2403 2412 2425
  test/resources/microshift-process.resource
  test/suites/greenboot/greenboot.robot
  test/suites/standard/hostname.robot
  test/suites/standard/kustomize.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2308 USHIFT-1663: Add missing psa label syncing rbac manifests
  assets/controllers/cluster-policy-controller/podsecurity-admission-label-privileged-namespaces-syncer-controller-clusterrole.yaml
  assets/controllers/cluster-policy-controller/podsecurity-admission-label-privileged-namespaces-syncer-controller-clusterrolebinding.yaml
  pkg/cmd/run.go
  pkg/controllers/cluster-policy-controller.go
  pkg/controllers/infra-services-controller.go
  scripts/auto-rebase/assets.yaml
Labels: lgtm, approved, jira/valid-reference

#2442 USHIFT-1741: Ansible script bump golang version to 1.20.3 for MicroShift 4.14
  ansible/roles/install-microshift/defaults/main.yml
  ansible/roles/setup-microshift-host/defaults/main.yml
Labels: lgtm, approved, jira/valid-reference

#2352 USHIFT-1690: multi-nic keyword bug fix
  test/resources/microshift-network.resource
  test/resources/oc.resource
  test/suites/standard/hostname.robot
  test/suites/storage/pvc-resize.robot
  test/suites/storage/reboot.robot
  test/suites/storage/snapshot.robot
Labels: lgtm, approved, jira/valid-reference

#2430 OCPBUGS-20037: Fix journal entries to belong to greenboot unit
  packaging/greenboot/functions.sh
  packaging/greenboot/microshift-running-check.sh
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2370 OCPBUGS-19422: add test to look for errors in logs
  test/resources/journalctl.py
  test/suites/standard/log-scan.robot
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2448 [release-4.14] OCPBUGS-19939: Commit busybox fix for pulling from Quay.io
  test/assets/hello-microshift.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2458 Fix typos in howto_offline_containers.md
  docs/user/howto_offline_containers.md
Labels: lgtm, approved, ok-to-test

#2443 USHIFT-1745: testing instructions for disconnected operation
  docs/user/howto_test_offline.md
Labels: lgtm, approved, jira/valid-reference

#2454 USHIFT-1725: warn the user when the logging level is unrecognized
  pkg/cmd/run.go
  pkg/cmd/showConfig.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/debugging.go
  pkg/config/debugging_test.go
  test/suites/standard/configuration.robot
Labels: lgtm, approved, jira/valid-reference

#2459 USHIFT-1695: improve template argument handling in build images
  test/bin/build_images.sh
Labels: lgtm, approved, jira/valid-reference

#2361 USHIFT-1666: Selinux domain transition test
  test/assets/selinux-test-exec.sh
  test/resources/selinux.py
  test/resources/selinux.resource
Labels: lgtm, approved, jira/valid-reference

#2469 NO-ISSUE: Correct minor issues found while reviewing howto_test_offline
  docs/user/howto_test_offline.md
Labels: lgtm, approved, jira/valid-reference

#2451 USHIFT-1746: Ansible support prerelease repos
  ansible/roles/install-microshift/defaults/main.yml
  ansible/roles/manage-repos/defaults/main.yml
  ansible/roles/manage-repos/tasks/main.yml
  ansible/roles/manage-repos/templates/ocpbeta.repo.j2
  ansible/roles/microshift-start/tasks/main.yml
  ansible/vars/all.yml
Labels: lgtm, approved, jira/valid-reference

#2470 USHIFT-1724: Add runner and minimal conformance test list
  origin/run.sh
  origin/suite.txt
Labels: lgtm, approved, jira/valid-reference

#2475 USHIFT-1766: Use mirror for unreleased RPMs for prev release
  test/bin/build_images.sh
  test/bin/get_rel_version_repo.sh
  test/image-blueprints/group2/rhel92-microshift-previous-minor.toml
  test/package-sources/microshift-prel.toml
Labels: lgtm, approved, jira/valid-reference

#2441 OCPBUGS-19363: No update of CoreDNS configmap for systemd-resolved
  assets/components/openshift-dns/dns/configmap.yaml
  pkg/components/controllers.go
  test/image-blueprints/group2/rhel92-source.toml
  test/scenarios-periodics/el92-src@osconfig.sh
  test/suites/osconfig/cleanup-data.robot
  test/suites/osconfig/systemd-resolved.robot
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#2482 USHIFT-1771: RHEL 9.3 Beta Development environment setup
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#2465 USHIFT-1628: Control test-framework guest OS and VM without network
  test/resources/libvirt.resource
  test/resources/qemu-guest-agent.py
Labels: lgtm, approved, jira/valid-reference

#2478 USHIFT-1768: Single command to rebase only images
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#2489 [release-4.14] USHIFT-1779: fix golang check in spec file
  packaging/rpm/microshift.spec
Labels: lgtm, approved, cherry-pick-approved, staff-eng-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2495 USHIFT-1778: Fix rpm spec version comparison
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#2496 USHIFT-1780: Rebase lvms registry.access.redhat.com lvms4 lvms operator bundle v4.14.0-10
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  scripts/auto-rebase/last_lvms_rebase.sh
Labels: lgtm, approved, jira/valid-reference

#2512 USHIFT-643: Add system:router cluster role
  assets/components/openshift-router/cluster-role-system-router.yaml
  pkg/components/controllers.go
  scripts/auto-rebase/assets.yaml
Labels: lgtm, approved, jira/valid-reference

#2455 USHIFT-1751: Add role to run kube-burner workloads
  ansible/roles/fetch-kubeconfig/defaults/main.yml
  ansible/roles/fetch-kubeconfig/tasks/main.yml
  ansible/roles/run-workloads/defaults/main.yml
  ansible/roles/run-workloads/tasks/kube-burner.yml
  ansible/roles/run-workloads/tasks/main.yml
  ansible/roles/setup-localhost/defaults/main.yml
  ansible/roles/setup-localhost/tasks/main.yml
  ansible/setup-node.yml
Labels: lgtm, approved, jira/valid-reference

#2484 USHIFT-1774: Add router stress tests
  origin/suite.txt
Labels: lgtm, approved, jira/valid-reference

#2528 USHIFT-1748: Remove carry patch and rebase 4.15
  Makefile.kube_git.var
  Makefile.version.aarch64.var
  Makefile.version.x86_64.var
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  etcd/go.mod
  etcd/go.sum
  etcd/vendor/modules.txt
  go.mod
  go.sum
  packaging/crio.conf.d/microshift_amd64.conf
  packaging/crio.conf.d/microshift_arm64.conf
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/commits.txt
  scripts/auto-rebase/last_rebase.sh
  scripts/auto-rebase/rebase_patches/0040-resourcequota-newmonitor.patch
  vendor/github.com/vmware/govmomi/find/finder.go
  vendor/github.com/vmware/govmomi/internal/version/version.go
  vendor/github.com/vmware/govmomi/list/lister.go
  vendor/github.com/vmware/govmomi/lookup/client.go
  vendor/github.com/vmware/govmomi/object/host_certificate_info.go
  vendor/github.com/vmware/govmomi/object/search_index.go
  vendor/github.com/vmware/govmomi/vim25/soap/client.go
  vendor/github.com/vmware/govmomi/vim25/soap/error.go
  vendor/k8s.io/apiserver/pkg/server/options/encryptionconfig/config.go
  vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/aggregator.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/downloader.go
  vendor/k8s.io/kube-aggregator/pkg/controllers/openapi/controller.go
  vendor/k8s.io/kubernetes/pkg/controller/cronjob/cronjob_controllerv2.go
  vendor/k8s.io/kubernetes/pkg/controller/job/metrics/metrics.go
  vendor/k8s.io/kubernetes/pkg/controller/podautoscaler/horizontal.go
  vendor/k8s.io/kubernetes/pkg/controller/statefulset/stateful_set_utils.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container_linux.go
  vendor/k8s.io/kubernetes/pkg/registry/core/pod/storage/eviction.go
  vendor/k8s.io/kubernetes/pkg/registry/core/service/storage/storage.go
  vendor/k8s.io/kubernetes/pkg/scheduler/internal/queue/scheduling_queue.go
  vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#2518 USHIFT-1804: Implement VM creation procedure for no-NIC scenario
  test/bin/build_images.sh
  test/bin/ci_phase_iso_build.sh
  test/bin/scenario.sh
  test/image-blueprints/group3/rhel92-source-isolated.image-installer
  test/image-blueprints/group3/rhel92-source-isolated.toml
  test/kickstart-templates/kickstart-offline.ks.template
  test/scenarios-periodics/el92-src@isolated-net.sh
  test/scenarios-periodics/el92-src@offline.sh
Labels: lgtm, approved, jira/valid-reference

#2537 USHIFT-1759: Edit origin readme
  origin/README.md
Labels: lgtm, approved, jira/valid-reference

#2530 USHIFT-1628 [BUG] Custom qemu-guest-agent library mishandles non-0 virsh status
  test/resources/qemu-guest-agent.py
Labels: lgtm, approved
