Repository openshift/microshift, pull requests merged in 2023-04, with the labels that each got.

#1608 USHIFT-1044: fix image verification test
  scripts/verify_images.sh
Labels: lgtm, approved, jira/valid-reference

#1599 NO-ISSUE: add help and argument parsing to release note script
  scripts/release-notes/gen-ec-release-notes.py
Labels: lgtm, approved, jira/valid-reference

#1607 NO-ISSUE: change default OS in VM management script to 9.2-beta
  scripts/devenv-builder/manage-vm.sh
Labels: lgtm, approved, jira/valid-reference

#1613 USHIFT-1004: delete no longer used Dockerfile
  packaging/images/openshift-ci/Dockerfile
Labels: lgtm, approved, jira/valid-reference

#1615 NO-ISSUE: Fix spelling error in getting started docs
  docs/getting_started.md
Labels: lgtm, approved, jira/valid-reference

#1618 OCPBUGS-11374: RPM: Match build and install time min versions
  packaging/rpm/microshift.spec
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1442 USHIFT-936, USHIFT-942: reconcile the internal and external config data structures
  etcd/cmd/microshift-etcd/run.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/apiserver.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/debugging.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/dns.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/etcd.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/files.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/flags.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/ingress.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/kubeconfig.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/network.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/node.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/util.go
  pkg/assets/crd.go
  pkg/cmd/init.go
  pkg/cmd/run.go
  pkg/cmd/showConfig.go
  pkg/components/components.go
  pkg/components/controllers.go
  pkg/components/networking.go
  pkg/components/render.go
  pkg/components/render_test.go
  pkg/components/storage.go
  pkg/config/apiserver.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/debugging.go
  pkg/config/debugging_test.go
  pkg/config/dns.go
  pkg/config/etcd.go
  pkg/config/files.go
  pkg/config/flags.go
  pkg/config/ingress.go
  pkg/config/kubeconfig.go
  pkg/config/network.go
  pkg/config/node.go
  pkg/config/util.go
  pkg/controllers/cluster-policy-controller.go
  pkg/controllers/etcd.go
  pkg/controllers/infra-services-controller.go
  pkg/controllers/kube-apiserver.go
  pkg/controllers/kube-controller-manager.go
  pkg/controllers/kube-controller-manager_test.go
  pkg/controllers/kube-scheduler.go
  pkg/controllers/openshift-crd-manager.go
  pkg/controllers/openshift-default-scc-manager.go
  pkg/controllers/openshift-route-controller-manager.go
  pkg/controllers/version.go
  pkg/kustomize/apply.go
  pkg/loadbalancerservice/controller.go
  pkg/mdns/controller.go
  pkg/node/kubelet.go
  pkg/node/netconfig.go
  pkg/sysconfwatch/sysconfwatch_linux.go
Labels: lgtm, approved, priority/important-longterm, jira/valid-reference

#1606 USHIFT-1032: shellcheck verify
  .shellcheckrc
  Makefile
  cockpit-plugin/test/browser/browser.sh
  cockpit-plugin/test/browser/run-test.sh
  hack/verify_images.sh
  packaging/greenboot/functions.sh
  packaging/greenboot/microshift-pre-rollback.sh
  packaging/greenboot/microshift-running-check.sh
  packaging/rpm/make-rpm.sh
  scripts/auto-rebase/get-ci-token.sh
  scripts/auto-rebase/rebase.sh
  scripts/auto-rebase/rebase_job_entrypoint.sh
  scripts/devenv-builder/configure-vm.sh
  scripts/devenv-builder/create-vm.sh
  scripts/devenv-builder/manage-vm.sh
  scripts/fetch_tools.sh
  scripts/image-builder/build.sh
  scripts/image-builder/cleanup.sh
  scripts/image-builder/configure.sh
  scripts/image-builder/create-vm.sh
  scripts/microshift-cleanup-data.sh
  scripts/review-dashboard/setup.sh
  validate-microshift/cluster-debug-info.sh
  validate-microshift/kuttl-test.sh
Labels: lgtm, approved, jira/valid-reference

#1625 USHIFT-1055: fix: quote error
  scripts/image-builder/build.sh
Labels: lgtm, approved, jira/valid-reference

#1622 USHIFT-1052: Speed up greenboot check by checking Pod restarts in parallel
  packaging/greenboot/microshift-running-check.sh
Labels: lgtm, approved, jira/valid-reference

#1624 USHIFT-662: remove user directory configuration file
  docs/howto_config.md
  etcd/vendor/github.com/openshift/microshift/pkg/config/files.go
  pkg/components/networking.go
  pkg/components/storage.go
  pkg/config/files.go
Labels: lgtm, approved, jira/valid-reference

#1631 OCPBUGS-11512: avoid requiring jq during build
  Makefile
  Makefile.version.aarch64.var
  Makefile.version.x86_64.var
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1634 USHIFT-1052: Run "Pod restart" check in background
  packaging/greenboot/microshift-running-check.sh
Labels: lgtm, approved, jira/valid-reference

#1638 OCPBUGS-11564: Explicitly install runc before building ISO images
  scripts/image-builder/configure.sh
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1642 USHIFT-1050: Add hadolint : Linter for Dockerfiles and Containerfiles
  .hadolint.yaml
  Makefile
  packaging/images/openshift-ci/Dockerfile.test-runtime
  scripts/fetch_tools.sh
Labels: lgtm, approved, jira/valid-reference

#1646 USHIFT-1071 licensecheck verify
  Makefile
  scripts/fetch_tools.sh
Labels: lgtm, approved

#1650 [release-4.13] OCPBUGS-11593: build without jq
  Makefile
  Makefile.version.aarch64.var
  Makefile.version.x86_64.var
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, cherry-pick-approved, bugzilla/valid-bug, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1647 OCPBUGS-11592: increase etcd memory limit floor
  docs/howto_config.md
  etcd/vendor/github.com/openshift/microshift/pkg/config/etcd.go
  pkg/config/config_test.go
  pkg/config/etcd.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1645 USHIFT-1053: remove user data dir
  etcd/cmd/microshift-etcd/run.go
  etcd/vendor/github.com/mitchellh/go-homedir/LICENSE
  etcd/vendor/github.com/mitchellh/go-homedir/README.md
  etcd/vendor/github.com/mitchellh/go-homedir/homedir.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/files.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/kubeconfig.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/node.go
  etcd/vendor/modules.txt
  pkg/cmd/init.go
  pkg/cmd/run.go
  pkg/components/components.go
  pkg/components/controllers.go
  pkg/components/networking.go
  pkg/config/config_test.go
  pkg/config/files.go
  pkg/config/kubeconfig.go
  pkg/config/node.go
  pkg/controllers/etcd.go
  pkg/controllers/kube-apiserver.go
  pkg/controllers/kube-controller-manager.go
  pkg/controllers/kube-scheduler.go
  pkg/controllers/openshift-route-controller-manager.go
  pkg/node/kubelet.go
  vendor/github.com/mitchellh/go-homedir/LICENSE
  vendor/github.com/mitchellh/go-homedir/README.md
  vendor/github.com/mitchellh/go-homedir/homedir.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#1656 OCPBUGS-11497:increase etcd memory limit floor
  docs/howto_config.md
  etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
  pkg/config/config.go
Labels: lgtm, approved, cherry-pick-approved, bugzilla/valid-bug, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1655 USHIFT-1050: Set textrel_shlib_t SELinux context on hadolint static executable
  scripts/fetch_tools.sh
Labels: lgtm, approved, jira/valid-reference

#1658 OCPBUGS-11635: rename ovn-kubernetes-microshift image
  assets/components/ovn/master/daemonset.yaml
  assets/components/ovn/node/daemonset.yaml
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1614 USHIFT-1030: fix pylint finding issues
  Makefile
  hack/verify-py.sh
  scripts/auto-rebase/handle_assets.py
  scripts/auto-rebase/presubmit.py
  scripts/auto-rebase/rebase.py
  scripts/auto-rebase/rebase.sh
  scripts/jira/cloner.py
  scripts/release-notes/gen_ec_release_notes.py
  scripts/requirements.txt
Labels: lgtm, approved, jira/valid-reference

#1643 OCPBUGS-11395: Remove stale kubeconfigs
  etcd/vendor/github.com/openshift/microshift/pkg/config/kubeconfig.go
  pkg/cmd/init.go
  pkg/cmd/init_test.go
  pkg/config/kubeconfig.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1636 USHIFT-1069: add script for automating ticket status based on branch
  scripts/jira/README.md
  scripts/jira/requirements.txt
  scripts/jira/start_ticket.py
  scripts/jira/start_ticket.sh
Labels: lgtm, approved, jira/valid-reference

#1662 USHIFT-1079: link to container registry credentials docs
  docs/howto_offline_containers.md
Labels: lgtm, approved, jira/valid-reference

#1659 OCPBUGS-11538: upgrade openvswitch package version for 4.14
  packaging/rpm/microshift.spec
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1673 OCPBUGS-11538: Fix rpm spec history for ovs version upgrade
  packaging/rpm/microshift.spec
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1657 USHIFT-1043: ignore case when looking at logging level
  etcd/vendor/github.com/openshift/microshift/pkg/config/debugging.go
  pkg/config/debugging.go
  pkg/config/debugging_test.go
Labels: lgtm, approved, jira/valid-reference

#1668 USHIFT-1064: lightweight, unprivileged container image "MicroShift Test"
  packaging/images/openshift-ci/Dockerfile.microshift-test
Labels: lgtm, approved, jira/valid-reference

#1674 OCPBUGS-11811: upgrade openvswitch package version for 4.13
  packaging/rpm/microshift.spec
Labels: lgtm, approved, cherry-pick-approved, bugzilla/valid-bug, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1678 USHIFT-1106: separate slow and fast verify checks
  Makefile
Labels: lgtm, approved, jira/valid-reference

#1682 OCPBUGS-7930: Add osbuild2copr.sh script to facilitate embedding of containers into ISO
  docs/rhel4edge_iso.md
  hack/osbuild2copr.sh
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1705 Unblocking CI selinux dependencies
  packaging/rpm/microshift.spec
Labels: lgtm, approved

#1697 USHIFT-974: make the kustomize paths configurable
  cockpit-plugin/packaging/config-openapi-spec.json
  docs/howto_config.md
  etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/files.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/manifests.go
  packaging/microshift/config.yaml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/files.go
  pkg/config/manifests.go
  pkg/kustomize/apply.go
Labels: lgtm, approved, jira/valid-reference

#1691 USHIFT-1064: use microshift-test image for e2e test
  e2e/tests/0030-router-smoke-test.sh
  e2e/tests/0031-loadbalancer-smoke-test.sh
  e2e/tests/assets/microshift-test.yaml
  packaging/images/openshift-ci/Dockerfile.microshift-test
Labels: lgtm, approved, jira/valid-reference

#1696 USHIFT-1121: switch uname -i to uname -m
  Makefile
  docs/devenv_cloud.md
  docs/devenv_setup.md
  docs/devenv_setup_auto.md
  docs/howto_offline_containers.md
  docs/rhel4edge_iso.md
  hack/osbuild2copr.sh
  scripts/devenv-builder/configure-vm.sh
  scripts/image-builder/build.sh
  scripts/image-builder/create-vm.sh
Labels: lgtm, approved, jira/valid-reference

#1699 USHIFT-1125: add dry-run mode to release note script
  scripts/release-notes/gen_ec_release_notes.py
Labels: lgtm, approved, jira/valid-reference

#1700 USHIFT-1061: Move hack/config-gen into cmd/generate-config directory
  assets/config/config-openapi-spec.json
  cmd/generate-config/README.md
  cmd/generate-config/cmd.go
  cmd/generate-config/configcrd/config_crd.go
  cmd/generate-config/opts.go
  cmd/generate-config/parser.go
  cmd/generate-config/templates/config-file.template.yaml
  cmd/generate-config/templates/custom-templates.tpl
  cmd/generate-config/util.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
  hack/generate-config.sh
  pkg/config/config.go
  scripts/auto-rebase/assets.yaml
  scripts/generate-config.sh
  scripts/verify/verify-config.sh
Labels: lgtm, approved, tide/merge-method-squash, jira/valid-reference

#1710 NO-ISSUE: Make authorized keys content replacement more robust in build.sh
  scripts/image-builder/build.sh
Labels: lgtm, approved, jira/valid-reference

#1724 NO-ISSUE: Add pliurh to reviewers
  OWNERS
Labels: lgtm, approved, jira/valid-reference

#1709 USHIFT-962: Standardize network configuration in config.yaml
  assets/config/config-openapi-spec.json
  docs/howto_config.md
  etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/network.go
  packaging/microshift/config.yaml
  pkg/cmd/run.go
  pkg/components/render.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/network.go
  pkg/controllers/kube-controller-manager.go
Labels: lgtm, approved, jira/valid-reference

#1712 USHIFT-1122: set minimum container-selinux dependency to 2.208
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#1725 USHIFT-1061: Move config-openapi-spec.json out of assets/config
  cmd/generate-config/README.md
  cmd/generate-config/config/config-openapi-spec.json
  scripts/auto-rebase/assets.yaml
  scripts/generate-config.sh
  scripts/verify/verify-config.sh
Labels: lgtm, approved, jira/valid-reference

#1733 USHIFT-1221: disable selinux for 4.13 CI temporarily
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, cherry-pick-approved, bugzilla/valid-bug, backport-risk-assessed, jira/valid-reference
