Repository openshift/microshift, pull requests merged in 2023-01, with the labels that each got.

#1230 Mention about default config template path in config doc
  docs/howto_config.md
Labels: lgtm, approved

#1238 Fix formatting after changing CI's image to go1.19
  pkg/controllers/cluster-policy-controller.go
  pkg/controllers/kube-scheduler.go
  pkg/controllers/openshift-crd-manager.go
  pkg/controllers/openshift-default-scc-manager.go
  pkg/controllers/version.go
  pkg/mdns/routes.go
  pkg/mdns/server/resolver.go
  pkg/mdns/server/server.go
  pkg/util/net.go
  pkg/util/sigchannel/sigchannel.go
Labels: lgtm, approved

#1242 OCPBUGS-5537: USHIFT-601 rebase: entrypoint and create_pr.py
  scripts/auto-rebase/create_pr.py
  scripts/auto-rebase/rebase_job_entrypoint.sh
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1249 USHIFT-755 Add security label to CSIDriver asset
  assets/components/lvms/csi-driver.yaml
Labels: lgtm, approved

#1243 USHIFT-740: Enable gpgcheck when installing RPMs
  docs/config/microshift-starter.ks
  docs/devenv_rhel8.md
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved

#1253 Remove stale URL and fix typo
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, approved

#1256 USHIFT-758: Include arm release in rebase branch name
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved

#1252 Updated devevn_rhel8 doc with
  docs/devenv_rhel8.md
Labels: lgtm, approved, tide/merge-method-squash

#1258 OCPBUGS-5859: Include arm release in rebase branch name
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, cherry-pick-approved, staff-eng-approved, bugzilla/valid-bug, backport-risk-assessed, jira/valid-bug

#1259 USHIFT-609: Upgrade TopoLVM image to v4.12.0-2
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
Labels: lgtm, approved

#1262 OCPBUGS-5907: Cherrypick 4.12: Upgrade TopoLVM image to v4.12.0-2
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
Labels: lgtm, approved, cherry-pick-approved, staff-eng-approved, bugzilla/valid-bug, backport-risk-assessed, jira/valid-bug

#1255 USHIFT-589: add changelog data to rebase PRs
  docs/rebase.md
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/commits.txt
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved

#1223 USHIFT-549 USHIFT-679: Python script for rebase job
  scripts/auto-rebase/create_pr.py
  scripts/auto-rebase/rebase.py
  scripts/auto-rebase/rebase.sh
  scripts/auto-rebase/rebase_job_entrypoint.sh
Labels: lgtm, approved

#1270 rebase-4.13.0-0.nightly_amd64-2023-01-17-152326_arm64-2023-01-17-171314
  Makefile
  Makefile.kube_git.var
  assets/components/openshift-router/deployment.yaml
  assets/controllers/kube-apiserver/defaultconfig.yaml
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  go.mod
  go.sum
  packaging/crio.conf.d/microshift_amd64.conf
  packaging/crio.conf.d/microshift_arm64.conf
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/commits.txt
  scripts/auto-rebase/last_rebase.sh
  scripts/auto-rebase/rebase.sh
  scripts/auto-rebase/rebase_patches/0002-disable-APIrequestcount-controller.patch
  vendor/github.com/openshift/cluster-policy-controller/pkg/quota/clusterquotareconciliation/reconciliation_controller.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
  vendor/k8s.io/kubernetes/plugin/pkg/admission/security/podsecurity/patch_podspecextractor.go
  vendor/modules.txt
Labels: lgtm, approved

#1280 USHIFT-781: add 'get' command line client
  cmd/microshift/main.go
  pkg/cmd/get.go
Labels: lgtm, approved

#1285 OCPBUGS-6080: Use rhocp-4.12 release channel for OCP dependencies
  docs/devenv_rhel8.md
  scripts/devenv-builder/configure-vm.sh
  scripts/image-builder/build.sh
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1286 OCPBUGS-6081: Use rhocp-4.12 release channel for OCP dependencies
  docs/devenv_rhel8.md
  scripts/devenv-builder/configure-vm.sh
  scripts/image-builder/build.sh
Labels: lgtm, approved, cherry-pick-approved, bugzilla/valid-bug, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1266 USHIFT-516: add changelog to rebase script in 4.12 branch
  docs/rebase.md
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/commits.txt
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, cherry-pick-approved, bugzilla/valid-bug, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1214 Update default CNI plugin doc
  README.md
  docs/default_cni_plugin.md
  docs/network/default_cni_plugin.md
Labels: lgtm, approved

#1203 NP-660: use systemd-resolved in CoreDNS configmap
  assets/components/openshift-dns/dns/configmap.yaml
  pkg/components/controllers.go
  pkg/config/config.go
  pkg/node/kubelet.go
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved

#1291 Update MetalLB how to with instructions for k8s 1.25+
  docs/config/nginx-IP-header.yaml
  docs/howto_load_balancer.md
Labels: lgtm, approved, tide/merge-method-squash

#1295 USHIFT-791: Rebase: don't change Corefile in DNS's ConfigMap
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#1299 USHIFT-794: Create rebase PR only if it contains "functional changes"
  scripts/auto-rebase/rebase.py
Labels: lgtm, approved, jira/valid-reference

#1279 USHIFT-543: Delete old rebase branches
  scripts/auto-rebase/rebase.py
Labels: lgtm, approved

#1220 NP-648: single pod ovnk
  assets/components/ovn/clusterrole.yaml
  assets/components/ovn/clusterrolebinding.yaml
  assets/components/ovn/configmap.yaml
  assets/components/ovn/master/daemonset.yaml
  assets/components/ovn/node/daemonset.yaml
  assets/components/ovn/node/serviceaccount.yaml
  assets/components/ovn/role.yaml
  assets/components/ovn/rolebinding.yaml
  pkg/components/networking.go
Labels: lgtm, approved

#1304 USHIFT-816: rebase.py - personal tokens
  scripts/auto-rebase/rebase.py
Labels: lgtm, approved, jira/valid-reference

#1300 NP-641: Avoid firewalld flush of iptables
  packaging/rpm/microshift.spec
  packaging/systemd/firewalld-no-iptables.conf
Labels: lgtm, approved, jira/valid-reference
