Repository openshift/microshift, pull requests merged in 2023-02, with the labels that each got.

#1108 USHIFT-432: CSI image / manifest rebase script
  assets/components/lvms/topolvm-controller_deployment.yaml
  assets/components/lvms/topolvm-node-metrics_v1_service.yaml
  assets/components/lvms/topolvm-node_daemonset.yaml
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  docs/rebase.md
  scripts/auto-rebase/rebase.py
  scripts/auto-rebase/rebase.sh
  scripts/auto-rebase/rebase_job_entrypoint.sh
Labels: lgtm, approved, jira/valid-reference

#1321 USHIFT-854: Set spareGB LVMD default to zero
  pkg/components/render_test.go
  pkg/config/lvmd/types.go
Labels: lgtm, approved, jira/valid-reference

#1317 USHIFT-432: Add LVMS to last_rebase.sh
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#1322 OCPBUGS-7056: fix ovn config file path
  pkg/components/networking.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1210 NP-646: Prefer OVN-K gateway IP as the nodeIP
  pkg/util/net.go
Labels: lgtm, approved

#1323 USHIFT-819: MicroShift devenv to support RHEL 9 and CentOS 9
  README.md
  ansible/README.md
  docs/default_csi_plugin.md
  docs/devenv_cloud.md
  docs/devenv_setup.md
  docs/devenv_setup_auto.md
  docs/network/default_cni_plugin.md
  docs/rebase.md
  docs/rhel4edge_iso.md
  scripts/devenv-builder/configure-vm.sh
  scripts/devenv-builder/create-vm.sh
Labels: lgtm, approved, jira/valid-reference

#1327 USHIFT-856: Reduce rebase logs by quieting git fetch
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#1330 Revert single pod ovnk
  assets/components/ovn/clusterrole.yaml
  assets/components/ovn/clusterrolebinding.yaml
  assets/components/ovn/configmap.yaml
  assets/components/ovn/master/daemonset.yaml
  assets/components/ovn/node/daemonset.yaml
  assets/components/ovn/node/serviceaccount.yaml
  assets/components/ovn/role.yaml
  assets/components/ovn/rolebinding.yaml
  pkg/components/networking.go
Labels: lgtm, approved

#1314 USHIFT-850: Document rebase job internals and testing
  docs/rebase.md
  scripts/auto-rebase/rebase_job_entrypoint.sh
Labels: lgtm, approved, jira/valid-reference

#1328 OCPBUGS-6858: Add minimum CRIO version as rpm requirement
  packaging/rpm/microshift.spec
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1334 OCPBUGS-7124: Delete microshift RPM files from rhocp repo when building ISO images
  scripts/image-builder/build.sh
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1227 Initial implementation of MicroShift integration with greenboot
  README.md
  docs/devenv_setup.md
  docs/greenboot.md
  docs/greenboot_dev.md
  packaging/greenboot/microshift-running-check.sh
  packaging/rpm/microshift.spec
  scripts/image-builder/config/blueprint_v0.0.1.toml
Labels: lgtm, approved

#1338 Add mdns service in firewalld
  docs/howto_firewall.md
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved

#1329 OCPBUGS-7139: Add minimum CRIO version as rpm requirement for MicroShift 4.12
  packaging/rpm/microshift.spec
Labels: lgtm, approved, cherry-pick-approved, bugzilla/valid-bug, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#976 ETCD-319: adding transient systemd unit for etcd
  etcd/cmd/microshift-etcd/run.go
  hack/cleanup.sh
  pkg/controllers/etcd.go
Labels: lgtm, approved

#1342 Add note for mtu change
  docs/network/default_cni_plugin.md
Labels: lgtm, approved

#1341 optionally enable mdns service in firewalld
  docs/howto_firewall.md
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved

#1344 NO-ISSUE: Fix URL formatting in rebase.md
  docs/rebase.md
Labels: lgtm, approved, jira/valid-reference

#1345 NO-ISSUE: Optional pull-secret for extracting lvms bundle
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#1309 OCPBUGS-6908: 4.12 Avoid firewalld flush of iptables
  packaging/rpm/microshift.spec
  packaging/systemd/firewalld-no-iptables.conf
Labels: lgtm, approved, cherry-pick-approved, bugzilla/valid-bug, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1352 NO-ISSUE: Update getting started doc to use release version
  docs/config/microshift-starter.ks
  docs/getting_started.md
Labels: lgtm, approved, jira/valid-reference

#1346 NO-ISSUE: fix rebase branch name for GH query
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, cherry-pick-approved, bugzilla/valid-bug, backport-risk-assessed, jira/valid-reference

#1353 USHIFT-790: always take image version from content when rebasing
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#1298 USHIFT-716: add configurable KAS advertise address
  docs/howto_config.md
  pkg/cmd/init.go
  pkg/cmd/run.go
  pkg/config/config.go
  pkg/controllers/kube-apiserver.go
  pkg/node/netconfig.go
Labels: lgtm, approved, jira/valid-reference

#1370 OCPBUGS-7444: remove firewall known issue in the doc
  docs/network/default_cni_plugin.md
  docs/network/host_networking.md
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1358 USHIFT-857: Fix image builder scripts to run on RHEL 9
  docs/rhel4edge_iso.md
  scripts/devenv-builder/configure-vm.sh
  scripts/image-builder/build.sh
  scripts/image-builder/config/kickstart.ks.template
  scripts/image-builder/configure.sh
Labels: lgtm, approved, jira/valid-reference

#1359 USHIFT-870: do not require kubeconfig to run rebase script
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#1361 USHIFT-793: add a script to automatically produce EC release notes
  scripts/release-notes/gen-ec-release-notes.py
Labels: lgtm, approved, jira/valid-reference

#1371 NO-ISSUE: bring back tabular `get pods` to debug info
  validate-microshift/cluster-debug-info.sh
Labels: lgtm, approved, jira/valid-reference

#1347 USHIFT-852: assets.yaml declaring manifests to copy from releases
  assets/components/lvms/topolvm-controller_deployment.yaml
  assets/components/lvms/topolvm-controller_rbac.authorization.k8s.io_v1_role.yaml
  assets/components/lvms/topolvm-controller_rbac.authorization.k8s.io_v1_rolebinding.yaml
  assets/components/lvms/topolvm-lvmd-config_configmap_v1.yaml
  assets/components/lvms/topolvm-node-securitycontextconstraint.yaml
  assets/components/lvms/topolvm-node_daemonset.yaml
  assets/components/lvms/topolvm-openshift-storage_namespace.yaml
  assets/components/openshift-dns/dns/daemonset.yaml
  assets/components/openshift-dns/dns/service.yaml
  assets/components/openshift-router/deployment.yaml
  assets/components/service-ca/deployment.yaml
  pkg/components/render.go
  pkg/components/render_test.go
  pkg/components/storage.go
  scripts/auto-rebase/assets.yaml
  scripts/auto-rebase/handle-assets.py
  scripts/auto-rebase/rebase.sh
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#1303 OCPBUGS-6785: Use systemd-resolved in CoreDNS configmap
  assets/components/openshift-dns/dns/configmap.yaml
  pkg/components/controllers.go
  pkg/config/config.go
  pkg/node/kubelet.go
Labels: lgtm, approved, cherry-pick-approved, bugzilla/valid-bug, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1351 USHIFT-377: make sure all files from assets/ are handled by rebase
  Makefile
  scripts/auto-rebase/presubmit.py
Labels: lgtm, approved, jira/valid-reference

#1376 USHIFT-130: Add openshift-clients to rpm for sos use
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#1372 NP-621: add doc for nodeport host addresses
  docs/network/default_cni_plugin.md
Labels: lgtm, approved, jira/valid-reference

#1377 USHIFT-885: Remove get command
  cmd/microshift/main.go
  packaging/greenboot/microshift-running-check.sh
  pkg/cmd/get.go
Labels: lgtm, approved, jira/valid-reference

#1384 USHIFT-387: simplify configuration mechanisms
  docs/howto_config.md
  go.mod
  go.sum
  pkg/cmd/run.go
  pkg/cmd/showConfig.go
  pkg/config/config.go
  pkg/config/config_test.go
  test/config.yaml
  test/config_bad_subjectaltnames.yaml
  vendor/github.com/kelseyhightower/envconfig/.travis.yml
  vendor/github.com/kelseyhightower/envconfig/LICENSE
  vendor/github.com/kelseyhightower/envconfig/MAINTAINERS
  vendor/github.com/kelseyhightower/envconfig/README.md
  vendor/github.com/kelseyhightower/envconfig/doc.go
  vendor/github.com/kelseyhightower/envconfig/env_os.go
  vendor/github.com/kelseyhightower/envconfig/env_syscall.go
  vendor/github.com/kelseyhightower/envconfig/envconfig.go
  vendor/github.com/kelseyhightower/envconfig/usage.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#1373 OCPBUGS-6859: Create empty manifest directory when installing MicroShift
  packaging/rpm/microshift.spec
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1184 USHIFT-717: Remove IPs from certificates
  etcd/cmd/microshift-etcd/run.go
  pkg/cmd/init.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/controllers/etcd.go
  pkg/controllers/kube-apiserver.go
  pkg/controllers/kube-controller-manager.go
  pkg/controllers/kube-scheduler.go
  pkg/controllers/openshift-route-controller-manager.go
  pkg/node/kubelet.go
Labels: lgtm, approved

#1236 NP-603: default to system mtu in ovnk
  assets/components/ovn/master/daemonset.yaml
  docs/network/default_cni_plugin.md
  docs/network/host_networking.md
  docs/network/ovn_kubernetes_traffic_flows.md
  pkg/config/ovn/ovn.go
Labels: lgtm, approved

#1396 USHIFT-851 remove references to lvms-operator/provisioner in manifests
  assets/components/lvms/topolvm-controller_deployment.yaml
  assets/components/lvms/topolvm-node-metrics_v1_service.yaml
  assets/components/lvms/topolvm-node_daemonset.yaml
Labels: lgtm, approved

#1387 USHIFT-498: Consolidate container images inclusion in ISO to use standard OS tools
  docs/rhel4edge_iso.md
  hack/osbuild2copr.sh
  packaging/rpm/example-user-containers.yaml
  packaging/rpm/make-microshift-images-rpm.sh
  packaging/rpm/microshift.yaml
  packaging/rpm/paack.py
  scripts/image-builder/build.sh
  scripts/image-builder/cleanup.sh
  scripts/image-builder/config/ostree-copr.toml
Labels: lgtm, approved, jira/valid-reference

#1390 USHIFT-691: Configure RPM dependencies to use packages from OCP 4.13 beta mirror site
  docs/devenv_setup.md
  scripts/devenv-builder/configure-vm.sh
  scripts/image-builder/build.sh
Labels: lgtm, approved, jira/valid-reference

#1399 USHIFT-910: Remove redundant coreos package deletion from build.sh
  scripts/image-builder/build.sh
Labels: lgtm, approved, jira/valid-reference

#1348 OCPBUGS-7205: don't advertise ovn-kubernetes local addresses in mdns
  pkg/config/ovn/ovn.go
  pkg/mdns/controller.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-important, jira/valid-reference

#1402 USHIFT-896: Enable activations of all ethernet interfaces in kickstart
  scripts/devenv-builder/config/kickstart.ks.template
  scripts/image-builder/config/kickstart.ks.template
Labels: lgtm, approved, jira/valid-reference

#1405 USHIFT-896: Use UUID for enabling automatic network device connections in kickstart
  scripts/devenv-builder/config/kickstart.ks.template
  scripts/image-builder/config/kickstart.ks.template
Labels: lgtm, approved, jira/valid-reference

#1410 USHIFT-912: Fix 4.13 devenv installation instructions to only use RHEL / CentOS 9.x
  docs/devenv_setup.md
  docs/devenv_setup_auto.md
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#1409 USHIFT-912: Update 4.12 devenv configuration instructions to use the right branch
  docs/devenv_rhel8.md
  docs/devenv_rhel8_auto.md
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, cherry-pick-approved, bugzilla/valid-bug, backport-risk-assessed, jira/valid-reference

#1391 OCPBUGS-7779: apply service ca-bundle directly to ingress configmap
  assets/components/openshift-router/configmap.yaml
  pkg/components/controllers.go
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1418 USHIFT-289: change names of release images in rebase procedure
  scripts/auto-rebase/rebase_job_entrypoint.sh
Labels: lgtm, approved, jira/valid-reference

#1354 USHIFT-148: Implement MicroShift pre-rollback Greenboot procedure
  ansible/roles/microshift-start/tasks/main.yml
  docs/config/microshift-starter.ks
  docs/devenv_setup.md
  docs/devenv_setup_auto.md
  docs/greenboot.md
  docs/greenboot_dev.md
  docs/howto_http_proxy.md
  hack/cleanup.sh
  packaging/greenboot/microshift-pre-rollback.sh
  packaging/greenboot/microshift-running-check.sh
  packaging/rpm/microshift.spec
  scripts/devenv-builder/configure-vm.sh
  scripts/image-builder/config/kickstart.ks.template
  scripts/microshift-cleanup-data.sh
Labels: lgtm, approved, jira/valid-reference

#1383 USHIFT-760: Document building microshift binaries from SRPM
  docs/rpm_packages.md
Labels: lgtm, approved, jira/valid-reference

#1417 NO-ISSUE: Add routes and kubectl firewall rules to configure-vm.sh
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#1422 USHIFT-896: Fix kickstart to edit autoconnect option in the configuration files
  scripts/image-builder/config/kickstart.ks.template
Labels: lgtm, approved, jira/valid-reference

#1419 USHIFT-289: Revert "change names of rebase image configmaps"
  scripts/auto-rebase/rebase_job_entrypoint.sh
Labels: lgtm, approved, jira/valid-reference
