Repository openshift/microshift, pull requests merged in 2023-11, with the labels that each got.

#2523 USHIFT-1801: change build_rpms.sh to create rpm with podman in CI
  Makefile
  test/bin/build_rpms.sh
Labels: lgtm, approved, jira/valid-reference

#2543 OCPBUGS-22809: Fix selinux labeling for microshift executable files
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2549 USHIFT-1760: Skip invariants with an env var
  origin/pkg/defaultmonitortests/types.go
Labels: lgtm, approved, jira/valid-reference

#2468 [release-4.14] OCPBUGS-20498: Add logs plugin to sos helper
  scripts/microshift-sos-report.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2553 USHIFT-1812: `make rpm-podman` only for x86_64
  test/bin/build_rpms.sh
Labels: lgtm, approved, jira/valid-reference

#2502 USHIFT-1777: Add rpm checks after building
  packaging/rpm/make-rpm.sh
Labels: lgtm, approved, jira/valid-reference

#2555 USHIFT-1804: Report OK status for IP and SSH in offline scenarios
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2564 [USHIFT-2378] CI: Build group3 images unconditionally
  test/bin/ci_phase_iso_build.sh
Labels: lgtm, approved

#2544 [release-4.14] OCPBUGS-22810: Fix selinux labeling for microshift executable files
  packaging/rpm/microshift.spec
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2545 USHIFT-1818: fix argument processing for login command
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2557 USHIFT-1823: add VM property abstraction to scenario.sh
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2569 USHIFT-1830: separate release branches in the review dashboard
  scripts/review-dashboard/dinghy.yaml
Labels: lgtm, approved, jira/valid-reference

#2556 USHIFT-1821: allow scenario steps to report being skipped
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2522 USHIFT-1547: Implement build ISO artifact caching in AWS S3 buckets
  scripts/fetch_tools.sh
  test/bin/ci_phase_iso_boot.sh
  test/bin/ci_phase_iso_build.sh
  test/bin/ci_phase_test.sh
  test/bin/common.sh
  test/bin/manage_build_cache.sh
Labels: lgtm, approved, jira/valid-reference

#2565 USHIFT-1820: Skip sos microshift profile if its disabled
  scripts/microshift-sos-report.sh
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2570 USHIFT-1842: bump CI golang builder to 4.15 based on RHEL9
  Makefile
Labels: lgtm, approved, jira/valid-reference

#2503 USHIFT-1405: Standard suite on RHEL-9.3
  scripts/image-builder/configure.sh
  test/bin/build_images.sh
  test/bin/ci_phase_iso_build.sh
  test/image-blueprints/group3/rhel93.image-installer
  test/image-blueprints/group3/rhel93.toml
  test/image-blueprints/group4/rhel93-source.toml
  test/requirements.txt
  test/resources/selinux.py
  test/resources/selinux.resource
  test/scenarios-periodics/el93-src@standard-suite.sh
Labels: lgtm, approved, jira/valid-reference

#2548 USHIFT-1716: Report microshift service status in the microshift-cleanup-data script
  scripts/microshift-cleanup-data.sh
Labels: lgtm, approved, jira/valid-reference

#2497 USHIFT-1781: Add unprivileged router tests
  origin/NOTES
  origin/suite.txt
  origin/test/extended/router/unprivileged.go
  origin/test/extended/util/annotate/generated/zz_generated.annotations.go
  origin/test/extended/util/pods.go
Labels: lgtm, approved, jira/valid-reference

#2560 USHIFT-1825: let scenarios override the randomization order of tests
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2561 USHIFT-1826: let scenarios skip waiting for greenboot
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2562 USHIFT-1827: add some breadcrumb output to build_rpms.sh
  test/bin/build_rpms.sh
Labels: lgtm, approved, jira/valid-reference

#2566 USHIFT-1829: add debug log for robotframework
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2567 OCPBUGS-22936: don't fail to clean up if crio is not running
  scripts/microshift-cleanup-data.sh
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2536 USHIFT-1859: Kustomization: enable server-side apply to avoid big resources failing
  pkg/kustomize/apply.go
Labels: lgtm, approved, jira/valid-reference

#2563 USHIFT-1828: add convenience keyword for running shell commands and testing results
  test/resources/microshift-host.resource
Labels: lgtm, approved, jira/valid-reference

#2483 USHIFT-1773: Add router scoped tests
  origin/NOTES
  origin/suite.txt
  origin/test/extended/router/scoped.go
  origin/test/extended/util/annotate/generated/zz_generated.annotations.go
Labels: lgtm, approved, jira/valid-reference

#2485 USHIFT-1775: Add router metrics tests
  origin/suite.txt
  origin/test/extended/router/metrics.go
Labels: lgtm, approved, jira/valid-reference

#2558 USHIFT-1824: add ssh wrapper functions to scenario.sh
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2589 USHIFT-1868: Remove readonly flag from vars in loop
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2554 OCPBUGS-22322: Don't create backups for current boot
  pkg/admin/prerun/prerun.go
  test/resources/ostree-data.resource
  test/scenarios/el92-src@backups.sh
  test/suites/backup/backups.robot
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2594 USHIFT-1873: Remove osbuild's repo substitution for RHEL9.3 to beta
  scripts/image-builder/configure.sh
Labels: lgtm, approved, jira/valid-reference

#2582 USHIFT-1762: upgrade from 9.2+4.14 to 9.3+4.15
  test/image-blueprints/group4/rhel93-crel.toml
  test/scenarios-periodics/el93-crel@upgrade-from-el92-prel.sh
  test/scenarios-periodics/el93-src@upgrade-from-el92-prel.sh
Labels: lgtm, approved, jira/valid-reference

#2584 USHIFT-1879: Test harness - change PS4 to improve debuggability
  test/bin/ci_phase_iso_boot.sh
  test/bin/ci_phase_iso_build.sh
  test/bin/ci_phase_test.sh
Labels: lgtm, approved, jira/valid-reference

#2590 USHIFT-1870: Record sos-report in junit
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2583 USHIFT-1406: Upgrade el93: crel to src
  test/scenarios-periodics/el93-crel@upgrade-to-el93-src.sh
Labels: lgtm, approved, jira/valid-reference

#2595 USHIFT-1876: enable directory listing in test harness webserver
  test/bin/start_webserver.sh
Labels: lgtm, approved, jira/valid-reference

#2585 USHIFT-1846: Reorganize image blueprints into layers of job types
  test/bin/build_images.sh
  test/bin/ci_phase_iso_build.sh
  test/image-blueprints/layer1-base/group1/rhel92.image-installer
  test/image-blueprints/layer1-base/group1/rhel92.toml
  test/image-blueprints/layer2-presubmit/group1/rhel-9.2-microshift-source-aux.alias
  test/image-blueprints/layer2-presubmit/group1/rhel92-crel.toml
  test/image-blueprints/layer2-presubmit/group1/rhel92-microshift-previous-minor.image-installer
  test/image-blueprints/layer2-presubmit/group1/rhel92-microshift-previous-minor.toml
  test/image-blueprints/layer2-presubmit/group1/rhel92-source-base.toml
  test/image-blueprints/layer2-presubmit/group1/rhel92-source-fake-next-minor.toml
  test/image-blueprints/layer2-presubmit/group1/rhel92-source-fake-yplus2-minor.toml
  test/image-blueprints/layer2-presubmit/group1/rhel92-source.toml
  test/image-blueprints/layer3-periodic/group1/rhel92-source-isolated.image-installer
  test/image-blueprints/layer3-periodic/group1/rhel92-source-isolated.toml
  test/image-blueprints/layer3-periodic/group1/rhel93.image-installer
  test/image-blueprints/layer3-periodic/group1/rhel93.toml
  test/image-blueprints/layer3-periodic/group2/rhel93-crel.toml
  test/image-blueprints/layer3-periodic/group2/rhel93-source.toml
Labels: lgtm, approved, jira/valid-reference

#2604 OCPBUGS-23220: Remove keyfile nm plugin force when installing
  packaging/network-manager-conf/microshift-nm.conf
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2602 USHIFT-1885: Reorganize test image blueprints to maximally build in layer1
  test/bin/build_images.sh
  test/bin/ci_phase_iso_build.sh
  test/bin/manage_build_cache.sh
  test/image-blueprints/layer1-base/group1/rhel93.image-installer
  test/image-blueprints/layer1-base/group1/rhel93.toml
  test/image-blueprints/layer1-base/group2/rhel92-microshift-previous-minor.image-installer
  test/image-blueprints/layer1-base/group2/rhel92-microshift-previous-minor.toml
  test/image-blueprints/layer3-periodic/group1/rhel93-crel.toml
  test/image-blueprints/layer3-periodic/group1/rhel93-source.toml
Labels: lgtm, approved, jira/valid-reference

#2609 USHIFT-1887: Archive ostree commit repo contents before uploading to S3
  test/bin/manage_build_cache.sh
Labels: lgtm, approved, jira/valid-reference

#2610 USHIFT-1845: Avoid overwriting existing build cache contents in S3 on upload
  test/bin/manage_build_cache.sh
Labels: lgtm, approved, jira/valid-reference

#2613 USHIFT-1845: Verify build cache and skip CI rebuild and upload if data already exists
  test/bin/ci_phase_iso_build.sh
Labels: lgtm, approved, jira/valid-reference

#2618 NO-ISSUE: Update osbuild and osbuild-composer
  scripts/image-builder/configure.sh
Labels: lgtm, approved, jira/valid-reference

#2598 OCPBUGS-23156: Rebase lvms registry.access.redhat.com lvms4 lvms operator bundle v4.14.1-4
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  scripts/auto-rebase/last_lvms_rebase.sh
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2542 USHIFT-1816: use the package as source of truth for version of microshift in tests
  test/resources/microshift-rpm.resource
  test/suites/standard/version.robot
Labels: lgtm, approved, jira/valid-reference

#2626 USHIFT-1525: Extract LVMS from rebase.sh into rebase-lvms.sh
  scripts/auto-rebase/last_lvms_rebase.sh
  scripts/auto-rebase/rebase-lvms.sh
  scripts/auto-rebase/rebase.sh
  scripts/auto-rebase/rebase_job_entrypoint.sh
Labels: lgtm, approved, jira/valid-reference

#2625 OCPBUGS-23436: Rebase lvms registry.access.redhat.com lvms4 lvms operator bundle v4.14.1-4
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  scripts/auto-rebase/last_lvms_rebase.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2635 USHIFT-1633: Update Go version in go.mod during rebase
  etcd/go.mod
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#2632 OCPBUGS-22858: Fix ostree status error message in greenboot on non-ostree systems
  packaging/greenboot/functions.sh
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2624 NP-849: Add instruction for configuring OVN-K log level
  docs/user/debugging_tips.md
Labels: lgtm, approved, jira/valid-reference

#2599 USHIFT-1845 USHIFT-1846: Update testing framework documentation with the new layering and caching techniques
  test/README.md
Labels: lgtm, approved, jira/valid-reference

#2608 USHIFT-1883: New assets and embedded component: Openshift lifecycle management
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-catalogsources.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-clusterserviceversions.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-installplans.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-namespace.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-olmconfigs.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-operatorconditions.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-operatorgroups.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-operators.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-packageserver.pdb.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-pprof-config.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-pprof-rbac.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-pprof-secret.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-subscriptions.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_01-olm-operator.serviceaccount.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_02-olmconfig.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_02-services.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_06-psm-operator.deployment.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_06-psm-operator.service.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_06-psm-operator.servicemonitor.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_07-collect-profiles.cronjob.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_07-olm-operator.deployment.aarch64.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_07-olm-operator.deployment.x86_64.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_08-catalog-operator.deployment.aarch64.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_08-catalog-operator.deployment.x86_64.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_09-aggregated.clusterrole.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_11-olm-operators.configmap.removed.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_12-olm-operators.catalogsource.removed.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_13-operatorgroup-default.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_14-packageserver.subscription.removed.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_15-csv-viewer.rbac.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_99-operatorstatus.yaml
  assets/optional/operator-lifecycle-manager/0000_90_olm_00-service-monitor.yaml
  assets/optional/operator-lifecycle-manager/0000_90_olm_01-prometheus-rule.yaml
  assets/optional/operator-lifecycle-manager/image-references
  assets/optional/operator-lifecycle-manager/kustomization.yaml
  assets/optional/operator-lifecycle-manager/release-aarch64.json
  assets/optional/operator-lifecycle-manager/release-x86_64.json
  scripts/auto-rebase/assets.yaml
  scripts/auto-rebase/presubmit.py
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#2534 USHIFT-1798: introduce fips periodic scenario on rpm based system
  test/bin/scenario.sh
  test/kickstart-templates/kickstart-liveimg.ks.template
  test/scenarios-periodics/el92-src@fips.sh
  test/suites/fips/validate-fips.robot
Labels: lgtm, approved, jira/valid-reference

#2378 USHIFT-1628: Test MicroShift if offline environment
  test/assets/hello-microshift-service.yaml
  test/bin/scenario.sh
  test/image-blueprints/layer3-periodic/group1/rhel92-source-isolated.toml
  test/kickstart-templates/kickstart-offline.ks.template
  test/resources/common.resource
  test/resources/libvirt.resource
  test/resources/qemu-guest-agent.py
  test/resources/systemd.resource
  test/scenarios-periodics/el92-src@offline.sh
  test/suites/network/offline.robot
Labels: lgtm, approved, jira/valid-reference

#2633 OCPBUGS-22338: Add base etcd version output to microshift-etcd
  etcd/cmd/microshift-etcd/run.go
  etcd/cmd/microshift-etcd/version.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2653 USHIFT-1942: Upgrade pyyaml version to 6.0.1 in RF
  test/requirements.txt
Labels: lgtm, approved, jira/valid-reference

#2652 USHIFT-1941: Fix osconfig tests failing due to unplanned reboots and service failures
  test/resources/systemd.resource
  test/suites/osconfig/cleanup-data.robot
  test/suites/osconfig/systemd-resolved.robot
Labels: lgtm, approved, jira/valid-reference

#2654 USHIFT-1940: use different build image for arm
  Makefile
  packaging/images/Containerfile.rpm-builder
  test/bin/build_rpms.sh
Labels: lgtm, approved, jira/valid-reference

#2631 USHIFT-1845: improve CI check_contents function in manage_build_cache
  test/bin/manage_build_cache.sh
Labels: lgtm, approved, jira/valid-reference

#2644 USHIFT-1526: Update kubelet config during rebase
  assets/core/kubelet.yaml
  pkg/node/kubelet.go
  scripts/auto-rebase/assets.yaml
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#2603 USHIFT-1949: Require openvswitch3.1 or openvswitch to allow installation on Fedora
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#2661 USHIFT-1940: update to multiplatform builder image
  Makefile
  packaging/images/Containerfile.rpm-builder
Labels: lgtm, approved, jira/valid-reference

#2668 NO-ISSUE: Update osbuild
  scripts/image-builder/configure.sh
Labels: lgtm, approved, jira/valid-reference

#2662 OPRUN-3064: OLM Update assets to include latest fixes
  assets/optional/operator-lifecycle-manager/0000_50_olm_15-csv-viewer.rbac.yaml
  assets/optional/operator-lifecycle-manager/kustomization.yaml
  scripts/auto-rebase/assets.yaml
Labels: lgtm, approved, jira/valid-reference

#2614 OPRUN-3064: RPM package for Openshift-lifecycle-manager microshfit manifests
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#2651 USHIFT-1938: Verify assets after rebase presubmit
  scripts/auto-rebase/rebase_job_entrypoint.sh
Labels: lgtm, approved, jira/valid-reference

#2643 USHIFT-1901: Retry once failed composer build
  test/bin/build_images.sh
  test/bin/wait_images.py
Labels: lgtm, approved, jira/valid-reference

#2671 NO-ISSUE: Update design.md
  docs/contributor/design.md
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#2667 USHIFT-1954: Fix the check for resolvConf option in the kubelet configuration file
  test/suites/osconfig/systemd-resolved.robot
Labels: lgtm, approved, jira/valid-reference
