Repository openshift/microshift, pull requests merged in 2023-08, with the labels that each got.

#2131 [USHIFT-1096] Add RF Test: Upgrade host from main to PR branch
  test/Makefile
  test/bin/build_images.sh
  test/bin/build_rpms.sh
  test/bin/common.sh
  test/bin/create_local_repo.sh
  test/bin/manage_vm_storage_pool.sh
  test/bin/scenario.sh
  test/image-blueprints/group2/rhel92-source-main.toml
  test/package-sources/microshift-main.toml
  test/scenarios/rhel-9.2-microshift-source-main.sh
Labels: lgtm, approved

#2109 USHIFT-1471: Use data/version for default backup name
  pkg/admin/prerun/version.go
  pkg/cmd/admin.go
Labels: lgtm, approved, jira/valid-reference

#2140 USHIFT-1510: Enhance multinode configuration scripts to be more resilient
  scripts/multinode/configure-pri.sh
  scripts/multinode/configure-sec.sh
Labels: lgtm, approved, jira/valid-reference

#2145 NO-ISSUE: Review scenario part of the test harness
  scripts/image-builder/cleanup.sh
  test/README.md
  test/bin/build_images.sh
  test/bin/rebuild_source_images.sh
  test/bin/scenario.sh
  test/bin/start_webserver.sh
Labels: lgtm, approved, jira/valid-reference

#2156 NO-ISSUE: set the correct permission for osbuild-composer
  scripts/image-builder/configure.sh
Labels: lgtm, approved, jira/valid-reference

#2144 USHIFT-1521: separate rebase of OCP and LVMS
  docs/contributor/rebase.md
  scripts/auto-rebase/assets.yaml
  scripts/auto-rebase/handle_assets.py
  scripts/auto-rebase/last_lvms_rebase.sh
  scripts/auto-rebase/lvms_assets.yaml
  scripts/auto-rebase/presubmit.py
  scripts/auto-rebase/rebase.py
  scripts/auto-rebase/rebase.sh
  scripts/auto-rebase/rebase_job_entrypoint.sh
  scripts/fetch_tools.sh
Labels: lgtm, approved, jira/valid-reference

#2108 USHIFT-1470: Add subcommand to restore a backup
  cmd/microshift/main.go
  pkg/cmd/admin.go
  test/suites-ostree/backup-restore.robot
Labels: lgtm, approved, jira/valid-reference

#2157 USHIFT-1528: Don't throw an error when there is no rollback deploy
  pkg/admin/prerun/system.go
Labels: lgtm, approved, jira/valid-reference

#2138 USHIFT-1517: add junit output for image build and VM boot steps
  test/README.md
  test/bin/build_images.sh
  test/bin/ci_phase_iso_boot.sh
  test/bin/manage_vm_connections.sh
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2125 USHIFT-1504: add more labels to rebase PRs automatically
  scripts/auto-rebase/rebase.py
Labels: lgtm, approved, jira/valid-reference

#2150 USHIFT-1389: Enhance greenboot check script to print cluster debugging information on failures
  packaging/greenboot/functions.sh
  packaging/greenboot/microshift-running-check.sh
Labels: lgtm, approved, jira/valid-reference

#2116 USHIFT-1472: Deploy and boot ID in version file to avoid unnecessary restores
  pkg/admin/prerun/prerun.go
  pkg/admin/prerun/version.go
  pkg/admin/prerun/version_test.go
  test/Makefile
  test/README.md
  test/bin/build_images.sh
  test/bin/build_rpms.sh
  test/bin/common.sh
  test/bin/create_local_repo.sh
  test/image-blueprints/group2/rhel92-source-fake-yplus2-minor.toml
  test/package-sources/microshift-fake-yplus2-minor.toml
  test/resources/microshift-host.resource
  test/scenarios/rhel-9.2-microshift-source-block-upgrade-current-2minor.sh
  test/scenarios/rhel-9.2-microshift-source-block-upgrade-previous-2minor.sh
  test/suites-ostree/block-upgrade-2-minor.robot
  test/suites/version.robot
Labels: lgtm, approved, jira/valid-reference

#2167 USHIFT-1535 Don't body.Close() if error happened
  pkg/util/net.go
Labels: lgtm, approved

#2168 NO-ISSUE: Log "pid to scenario" mapping for easier debugging
  test/bin/ci_phase_iso_boot.sh
Labels: lgtm, approved, jira/valid-reference

#2158 USHIFT-1096: adjust upgrade test to create a base from the source branch of the PR
  test/Makefile
  test/bin/build_images.sh
  test/bin/build_rpms.sh
  test/bin/common.sh
  test/bin/create_local_repo.sh
  test/image-blueprints/group2/rhel92-source-base.toml
  test/package-sources/microshift-base.toml
  test/package-sources/microshift-main.toml
  test/scenarios/rhel-9.2-microshift-source-upgrade-base-branch.sh
Labels: lgtm, approved, jira/valid-reference

#2173 USHIFT-1504: rebase labels 4.13 take 2
  scripts/auto-rebase/rebase.py
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2182 NO-ISSUE: Document how to add second interface in libvirt quay VM
  docs/contributor/howto_quay_mirror.md
Labels: lgtm, approved, jira/valid-reference

#2163 USHIFT-1392: feat: add e2e test for staged failed update scenario
  test/agent/microshift-test-agent.sh
  test/resources/ostree-data.resource
  test/resources/ostree.resource
  test/scenarios/rhel-9.2-microshift-source-failed-staged.sh
  test/suites-ostree/backup-restore.robot
  test/suites-ostree/staged-failed-upgrade.robot
Labels: lgtm, approved, jira/valid-reference

#2129 USHIFT-1487: refactor: rename prerun struct to datamanager
  pkg/admin/prerun/prerun.go
  pkg/cmd/run.go
Labels: lgtm, approved, jira/valid-reference

#2162 USHIFT-1531: Loop and timeout for getting VM IP in scenarios
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2183 USHIFT-1552: update the valid-bug label used in rebase PRs
  scripts/auto-rebase/rebase.py
Labels: lgtm, approved, jira/valid-reference

#2178 USHIFT-1512: Increase the default devenv disk size to 70GB
  docs/contributor/devenv_setup.md
  scripts/devenv-builder/manage-vm.sh
Labels: lgtm, approved, jira/valid-reference

#2115 USHIFT-1426: remove openvswitch pin in test image blueprint
  test/image-blueprints/group2/rhel92-microshift-previous-minor.toml
Labels: lgtm, approved, jira/valid-reference

#2179 USHIFT-1512: Prerequisites for automated testing of disconnected use-case
  scripts/image-builder/configure.sh
  test/README.md
  test/assets/isolated-network.xml
  test/bin/build_images.sh
  test/bin/ci_phase_iso_boot.sh
  test/bin/ci_phase_iso_build.sh
  test/bin/common.sh
  test/bin/configure_hypervisor_firewall.sh
  test/bin/manage_hypervisor_config.sh
  test/bin/manage_vm_connections.sh
  test/bin/manage_vm_storage_pool.sh
  test/bin/scenario.sh
  test/bin/setup_local.sh
  test/scenario_settings.sh.example
Labels: lgtm, approved, jira/valid-reference

#2188 NO-ISSUE: Separate golang archive installation commands
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#2193 USHIFT-1555: add timeout for long running command
  packaging/greenboot/functions.sh
Labels: lgtm, approved, jira/valid-reference

#2199 Revert "USHIFT-1555: add timeout for long running command"
  packaging/greenboot/functions.sh
Labels: lgtm, approved, jira/valid-reference

#2196 USHIFT-1566: fix valid-bug label in rebase.py on 4.13
  scripts/auto-rebase/rebase.py
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2206 USHIFT-1577: Replace caddy by nginx web server
  scripts/image-builder/configure.sh
  test/README.md
  test/bin/cleanup.sh
  test/bin/start_webserver.sh
Labels: lgtm, approved, jira/valid-reference

#2209 USHIFT-1578: Optimize virt-install and greenboot sequences in scenario.sh
  test/bin/scenario.sh
  test/scenario_settings.sh.example
Labels: lgtm, approved, jira/valid-reference

#2194 USHIFT-1551: Select a host IP as nodeIP when no default route
  etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
  etcd/vendor/github.com/openshift/microshift/pkg/util/net.go
  pkg/config/config.go
  pkg/sysconfwatch/sysconfwatch_linux.go
  pkg/util/net.go
Labels: lgtm, approved, jira/valid-reference

#2208 USHIFT-1580: Consolidate cleanup of composer / hypervisor and optimize VM boot sequence
  scripts/image-builder/cleanup.sh
  test/README.md
  test/bin/ci_phase_iso_boot.sh
  test/bin/ci_phase_iso_build.sh
  test/bin/cleanup.sh
  test/bin/cleanup_composer.sh
  test/bin/cleanup_hypervisor.sh
  test/bin/composer_cleanup.sh
  test/bin/manage_hypervisor_config.sh
Labels: lgtm, approved, jira/valid-reference

#2217 USHIFT-1578: Increase backoff between virt-install
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2219 USHIFT-1591: Optimize VM creation process by creating multiple libvirt storage pools
  test/bin/build_images.sh
  test/bin/common.sh
  test/bin/manage_hypervisor_config.sh
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2213 USHIFT-1120: migrate greenboot tests to RF
  e2e/tests/0100-greenboot.sh
  e2e/tests/assets/greenboot-test.sh
  test/assets/kustomizations/greenboot/busybox.yaml
  test/assets/kustomizations/greenboot/kustomization.yaml
  test/resources/microshift-process.resource
  test/suites/greenboot.robot
Labels: lgtm, approved, jira/valid-reference

#2223 NO-ISSUE Capture VM installation log
  scripts/image-builder/configure.sh
  test/bin/scenario.sh
Labels: lgtm, approved

#2222 USHIFT-1591: Delete the VM-specific storage pool in scenario cleanup
  test/bin/common.sh
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2177 USHIFT-1465 Refactor prerun logs
  pkg/admin/data/data_manager.go
  pkg/admin/prerun/backups.go
  pkg/admin/prerun/health.go
  pkg/admin/prerun/prerun.go
  pkg/admin/prerun/system.go
  pkg/admin/prerun/upgrade_blocking.go
  pkg/admin/prerun/version.go
  pkg/cmd/run.go
  test/resources/ostree.resource
  test/suites-ostree/block-upgrade-2-minor.robot
Labels: lgtm, approved

#2225 USHIFT-1544: Test harness: rename scenarios and discover coverage gaps
  test/README.md
  test/bin/scenario.sh
  test/scenarios-periodics/el92-src@cncf-conformance.sh
  test/scenarios-periodics/el92-src@failed-upgrade-backup-fails.sh
  test/scenarios/el92-base@upgrade-ok.sh
  test/scenarios/el92-prel@upgrade-block-2minor.sh
  test/scenarios/el92-prel@upgrade-ok.sh
  test/scenarios/el92-src@backup-and-restore-on-reboot.sh
  test/scenarios/el92-src@downgrade-block.sh
  test/scenarios/el92-src@fdo.sh
  test/scenarios/el92-src@manual-rollback.sh
  test/scenarios/el92-src@pruning-old-backups.sh
  test/scenarios/el92-src@standard-suite.sh
  test/scenarios/el92-src@upgrade-block-to-fake-y2.sh
  test/scenarios/el92-src@upgrade-fails-cannot-backup.sh
  test/scenarios/el92-src@upgrade-fails-on-1st-boot-but-reconvers-on-2nd.sh
Labels: lgtm, approved, jira/valid-reference

#2235 NO-ISSUE: Updateability contrib doc: update `version` schema
  docs/contributor/updateability.md
Labels: lgtm, approved, jira/valid-reference

#2227 USHIFT-1111: Remove kuttl (`validate-microshift/`)
  validate-microshift/.gitignore
  validate-microshift/cluster-debug-info.sh
  validate-microshift/e2e/microshift/15-assert.yaml
  validate-microshift/e2e/microshift/20-assert.yaml
  validate-microshift/e2e/microshift/25-assert.yaml
  validate-microshift/e2e/microshift/30-assert.yaml
  validate-microshift/e2e/microshift/35-assert.yaml
  validate-microshift/e2e/microshift/40-assert.yaml
  validate-microshift/kuttl-test.sh
  validate-microshift/kuttl-test.yaml
Labels: lgtm, approved, jira/valid-reference

#2240 USHIFT-1544: Change OSTree suites filenames to improve descriptiveness
  docs/contributor/updateability.md
  test/scenarios-periodics/el92-src@upgrade-fails-cannot-backup.sh
  test/scenarios/el92-base@upgrade-ok.sh
  test/scenarios/el92-prel@upgrade-block-2minor.sh
  test/scenarios/el92-prel@upgrade-ok.sh
  test/scenarios/el92-src@backup-and-restore-on-reboot.sh
  test/scenarios/el92-src@downgrade-block.sh
  test/scenarios/el92-src@manual-rollback.sh
  test/scenarios/el92-src@pruning-old-backups.sh
  test/scenarios/el92-src@upgrade-block-to-fake-y2.sh
  test/scenarios/el92-src@upgrade-fails-on-1st-boot-but-recovers-on-2nd.sh
  test/scenarios/el92-src@upgrade-fails.sh
  test/suites-ostree/backup-prune-old.robot
  test/suites-ostree/backup-restore-on-reboot.robot
  test/suites-ostree/downgrade-block.robot
  test/suites-ostree/rollback-manual.robot
  test/suites-ostree/upgrade-block-2-minor.robot
  test/suites-ostree/upgrade-fails-and-rolls-back.robot
  test/suites-ostree/upgrade-fails-on-1st-boot-but-recovers-on-2nd.robot
  test/suites-ostree/upgrade-successful.robot
Labels: lgtm, approved, jira/valid-reference

#2241 NO-ISSUE: Remove "greenboot-complete" from scenario.sh junit
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2243 USHIFT-1610: design principle updates
  docs/contributor/design.md
Labels: lgtm, approved, jira/valid-reference

#2248 USHIFT-1607: Fix bug when checking for cncf tar file
  test/scenarios-periodics/el92-src@cncf-conformance.sh
Labels: lgtm, approved, jira/valid-reference

#2249 USHIFT-1507: SOS Report to Grafana Loki
  scripts/sos-to-loki/README.md
  scripts/sos-to-loki/grafana/grafana.ini
  scripts/sos-to-loki/grafana/provisioning/datasources/loki.yaml
  scripts/sos-to-loki/loki/local-config.yaml
  scripts/sos-to-loki/pod.yaml
  scripts/sos-to-loki/promtail/config.yml
  scripts/sos-to-loki/sos-to-loki.sh
Labels: lgtm, approved, jira/valid-reference

#2195 USHIFT-1512: Add isolated network test
  test/assets/isolated-lb-service.yaml
  test/bin/ci_phase_iso_build.sh
  test/image-blueprints/group2/rhel92-source-isolated.toml
  test/kickstart-templates/kickstart.ks.template
  test/resources/microshift-host.resource
  test/resources/microshift-process.resource
  test/scenarios/el92-src@isolated-net.sh
  test/suites/isolated-net/isolated-network.robot
Labels: lgtm, approved, jira/valid-reference

#2212 USHIFT-1564: Selinux update
  packaging/rpm/microshift.spec
  packaging/selinux/microshift.fc
  packaging/selinux/microshift.te
Labels: lgtm, approved, jira/valid-reference

#2255 USHIFT-1619: Set topolvm deployment strategy recreate
  assets/components/lvms/topolvm-controller_deployment.yaml
Labels: lgtm, approved, jira/valid-reference

#2226 USHIFT-1117: migrate reboot tests to RF
  e2e/tests/0040-reboot.sh
  test/assets/reboot/pod-with-pvc.yaml
  test/resources/oc.resource
  test/suites/storage/reboot.robot
Labels: lgtm, approved, jira/valid-reference

#2190 [USHIFT-1108] Add periodic scenario to test upgrade from latest release to head of next y-stream branch or main
  test/scenarios-periodics/el92-src@upgrade-from-release-fails-and-rollsback.sh
Labels: lgtm, approved

#2258 USHIFT-1623: add support for vnc consoles to scenario vms
  test/README.md
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2247 USHIFT-1590: Event cache configuration update
  pkg/controllers/cluster-policy-controller.go
Labels: lgtm, approved, jira/valid-reference

#2263 USHIFT-1108: Rename failing upgrade from prev release scenario
  test/scenarios-periodics/el92-prel@upgrade-fails-and-rolls-back.sh
Labels: lgtm, approved, jira/valid-reference

#2267 USHIFT-1623: add VNC_CONSOLE to example scenario settings file
  test/scenario_settings.sh.example
Labels: lgtm, approved, jira/valid-reference

#2234 USHIFT-1118: Merge Router and Load-Balancer suite into single Networking
  e2e/tests/0031-loadbalancer-smoke-test.sh
  test/resources/oc.resource
  test/suites/standard/load-balancer.robot
  test/suites/standard/networking-smoke.robot
Labels: lgtm, approved, jira/valid-reference

#2265 USHIFT-1624: quiet logging about node IP
  pkg/util/net.go
Labels: lgtm, approved, jira/valid-reference

#2256 USHIFT-1620: add a script to produce the full rebase history
  scripts/auto-rebase/rebase_history.sh
Labels: lgtm, approved, jira/valid-reference

#2262 USHIFT-1622: Change method to obtain K8s version information
  Makefile.kube_git.var
  docs/contributor/rebase.md
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#2271 USHIFT-1524: migrate pvc-resize test to RF
  e2e/tests/0030-router-smoke-test.sh
  e2e/tests/0050-pvc-resize.sh
  e2e/tests/assets/microshift-test.yaml
  e2e/tests/assets/pod-with-pvc.yaml
  test/resources/oc.resource
  test/suites/storage/pvc-resize.robot
Labels: lgtm, approved, jira/valid-reference

#2279 USHIFT-1601: Implement MicroShift RPM upgrade tests on a non-ostree system
  test/bin/build_images.sh
  test/bin/create_local_repo.sh
  test/bin/scenario.sh
  test/image-blueprints/group2/rhel92-microshift-previous-minor.image-installer
  test/kickstart-templates/kickstart-liveimg.ks.template
  test/resources/microshift-rpm.resource
  test/scenarios/el92-prel@upgrade-rpm-ok.sh
  test/suites/upgrade/upgrade-rpm-successful.robot
Labels: lgtm, approved, jira/valid-reference

#2289 NO-ISSUE: Correct test file references in the docs
  docs/contributor/updateability.md
Labels: lgtm, approved, jira/valid-reference
