Repository openshift/microshift, pull requests merged in 2023-05, with the labels that each got.

#1744 USHIFT-1229: fix the location of kube-apiserver configuration assets
  scripts/auto-rebase/assets.yaml
Labels: lgtm, approved, jira/valid-reference

#1736 USHIFT-1222: make pylint configuration more static
  .pylintrc
  scripts/release-notes/gen_ec_release_notes.py
  scripts/verify/verify-py.sh
Labels: lgtm, approved, jira/valid-reference

#1743 OCPBUGS-11421: remove version specifier for container-selinux
  packaging/rpm/microshift.spec
  validate-microshift/cluster-debug-info.sh
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1745 NO-ISSUE: fixing typo with crio package in kickstart file - from criu -> crio
  docs/config/microshift-starter.ks
Labels: lgtm, approved, jira/valid-reference

#1742 USHIFT-1201 Backport configure-vm.sh to 4.13
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, cherry-pick-approved, bugzilla/valid-bug, backport-risk-assessed

#1751 USHIFT-1234: globally disable a few pylint rules that are commonly an issue
  .pylintrc
  scripts/auto-rebase/handle_assets.py
  scripts/auto-rebase/presubmit.py
  scripts/auto-rebase/rebase.py
  scripts/jira/cloner.py
  scripts/release-notes/gen_ec_release_notes.py
Labels: lgtm, approved, jira/valid-reference

#1757 USHIFT-974: fix docs and default config file for manifest locations
  cmd/generate-config/config/config-openapi-spec.json
  docs/howto_config.md
  etcd/vendor/github.com/openshift/microshift/pkg/config/manifests.go
  packaging/microshift/config.yaml
  pkg/config/manifests.go
Labels: lgtm, approved, jira/valid-reference

#1756 USHIFT-1119: Use ubi9 base image for test-runtime in CI
  packaging/images/openshift-ci/Dockerfile.test-runtime
Labels: lgtm, approved, jira/valid-reference

#1708 USHIFT-1119: Add load-balancer Robot Framework test
  test/Makefile
  test/assets/hello-microshift.yaml
  test/requirements.txt
  test/resources/common.resource
  test/resources/kubeconfig.resource
  test/suites/load-balancer.robot
  test/suites/variables.yaml
Labels: lgtm, approved, jira/valid-reference

#1767 Increase disk size validation
  docs/rhel4edge_iso.md
  scripts/image-builder/build.sh
Labels: lgtm, approved, ok-to-test

#1770 USHIFT-1235: Fix docs for RHEL DVD file names to be of the 9.2 version
  docs/devenv_cloud.md
  docs/devenv_setup.md
  docs/devenv_setup_auto.md
Labels: lgtm, approved, jira/valid-reference

#1764 OCPBUGS-13239: Remove CPU Pinning
  packaging/crio.conf.d/microshift-ovn.conf
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1732 USHIFT-1218: Implement ostree updates from the local repository and edge commit
  Makefile
  docs/rhel4edge_iso.md
  scripts/image-builder/build.sh
  scripts/image-builder/config/blueprint_v0.0.1.toml
  scripts/image-builder/config/kickstart.ks.template
Labels: lgtm, approved, jira/valid-reference

#1729 OCPBUGS-13078: Remove config flag externalGatewayInterface from ovn.yaml
  docs/network/default_cni_plugin.md
  docs/network/host_networking.md
  packaging/microshift/ovn.yaml
  pkg/config/ovn/ovn.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-important, jira/valid-reference

#1778 OCPBUGS-12977: Fix log message when CSI is disabled
  pkg/components/storage.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1765 USHIFT-1240: add runner for robot framework tests
  .gitignore
  Makefile
  test/Makefile
  test/README.md
  test/resources/kubeconfig.resource
  test/resources/microshift-host.resource
  test/run.sh
  test/variables.yaml.example
Labels: lgtm, approved, jira/valid-reference

#1777 USHIFT-986: Use UBI image and EPEL repo for running tinyproxy container for CRIO proxy doc
  docs/config/Containerfile.tinyproxy
Labels: lgtm, approved, jira/valid-reference

#1782 USHIFT-1238: pass all locals to template when creating pr message
  scripts/auto-rebase/rebase.py
Labels: lgtm, approved, jira/valid-reference

#1785 USHIFT-1235: Fix RHEL 9.2 DVD name following the operating system GA
  ansible/roles/create-vm/defaults/main.yml
  docs/devenv_cloud.md
  docs/devenv_setup.md
  docs/devenv_setup_auto.md
  scripts/devenv-builder/manage-vm.sh
Labels: lgtm, approved, jira/valid-reference

#1788 [release-4.13] USHIFT-1241: Fix RHEL 9.2 DVD name following the operating system GA
  docs/devenv_cloud.md
  docs/devenv_setup.md
  docs/devenv_setup_auto.md
  scripts/devenv-builder/manage-vm.sh
Labels: lgtm, approved, cherry-pick-approved, staff-eng-approved, bugzilla/valid-bug, backport-risk-assessed, jira/valid-reference

#1775 OCPBUGS-11967: Use ovn-k masquerade nexthop address as gateway route's default gw
  assets/components/ovn/common/configmap.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-important, jira/valid-reference

#1790 revert: add cpu pinning back
  packaging/crio.conf.d/microshift-ovn.conf
Labels: lgtm, approved

#1784 USHIFT-1082: Update test-runtime image dependencies
  packaging/images/openshift-ci/Dockerfile.test-runtime
Labels: lgtm, approved, jira/valid-reference

#1789 USHIFT-1243: Start using RHEL 9.2 repositories for devenv and image builder
  docs/devenv_setup.md
  docs/rhel4edge_iso.md
  hack/osbuild2copr.sh
  scripts/devenv-builder/configure-vm.sh
  scripts/image-builder/build.sh
  scripts/image-builder/configure.sh
Labels: lgtm, approved, jira/valid-reference

#1800 USHIFT-1238: fix changelog truncation in changelog script
  scripts/auto-rebase/rebase.py
Labels: lgtm, approved, jira/valid-reference

#1797 USHIFT-1259: update configure-vm.sh to lock RHEL minor release
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#1807 USHIFT-1263: always use ushift to find active sprints
  scripts/jira/start_ticket.py
Labels: lgtm, approved, jira/valid-reference

#1796 USHIFT-1244: Start using RHEL 9.2 repositories for devenv and image builder
  docs/devenv_setup.md
  docs/rhel4edge_iso.md
  hack/osbuild2copr.sh
  scripts/devenv-builder/configure-vm.sh
  scripts/image-builder/build.sh
  scripts/image-builder/configure.sh
Labels: lgtm, approved, cherry-pick-approved, bugzilla/valid-bug, backport-risk-assessed, jira/valid-reference

#1734 USHIFT-1198: add tests for version API
  test/resources/YAML.py
  test/resources/common.resource
  test/resources/kubeconfig.resource
  test/resources/microshift-host.resource
  test/resources/microshift-process.resource
  test/resources/oc.resource
  test/run.sh
  test/suites/version.robot
Labels: lgtm, approved, jira/valid-reference

#1831 [release-4.13] USHIFT-1271: Switch to rhocp-4.13 repositories in devenv and ISO build environments
  scripts/devenv-builder/configure-vm.sh
  scripts/image-builder/build.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1830 USHIFT-1270: The ISO image version should be deduced from the microshift RPM
  scripts/image-builder/build.sh
  scripts/image-builder/cleanup.sh
  scripts/image-builder/create-vm.sh
Labels: lgtm, approved, jira/valid-reference

#1804 USHIFT-1250: Add an option to build.sh to customize open firewall ports
  docs/rhel4edge_iso.md
  scripts/image-builder/build.sh
Labels: lgtm, approved, jira/valid-reference

#1717 USHIFT-1202: Use hostnames over IPs in apiserver when connecting to kubelet
  pkg/controllers/kube-apiserver.go
Labels: lgtm, approved, jira/valid-reference

#1832 USHIFT-1246: Enable custom variables file and venv dir in RF
  test/run.sh
Labels: lgtm, approved, jira/valid-reference

#1726 USHIFT-485: Add script which adds worker node running via kubelet
  scripts/configure-multinode.sh
Labels: lgtm, approved, jira/valid-reference

#1837 NO-ISSUE Update python scripts to use python3
  scripts/auto-rebase/rebase.py
  scripts/jira/start_ticket.py
Labels: lgtm, approved

#1840 Ensure pip is up to date within the Robot Framework venv.
  test/run.sh
Labels: lgtm, approved

#1820 USHIFT-1268: add linter for robotframework files
  Makefile
  scripts/fetch_tools.sh
  scripts/verify/verify-rf.sh
  test/requirements.txt
  test/resources/common.resource
  test/resources/kubeconfig.resource
  test/resources/microshift-host.resource
  test/resources/microshift-process.resource
  test/resources/oc.resource
  test/run.sh
  test/suites/load-balancer.robot
Labels: lgtm, approved, jira/valid-reference

#1838 USHIFT-1281: Add CI Troubleshooting section to the docs
  docs/images/pcp_charts.png
  docs/openshift_ci.md
Labels: lgtm, approved, jira/valid-reference

#1845 USHIFT-898: Port getting started instructions to work on RHEL 9.2 with MicroShift 4.13
  docs/config/microshift-starter.ks
  docs/getting_started.md
Labels: lgtm, approved, jira/valid-reference

#1850 USHIFT-957: [release-4.13] Port Getting Started instructions to use RHEL 9.2 and MicroShift 4.13
  docs/config/microshift-starter.ks
  docs/getting_started.md
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1854 USHIFT-1286: Use exit code 1 in greenboot failures
  packaging/greenboot/microshift-running-check.sh
Labels: lgtm, approved, jira/valid-reference

#1843 USHIFT-1284: make test login to microshift host more reliable
  test/resources/microshift-host.resource
  test/variables.yaml.example
Labels: lgtm, approved, jira/valid-reference
