Repository openshift/microshift, pull requests merged in 2023-12, with the labels that each got.

#2676 USHIFT-1963: ignore 4.14 for candidate release notes
  scripts/release-notes/gen_ec_release_notes.py
Labels: lgtm, approved, jira/valid-reference

#2677 USHIFT-1952: Retry after microshift-cleanup-data when greenboot reports a failure in scenario.sh
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2678 USHIFT-1961: make sure FIPS compliance test runs on a stopped system
  test/suites/fips/validate-fips.robot
Labels: lgtm, approved, jira/valid-reference

#2684 USHIFT-1967: keep sos_report on EXIT trap
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2663 USHIFT-1861 Router/Ingress Smoke tests should wait for env cleanup
  test/suites/standard/networking-smoke.robot
Labels: lgtm, approved

#2687 USHIFT-1961: add stderr to FIPS test
  test/suites/fips/validate-fips.robot
Labels: lgtm, approved, jira/valid-reference

#2634 OCPBUGS-22854: The microshift-release-info RPM is no longer required and it contains sample blueprints
  Makefile
  packaging/blueprint/blueprint.toml.template
  packaging/images/Containerfile.rpm-builder
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2696 USHIFT-1974: Add microshift-olm to build.sh blueprint
  scripts/image-builder/config/blueprint_v0.0.1.toml
Labels: lgtm, approved, jira/valid-reference

#2648 USHIFT-1769: Abort rebase if manifests change
  assets/optional/operator-lifecycle-manager/0000_50_olm_07-olm-operator.deployment.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_08-catalog-operator.deployment.yaml
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#2697 USHIFT-1961: skip running FIPS tests on ARM architecture
  test/scenarios-periodics/el92-src@fips.sh
Labels: lgtm, approved, jira/valid-reference

#2699 USHIFT-1977: add strictfipsruntime tag to microshift binary build
  Makefile
Labels: lgtm, approved, jira/valid-reference

#2692 USHIFT-1973: RF test for OLM
  scripts/microshift-cleanup-data.sh
  test/assets/olm/catalog-source.yaml
  test/assets/olm/subscription-cert-manager.yaml
  test/image-blueprints/layer3-periodic/group1/rhel92-source-with-optionals.toml
  test/resources/oc.resource
  test/scenarios-periodics/el92-src@optional.sh
  test/suites/optional/olm.robot
Labels: lgtm, approved, jira/valid-reference

#2703 USHIFT-1975: add check-payload test rpm scan to fips scenario
  Makefile
  test/image-blueprints/layer3-periodic/group1/rhel92-source-isolated.toml
  test/suites/fips/validate-fips.robot
Labels: lgtm, approved, jira/valid-reference

#2707 remove quotes from argument passed to keyword
  test/resources/common.resource
  test/resources/microshift-network.resource
  test/suites/standard/networking-smoke.robot
Labels: lgtm, approved

#2713 USHIFT-2011: snapshot test should end with healthy system
  test/suites/storage/snapshot.robot
Labels: lgtm, approved, jira/valid-reference

#2647 OCPQE-17114: Stress Testing
  scripts/image-builder/config/blueprint_v0.0.1.toml
  test/bin/scenario.sh
  test/bin/stress_testing.sh
  test/image-blueprints/layer1-base/group1/rhel92.toml
  test/image-blueprints/layer1-base/group1/rhel93.toml
  test/run.sh
Labels: lgtm, approved, jira/valid-reference

#2722 USHIFT-2044: Enable RHEL CDN repos to avoid RHUI issues
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#2721 set DEST_DIR before fetch_tools.sh script
  test/run.sh
Labels: lgtm, approved

#2733 USHIFT-2048: Backport FIPS fixes [4.15]
  Makefile
  scripts/image-builder/configure.sh
  test/image-blueprints/layer3-periodic/group1/rhel92-source-isolated.toml
  test/scenarios-periodics/el92-src@fips.sh
  test/suites/fips/validate-fips.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2736 NO-ISSUE: Update osbuild
  scripts/image-builder/configure.sh
Labels: lgtm, approved, jira/valid-reference

#2700 USHIFT-1955: Implement microshift-olm plugin altering greenboot functionality
  packaging/greenboot/functions.sh
  packaging/greenboot/microshift-running-check-olm.sh
  packaging/greenboot/microshift-running-check.sh
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#2670 USHIFT-1926: Implement certificate cleanup option in microshift-cleanup-data script
  scripts/microshift-cleanup-data.sh
  test/resources/common.resource
  test/suites/osconfig/cleanup-data.robot
Labels: lgtm, approved, jira/valid-reference

#2725 USHIFT-1971: stop etcd if active before starting
  pkg/controllers/etcd.go
Labels: lgtm, approved, jira/valid-reference

#2726 USHIFT-2046: Source common.sh after deps are installed
  test/bin/ci_phase_iso_build.sh
Labels: lgtm, approved, jira/valid-reference

#2727 USHIFT-2047: Source common.sh after deps are installed [4.15]
  test/bin/ci_phase_iso_build.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2683 USHIFT-1956: Add mirror registry options to test harness
  test/README.md
  test/bin/ci_phase_iso_boot.sh
  test/bin/mirror_registry.sh
  test/bin/scenario.sh
  test/kickstart-templates/kickstart.ks.template
Labels: lgtm, approved, jira/valid-reference

#2724 USHIFT-1861: Fix network smoke tests flakes
  assets/components/openshift-router/deployment.yaml
  scripts/auto-rebase/rebase.sh
  test/suites/standard/networking-smoke.robot
Labels: lgtm, approved, jira/valid-reference

#2745 USHIFT-2063: Display manage_build_cache.sh output for getlast command during CI builds
  test/bin/ci_phase_iso_build.sh
Labels: lgtm, approved, jira/valid-reference

#2740 USHIFT-2071: LVMS docs should include cases where no vgs exist on the system
  docs/contributor/storage/default_csi_plugin.md
Labels: lgtm, approved, jira/valid-reference

#2751 USHIFT-2062: Remove FIPS tests from 4.14
  test/scenarios-periodics/el92-src@fips.sh
  test/suites/fips/validate-fips.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2752 USHIFT-1961: FIPS test log information about microshift RPM
  test/suites/fips/validate-fips.robot
Labels: lgtm, approved, jira/valid-reference

#2756 USHIFT-1961: remove golang cache when building from ART container
  Makefile
Labels: lgtm, approved, jira/valid-reference

#2750 USHIFT-2063: Make fetch_tools.sh more robust when parsing function names
  scripts/fetch_tools.sh
Labels: lgtm, approved, jira/valid-reference

#2757 USHIFT-1956: Reinstate greenboot fail fast checks
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2669 USHIFT-1860: introduce certificate rotation tests
  test/suites/standard/validate-certificate-rotation.robot
Labels: lgtm, approved, jira/valid-reference

#2748 USHIFT-2068: Implement retries on failed skopeo in mirror-images.sh
  scripts/image-builder/mirror-images.sh
Labels: lgtm, approved, jira/valid-reference

#2762 USHIFT-2080: configure-vm.sh: skip dnf update on demand
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#2764 USHIFT-2085: RPM produced when building base branch should not use the default name
  test/Makefile
Labels: lgtm, approved, jira/valid-reference

#2770 OCPBUGS-24444: Check topolvm only when it should be deployed
  packaging/greenboot/microshift-running-check.sh
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2766 USHIFT-2067: Use registry mirror in all architectures
  test/bin/ci_phase_iso_boot.sh
  test/bin/mirror_registry.sh
  test/bin/scenario.sh
  test/kickstart-templates/kickstart.ks.template
Labels: lgtm, approved, jira/valid-reference

#2739 USHIFT-2053: only install osbuild from COPR on RHEL 9.3
  scripts/image-builder/configure.sh
Labels: lgtm, approved, jira/valid-reference

#2777 USHIFT-2067: Enable insecure in kickstart template
  test/kickstart-templates/kickstart.ks.template
Labels: lgtm, approved, jira/valid-reference

#2778 [release-4.15] USHIFT-2103: Add registry mirror to metal jobs
  test/README.md
  test/bin/ci_phase_iso_boot.sh
  test/bin/mirror_registry.sh
  test/bin/scenario.sh
  test/kickstart-templates/kickstart.ks.template
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2760 USHIFT-2078: Dynamically use latest available RHOCP repo
  scripts/devenv-builder/configure-vm.sh
  scripts/get-latest-rhocp-repo.sh
  scripts/image-builder/build.sh
  scripts/image-builder/config/rhocp-4.14.toml.template
  scripts/image-builder/config/rhocp.toml.template
  test/bin/build_images.sh
  test/package-sources/rhocp-4.14.toml
  test/package-sources/rhocp.toml
Labels: lgtm, approved, jira/valid-reference

#2746 USHIFT-1968: SELinux syntax cleanup
  packaging/selinux/microshift.fc
  packaging/selinux/microshift.te
  test/resources/selinux.py
Labels: lgtm, approved, jira/valid-reference

#2787 USHIFT-2108: get-latest-rhocp-repo.sh: drop usage of `make debug`
  scripts/get-latest-rhocp-repo.sh
Labels: lgtm, approved, jira/valid-reference

#2788 [release-4.15] USHIFT-2107: Dynamically use latest available RHOCP repo
  scripts/devenv-builder/configure-vm.sh
  scripts/get-latest-rhocp-repo.sh
  scripts/image-builder/build.sh
  scripts/image-builder/config/rhocp-4.14.toml.template
  scripts/image-builder/config/rhocp.toml.template
  test/bin/build_images.sh
  test/package-sources/rhocp-4.14.toml
  test/package-sources/rhocp.toml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2785 OCPBUGS-25784: Bring back release*.json to microshift-olm RPMs
  assets/optional/operator-lifecycle-manager/release-olm-aarch64.json
  assets/optional/operator-lifecycle-manager/release-olm-x86_64.json
  packaging/rpm/microshift.spec
  scripts/auto-rebase/assets.yaml
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2737 USHIFT-2051: always build images not available in the cache
  test/bin/build_images.sh
  test/bin/ci_phase_iso_build.sh
Labels: lgtm, approved, jira/valid-reference

#2794 USHIFT-2111: Add test execution timeout to RF with 30m default
  test/README.md
  test/bin/scenario.sh
  test/scenarios-periodics/el92-src@osconfig.sh
Labels: lgtm, approved, jira/valid-reference

#2796 USHIFT-2110: certificate rotation test revert to date command
  test/suites/standard/validate-certificate-rotation.robot
Labels: lgtm, approved, jira/valid-reference

#2797 USHIFT-2123: Use dnf_retry.sh script when installing RPM packages
  scripts/devenv-builder/configure-vm.sh
  scripts/devenv-builder/manage-vm.sh
  scripts/dnf_retry.sh
  scripts/image-builder/configure.sh
  test/bin/ci_phase_iso_build.sh
  test/bin/mirror_registry.sh
Labels: lgtm, approved, jira/valid-reference

#2798 USHIFT-2124: [release-4.15] Add test execution timeout to RF with 30m default
  test/README.md
  test/bin/scenario.sh
  test/scenarios-periodics/el92-src@osconfig.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2810 USHIFT-2123: Make sure rc is zero when exiting dnf_retry.sh loop
  scripts/dnf_retry.sh
Labels: lgtm, approved, jira/valid-reference

#2811 [release-4.15] USHIFT-2127: Make sure rc is zero when exiting dnf_retry.sh loop
  scripts/dnf_retry.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2814 NO-ISSUE: Upgrade osbuild copr version to 97 and 102
  scripts/image-builder/configure.sh
Labels: lgtm, approved, jira/valid-reference

#2815 [release-4.15] NO-ISSUE: Upgrade osbuild copr version to 97 and 102
  scripts/image-builder/configure.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2816 [release-4.14] NO-ISSUE: Upgrade osbuild copr version to 97 and 102
  scripts/image-builder/configure.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2812 USHIFT-2129: Fix unbuffer not to run elevated when executing virt-install command
  rebase_sh.log
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2817 USHIFT-2110: certificate rotation test add timezone UTC
  test/suites/standard/validate-certificate-rotation.robot
Labels: lgtm, approved, jira/valid-reference

#2780 OCPBUGS-24689: The microshift-cleanup-data script should delete pods from all namespaces
  scripts/microshift-cleanup-data.sh
  test/suites/osconfig/cleanup-data.robot
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2819 [release-4.15] USHIFT-2132: Fix unbuffer not to run elevated when executing virt-install command
  rebase_sh.log
  test/bin/scenario.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2820 USHIFT-2123: Add tracing to dnf_retry.sh and fix rc logic
  scripts/dnf_retry.sh
Labels: lgtm, approved, jira/valid-reference

#2822 USHIFT-2134: make sure greenboot report success after hostname change test
  test/suites/standard/hostname.robot
Labels: lgtm, approved, jira/valid-reference
