Repository openshift/microshift, pull requests merged in 2023-09, with the labels that each got.

#2288 USHIFT-1639: Delete e2e directory from microshift project
  e2e/main.sh
Labels: lgtm, approved, jira/valid-reference

#2277 USHIFT-1538: Verify contents of a backup before restoring
  pkg/admin/data/data_manager.go
  pkg/admin/data/data_manager_test.go
  pkg/cmd/admin.go
Labels: lgtm, approved, jira/valid-reference

#2278 USHIFT-1634: Pruning old backups: don't remove manual backups
  pkg/admin/prerun/backups.go
  pkg/admin/prerun/backups_test.go
  test/resources/libostree.py
Labels: lgtm, approved, jira/valid-reference

#2293 USHIFT-1649: add more references about pod security admission enforcement
  docs/user/howto_pod_security.md
Labels: lgtm, approved, jira/valid-reference

#2282 USHIFT-1637: `microshift {backup,restore}` UX improvements
  docs/contributor/updateability.md
  pkg/admin/data/run_check.go
  pkg/cmd/admin.go
  pkg/cmd/admin_test.go
  pkg/util/util.go
  test/resources/ostree-data.resource
Labels: lgtm, approved, jira/valid-reference

#2299 USHIFT-1655: Increase cncf conformance timeout
  test/scenarios-periodics/el92-src@cncf-conformance.sh
Labels: lgtm, approved, jira/valid-reference

#2298 NO-ISSUE: Update owners
  OWNERS
Labels: lgtm, approved, jira/valid-reference

#2297 USHIFT-1636: Fix structured logging in health.go
  pkg/admin/prerun/health.go
Labels: lgtm, approved, jira/valid-reference

#2302 USHIFT-1658: `microshift {backup,restore}`: print usage if given invalid arg
  pkg/cmd/admin.go
Labels: lgtm, approved, jira/valid-reference

#2304 USHIFT-1508: go.mod - use openshift/etcd
  go.mod
  go.sum
  vendor/go.etcd.io/etcd/api/v3/version/version.go
  vendor/go.etcd.io/etcd/client/pkg/v3/logutil/zap.go
  vendor/go.etcd.io/etcd/client/pkg/v3/tlsutil/versions.go
  vendor/go.etcd.io/etcd/client/pkg/v3/transport/listener.go
  vendor/go.etcd.io/etcd/client/v3/doc.go
  vendor/go.etcd.io/etcd/client/v3/internal/endpoint/endpoint.go
  vendor/go.etcd.io/etcd/client/v3/patch_cluster.go
  vendor/go.etcd.io/etcd/client/v3/txn.go
  vendor/go.etcd.io/etcd/client/v3/watch.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#2287 OCPBUGS-14678: microshift-etcd shuts down independently
  pkg/cmd/run.go
  pkg/controllers/etcd.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2315 USHIFT-1665: Fix show-config command to require root priviledges
  pkg/cmd/showConfig.go
  test/suites/standard/show-config.robot
Labels: lgtm, approved, jira/valid-reference

#2307 USHIFT-1654: Fix openshift-route-controller RBAC failures
  assets/controllers/route-controller-manager/ns.yaml
  assets/controllers/route-controller-manager/route-controller-manager-clusterrole.yaml
  assets/controllers/route-controller-manager/route-controller-manager-clusterrolebinding.yaml
  assets/controllers/route-controller-manager/sa.yaml
  pkg/controllers/openshift-route-controller-manager.go
  scripts/auto-rebase/assets.yaml
Labels: lgtm, approved, jira/valid-reference

#2312 USHIFT-1283: Configure klog verbosity with value from config
  pkg/cmd/run.go
Labels: lgtm, approved, jira/valid-reference

#2218 USHIFT-1568: feat: added initial smoke tests for selinux
  packaging/rpm/microshift.spec
  packaging/selinux/microshift.fc
  test/resources/selinux.py
  test/resources/selinux.resource
  test/suites/standard/validate-selinux-policy.robot
  test/suites/upgrade/upgrade-successful.robot
Labels: lgtm, approved, jira/valid-reference

#2294 USHIFT-1605: Add multi nic scenario support and robot test
  test/bin/scenario.sh
  test/kickstart-templates/kickstart-liveimg.ks.template
  test/kickstart-templates/kickstart.ks.template
  test/resources/microshift-network.resource
  test/resources/microshift-process.resource
  test/scenarios/el92-src@isolated-net.sh
  test/scenarios/el92-src@multi-nic.sh
  test/suites/network/isolated-network.robot
  test/suites/network/multi-nic.robot
  test/suites/standard/networking-smoke.robot
Labels: lgtm, approved, jira/valid-reference

#2306 USHIFT-1529: Storage upgrade remove trigger
  assets/crd/storage_version_state.crd.yaml
  docs/contributor/updateability.md
  pkg/assets/crd.go
  pkg/cmd/run.go
  pkg/controllers/kube-storage-version-trigger.go
  scripts/auto-rebase/assets.yaml
  test/assets/storage-version-migration/migration.beta.yaml
  test/assets/storage-version-migration/migration.stable.yaml
  test/suites/storage/storage-version-migration.robot
Labels: lgtm, approved, jira/valid-reference

#2313 USHIFT-1400: Don't ignore errors when creating changelog and last_*rebase.sh
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#2314 USHIFT-1509: Enhance microshift-cleanup-data script UX and functionality
  scripts/microshift-cleanup-data.sh
  test/resources/microshift-process.resource
Labels: lgtm, approved, jira/valid-reference

#2322 OCPBUGS-18706: Don't wait before applying a CRD
  pkg/assets/crd.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2319 OCPBUGS-18548: Stop all MicroShift components when signaled to exit
  pkg/controllers/infra-services-controller.go
  pkg/controllers/kube-apiserver.go
  pkg/controllers/openshift-default-scc-manager.go
  scripts/auto-rebase/rebase_patches/0030-kube-controller-manager-command-context.patch
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2311 USHIFT-1664: Introduce microshift-sos-report helper
  packaging/rpm/microshift.spec
  scripts/microshift-sos-report.sh
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2331 USHIFT-1682: Update kickstart template to have GPT disk label
  docs/config/microshift-starter.ks
  docs/contributor/rhel4edge_iso.md
  scripts/image-builder/config/kickstart.ks.template
Labels: lgtm, approved, jira/valid-reference

#2345 USHIFT-1681: Inject target branch name into rebase branch name
  docs/contributor/rebase.md
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#2342 USHIFT-1688: Fix image-builder/cleanup.sh to restart osbuilder service on exit
  scripts/image-builder/cleanup.sh
Labels: lgtm, approved, jira/valid-reference

#2356 USHIFT-1695: support building a single image in test harness
  test/bin/build_images.sh
Labels: lgtm, approved, jira/valid-reference

#2242 USHIFT-1606: Run parallel make jobs in build_rpm.sh script
  scripts/image-builder/configure.sh
  test/agent/microshift-test-agent.spec
  test/bin/build_rpms.sh
  test/bin/common.sh
Labels: lgtm, approved, jira/valid-reference

#2325 OCPBUGS-19296: Fix microshift-cleanup-data script and test its functionality
  scripts/microshift-cleanup-data.sh
  test/resources/microshift-process.resource
  test/resources/ostree-health.resource
  test/suites/greenboot/greenboot.robot
  test/suites/standard/cleanup-data.robot
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2351 OCPBUGS-19384: Use `gomplate` templating engine
  scripts/fetch_tools.sh
  test/bin/build_images.sh
  test/bin/common.sh
  test/image-blueprints/group2/rhel92-microshift-previous-minor.image-installer
  test/image-blueprints/group2/rhel92-microshift-previous-minor.toml
  test/image-blueprints/group2/rhel92-source-base.toml
  test/image-blueprints/group2/rhel92-source-fake-next-minor.toml
  test/image-blueprints/group2/rhel92-source-fake-yplus2-minor.toml
  test/image-blueprints/group2/rhel92-source-isolated.toml
  test/image-blueprints/group2/rhel92-source.toml
  test/package-sources/fast-datapath-rhel9.toml
  test/package-sources/microshift-base.toml
  test/package-sources/microshift-fake-next-minor.toml
  test/package-sources/microshift-fake-yplus2-minor.toml
  test/package-sources/microshift-local.toml
  test/package-sources/rhocp-4.13.toml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2375 OCPBUGS-19433: Add ingress smoke test
  test/assets/hello-microshift-ingress.yaml
  test/resources/microshift-network.resource
  test/suites/standard/networking-smoke.robot
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2384 OCPBUGS-19540: Log version when starting
  pkg/cmd/run.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2385 OCPBUGS-19567: Add logs plugin to sos helper
  scripts/microshift-sos-report.sh
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2367 USHIFT-335: Test mDNS resolution from the hypervisor/test runner
  scripts/devenv-builder/configure-vm.sh
  test/bin/manage_hypervisor_config.sh
  test/suites/standard/networking-smoke.robot
Labels: lgtm, approved, jira/valid-reference

#2382 [release-4.14] OCPBUGS-19525: Fix microshift-cleanup-data script and test its functionality
  scripts/microshift-cleanup-data.sh
  test/resources/microshift-process.resource
  test/resources/ostree-health.resource
  test/suites/greenboot/greenboot.robot
  test/suites/standard/cleanup-data.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2369 USHIFT-1711: do not close jira tickets if there are no PRs
  scripts/jira/manage_ticket.py
Labels: lgtm, approved, jira/valid-reference

#2355 USHIFT-1631: do not recommend sos obfuscation by default
  docs/user/debugging_tips.md
Labels: lgtm, approved, jira/valid-reference

#2402 OCPBUGS-19772: Add microshift-sos-report wrapper
  packaging/rpm/microshift.spec
  scripts/microshift-sos-report.sh
  test/bin/scenario.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2397 OCPBUGS-19719: Use cgo net for name resolution
  Makefile
  test/resources/microshift-host.resource
  test/resources/oc.resource
  test/suites/standard/hostname.robot
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2403 USHIFT-1705: feat: re-add /usr/lib check for kustomize
  test/suites/standard/kustomize.robot
Labels: lgtm, approved, jira/valid-reference

#2416 USHIFT-1705: hostname/kustomize tests: re-enable microshift.service after cleanup
  test/suites/standard/hostname.robot
Labels: lgtm, approved, jira/valid-reference

#2292 OCPBUGS-19457: Test update from current release
  test/README.md
  test/bin/build_images.sh
  test/bin/common.sh
  test/bin/get_crel_version_repo.sh
  test/bin/scenario.sh
  test/image-blueprints/group2/rhel92-crel.toml
  test/package-sources/microshift-crel.toml
  test/scenarios-periodics/el92-crel@upgrade-fails.sh
  test/scenarios/el92-crel@upgrade-ok.sh
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
