Repository openshift/microshift, pull requests merged in 2024-03, with the labels that each got.

#3094 USHIFT-2473: add missing quote to microshift-ext template
  test/image-blueprints/layer4-ext/group1/rhel93_microshift-ext.toml
Labels: lgtm, approved, jira/valid-reference

#3088 USHIFT-2286: Use timeout command for interrupting failed VM installations
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#3080 [release-4.15] USHIFT-2467: Hardcode version values to ensure right repositories
  test/bin/build_images.sh
  test/bin/get_rel_version_repo.sh
  test/package-sources/microshift-crel.toml
  test/package-sources/microshift-prel.toml
  test/package-sources/rhocp-4.14.toml
  test/package-sources/rhocp-4.15.toml
  test/package-sources/rhocp.toml
  test/scenarios/el92-src@rpm-install.sh
  test/suites/rpm/install-and-upgrade-successful.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3096 USHIFT-2474: remove gh dependency in release notes script
  scripts/release-notes/gen_ec_release_notes.py
Labels: lgtm, approved, jira/valid-reference

#3097 [release-4.15] USHIFT-2389: Use timeout command for interrupting failed VM installations
  test/bin/scenario.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3071 USHIFT-2460: Fix Stress Testing script
  test/bin/stress_testing.sh
Labels: lgtm, approved, jira/valid-reference

#3098 [release-4.15] USHIFT-2476: change sonobuoy command to match the CNCF readme
  test/scenarios-periodics/el92-src@cncf-conformance.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3081 [release-4.15] OCPBUGS-29281: Rebase lvms registry.access.redhat.com lvms4 lvms operator bundle v4.15.0
  assets/components/lvms/topolvm-configmap_lvms-version.yaml
  assets/components/lvms/topolvm-controller_rbac.authorization.k8s.io_v1_clusterrole.yaml
  assets/components/lvms/topolvm-node_rbac.authorization.k8s.io_v1_clusterrole.yaml
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  scripts/auto-rebase/last_lvms_rebase.sh
  scripts/auto-rebase/lvms_assets.yaml
  scripts/auto-rebase/rebase-lvms.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3103 USHIFT-2116: CI implementation - Introduce cluster id
  test/run.sh
Labels: lgtm, approved, jira/valid-reference

#3104 USHIFT-2478: fix jira script logic to handle closed PRs
  scripts/jira/manage_ticket.py
Labels: lgtm, approved, jira/valid-reference

#3108 USHIFT-2431: Add junit integration to CNCF tests
  test/bin/scenario.sh
  test/scenarios-periodics/el92-src@cncf-conformance.sh
Labels: lgtm, approved, jira/valid-reference

#2992 [release-4.15] OCPBUGS-29246: Create microshift-olm-release-info RPM
  packaging/rpm/microshift.spec
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3075 USHIFT-2261 USHIFT-2459: Add namespace ownership support for router
  assets/components/openshift-router/deployment.yaml
  cmd/generate-config/config/config-openapi-spec.json
  docs/user/howto_config.md
  packaging/microshift/config.yaml
  pkg/components/controllers.go
  pkg/config/config.go
  pkg/config/ingress.go
  scripts/auto-rebase/rebase.sh
  test/resources/microshift-network.resource
  test/suites/network/multi-nic.robot
  test/suites/standard1/networking-smoke.robot
  test/suites/standard1/router.robot
Labels: lgtm, approved, qe-approved, jira/valid-reference

#3120 USHIFT-2546: Remove go mod toolchain on rebase
  etcd/go.mod
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#3116 USHIFT-2543: add overrides for CI scripts
  .gitignore
  test/README.md
  test/bin/common.sh
  test/dev_overrides.sh.example
Labels: lgtm, approved, jira/valid-reference

#2952 USHIFT-2170: support upgrading 2 Y versions at a time
  pkg/admin/prerun/version.go
  pkg/admin/prerun/version_test.go
  test/Makefile
  test/bin/build_images.sh
  test/bin/build_rpms.sh
  test/bin/common.sh
  test/bin/create_local_repo.sh
  test/bin/get_rel_version_repo.sh
  test/bin/scenario.sh
  test/image-blueprints/layer1-base/group2/rhel92-microshift-yminus2.toml
  test/package-sources/microshift-fake-yplus2-minor.toml
  test/package-sources/rhocp-y2.toml
  test/scenarios/el92-src@upgrade-block-to-fake-y2.sh
  test/scenarios/el92-yminus2@upgrade-ok.sh
  test/suites/upgrade/upgrade-block-2-minor.robot
Labels: lgtm, approved, jira/valid-reference

#3110 USHIFT-2464: scan FIPS on container images
  test/image-blueprints/layer3-periodic/group1/rhel92-source-isolated.toml
  test/suites/fips/validate-fips.robot
Labels: lgtm, approved, jira/valid-reference

#3126 USHIFT-2549: simplify repoquery command used to look up microshift RPM version
  test/bin/get_rel_version_repo.sh
Labels: lgtm, approved, jira/valid-reference

#3128 USHIFT-2555: detect existing VM in scenario.sh create
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#3127 USHIFT-2554: Fix exit sequence error code in action_create and action_run of scenario.sh
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#3087 USHIFT-2086: Expose router as LoadBalancer service
  assets/components/openshift-router/deployment.yaml
  assets/components/openshift-router/service-cloud.yaml
  origin/patches/router-exposed.patch
  pkg/components/controllers.go
  scripts/auto-rebase/assets.yaml
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, qe-approved, jira/valid-reference

#3115 USHIFT-2542: Skip cncf conformance in presubmits
  test/bin/ci_phase_iso_boot.sh
  test/bin/ci_phase_test.sh
  test/bin/common.sh
Labels: lgtm, approved, jira/valid-reference

#3084 USHIFT-2222: RPM packages for Multus CNI
  assets/optional/multus/06-daemonset.yaml
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#3135 [release-4.15] USHIFT-2559: Fix exit sequence error code in action_create and action_run of scenario.sh
  test/bin/scenario.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3125 USHIFT-2550: Change configure-vm.sh to not install optional RPMs by default
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#3141 OCPBUGS-30807: Add --collect to systemd-run microshift-etcd
  pkg/controllers/etcd.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3144 USHIFT-2542: Fix scenario removal
  test/bin/ci_phase_iso_boot.sh
Labels: lgtm, approved, jira/valid-reference

#3109 USHIFT-2506: CNCF remove parallel execution
  test/scenarios-periodics/el92-src@cncf-conformance.sh
Labels: lgtm, approved, jira/valid-reference

#3150 [release-4.15] USHIFT-2610: Skip cncf conformance in presubmits
  test/bin/ci_phase_iso_boot.sh
  test/bin/ci_phase_test.sh
  test/bin/common.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3114 [release-4.15] USHIFT-2607: CNCF remove parallel execution
  test/scenarios-periodics/el92-src@cncf-conformance.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3154 [release-4.14] USHIFT-2609: CNCF-4.14 remove parallel execution
  test/scenarios-periodics/el92-src@cncf-conformance.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3149 USHIFT-2606: add rpm repo details to release notes
  scripts/release-notes/gen_ec_release_notes.py
Labels: lgtm, approved, jira/valid-reference

#3148 USHIFT-2459: Add docs to namespaceOwnership
  cmd/generate-config/config/config-openapi-spec.json
  packaging/microshift/config.yaml
  pkg/config/ingress.go
Labels: lgtm, approved, jira/valid-reference

#3159 USHIFT-1349: use pygithub library to get application token
  scripts/release-notes/gen_ec_release_notes.py
  scripts/release-notes/gen_ec_release_notes.sh
  scripts/release-notes/requirements.txt
  scripts/release-notes/tag_stable_releases.py
Labels: lgtm, approved, jira/valid-reference

#3161 USHIFT-2615: Use registry.redhat.io + manual rebase
  docs/contributor/rebase.md
  etcd/go.sum
  etcd/vendor/github.com/openshift/microshift/pkg/config/ingress.go
  go.sum
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/last_lvms_rebase.sh
  scripts/auto-rebase/rebase_job_entrypoint.sh
Labels: lgtm, approved, jira/valid-reference

#3162 [release-4.15] USHIFT-2617: Use registry.redhat.io for lvms in rebase
  docs/contributor/rebase.md
  scripts/auto-rebase/last_lvms_rebase.sh
  scripts/auto-rebase/rebase_job_entrypoint.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3167 [release-4.14] USHIFT-2609: Fix sonobuoy test start syntax
  test/scenarios-periodics/el92-src@cncf-conformance.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#3168 [release-4.14] USHIFT-2791: Use registry.redhat.io for lvms in rebase
  docs/contributor/rebase.md
  scripts/auto-rebase/last_lvms_rebase.sh
  scripts/auto-rebase/rebase_job_entrypoint.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3180 rebase-main-4.16.0-0.nightly-2024-03-24-191602_amd64-2024-03-24_arm64-2024-03-24
  Makefile.kube_git.var
  Makefile.version.aarch64.var
  Makefile.version.x86_64.var
  assets/components/service-ca/deployment.yaml
  assets/crd/0000_03_config-operator_01_securitycontextconstraints.crd.yaml
  assets/crd/0000_03_config-operator_02_rangeallocations.crd.yaml
  assets/optional/multus/release-multus-aarch64.json
  assets/optional/multus/release-multus-x86_64.json
  assets/optional/operator-lifecycle-manager/kustomization.aarch64.yaml
  assets/optional/operator-lifecycle-manager/kustomization.x86_64.yaml
  assets/optional/operator-lifecycle-manager/release-olm-aarch64.json
  assets/optional/operator-lifecycle-manager/release-olm-x86_64.json
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  etcd/go.mod
  etcd/go.sum
  etcd/vendor/modules.txt
  go.mod
  go.sum
  packaging/crio.conf.d/10-microshift_amd64.conf
  packaging/crio.conf.d/10-microshift_arm64.conf
  pkg/assets/crd.go
  scripts/auto-rebase/assets.yaml
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/commits.txt
  scripts/auto-rebase/last_rebase.sh
  scripts/auto-rebase/rebase.sh
  vendor/k8s.io/apiserver/pkg/cel/environment/base.go
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/policy_static.go
  vendor/k8s.io/kubernetes/pkg/kubelet/managed/managed.go
  vendor/modules.txt
Labels: lgtm, approved

#3137 USHIFT-2226: Test Multus - Bridge CNI
  test/assets/multus/bridge-nad.yaml
  test/assets/multus/bridge-pod.yaml
  test/assets/multus/bridge-preexisting-nad.yaml
  test/assets/multus/bridge-preexisting-pod.yaml
  test/image-blueprints/layer3-periodic/group1/rhel92-source-with-optionals.toml
  test/resources/DataFormats.py
  test/resources/microshift-host.resource
  test/resources/oc.resource
  test/suites/optional/multus.robot
Labels: lgtm, approved, jira/valid-reference

#3184 NO-ISSUE: Add microshift-multus to image-builder's blueprint
  scripts/image-builder/config/blueprint_v0.0.1.toml
Labels: lgtm, approved, jira/valid-reference

#3186 make it clearer to avoid image builder in Getting Started
  docs/user/getting_started.md
Labels: lgtm, approved, ok-to-test

#3155 USHIFT-2228: Test Multus - macvlan CNI
  test/assets/multus/macvlan-nad.yaml
  test/assets/multus/macvlan-pod.yaml
  test/suites/optional/multus.robot
Labels: lgtm, approved, jira/valid-reference

#3193 USHIFT-2228: Fix Multus Macvlan test
  test/suites/optional/multus.robot
Labels: lgtm, approved, jira/valid-reference

#3194 USHIFT-2803: update multiplatform builder image
  Makefile
  packaging/images/Containerfile.rpm-builder
Labels: lgtm, approved, jira/valid-reference
