Repository openshift/microshift, pull requests merged in 2024-04, with the labels that each got.

#3163 USHIFT-1349: automatically track pre-release versions in release note script
  scripts/release-notes/gen_ec_release_notes.py
Labels: lgtm, approved, jira/valid-reference

#3198 USHIFT-2792: Increase systemd timeout from `2m` to `4m`
  packaging/systemd/microshift.service
Labels: lgtm, approved, jira/valid-reference

#3206 [release-4.15] USHIFT-2810: update multiplatform builder image
  Makefile
  packaging/images/Containerfile.rpm-builder
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3095 USHIFT-2444: Router enable/disable
  .golangci.yaml
  assets/components/openshift-router/deployment.yaml
  cmd/generate-config/config/config-openapi-spec.json
  docs/user/howto_config.md
  packaging/microshift/config.yaml
  pkg/assets/admission-registration.go
  pkg/assets/apps.go
  pkg/assets/core.go
  pkg/assets/handler.go
  pkg/assets/rbac.go
  pkg/assets/scc.go
  pkg/assets/scheduling.go
  pkg/assets/storage.go
  pkg/components/controllers.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/ingress.go
  scripts/auto-rebase/rebase.sh
  test/suites/standard1/router.robot
Labels: lgtm, approved, jira/valid-reference

#3173 USHIFT-2798: MicroShift bootc pilot
  test/bin/build_bootc_images.sh
  test/bin/ci_phase_iso_build.sh
  test/bin/common.sh
  test/bin/pyutils/build_bootc_images.py
  test/bin/pyutils/common.py
  test/bin/scenario.sh
  test/image-blueprints/layer5-bootc/group1/cos9-bootc-source.containerfile
  test/kickstart-templates/includes/main-ostreecontainer.cfg
  test/kickstart-templates/includes/post-bootc-wa.cfg
  test/kickstart-templates/kickstart-bootc.ks.template
  test/scenarios-bootc/cos9-src@bootc-standard2.sh
Labels: lgtm, approved, jira/valid-reference

#3143 USHIFT-2087: Add configurable router ports
  assets/components/openshift-router/service-cloud.yaml
  cmd/generate-config/config/config-openapi-spec.json
  docs/user/howto_config.md
  packaging/microshift/config.yaml
  pkg/components/controllers.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/ingress.go
  scripts/auto-rebase/rebase.sh
  test/resources/microshift-network.resource
  test/suites/standard1/router.robot
Labels: lgtm, approved, jira/valid-reference

#3212 USHIFT-2553: Upgrade test with Multus workload
  test/image-blueprints/layer3-periodic/group1/rhel92-crel-with-optionals.toml
  test/resources/multus.resource
  test/scenarios-periodics/el92-src@optional-upgrade.sh
  test/suites/optional/multus.robot
  test/suites/upgrade/upgrade-multus.robot
Labels: lgtm, approved, jira/valid-reference

#3224 NO-ISSUE: FIX REBASE TEMPLATE + rebase-main-4.16.0-0.nightly-2024-04-07-182401_amd64-2024-04-07_arm64-2024-04-05
  Makefile.kube_git.var
  Makefile.version.aarch64.var
  Makefile.version.x86_64.var
  assets/components/csi-snapshot-controller/05_operand_rbac.yaml
  assets/components/csi-snapshot-controller/clusterrole.yaml
  assets/components/csi-snapshot-controller/webhook_config.yaml
  assets/optional/multus/kustomization.x86_64.yaml
  assets/optional/multus/release-multus-aarch64.json
  assets/optional/multus/release-multus-x86_64.json
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-catalogsources.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-clusterserviceversions.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-subscriptions.crd.yaml
  assets/optional/operator-lifecycle-manager/kustomization.x86_64.yaml
  assets/optional/operator-lifecycle-manager/release-olm-aarch64.json
  assets/optional/operator-lifecycle-manager/release-olm-x86_64.json
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  etcd/go.mod
  etcd/go.sum
  etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/ingress.go
  etcd/vendor/modules.txt
  go.mod
  go.sum
  packaging/crio.conf.d/10-microshift_amd64.conf
  packaging/crio.conf.d/10-microshift_arm64.conf
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/commits.txt
  scripts/auto-rebase/last_rebase.sh
  scripts/auto-rebase/rebase.sh
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/lister_watcher.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/watch_progress.go
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation_patch.go
  vendor/k8s.io/kubernetes/pkg/controller/disruption/disruption.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_volumes.go
  vendor/k8s.io/kubernetes/pkg/kubelet/winstats/perfcounter_nodestats.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#3142 OCPBUGS-30833: Added a check for loadBalancerClass for built-in load balancing service.
  pkg/loadbalancerservice/controller.go
Labels: lgtm, approved, ok-to-test, qe-approved, jira/valid-bug, jira/valid-reference

#3223 OCPBUGS-31739: Use host directory /run/cni/bin for CNI binaries
  assets/components/ovn/multi-node/node/daemonset.yaml
  assets/components/ovn/single-node/master/daemonset.yaml
  assets/optional/multus/05-configmap.yaml
  assets/optional/multus/06-daemonset.yaml
  packaging/crio.conf.d/10-microshift_amd64.conf
  packaging/crio.conf.d/10-microshift_arm64.conf
  packaging/crio.conf.d/12-microshift-multus.conf
  scripts/microshift-cleanup-data.sh
  test/image-blueprints/layer5-bootc/group1/cos9-bootc-source.containerfile
  test/suites/osconfig/cleanup-data.robot
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3227 USHIFT-2917: do not sign tags used for release notes
  scripts/release-notes/gen_ec_release_notes.py
Labels: lgtm, approved, jira/valid-reference

#3130 USHIFT-2455 USHIFT-2456 USHIFT-2457 USHIFT-2458: Introduce adding Custom CA certs for API endpoint
  cmd/generate-config/config/config-openapi-spec.json
  docs/user/howto_config.md
  packaging/microshift/config.yaml
  pkg/cmd/init.go
  pkg/config/apiserver.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/controllers/kube-apiserver.go
  pkg/util/cert.go
  pkg/util/kubeconfig.go
  pkg/util/net.go
  test/assets/custom-certs/csr-no-san.conf.template
  test/assets/custom-certs/csr.conf.template
  test/resources/common.resource
  test/resources/kubeconfig.resource
  test/resources/openssl.resource
  test/suites/standard2/validate-custom-certificates.robot
Labels: lgtm, approved, jira/valid-reference

#3225 USHIFT-2807: Add selected rpm-ostree scenario tests to bootc on CentOS
  test/bin/pyutils/build_bootc_images.py
  test/image-blueprints/layer5-bootc/group1/cos9-bootc-source-optionals.containerfile
  test/scenarios-bootc/cos9-src@backup-and-restore-on-reboot.sh
  test/scenarios-bootc/cos9-src@backups.sh
  test/scenarios-bootc/cos9-src@greenboot.sh
  test/scenarios-bootc/cos9-src@log-scan.sh
  test/scenarios-bootc/cos9-src@multi-nic.sh
  test/scenarios-bootc/cos9-src@osconfig.sh
  test/scenarios-bootc/cos9-src@standard-suite2.sh
  test/scenarios-bootc/cos9-src@storage.sh
  test/scenarios-periodics/cos9-src@rpm-standard2.sh
  test/scenarios-periodics/el92-src@greenboot.sh
  test/scenarios/el92-src@backup-and-restore-on-reboot.sh
  test/scenarios/el92-src@backups.sh
  test/scenarios/el92-src@storage.sh
Labels: lgtm, approved, jira/valid-reference

#3229 OCPBUGS-31739: Fix multus manifest: remove defaultMode
  assets/optional/multus/06-daemonset.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3211 USHIFT-2443: Introduce router IP address listening configuration
  cmd/generate-config/config/config-openapi-spec.json
  docs/user/howto_config.md
  packaging/microshift/config.yaml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/ingress.go
  pkg/loadbalancerservice/controller.go
  pkg/loadbalancerservice/router.go
  test/resources/microshift-network.resource
  test/suites/standard1/router.robot
Labels: lgtm, approved, qe-approved, jira/valid-reference

#3232 USHIFT-2966: ensure the output of git push is in the traceback if there is an error
  scripts/release-notes/gen_ec_release_notes.py
Labels: lgtm, approved, jira/valid-reference

#3231 USHIFT-2942: Template interfaces in Multus tests and enable bootc-optional scenario
  test/assets/multus/ipvlan-nad.yaml
  test/assets/multus/macvlan-nad.yaml
  test/scenarios-bootc/cos9-src@optional.sh
  test/suites/optional/multus.robot
Labels: lgtm, approved, jira/valid-reference

#3235 USHIFT-2967: use oc command with custom-ca
  test/resources/microshift-process.resource
  test/suites/standard2/validate-custom-certificates.robot
Labels: lgtm, approved, jira/valid-reference

#3238 USHIFT-2968: Simplify router tests
  test/suites/standard1/router.robot
Labels: lgtm, approved, jira/valid-reference

#3228 USHIFT-2806: Initial implementation of RHEL 9.4 bootc test
  test/bin/pyutils/build_bootc_images.py
  test/bin/pyutils/common.py
  test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source.containerfile
  test/scenarios-bootc/el94-src@standard-suite2.sh
Labels: lgtm, approved, jira/valid-reference

#3230 USHIFT-2964: Get separate journal along SOS
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#3236 USHFT-2969: Release notes job: use token for `git` commands
  scripts/release-notes/gen_ec_release_notes.py
Labels: lgtm, approved

#3245 USHIFT-2969: Release notes job: fix missing /
  scripts/release-notes/gen_ec_release_notes.py
Labels: lgtm, approved, jira/valid-reference

#3246 USHIFT-2992: Always allow RHSM to manage repos
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#3252 USHIFT-2997: bound release notes generation
  scripts/release-notes/gen_ec_release_notes.py
Labels: lgtm, approved, jira/valid-reference

#3105 USHIFT-2454: audit log configuration
  cmd/generate-config/config/config-openapi-spec.json
  docs/user/howto_config.md
  packaging/microshift/config.yaml
  pkg/config/apiserver.go
  pkg/config/apiserver/audit.go
  pkg/config/apiserver/audit_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/controllers/kube-apiserver.go
  test/suites/standard1/configuration.robot
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/audit_policies.go
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/manifests/allrequestbodies-rules.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/manifests/base-policy.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/manifests/default-rules.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/manifests/none-rules.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/manifests/writerequestbodies-rules.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/allrequestbodies.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/audit-policies-cm-scenario-1.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/default.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/multipleCr.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/none.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/oauth.yaml
  vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/writerequestbodies.yaml
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#3256 USHIFT-2975: Enhance removal of autoconnect option from network manager configuration
  test/kickstart-templates/includes/post-network.cfg
Labels: lgtm, approved, jira/valid-reference

#3257 USHIFT-2910: Move firewall configuration to container files for bootc images
  test/image-blueprints/layer5-bootc/group1/cos9-bootc-source.containerfile
  test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source.containerfile
  test/scenarios-bootc/cos9-src@backup-and-restore-on-reboot.sh
  test/scenarios-bootc/cos9-src@backups.sh
  test/scenarios-bootc/cos9-src@greenboot.sh
  test/scenarios-bootc/cos9-src@log-scan.sh
  test/scenarios-bootc/cos9-src@multi-nic.sh
  test/scenarios-bootc/cos9-src@optional.sh
  test/scenarios-bootc/cos9-src@osconfig.sh
  test/scenarios-bootc/cos9-src@standard-suite2.sh
  test/scenarios-bootc/cos9-src@storage.sh
  test/scenarios-bootc/el94-src@backup-and-restore-on-reboot.sh
  test/scenarios-bootc/el94-src@backups.sh
  test/scenarios-bootc/el94-src@greenboot.sh
  test/scenarios-bootc/el94-src@log-scan.sh
  test/scenarios-bootc/el94-src@multi-nic.sh
  test/scenarios-bootc/el94-src@optional.sh
  test/scenarios-bootc/el94-src@osconfig.sh
  test/scenarios-bootc/el94-src@standard-suite2.sh
  test/scenarios-bootc/el94-src@storage.sh
Labels: lgtm, approved, jira/valid-reference

#3260 USHIFT-2975: Fix all kickstart files not to use nmcli
  docs/config/microshift-starter.ks
  scripts/image-builder/config/kickstart.ks.template
Labels: lgtm, approved, jira/valid-reference

#3251 USHIFT-2992: Changes to scripts for RHEL9.4
  scripts/devenv-builder/configure-vm.sh
  scripts/image-builder/cleanup.sh
  test/bin/build_images.sh
Labels: lgtm, approved, jira/valid-reference

#3258 USHIFT-3004: Run linter on bootc container files
  Makefile
  test/image-blueprints/layer5-bootc/group1/cos9-bootc-source-optionals.containerfile
  test/image-blueprints/layer5-bootc/group1/cos9-bootc-source.containerfile
  test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source-optionals.containerfile
  test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source.containerfile
Labels: lgtm, approved, jira/valid-reference

#3269 USHIFT-2993: Restart CRI-O on microshift-multus RPM install
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#3268 USHIFT-2929: Implement bootc container file parallel processing
  test/bin/pyutils/build_bootc_images.py
  test/bin/pyutils/common.py
  test/image-blueprints/layer5-bootc/group2/cos9-bootc-source-optionals.containerfile
  test/image-blueprints/layer5-bootc/group2/rhel94-bootc-source-optionals.containerfile
Labels: lgtm, approved, jira/valid-reference

#3271 USHIFT-2992: Image builder cleanup: don't stop osbuild-composer.socket
  scripts/image-builder/cleanup.sh
Labels: lgtm, approved, jira/valid-reference

#3277 USHIFT-3017: Retry curl in macvlan/ipvlan tests for extra robustness
  test/suites/optional/multus.robot
Labels: lgtm, approved, jira/valid-reference

#3286 USHIFT-3020: Multus RF: Get list of interfaces in more robust way
  test/suites/optional/multus.robot
Labels: lgtm, approved, jira/valid-reference

#3284 USHIFT-3018: Increase CI resource wait default timeout to 60s
  test/resources/oc.resource
Labels: lgtm, approved, jira/valid-reference

#3290 USHIFT-3099: wait_images.py: fix restart_job so it's aware of warnings printed to stdout
  test/bin/wait_images.py
Labels: lgtm, approved, jira/valid-reference

#3285 OCPBUGS-32946: Default to watch all interfaces and IPs for router lis…
  pkg/config/config.go
  pkg/loadbalancerservice/router.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#3270 USHIFT-2926: Implement bootc-image-builder support for creating CentOS ISO files
  test/bin/common.sh
  test/bin/pyutils/build_bootc_images.py
  test/bin/pyutils/common.py
  test/bin/scenario.sh
  test/image-blueprints/layer5-bootc/group1/centos9-bootc.image-bootc
  test/kickstart-templates/includes/main-prologue.cfg
  test/scenarios-bootc/cos9-src@backup-and-restore-on-reboot.sh
  test/scenarios-bootc/cos9-src@backups.sh
  test/scenarios-bootc/cos9-src@greenboot.sh
  test/scenarios-bootc/cos9-src@log-scan.sh
  test/scenarios-bootc/cos9-src@multi-nic.sh
  test/scenarios-bootc/cos9-src@optional.sh
  test/scenarios-bootc/cos9-src@osconfig.sh
  test/scenarios-bootc/cos9-src@standard-suite2.sh
  test/scenarios-bootc/cos9-src@storage.sh
Labels: lgtm, approved, jira/valid-reference

#3293 USHIFT-3113: Enhancements for build_bootc_image.py script
  test/bin/pyutils/build_bootc_images.py
  test/bin/pyutils/common.py
Labels: lgtm, approved, jira/valid-reference

#3296 OCPBUGS-31661: Remove references to redundant files in selinux packaging
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
