Repository openshift/microshift, pull requests merged in 2024-11, with the labels that each got.

#4130 USHIFT-4740: Add explicit parent directive option in ostree blueprints
  test/README.md
  test/bin/build_images.sh
  test/image-blueprints/layer2-presubmit/group1/rhel94-crel.toml
  test/image-blueprints/layer3-periodic/group1/rhel94-crel-with-optionals.toml
Labels: lgtm, approved, jira/valid-reference

#4139 USHIFT-4727: Temporarily disable upgrade-ok tests to unblock CI
  test/scenarios/presubmits/el94-crel@el94-src@upgrade-ok.sh.disabled
  test/scenarios/presubmits/el94-prel@el94-src@upgrade-ok.sh.disabled
  test/scenarios/presubmits/el94-yminus2@el94-src@upgrade-ok.sh.disabled
Labels: lgtm, approved, jira/valid-reference

#4143 [release-4.17] USHIFT-4563: Save and restore default config in custom certs e2e tests
  test/suites/standard2/validate-custom-certificates.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4141 USHIFT-4740: Fix previous-to-newer release rpm-ostree upgrade tests
  test/image-blueprints/layer1-base/group3/rhel94-microshift-previous-minor.image-installer
  test/image-blueprints/layer1-base/group3/rhel94-microshift-previous-minor.toml
  test/image-blueprints/layer1-base/group4/rhel94-crel-with-optionals.toml
  test/image-blueprints/layer1-base/group4/rhel94-crel.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-base.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-fake-next-minor.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-with-optionals.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source.toml
  test/scenarios/presubmits/el94-crel@el94-src@upgrade-ok.sh
  test/scenarios/presubmits/el94-prel@el94-src@upgrade-ok.sh
  test/scenarios/presubmits/el94-yminus2@el94-src@upgrade-ok.sh
Labels: lgtm, approved, jira/valid-reference

#4142 USHIFT-4744: Remove limits from servicemesh operator deployment
  assets/optional/gateway-api/03-servicemesh-operator3_apps_v1_deployment.yaml
  scripts/auto-rebase/rebase_gateway_api.sh
Labels: lgtm, approved, jira/valid-reference

#4127 USHIFT-3144: Obsolete scripts/image-builder directory and build.sh script
  Makefile
  docs/contributor/howto_quay_mirror.md
  docs/contributor/multinode/config_r4e.md
  docs/contributor/multinode/config_rpm.md
  docs/contributor/rhel4edge_iso.md
  docs/user/howto_mirror_images.md
  scripts/devenv-builder/cleanup-composer.sh
  scripts/devenv-builder/configure-composer.sh
  scripts/image-builder/build.sh
  scripts/image-builder/config/blueprint_v0.0.1.toml
  scripts/image-builder/config/custom-rpms.toml.template
  scripts/image-builder/config/fast-datapath.toml.template
  scripts/image-builder/config/installer.toml
  scripts/image-builder/config/kickstart.ks.template
  scripts/image-builder/config/microshift-local.toml.template
  scripts/image-builder/config/registries.conf.template
  scripts/image-builder/config/rhocp.toml.template
  scripts/image-builder/download-rpms.sh
  scripts/mirror-images.sh
  test/bin/ci_phase_boot_and_test.sh
  test/bin/manage_composer_config.sh
  test/bin/mirror_registry.sh
Labels: lgtm, approved, jira/valid-reference

#4125 USHIFT-4727: Implement offline network configuration in kickstart
  test/kickstart-templates/includes/post-offline.cfg
  test/kickstart-templates/includes/post-system.cfg
  test/kickstart-templates/kickstart-offline.ks.template
  test/suites/network/offline.robot
Labels: lgtm, approved, jira/valid-reference

#4157 ART-10563: Remove dnf upgrade from image mode container builds
  packaging/imagemode/Containerfile.repobase
  packaging/imagemode/Containerfile.repourl
  packaging/imagemode/Containerfile.rhocp
Labels: lgtm, approved, jira/valid-reference

#4155 USHIFT-4757: Skip installing gateway-api as optional rpm
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#4162 OCPBUGS-44376: Add skip renames to upstream tests
  origin/skip.txt
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4148 USHIFT-4746: Describe the resource after failed `Oc Wait`
  test/resources/kubeconfig.resource
  test/resources/oc.resource
  test/suites/optional/gateway-api.robot
  test/suites/standard1/router.robot
Labels: lgtm, approved, jira/valid-reference

#4161 USHIFT-4572: Rework network handing in launch_vm
  test/bin/scenario.sh
  test/scenarios-bootc/periodics/cos9-src@isolated-net.sh
  test/scenarios-bootc/periodics/el94-src@isolated-net.sh
  test/scenarios-bootc/presubmits/cos9-src@multi-nic.sh
  test/scenarios-bootc/presubmits/cos9-src@optional.sh
  test/scenarios-bootc/presubmits/el94-src@dual-stack.sh
  test/scenarios-bootc/presubmits/el94-src@multi-nic.sh
  test/scenarios-bootc/presubmits/el94-src@optional.sh
  test/scenarios/periodics/el94-src@isolated-net.sh
  test/scenarios/periodics/el94-src@offline.sh
  test/scenarios/periodics/el94-src@optional.sh
  test/scenarios/presubmits/el94-src@dual-stack.sh
  test/scenarios/presubmits/el94-src@ipv6.sh
  test/scenarios/presubmits/el94-src@multi-nic.sh
Labels: lgtm, approved, jira/valid-reference

#4159 USHIFT-4747: Fail if --dont-save-failed is used without --auto-recovery
  pkg/cmd/admin.go
Labels: lgtm, approved, jira/valid-reference

#4160 USHIFT-4523: Retry setup steps for footprint-and-performance
  scripts/ci-footprint-and-performance/1-setup.sh
Labels: lgtm, approved, jira/valid-reference

#4156 OCPBUGS-42864: Add sample kickstart files to microshift-release-info RPM and document usage
  packaging/kickstart/README.md
  packaging/kickstart/kickstart-bootc.ks.template
  packaging/kickstart/kickstart-ostree.ks.template
  packaging/kickstart/kickstart-rpm.ks.template
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4180 USHIFT-4889: Disable AWS' RHUI repositories
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#4154 USHIFT-4743: Add user docs for gateway api
  docs/user/howto_gateway_api.md
Labels: lgtm, approved, jira/valid-reference

#4183 USHIFT-4891: Add support for multi NIC on RF QE env
  test/suites/network/multi-nic.robot
Labels: lgtm, approved, jira/valid-reference

#4172 NO-ISSUE: Sprint metrics charting capabilities and date adjustment
  scripts/jira/requirements.txt
  scripts/jira/sprint_metrics.py
  scripts/jira/sprint_metrics_config.json
Labels: lgtm, approved, jira/valid-reference

#4190 USHIFT-4893: Add ipv6 back to aws cloudformation stack template
  scripts/aws/cf-gen.yaml
Labels: lgtm, approved, jira/valid-reference

#4197 [release-4.17] USHIFT-4889: Disable RHUI
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4199 [release-4.16] USHIFT-4889: Disable RHUI
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4120 USHIFT-4330: Running RF tests against a MicroShift in container
  test/assets/lvmd.yaml
  test/bin/common.sh
  test/bin/common_versions.sh
  test/bin/scenario.sh
  test/bin/scenario_container.sh
  test/kickstart-templates/includes/post-bootc-container-tweaks.cfg
  test/kickstart-templates/includes/post-microshift.cfg
  test/kickstart-templates/includes/post-system.cfg
  test/kickstart-templates/kickstart-bootc-container.ks.template
  test/resources/DataFormats.py
  test/resources/microshift-config.resource
  test/resources/microshift-host.resource
  test/scenarios-bootc-containers/presubmits/el94-src@auto-recovery.sh
  test/scenarios-bootc-containers/presubmits/el94-src@backups.sh
  test/scenarios-bootc-containers/presubmits/el94-src@log-scan.sh
  test/scenarios-bootc-containers/presubmits/el94-src@optional.sh
  test/scenarios-bootc-containers/presubmits/el94-src@standard-suite1.sh
  test/scenarios-bootc-containers/presubmits/el94-src@standard-suite2.sh
  test/scenarios-bootc-containers/presubmits/el94-src@storage.sh
  test/suites/optional/multus.robot
Labels: lgtm, approved, jira/valid-reference

#4000 USHIFT-4378: introduce ingress customization fields
  assets/components/openshift-router/deployment.yaml
  cmd/generate-config/config/config-openapi-spec.json
  docs/user/howto_config.md
  etcd/vendor/github.com/openshift/api/operator/v1/Makefile
  etcd/vendor/github.com/openshift/api/operator/v1/doc.go
  etcd/vendor/github.com/openshift/api/operator/v1/register.go
  etcd/vendor/github.com/openshift/api/operator/v1/types.go
  etcd/vendor/github.com/openshift/api/operator/v1/types_authentication.go
  etcd/vendor/github.com/openshift/api/operator/v1/types_cloudcredential.go
  etcd/vendor/github.com/openshift/api/operator/v1/types_config.go
  etcd/vendor/github.com/openshift/api/operator/v1/types_console.go
  etcd/vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  etcd/vendor/github.com/openshift/api/operator/v1/types_csi_snapshot.go
  etcd/vendor/github.com/openshift/api/operator/v1/types_dns.go
  etcd/vendor/github.com/openshift/api/operator/v1/types_etcd.go
  etcd/vendor/github.com/openshift/api/operator/v1/types_ingress.go
  etcd/vendor/github.com/openshift/api/operator/v1/types_insights.go
  etcd/vendor/github.com/openshift/api/operator/v1/types_kubeapiserver.go
  etcd/vendor/github.com/openshift/api/operator/v1/types_kubecontrollermanager.go
  etcd/vendor/github.com/openshift/api/operator/v1/types_kubestorageversionmigrator.go
  etcd/vendor/github.com/openshift/api/operator/v1/types_machineconfiguration.go
  etcd/vendor/github.com/openshift/api/operator/v1/types_network.go
  etcd/vendor/github.com/openshift/api/operator/v1/types_openshiftapiserver.go
  etcd/vendor/github.com/openshift/api/operator/v1/types_openshiftcontrollermanager.go
  etcd/vendor/github.com/openshift/api/operator/v1/types_scheduler.go
  etcd/vendor/github.com/openshift/api/operator/v1/types_serviceca.go
  etcd/vendor/github.com/openshift/api/operator/v1/types_servicecatalogapiserver.go
  etcd/vendor/github.com/openshift/api/operator/v1/types_servicecatalogcontrollermanager.go
  etcd/vendor/github.com/openshift/api/operator/v1/types_storage.go
  etcd/vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  etcd/vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  etcd/vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/ingress.go
  etcd/vendor/modules.txt
  packaging/microshift/config.yaml
  pkg/components/controllers.go
  pkg/config/config.go
  pkg/config/ingress.go
  scripts/auto-rebase/rebase.sh
  test/suites/standard1/router.robot
Labels: lgtm, approved, jira/valid-reference

#4187 [release-4.17] USHIFT-4746: Describe after failed oc wait
  test/resources/kubeconfig.resource
  test/resources/oc.resource
  test/suites/standard1/router.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4186 USHIFT-4078: Wait for vg-manager to exist before waiting for availability
  test/resources/oc.resource
  test/suites/standard1/configuration.robot
Labels: lgtm, approved, jira/valid-reference

#4178 [release-4.17] USHIFT-3489: Add support for multi NIC on RF QE env
  test/suites/network/multi-nic.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4188 USHIFT-4746: Convert missed `oc wait` command to keyword
  test/resources/oc.resource
Labels: lgtm, approved, jira/valid-reference

#4185 NO-ISSUE: Fix selinux volume permissions when mirroring containers
  test/bin/mirror_registry.sh
Labels: lgtm, approved, jira/valid-reference

#4204 USHIFT-4899: Increase etcd max memory from 128 to 256
  test/suites/standard1/show-config.robot
  test/suites/standard2/etcd.robot
Labels: lgtm, approved, jira/valid-reference

#4201 USHIFT-4895: Add ipv6 bootc scenario
  test/kickstart-templates/includes/pre-host-resolution.cfg
  test/kickstart-templates/kickstart-bootc.ks.template
  test/scenarios-bootc/presubmits/el94-src@ipv6.sh
Labels: lgtm, approved, jira/valid-reference

#4173 USHIFT-4742: Bootc and ostree blueprint structure reorganization
  test/bin/ci_phase_iso_build.sh
  test/image-blueprints-bootc/README.md
  test/image-blueprints-bootc/layer1-base/group1/rhel94-bootc-base.containerfile
  test/image-blueprints-bootc/layer1-base/group1/rhel94-test-agent.containerfile
  test/image-blueprints-bootc/layer1-base/group2/centos9-bootc.image-bootc
  test/image-blueprints-bootc/layer1-base/group2/rhel94-bootc-crel-optionals.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel94-bootc-crel.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel94-bootc-prel.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel94-bootc.image-bootc
  test/image-blueprints-bootc/layer1-base/group2/rhel94-ostree-microshift-previous-minor.container-encapsulate
  test/image-blueprints-bootc/layer1-base/group2/rhel94-ostree-microshift-yminus2.container-encapsulate
  test/image-blueprints-bootc/layer2-source/group1/cos9-bootc-source.containerfile
  test/image-blueprints-bootc/layer2-source/group1/rhel94-bootc-source-base.containerfile
  test/image-blueprints-bootc/layer2-source/group1/rhel94-bootc-source.containerfile
  test/image-blueprints-bootc/layer2-source/group2/microshift-imagestore-config.sh.template
  test/image-blueprints-bootc/layer2-source/group2/rhel94-bootc-source-aux.containerfile
  test/image-blueprints-bootc/layer2-source/group2/rhel94-bootc-source-fake-next-minor.containerfile
  test/image-blueprints-bootc/layer2-source/group2/rhel94-bootc-source-fips.containerfile
  test/image-blueprints-bootc/layer2-source/group2/rhel94-bootc-source-isolated.containerfile
  test/image-blueprints-bootc/layer2-source/group2/rhel94-bootc-source-optionals.containerfile
  test/image-blueprints-bootc/layer2-source/group2/rhel94-bootc-source-ostree-parent-previous-minor.containerfile
  test/image-blueprints-bootc/layer2-source/group2/rhel94-bootc-source-ostree-parent-yminus2.containerfile
  test/image-blueprints-bootc/layer2-source/group3/cos9-bootc-source-fips.containerfile
  test/image-blueprints-bootc/layer2-source/group3/cos9-bootc-source-flannel.containerfile
  test/image-blueprints-bootc/layer2-source/group3/cos9-bootc-source-isolated.containerfile
  test/image-blueprints-bootc/layer2-source/group3/cos9-bootc-source-optionals.containerfile
  test/image-blueprints-bootc/layer2-source/group3/rhel94-bootc-source-isolated.image-bootc
  test/image-blueprints/README.md
  test/image-blueprints/layer1-base/group4/rhel94-microshift-previous-minor.image-installer
  test/image-blueprints/layer1-base/group4/rhel94.image-installer
  test/image-blueprints/layer3-periodic/group1/rhel94-source-with-optionals.toml
  test/image-blueprints/layer4-ext/group1/rhel94_microshift-ext.image-installer
  test/image-blueprints/layer4-ext/group1/rhel94_microshift-ext.toml
  test/image-blueprints/layer5-bootc/group2/rhel94-bootc-crel-optionals.containerfile
Labels: lgtm, approved, jira/valid-reference

#4196 USHIFT-4519: Recover and re-panic certain subcomponents
  pkg/controllers/kube-apiserver.go
  pkg/controllers/kube-controller-manager.go
  pkg/controllers/kube-scheduler.go
  pkg/controllers/kube-storage-version-migrator.go
  pkg/controllers/openshift-route-controller-manager.go
  pkg/node/kubelet.go
Labels: lgtm, approved, jira/valid-reference

#4211 USHIFT-4924: Measure bootc build time and include build log in junit for failed builds
  test/bin/pyutils/build_bootc_images.py
  test/bin/pyutils/common.py
Labels: lgtm, approved, jira/valid-reference

#4214 USHIFT-4737: Add tag and digest capabilities to mirror script
  scripts/mirror-images.sh
Labels: lgtm, approved, jira/valid-reference

#4215 USHIFT-4699: Update bootc instructions with 4.17 version
  docs/config/Containerfile.bootc-rhel9
  docs/contributor/image_mode.md
  packaging/imagemode/Makefile
Labels: lgtm, approved, jira/valid-reference

#4224 USHIFT-4868: Remove centos9 image and tests from ostree
  test/image-blueprints/layer1-base/group1/centos9.image-fetcher
  test/scenarios/periodics/cos9-src@rpm-standard1.sh
  test/scenarios/periodics/cos9-src@rpm-standard2.sh
Labels: lgtm, approved, jira/valid-reference

#4119 USHIFT-4874: introduce upstream build using gh-action
  okd/gh-workflows/README.md
  okd/gh-workflows/build-upstream-rpms-only.png
  okd/gh-workflows/microshift-build-example.yaml
  okd/gh-workflows/run-in-bootc-container.png
  okd/src/microshift-okd-build-rpms.Containerfile
  okd/src/microshift-okd-run.Containerfile
Labels: lgtm, approved, jira/valid-reference

#4184 USHIFT-4892: Address Snyk issues
  .snyk
Labels: lgtm, approved, jira/valid-reference

#4233 Use older "Bootc Image Builder" (BIB) image
  test/bin/pyutils/build_bootc_images.py
Labels: lgtm, approved

#4228 USHIFT-4921: Remove ostree-to-bootc build dependency chain
  test/agent/microshift-test-agent.sh
  test/image-blueprints-bootc/README.md
  test/image-blueprints-bootc/layer1-base/group2/rhel94-bootc-yminus2.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel94-ostree-microshift-previous-minor.container-encapsulate
  test/image-blueprints-bootc/layer1-base/group2/rhel94-ostree-microshift-yminus2.container-encapsulate
  test/image-blueprints-bootc/layer2-source/group1/microshift-ovsdb-ownership.conf.template
  test/image-blueprints-bootc/layer2-source/group1/rhel94-bootc-source.containerfile
  test/image-blueprints-bootc/layer2-source/group2/microshift-imagestore-config.service.template
  test/image-blueprints-bootc/layer2-source/group2/rhel94-bootc-source-isolated.containerfile
  test/image-blueprints-bootc/layer2-source/group2/rhel94-bootc-source-ostree-parent-previous-minor.containerfile
  test/scenarios-bootc/periodics/el94-prel@el94-src@upgrade-ostree2bootc-ok.sh
  test/scenarios-bootc/periodics/el94-yminus2@el94-src@upgrade-ostree2bootc-ok.sh
  test/scenarios-bootc/presubmits/el94-yminus2@el94-src@upgrade-ok.sh
Labels: lgtm, approved, jira/valid-reference

#4243 [release-4.17] USHIFT-4899: Increase etcd max memory from 128 to 256
  test/suites/standard1/show-config.robot
  test/suites/standard2/etcd.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4226 USHIFT-4026: Add tests for MicroShift published image validation
  test/kickstart-templates/includes/main-ostreecontainer.cfg
  test/scenarios-bootc/periodics/el94-crel@published-images-standard1.sh
  test/scenarios-bootc/periodics/el94-crel@published-images-standard2.sh
Labels: lgtm, approved, jira/valid-reference

#4242 [release-4.16] USHIFT-4899: Increase etcd max memory from 128 to 256
  test/suites/standard1/show-config.robot
  test/suites/standard2/etcd.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4241 USHIFT-4908: Update podman-rpm build image
  Makefile
Labels: lgtm, approved, jira/valid-reference

#4248 USHIFT-5086: Fix local package downloads after removing sudo
  test/bin/build_images.sh
  test/bin/pyutils/build_bootc_images.py
Labels: lgtm, approved, jira/valid-reference
