Repository openshift/microshift, pull requests merged in 2024-08, with the labels that each got.

#3698 USHIFT-3773: Skip untainted nodes conformance test
  origin/skip.txt
Labels: lgtm, approved, jira/valid-reference

#3681 USHIFT-3772: Dual stack RF e2e tests
  scripts/devenv-builder/manage-vm.sh
  test/assets/dual-stack-network.xml
  test/assets/hello-microshift-service-ipv6.yaml
  test/bin/common.sh
  test/bin/manage_hypervisor_config.sh
  test/resources/libipv6.py
  test/scenarios/el94-src@dual-stack.sh
  test/suites/ipv6/dualstack.robot
Labels: lgtm, approved, jira/valid-reference

#3708 NO-ISSUE: Restart osbuild-composer after enabling kernel-rt repo
  scripts/image-builder/configure.sh
Labels: lgtm, approved, jira/valid-reference

#3705 USHIFT-3783: Additional parameter for node ipv6 address in dual stack
  cmd/generate-config/config/config-openapi-spec.json
  docs/user/howto_config.md
  etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/node.go
  etcd/vendor/github.com/openshift/microshift/pkg/util/net.go
  packaging/microshift/config.yaml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/node.go
  pkg/node/kubelet.go
  pkg/sysconfwatch/sysconfwatch_linux.go
  pkg/util/net.go
  test/suites/ipv6/dualstack.robot
Labels: lgtm, approved, jira/valid-reference

#3714 USHIFT-3790: Remove no-signature-verification option from bootc kickstart
  test/kickstart-templates/includes/main-ostreecontainer.cfg
Labels: lgtm, approved, jira/valid-reference

#3715 USHIFT-3764: Add gomplate processing to bootc container files
  test/bin/pyutils/build_bootc_images.py
  test/image-blueprints/layer5-bootc/group0/rhel94-ostree-microshift-previous-minor.container-encapsulate
  test/image-blueprints/layer5-bootc/group1/cos9-bootc-source.containerfile
  test/image-blueprints/layer5-bootc/group1/microshift_repo_config.sh.template
  test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source-ostree-parent.containerfile
  test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source.containerfile
  test/image-blueprints/layer5-bootc/group2/cos9-bootc-source-optionals.containerfile
  test/image-blueprints/layer5-bootc/group2/rhel94-bootc-source-optionals.containerfile
Labels: lgtm, approved, jira/valid-reference

#3707 NO-JIRA: fix: update script to git add rebase entrypoint script
  scripts/auto-rebase/rebase-lvms.sh
Labels: lgtm, approved, jira/valid-reference

#3727 USHIFT-3843: Fix local RPM query to include version and release
  test/bin/build_images.sh
  test/bin/create_local_repo.sh
  test/bin/pyutils/build_bootc_images.py
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#3721 USHIFT-2990: Early warning low latency job
  scripts/ci-footprint-and-performance/1-setup.sh
  scripts/ci-footprint-and-performance/2-test.sh
  scripts/ci-footprint-and-performance/setup/001-configure-wp-lowlat.sh
  scripts/ci-footprint-and-performance/setup/010-build-microshift.sh
  scripts/ci-footprint-and-performance/setup/020-enable-profile.sh
  scripts/ci-footprint-and-performance/setup/021-install-kernel-rt.sh
  scripts/ci-footprint-and-performance/setup/100-reboot.sh
  scripts/ci-footprint-and-performance/tests/001-wait-for-greenboot.sh
  scripts/ci-footprint-and-performance/tests/002-get-kubeconfig.sh
  scripts/ci-footprint-and-performance/tests/010-hwlatdetect.sh
  scripts/ci-footprint-and-performance/tests/011-oslat.sh
  scripts/ci-footprint-and-performance/tests/100-push-results-to-s3.sh
  scripts/ci-footprint-and-performance/tests/101-fail-if-latency-too-high.sh
  scripts/ci-footprint-and-performance/tests/functions.sh
Labels: lgtm, approved, jira/valid-reference

#3728 NO-ISSUE: Update the getting started docs for RHEL 9.4
  docs/user/getting_started.md
Labels: lgtm, approved, jira/valid-reference

#3699 USHIFT-3780: Reorganized test harness scripts
  test/README.md
  test/bin/ci_phase_iso_boot.sh
  test/bin/ci_phase_iso_build.sh
  test/bin/cleanup_composer.sh
  test/bin/cleanup_hypervisor.sh
  test/bin/manage_composer_config.sh
  test/bin/manage_hypervisor_config.sh
  test/bin/manage_webserver.sh
  test/bin/rebuild_source_images.sh
  test/bin/start_osbuild_workers.sh
  test/bin/start_webserver.sh
Labels: lgtm, approved, jira/valid-reference

#3690 USHIFT-3008: Getting started bootc documentation
  README.md
  docs/contributor/image_mode.md
  docs/user/howto_config.md
Labels: lgtm, approved, jira/valid-reference

#3700 USHIFT-3788: Workload partitioning RF tests
  test/resources/common.resource
  test/scenarios/presubmits/el94-src@low-latency.sh
  test/suites/standard2/workload-partitioning.robot
  test/suites/tuned/workload-partitioning.robot
Labels: lgtm, approved, jira/valid-reference

#3738 USHIFT-2990: ci-footprint-and-performance: make reboot as separate top-level step
  scripts/ci-footprint-and-performance/2-reboot.sh
  scripts/ci-footprint-and-performance/3-test.sh
Labels: lgtm, approved, jira/valid-reference

#3678 USHIFT-706: Add CSI Deployment Flag and Config
  cmd/generate-config/config/config-openapi-spec.json
  docs/user/howto_config.md
  etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/storage.go
  packaging/greenboot/functions.sh
  packaging/greenboot/microshift-running-check.sh
  packaging/microshift/config.yaml
  packaging/rpm/microshift.spec
  pkg/components/csi-snapshot-controller.go
  pkg/components/storage.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/storage.go
  pkg/config/storage_test.go
  test/resources/oc.resource
  test/suites/standard1/configuration.robot
  test/suites/tuned/microshift-tuned.robot
Labels: lgtm, approved, jira/valid-reference

#3743 USHIFT-3494: Add explicit command line mode to virtual machine creation
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#3744 USHIFT-3780: Fix cleanup-all option in manage_hypervisor_config.sh
  test/bin/manage_hypervisor_config.sh
Labels: lgtm, approved, jira/valid-reference

#3746 [release-4.16] USHIFT-3896: Add explicit command line mode to virtual machine creation
  test/bin/scenario.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3761 USHIFT-3776: Remove skip of topolvm check for `crel` image
  test/suites/upgrade/upgrade-successful.robot
Labels: lgtm, approved, jira/valid-reference

#3755 USHIFT-3789: Start using reqpart for partitioning disks in kickstart
  docs/config/microshift-starter.ks
  docs/contributor/image_mode.md
  scripts/image-builder/config/kickstart.ks.template
  test/kickstart-templates/includes/main-prologue.cfg
Labels: lgtm, approved, jira/valid-reference

#3770 USHIFT-4062: Add storage config docs for CSI pluggability
  docs/user/howto_config.md
Labels: lgtm, approved, jira/valid-reference

#3769 USHIFT-2987: Add support for low-latency feature
  test/run.sh
Labels: lgtm, approved, jira/valid-reference

#3733 USHIFT-3781: Merge build_rpms.sh and create_local_repo.sh
  test/README.md
  test/bin/build_rpms.sh
  test/bin/ci_phase_iso_build.sh
  test/bin/create_local_repo.sh
Labels: lgtm, approved, jira/valid-reference

#3783 USHIFT-4070: Add to support to target multiple RF test suites
  test/run.sh
Labels: lgtm, approved, jira/valid-reference

#3776 USHIFT-4069: rebase fix to workaround MCO's use of go templates in yaml files
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#3768 USHIFT-4061: change imagePullPolicy from Always to IfNotPresent
  assets/optional/multus/07-daemonset-dhcp.yaml
Labels: lgtm, approved, jira/valid-reference

#3775 USHIFT-3784: Removed manage_vm_connections.sh and PUBLIC_IP
  test/README.md
  test/bin/manage_vm_connections.sh
  test/bin/scenario.sh
  test/kickstart-templates/includes/post-microshift.cfg
  test/scenario_settings.sh.example
  test/scenarios/periodics/el94-src@cncf-conformance.sh
Labels: lgtm, approved, jira/valid-reference

#3791 NO-ISSUE: Performance CI job: get BRANCH and JOB_TYPE from CI
  scripts/ci-footprint-and-performance/tests/100-push-results-to-s3.sh
Labels: lgtm, approved, jira/valid-reference

#3808 USHIFT-4081: Skip new sig-network-edge idling tests
  origin/skip.txt
Labels: lgtm, approved, jira/valid-reference

#3807 OCPBUGS-38851: 4.17 rebase with kubelet.yaml fix
  Makefile.kube_git.var
  Makefile.version.aarch64.var
  Makefile.version.x86_64.var
  assets/optional/multus/kustomization.aarch64.yaml
  assets/optional/multus/kustomization.x86_64.yaml
  assets/optional/multus/release-multus-aarch64.json
  assets/optional/multus/release-multus-x86_64.json
  assets/optional/operator-lifecycle-manager/kustomization.aarch64.yaml
  assets/optional/operator-lifecycle-manager/kustomization.x86_64.yaml
  assets/optional/operator-lifecycle-manager/release-olm-aarch64.json
  assets/optional/operator-lifecycle-manager/release-olm-x86_64.json
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  etcd/go.mod
  etcd/go.sum
  etcd/vendor/modules.txt
  go.mod
  go.sum
  packaging/crio.conf.d/10-microshift_amd64.conf
  packaging/crio.conf.d/10-microshift_arm64.conf
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/commits.txt
  scripts/auto-rebase/last_rebase.sh
  scripts/auto-rebase/rebase.sh
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#3784 USHIFT-2804: Instructions for layered product teams for testing the products with MicroShift
  README.md
  docs/contributor/image_mode.md
  docs/contributor/layered_product_ci.md
Labels: lgtm, approved, jira/valid-reference

#3816 OCPBUGS-38974: Update openvswitch to 3.4
  packaging/rpm/microshift.spec
  test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source-ostree-parent.containerfile
  test/kickstart-templates/includes/post-cos9rpm.cfg
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3829 OCPBUGS-38848: Rebase 4.18 2024-08-29 with fixes
  Makefile.kube_git.var
  Makefile.version.aarch64.var
  Makefile.version.x86_64.var
  assets/components/openshift-router/cluster-role.yaml
  assets/crd/0000_03_config-operator_01_securitycontextconstraints.crd.yaml
  assets/crd/route.crd.yaml
  assets/optional/multus/kustomization.aarch64.yaml
  assets/optional/multus/kustomization.x86_64.yaml
  assets/optional/multus/release-multus-aarch64.json
  assets/optional/multus/release-multus-x86_64.json
  assets/optional/operator-lifecycle-manager/kustomization.aarch64.yaml
  assets/optional/operator-lifecycle-manager/kustomization.x86_64.yaml
  assets/optional/operator-lifecycle-manager/release-olm-aarch64.json
  assets/optional/operator-lifecycle-manager/release-olm-x86_64.json
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  etcd/go.mod
  etcd/go.sum
  etcd/vendor/modules.txt
  go.mod
  go.sum
  packaging/crio.conf.d/10-microshift_amd64.conf
  packaging/crio.conf.d/10-microshift_arm64.conf
  packaging/rpm/microshift.spec
  scripts/auto-rebase/assets.yaml
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/commits.txt
  scripts/auto-rebase/last_rebase.sh
  scripts/auto-rebase/rebase.sh
  test/bin/common_versions.sh
  test/image-blueprints/layer1-base/group2/rhel93-microshift-yminus2.toml
  test/image-blueprints/layer1-base/group2/rhel94-microshift-yminus2.toml
  test/scenarios/periodics/el92-yminus2@el94-crel@upgrade-ok.sh
  test/scenarios/periodics/el93-yminus2@el94-src@upgrade-ok.sh
  test/scenarios/periodics/el94-crel@el94-src@optional-upgrade.sh
  test/scenarios/periodics/el94-crel@el94-src@upgrade-ok.sh
  test/scenarios/periodics/el94-prel@el94-crel@upgrade-ok.sh
  test/scenarios/periodics/el94-yminus2@el94-src@upgrade-ok.sh
  test/scenarios/presubmits/el94-src@rpm-install.sh
  test/scenarios/presubmits/el94-yminus2@el94-src@upgrade-ok.sh
  test/suites/tuned/workload-partitioning.robot
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug, jira/severity-critical, jira/valid-reference
