Repository openshift/microshift, pull requests merged in 2024-02, with the labels that each got.

#2950 USHIFT-2241: use unique repo name when extracting container images
  test/bin/build_images.sh
Labels: lgtm, approved, jira/valid-reference

#2945 USHIFT-2237: move default for mirror registry to the output directory
  test/bin/common.sh
  test/bin/mirror_registry.sh
Labels: lgtm, approved, jira/valid-reference

#2867 USHIFT-2105: Recreate core components on microshift restarts
  test/kickstart-templates/includes/post-system.cfg
  test/scenarios/el92-src@log-scan.sh
  test/suites/logscan/log-scan.robot
  test/suites/network/multi-nic.robot
  test/suites/standard1/networking-smoke.robot
  test/suites/storage/snapshot.robot
Labels: lgtm, approved, jira/valid-reference

#2955 USHIFT-2247: Remove /usr/libexec/cni from CRI-O conf
  packaging/crio.conf.d/microshift_amd64.conf
  packaging/crio.conf.d/microshift_arm64.conf
Labels: lgtm, approved, jira/valid-reference

#2949 USHIFT-2239: Destroy VM when virt-install exits with errors
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2967 [release-4.15] USHIFT-2254: Greenboot failures in scenario testing
  test/kickstart-templates/kickstart-liveimg.ks.template
  test/kickstart-templates/kickstart-offline.ks.template
  test/kickstart-templates/kickstart.ks.template
  test/scenarios/el92-src@log-scan.sh
  test/suites/logscan/log-scan.robot
  test/suites/network/multi-nic.robot
  test/suites/standard1/networking-smoke.robot
  test/suites/storage/snapshot.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2932 USHIFT-2224: Rename CRI-O configs to include prefix
  packaging/crio.conf.d/10-microshift_amd64.conf
  packaging/crio.conf.d/10-microshift_arm64.conf
  packaging/crio.conf.d/11-microshift-ovn.conf
  packaging/rpm/microshift.spec
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#2956 USHIFT-2220: Initial Multus manifests
  assets/optional/multus/00-namespace.yaml
  assets/optional/multus/01-crd-networkattachmentdefinition.yaml
  assets/optional/multus/02-service-account.yaml
  assets/optional/multus/03-cluster-role.yaml
  assets/optional/multus/04-cluster-role-binding.yaml
  assets/optional/multus/05-configmap.yaml
  assets/optional/multus/06-daemonset.yaml
  assets/optional/multus/kustomization.yaml
  scripts/auto-rebase/assets.yaml
Labels: lgtm, approved, jira/valid-reference

#2966 USHIFT-2253: Improve microshift start time by reducing readiness checks intervals
  pkg/controllers/kube-apiserver.go
  pkg/util/net.go
Labels: lgtm, approved, jira/valid-reference

#2940 USHIFT-2090: Introduce cluster-id file creation on MicroShift startup
  docs/user/debugging_tips.md
  pkg/cmd/run.go
  pkg/controllers/clusterid.go
  test/suites/osconfig/clusterid.robot
Labels: lgtm, approved, jira/valid-reference

#2941 USHIFT-881: Add support for CentOS 9 OS in test harness framework
  test/README.md
  test/bin/build_images.sh
  test/bin/scenario.sh
  test/image-blueprints/layer1-base/group1/centos9.image-fetcher
  test/kickstart-templates/includes/main-cdrom.cfg
  test/kickstart-templates/includes/post-containers.cfg
  test/kickstart-templates/includes/post-cos9rpm.cfg
  test/kickstart-templates/kickstart-centos.ks.template
  test/scenarios-periodics/cos9-src@rpm-standard1.sh
  test/suites/rpm/install-and-upgrade-successful.robot
Labels: lgtm, approved, jira/valid-reference

#2979 Revert "USHIFT-2247: Remove /usr/libexec/cni from CRI-O conf"
  packaging/crio.conf.d/10-microshift_amd64.conf
  packaging/crio.conf.d/10-microshift_arm64.conf
Labels: lgtm, approved, jira/valid-reference

#2968 USHIFT-2257: detect the released RPMs using the current system architecture
  test/bin/get_rel_version_repo.sh
Labels: lgtm, approved, jira/valid-reference

#2978 USHIFT-2263: Add env var driven origin test list
  origin/run.sh
Labels: lgtm, approved, jira/valid-reference

#2980 Revert "USHIFT-2253: Improve microshift start time by reducing readiness checks intervals"
  pkg/controllers/kube-apiserver.go
  pkg/util/net.go
Labels: lgtm, approved, jira/valid-reference

#2982 USHIFT-2266: have the release note script handle the tag commands
  scripts/release-notes/gen_ec_release_notes.py
Labels: lgtm, approved, jira/valid-reference

#2923 OCPBUGS-27849: Create microshift-olm-release-info RPM
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2991 [release-4.14] USHIFT-2347: Work around broken osbuild dependency on RHEL 9.3
  scripts/image-builder/configure.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3002 USHIFT-2367: documentation preview build scripts
  scripts/docs-preview/Containerfile
  scripts/docs-preview/README.md
  scripts/docs-preview/build-in-container.sh
  scripts/docs-preview/build.sh
  scripts/docs-preview/common.sh
  scripts/docs-preview/serve.sh
  scripts/fetch_tools.sh
Labels: lgtm, approved, jira/valid-reference

#3007 USHIFT-2367: Minor enhancements of docs-preview scripts
  scripts/docs-preview/Containerfile
  scripts/docs-preview/README.md
  scripts/docs-preview/build-in-container.sh
  scripts/docs-preview/build.sh
  scripts/docs-preview/clean.sh
  scripts/docs-preview/common.sh
  scripts/docs-preview/serve.sh
Labels: lgtm, approved, jira/valid-reference

#3009 NO-ISSUE: Revert commits
  test/bin/stress_testing.sh
  test/suites/osconfig/clusterid.robot
Labels: lgtm, approved, jira/valid-reference

#3000 USHIFT-2118: Add 2 RF test for Cluster ID feature
  test/suites/osconfig/clusterid.robot
Labels: lgtm, approved, jira/valid-reference

#2993 OCPBUGS-29271: Rebase lvms registry.access.redhat.com lvms4 lvms operator bundle v4.15.0
  assets/components/lvms/topolvm-configmap_lvms-version.yaml
  assets/components/lvms/topolvm-controller_rbac.authorization.k8s.io_v1_clusterrole.yaml
  assets/components/lvms/topolvm-node_daemonset.yaml
  assets/components/lvms/topolvm-node_rbac.authorization.k8s.io_v1_clusterrole.yaml
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  scripts/auto-rebase/last_lvms_rebase.sh
  scripts/auto-rebase/lvms_assets.yaml
  scripts/auto-rebase/rebase-lvms.sh
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3018 USHIFT-2377: update getting started docs to point to 4.14
  docs/user/getting_started.md
Labels: lgtm, approved, jira/valid-reference

#3001 USHIFT-2366: include e2e.log in CNCF conformance artifacts
  test/scenarios-periodics/el92-src@cncf-conformance.sh
Labels: lgtm, approved, jira/valid-reference

#3023 USHIFT-2345: Revert "Work around broken osbuild dependency on RHEL 9.3"
  scripts/image-builder/configure.sh
Labels: lgtm, approved, jira/valid-reference

#3024 USHIFT-2346: Revert "[release-4.15] USHIFT-2346: Work around broken osbuild dependency on RHEL 9.3"
  scripts/image-builder/configure.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3016 USHIFT-2374: Add option to pull images on configure-vm
  scripts/devenv-builder/configure-vm.sh
  scripts/pull_retry.sh
Labels: lgtm, approved, jira/valid-reference

#3027 USHIFT-2374: Move pull images after starting crio
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#3026 USHIFT-2378: change sonobuoy command to match the CNCF readme
  test/scenarios-periodics/el92-src@cncf-conformance.sh
Labels: lgtm, approved, jira/valid-reference

#3031 USHIFT-2386: Add option to pull images in configure-vm.sh
  scripts/devenv-builder/configure-vm.sh
  scripts/pull_retry.sh
Labels: lgtm, approved, cherry-pick-approved, staff-eng-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3032 USHIFT-2382: Increase timeout for osconfig periodic scenario
  test/scenarios-periodics/el92-src@osconfig.sh
Labels: lgtm, approved, jira/valid-reference

#3033 USHIFT-2286: Specify per-platform console device names when starting VMs
  scripts/devenv-builder/manage-vm.sh
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#3040 USHIFT-2392: require story points and set target version on jira tickets
  scripts/jira/manage_ticket.py
  scripts/jira/manage_ticket.sh
Labels: lgtm, approved, jira/valid-reference

#3038 USHIFT-2391: remove FDO scenario
  test/scenarios-periodics/el92-src@fdo.sh
  test/suites/upgrade/fdo.robot
Labels: lgtm, approved, jira/valid-reference

#3047 USHIFT-2430: when closing check story points before dry-run flag
  scripts/jira/manage_ticket.py
Labels: lgtm, approved, jira/valid-reference

#3042 NO-ISSUE: rebase-main-4.16.0-0.nightly-2024-02-17-094036_amd64-2024-02-17_arm64-2024-02-19
  Makefile.kube_git.var
  Makefile.version.aarch64.var
  Makefile.version.x86_64.var
  assets/components/csi-snapshot-controller/webhook_deployment.yaml
  assets/components/csi-snapshot-controller/webhook_serviceaccount.yaml
  assets/core/kubelet.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-catalogsources.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-clusterserviceversions.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-installplans.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-namespace.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-olmconfigs.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-operatorconditions.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-operatorgroups.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-operators.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-packageserver.pdb.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-pprof-config.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-pprof-rbac.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-pprof-secret.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-subscriptions.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_01-olm-operator.serviceaccount.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_02-olmconfig.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_02-services.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_09-aggregated.clusterrole.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_13-operatorgroup-default.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_15-csv-viewer.rbac.yaml
  assets/optional/operator-lifecycle-manager/kustomization.aarch64.yaml
  assets/optional/operator-lifecycle-manager/kustomization.x86_64.yaml
  assets/optional/operator-lifecycle-manager/release-olm-aarch64.json
  assets/optional/operator-lifecycle-manager/release-olm-x86_64.json
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  etcd/go.mod
  etcd/go.sum
  etcd/vendor/go.etcd.io/etcd/api/v3/version/version.go
  etcd/vendor/go.etcd.io/etcd/client/pkg/v3/fileutil/purge.go
  etcd/vendor/go.etcd.io/etcd/server/v3/embed/etcd.go
  etcd/vendor/go.etcd.io/etcd/server/v3/etcdserver/server.go
  etcd/vendor/go.etcd.io/etcd/server/v3/mvcc/backend/batch_tx.go
  etcd/vendor/go.etcd.io/etcd/server/v3/mvcc/kvstore_compaction.go
  etcd/vendor/modules.txt
  go.mod
  go.sum
  packaging/crio.conf.d/10-microshift_amd64.conf
  packaging/crio.conf.d/10-microshift_arm64.conf
  pkg/components/csi-snapshot-controller.go
  scripts/auto-rebase/assets.yaml
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/commits.txt
  scripts/auto-rebase/last_rebase.sh
  scripts/auto-rebase/rebase.sh
  vendor/go.etcd.io/etcd/api/v3/version/version.go
  vendor/go.etcd.io/etcd/client/pkg/v3/fileutil/purge.go
  vendor/k8s.io/apiserver/pkg/apis/apiserver/types.go
  vendor/k8s.io/apiserver/pkg/apis/apiserver/v1alpha1/types.go
  vendor/k8s.io/apiserver/pkg/apis/apiserver/v1alpha1/zz_generated.conversion.go
  vendor/k8s.io/apiserver/pkg/apis/apiserver/validation/validation.go
  vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/oidc.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#2914 [release-4.15] USHIFT-2208: add periodic test scenario for the standard tests on rpm-based system
  packaging/selinux/microshift.fc
  packaging/selinux/microshift.te
  test/resources/selinux.py
  test/resources/selinux.resource
  test/scenarios-periodics/el92-src@rpm-standard1.sh
  test/scenarios-periodics/el92-src@rpm-standard2.sh
Labels: lgtm, approved, cherry-pick-approved, staff-eng-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3046 [release-4.14] USHIFT-2208: add periodic test scenario for the standard tests on rpm-based system
  test/resources/selinux.py
  test/resources/selinux.resource
  test/scenarios-periodics/el92-src@rpm-standard1.sh
  test/scenarios-periodics/el92-src@rpm-standard2.sh
  test/scenarios-periodics/el93-src@standard-suite1.sh
  test/scenarios-periodics/el93-src@standard-suite2.sh
  test/scenarios/el92-src@standard-suite1.sh
  test/scenarios/el92-src@standard-suite2.sh
  test/suites/standard1/cleanup-data.robot
  test/suites/standard1/kustomize.robot
  test/suites/standard1/log-scan.robot
  test/suites/standard1/networking-smoke.robot
  test/suites/standard1/show-config.robot
  test/suites/standard1/validate-selinux-policy.robot
  test/suites/standard1/version.robot
  test/suites/standard2/etcd.robot
  test/suites/standard2/hostname.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3012 USHIFT-2344: Add layer4 image-blueprints to support creating images with RPMs buillt elsewhere
  test/bin/build_images.sh
  test/image-blueprints/layer4-ext/group1/rhel92_microshift-ext.image-installer
  test/image-blueprints/layer4-ext/group1/rhel92_microshift-ext.toml
  test/image-blueprints/layer4-ext/group1/rhel93_microshift-ext.image-installer
  test/image-blueprints/layer4-ext/group1/rhel93_microshift-ext.toml
Labels: lgtm, approved, jira/valid-reference

#3017 USHIFT-2262: Fix log scan test to check for errors on startup and after restart
  test/scenarios/el92-src@log-scan.sh
  test/suites/logscan/log-scan.robot
Labels: lgtm, approved, jira/valid-reference

#3056 USHIFT-2381: Fix tmp directory creation when copying anaconda logs in CI
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#3051 USHIFT-2260: Add support to run Stress Testing conditions from Jenkins
  test/bin/stress_testing.sh
  test/run.sh
Labels: lgtm, approved, jira/valid-reference

#3065 USHIFT-2223: greenboot healthcheck for Multus
  packaging/greenboot/functions.sh
  packaging/greenboot/microshift-running-check-multus.sh
Labels: lgtm, approved, jira/valid-reference

#3064 USHIFT-2225: Create CRI-O cfg to use Multus over ovn-k
  packaging/crio.conf.d/12-microshift-multus.conf
Labels: lgtm, approved, jira/valid-reference

#2961 USHIFT-2221: Update Multus images during rebase
  assets/optional/multus/kustomization.aarch64.yaml
  assets/optional/multus/kustomization.x86_64.yaml
  assets/optional/multus/kustomization.yaml
  assets/optional/multus/release-multus-aarch64.json
  assets/optional/multus/release-multus-x86_64.json
  scripts/auto-rebase/assets.yaml
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#3011 USHIFT-2372: Correct the GROUP path assignment when calling build_images.sh with -t.
  test/bin/build_images.sh
Labels: lgtm, approved, jira/valid-reference

#3070 OCPBUGS-29847: Loosen openshift-marketplace security
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-namespace.yaml
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3082 USHIFT-2327: Multus - DHCP server
  assets/optional/multus/07-daemonset-dhcp.yaml
  assets/optional/multus/kustomization.yaml
  scripts/auto-rebase/assets.yaml
Labels: lgtm, approved, jira/valid-reference
