Repository openshift/microshift, pull requests merged in 2024-05, with the labels that each got.

#3309 OCPBUGS-31661: Add MicroShift RPM verification tests
  test/resources/microshift-rpm.resource
  test/suites/optional/multus.robot
  test/suites/optional/olm.robot
  test/suites/standard1/version.robot
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3305 USHIFT-3005: Remove ovsdb-server/memory-trim-on-compaction setting from OVN configuration
  assets/components/ovn/multi-node/master/daemonset.yaml
  assets/components/ovn/single-node/master/daemonset.yaml
Labels: lgtm, approved, jira/valid-reference

#3314 USHIFT-3127: Update docs and scripts for support RHEL 9.4 devenv
  docs/contributor/devenv_setup.md
  scripts/devenv-builder/configure-vm.sh
  scripts/devenv-builder/manage-vm.sh
  scripts/get-latest-rhocp-repo.sh
Labels: lgtm, approved, jira/valid-reference

#3317 USHIFT-3125: Switch to using non-beta RHEL 9.4 container images for bootc
  test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source.containerfile
Labels: lgtm, approved, jira/valid-reference

#3319 USHIFT-3100: Add conformance tests skip list
  origin/skip.txt
Labels: lgtm, approved, jira/valid-reference

#3321 USHIFT-2984: Add bootc image caching to ISO build process
  test/bin/ci_phase_iso_build.sh
Labels: lgtm, approved, jira/valid-reference

#3322 USHIFT-2210: Run FIPS tests on RPM and ostree-based RHEL 9.4 systems
  test/bin/scenario.sh
  test/image-blueprints/layer3-periodic/group1/rhel92-source-isolated.image-installer
  test/image-blueprints/layer3-periodic/group1/rhel94-source-isolated.image-installer
  test/image-blueprints/layer3-periodic/group1/rhel94-source-isolated.toml
  test/kickstart-templates/includes/post-fips.cfg
  test/kickstart-templates/kickstart-liveimg.ks.template
  test/kickstart-templates/kickstart.ks.template
  test/scenarios-periodics/el94-src@fips-rpm.sh
  test/scenarios-periodics/el94-src@fips.sh
  test/scenarios-periodics/el94-src@isolated-net.sh
  test/scenarios-periodics/el94-src@offline.sh
  test/scenarios-periodics/el94-src@rpm-standard1.sh
  test/scenarios-periodics/el94-src@rpm-standard2.sh
Labels: lgtm, approved, jira/valid-reference

#3331 USHIFT-3100: Update conformance skip list
  origin/skip.txt
Labels: lgtm, approved, jira/valid-reference

#3330 USHIFT-3139: Release notes job: create tag before referencing it
  scripts/release-notes/gen_ec_release_notes.py
Labels: lgtm, approved, jira/valid-reference

#3338 USHIFT-3141: Increase vm boot timeout to 30m in scenarios
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#3326 USHIFT-3138: Refactor scenarios not to exceed 20m runtime in pre-submits
  test/scenarios-bootc/cos9-src@osconfig-cleanup-data.sh
  test/scenarios-bootc/cos9-src@osconfig-lifecycle.sh
  test/scenarios-bootc/cos9-src@osconfig-misc.sh
  test/scenarios-bootc/el94-src@osconfig-cleanup-data.sh
  test/scenarios-bootc/el94-src@osconfig-lifecycle.sh
  test/scenarios-bootc/el94-src@osconfig-misc.sh
  test/suites/standard2/validate-certificate-rotation.robot
Labels: lgtm, approved, jira/valid-reference

#3320 USHIFT-2924: Add support for templates in bootc image and container files
  test/bin/common.sh
  test/bin/pyutils/build_bootc_images.py
  test/bootc-sources/microshift_repo_config.sh.template
  test/image-blueprints/layer5-bootc/group1/cos9-bootc-source.containerfile
  test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source.containerfile
  test/image-blueprints/layer5-bootc/group2/cos9-bootc-source-optionals.containerfile
  test/image-blueprints/layer5-bootc/group2/rhel94-bootc-source-optionals.containerfile
Labels: lgtm, approved, jira/valid-reference

#3340 OCPBUGS-30039: Switch to registry.redhat.io images for OpenSSL dependency in TopoLVM
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  packaging/images/openshift-ci/Dockerfile.test-runtime
  scripts/image-builder/config/registries.conf.template
  scripts/verify/verify-images.sh
  test/kickstart-templates/includes/post-containers.cfg
  test/suites/network/isolated-network.robot
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3343 USHIFT-2463: Add PreRunModifier flag to skip RF
  test/resources/SkipTests.py
  test/run.sh
Labels: lgtm, approved, jira/valid-reference

#3344 USHIFT-3151: The images/openshift-ci container files are no longer used
  packaging/images/openshift-ci/Dockerfile.microshift-test
  packaging/images/openshift-ci/Dockerfile.test-runtime
Labels: lgtm, approved, jira/valid-reference

#3310 USHIFT-2970: RHEL 9.4 PreSubmits
  test/image-blueprints/layer1-base/group1/rhel94.image-installer
  test/image-blueprints/layer1-base/group1/rhel94.toml
  test/image-blueprints/layer1-base/group2/rhel93-microshift-previous-minor.image-installer
  test/image-blueprints/layer1-base/group2/rhel93-microshift-previous-minor.toml
  test/image-blueprints/layer2-presubmit/group1/rhel-9.4-microshift-source-aux.alias
  test/image-blueprints/layer2-presubmit/group1/rhel94-crel.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-base.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-fake-next-minor.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source.toml
  test/scenarios/el92-prel@el94-src@upgrade-ok.sh
  test/scenarios/el92-yminus2@el94-src@upgrade-ok.sh
  test/scenarios/el93-prel@el94-src@upgrade-ok.sh
  test/scenarios/el94-base@el94-src@upgrade-ok.sh
  test/scenarios/el94-crel@el94-src@upgrade-ok.sh
  test/scenarios/el94-src@backup-and-restore-on-reboot.sh
  test/scenarios/el94-src@backups.sh
  test/scenarios/el94-src@downgrade-block.sh
  test/scenarios/el94-src@log-scan.sh
  test/scenarios/el94-src@multi-nic.sh
  test/scenarios/el94-src@rpm-install.sh
  test/scenarios/el94-src@standard-suite1.sh
  test/scenarios/el94-src@standard-suite2.sh
  test/scenarios/el94-src@storage.sh
  test/scenarios/el94-src@upgrade-fails-on-1st-boot-but-recovers-on-2nd.sh
  test/scenarios/el94-src@upgrade-fails.sh
Labels: lgtm, approved, jira/valid-reference

#3350 OCPBUGS-33588: Upgrade openvswitch package for 4.16
  packaging/rpm/microshift.spec
  test/bootc-sources/microshift_repo_config.sh.template
  test/kickstart-templates/includes/post-cos9rpm.cfg
  test/resources/microshift-rpm.resource
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3351 USHIFT-3154: Add terminationMessagePolicy to topolvm pods
  assets/components/lvms/topolvm-controller_deployment.yaml
  assets/components/lvms/topolvm-node_daemonset.yaml
Labels: lgtm, approved, jira/valid-reference

#3355 USHIFT-3155: Fix greenboot configuration update
  test/kickstart-templates/includes/post-system.cfg
Labels: lgtm, approved, jira/valid-reference

#3363 USHIFT-3169: Use RH's Community Operators instead of OperatorHub.io
  test/assets/olm/catalog-source.yaml
  test/assets/olm/subscription-cert-manager.yaml
  test/suites/optional/olm.robot
Labels: lgtm, approved, jira/valid-reference

#3364 [release-4.15] USHIFT-3170: Use RH's Community Operators instead of OperatorHub.io
  test/assets/olm/catalog-source.yaml
  test/assets/olm/subscription-cert-manager.yaml
  test/suites/optional/olm.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3359 USHIFT-2912: Use MicroShift-specific Multus images
  assets/optional/multus/06-daemonset.yaml
  assets/optional/multus/07-daemonset-dhcp.yaml
  assets/optional/multus/kustomization.aarch64.yaml
  assets/optional/multus/kustomization.x86_64.yaml
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#3362 NO-ISSUE: `scenario.sh recreate` command
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#3386 NO-ISSUE: Rebase 4e43a1545 4.16.0 0.nightly 2024 05 21 221942 amd64 2024 05 21 arm64 2024 05 22
  Makefile.version.aarch64.var
  Makefile.version.x86_64.var
  assets/controllers/kube-controller-manager/defaultconfig.yaml
  assets/optional/multus/kustomization.aarch64.yaml
  assets/optional/multus/kustomization.x86_64.yaml
  assets/optional/multus/release-multus-aarch64.json
  assets/optional/multus/release-multus-x86_64.json
  assets/optional/operator-lifecycle-manager/kustomization.aarch64.yaml
  assets/optional/operator-lifecycle-manager/kustomization.x86_64.yaml
  assets/optional/operator-lifecycle-manager/release-olm-aarch64.json
  assets/optional/operator-lifecycle-manager/release-olm-x86_64.json
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  packaging/crio.conf.d/10-microshift_amd64.conf
  packaging/crio.conf.d/10-microshift_arm64.conf
  pkg/controllers/kube-controller-manager_test.go
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/commits.txt
  scripts/auto-rebase/last_rebase.sh
Labels: lgtm, approved, jira/valid-reference

#3381 USHIFT-3241: Run standard-suite-2 with optional RPMs
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-with-optionals.toml
  test/scenarios/el94-src@standard-suite2.sh
Labels: lgtm, approved, jira/valid-reference

#3407 USHIFT-3177: Use only ipv4 addresses for default router
  pkg/loadbalancerservice/router.go
Labels: lgtm, approved, jira/valid-reference

#3406 USHIFT-3260: Fix build_bootc_images to be more robust when processing versions
  test/bin/pyutils/build_bootc_images.py
  test/bootc-sources/microshift_repo_config.sh.template
Labels: lgtm, approved, jira/valid-reference

#3414 [release-4.15] USHIFT-3267: Increase cncf result collection timeout to 10m
  test/scenarios-periodics/el92-src@cncf-conformance.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3365 USHIFT-3164: audit log defaults fix
  cmd/generate-config/config/config-openapi-spec.json
  docs/user/howto_config.md
  packaging/microshift/config.yaml
  pkg/config/apiserver.go
  pkg/config/config.go
Labels: lgtm, approved, jira/valid-reference

#3415 USHIFT-3136: Increase nginx resources and timeouts to mitigate failed ostree installations
  test/bin/start_webserver.sh
Labels: lgtm, approved, jira/valid-reference

#3413 USHIFT-3263: Increase cncf result collection timeout to 10m
  test/scenarios-periodics/el92-src@cncf-conformance.sh
Labels: lgtm, approved, jira/valid-reference
