Repository openshift/microshift, pull requests merged in 2024-06, with the labels that each got.

#3408 USHIFT-3159: Retry podman commands when building bootc images
  test/bin/pyutils/build_bootc_images.py
  test/bin/pyutils/common.py
Labels: lgtm, approved, jira/valid-reference

#3439 USHIFT-3315: Increase delete openshift-ingress pod timeout
  test/suites/standard1/router.robot
Labels: lgtm, approved, jira/valid-reference

#3441 USHIFT-3308: Declare openvswitch3.1 package as obsolete to allow seemless upgrade to openvswitch3.3
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#3454 USHIFT-3454: Temporarily add flaky tests from conformance to skip list
  origin/skip.txt
Labels: lgtm, approved, jira/valid-reference

#3449 NO-ISSUE: Update asset.yaml source for the route crd
  scripts/auto-rebase/assets.yaml
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#3455 USHIFT-3177: Remove warnings about not allowed addresses in router se…
  pkg/loadbalancerservice/router.go
Labels: lgtm, approved, jira/valid-reference

#3433 OCPBUGS-34491: fix: adjust topolvm controller probes
  assets/components/lvms/topolvm-controller_deployment.yaml
  assets/components/lvms/topolvm-node_daemonset.yaml
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#3462 USHIFT-3457: Various improvements of "Release notes" job
  scripts/release-notes/gen_ec_release_notes.py
Labels: lgtm, approved, jira/valid-reference

#3475 USHIFT-3477: Add explicit crun default runtime configuration for crio
  packaging/crio.conf.d/00-crio-crun.conf
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#3448 USHIFT-3136: Retry virt-install command in case of installation error
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#3484 [release-4.15] USHIFT-3276: Retry virt-install command in case of installation error
  test/bin/scenario.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3489 USHIFT-3210: Fix greenboot functions to use GREENBOOT_MAX_BOOT_ATTEMPTS
  packaging/greenboot/functions.sh
Labels: lgtm, approved, jira/valid-reference

#3483 USHIFT-2475: The build_images.sh script exits with error if depsolve stage fails
  test/bin/build_images.sh
Labels: lgtm, approved, jira/valid-reference

#3468 USHIFT-3177: Avoid updating default router ips if status is the same
  pkg/loadbalancerservice/controller.go
Labels: lgtm, approved, jira/valid-reference

#3470 USHIFT-3319: Re-Enable Non-Upgrade Scenarios Which Depend on 4.17 mirrored rpms
  test/kickstart-templates/includes/post-cos9rpm.cfg
  test/scenarios-periodics/cos9-src@rpm-standard1.sh
  test/scenarios-periodics/cos9-src@rpm-standard2.sh
  test/scenarios/el94-crel@el94-src@upgrade-ok.sh
Labels: lgtm, approved, jira/valid-reference

#3506 USHIFT-3501: separate periodic upgrade tests to reduce resource pressure on hypervisor
  test/scenarios-upgrades/el92-crel@el94-src@optional-upgrade.sh
  test/scenarios-upgrades/el92-prel@el94-crel@upgrade-ok.sh
  test/scenarios-upgrades/el92-prel@el94-src@upgrade-fails-and-rolls-back.sh
  test/scenarios-upgrades/el92-prel@el94-src@upgrade-ok.sh
  test/scenarios-upgrades/el92-yminus2@el94-crel@upgrade-ok.sh
  test/scenarios-upgrades/el93-prel@el94-crel@upgrade-ok.sh
  test/scenarios-upgrades/el93-prel@el94-src@upgrade-ok.sh
  test/scenarios-upgrades/el93-yminus2@el94-crel@upgrade-ok.sh
  test/scenarios-upgrades/el93-yminus2@el94-src@upgrade-ok.sh
  test/scenarios-upgrades/el94-crel@el94-src@optional-upgrade.sh
  test/scenarios-upgrades/el94-crel@el94-src@upgrade-fails.sh
  test/scenarios-upgrades/el94-crel@el94-src@upgrade-ok.sh
  test/scenarios-upgrades/el94-src@upgrade-fails-cannot-backup.sh
Labels: lgtm, approved, jira/valid-reference

#3500 USHIFT-3270: Increase dnf low-bitrate timeout
  test/resources/microshift-rpm.resource
Labels: lgtm, approved, jira/valid-reference

#3514 [release-4.14] USHIFT-2463: Add PreRunModifier flag to skip RF
  test/resources/SkipTests.py
  test/run.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3515 [release-4.15] USHIFT-2463: Add PreRunModifier flag to skip RF
  test/resources/SkipTests.py
  test/run.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3491 OCPBUGS-35507: Fix CRI-O version to match Kubernetes version
  packaging/rpm/microshift.spec
  scripts/devenv-builder/configure-vm.sh
  scripts/get-latest-rhocp-repo.sh
  scripts/image-builder/build.sh
  scripts/image-builder/config/rhocp.toml.template
  test/bin/build_images.sh
  test/bin/pyutils/build_bootc_images.py
  test/bin/scenario.sh
  test/bootc-sources/microshift_repo_config.sh.template
  test/kickstart-templates/includes/post-cos9rpm.cfg
  test/package-sources/rhocp-y.toml
  test/package-sources/rhocp-y1.toml
  test/scenarios/el94-crel@el94-src@upgrade-ok.sh.disabled
  test/scenarios/el94-src@rpm-install.sh
  test/suites/rpm/install-and-upgrade-successful.robot
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#3493 USHIFT-3494: Add log file printout to the console in case of anaconda errors
  test/kickstart-templates/includes/onerror-logs.cfg
  test/kickstart-templates/kickstart-bootc.ks.template
  test/kickstart-templates/kickstart-centos.ks.template
  test/kickstart-templates/kickstart-liveimg.ks.template
  test/kickstart-templates/kickstart-offline.ks.template
  test/kickstart-templates/kickstart.ks.template
Labels: lgtm, approved, jira/valid-reference

#3527 NO-ISSUE: Add runtime crun to crio for y-2 blueprint
  test/image-blueprints/layer1-base/group2/rhel92-microshift-yminus2.toml
Labels: lgtm, approved, jira/valid-reference

#3529 USHIFT-3002: Add router listenAddress ipv6 handling
  etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
  pkg/config/config.go
  pkg/loadbalancerservice/router.go
Labels: lgtm, approved, jira/valid-reference

#3542 OCPBUGS-35468: Filter out empty entries in router listenAddress
  etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
  pkg/config/config.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#3556 NO-ISSUE: Enable rhocp repos if mirror is used
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#3528 USHIFT-3482: IPv6 handling adjustments in configuration
  etcd/vendor/github.com/openshift/microshift/pkg/config/multinode.go
  etcd/vendor/github.com/openshift/microshift/pkg/util/cert.go
  etcd/vendor/github.com/openshift/microshift/pkg/util/net.go
  pkg/config/multinode.go
  pkg/controllers/kube-controller-manager.go
  pkg/controllers/kube-controller-manager_test.go
  pkg/controllers/openshift-route-controller-manager.go
  pkg/util/cert.go
  pkg/util/net.go
Labels: lgtm, approved, jira/valid-reference

#3516 USHIFT-3271: Prevent pod name-collisions in storage tests
  test/resources/common.resource
  test/suites/storage/pvc-resize.robot
  test/suites/storage/reboot.robot
  test/suites/storage/snapshot.robot
Labels: lgtm, approved, jira/valid-reference
