Repository openshift/microshift, pull requests merged in 2024-12, with the labels that each got.

#4260 NO-ISSUE: Bump golangci-lint version from 1.55.2 to 1.62.2
  pkg/admin/data/atomic_dir_copy.go
  pkg/admin/data/disk_space.go
  pkg/components/storage.go
  pkg/config/lvmd/lvmd_test.go
  pkg/mdns/controller.go
  scripts/fetch_tools.sh
Labels: lgtm, approved, jira/valid-reference

#4258 USHIFT-5089: Add retry on exception when pushing images to local registry
  test/bin/pyutils/build_bootc_images.py
Labels: lgtm, approved, jira/valid-reference

#4261 [release-4.18] USHIFT-4737: Revert skopeo retry
  scripts/mirror-images.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4250 USHIFT-4912: Update sonobuoy to 0.57.2
  test/scenarios-bootc/periodics/el94-src@cncf-conformance.sh
  test/scenarios/periodics/el94-src@cncf-conformance.sh
Labels: lgtm, approved, jira/valid-reference

#4265 NO-ISSUE: Allow using custom pool for the dev vm disk
  scripts/devenv-builder/create-vm.sh
  scripts/devenv-builder/manage-vm.sh
Labels: lgtm, approved, jira/valid-reference

#4264 [release-4.18] NO-ISSUE: Fix ostree parent templating
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-base.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-fake-next-minor.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-with-optionals.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source.toml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4229 USHIFT-4916: `microshift healthcheck` - wait for `microshift.service`
  cmd/microshift/main.go
  go.mod
  packaging/greenboot/microshift-running-check.sh
  pkg/cmd/healthcheck.go
  pkg/healthcheck/healthcheck.go
  pkg/healthcheck/service.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#4259 NO-ISSUE: Rebase main 4.19.0 with updates
  Makefile.kube_git.var
  Makefile.version.aarch64.var
  Makefile.version.x86_64.var
  assets/optional/multus/kustomization.aarch64.yaml
  assets/optional/multus/kustomization.x86_64.yaml
  assets/optional/multus/release-multus-aarch64.json
  assets/optional/multus/release-multus-x86_64.json
  assets/optional/operator-lifecycle-manager/kustomization.aarch64.yaml
  assets/optional/operator-lifecycle-manager/kustomization.x86_64.yaml
  assets/optional/operator-lifecycle-manager/release-olm-aarch64.json
  assets/optional/operator-lifecycle-manager/release-olm-x86_64.json
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  etcd/go.mod
  etcd/go.sum
  etcd/vendor/go.etcd.io/etcd/api/v3/version/version.go
  etcd/vendor/go.etcd.io/etcd/client/v3/README.md
  etcd/vendor/go.etcd.io/etcd/server/v3/etcdserver/api/v3rpc/watch.go
  etcd/vendor/go.etcd.io/etcd/server/v3/etcdserver/apply.go
  etcd/vendor/go.etcd.io/etcd/server/v3/mvcc/backend/backend.go
  etcd/vendor/modules.txt
  go.mod
  go.sum
  packaging/crio.conf.d/10-microshift_amd64.conf
  packaging/crio.conf.d/10-microshift_arm64.conf
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/commits.txt
  scripts/auto-rebase/last_rebase.sh
  scripts/devenv-builder/configure-vm.sh
  scripts/mirror-images.sh
  test/bin/common_versions.sh
  test/bin/pyutils/build_bootc_images.py
  test/bin/scenario.sh
  test/image-blueprints-bootc/layer1-base/group2/rhel94-bootc-crel-optionals.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel94-bootc-crel.containerfile
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-base.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-fake-next-minor.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-with-optionals.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source.toml
  test/scenarios-bootc/periodics/el94-crel@el94-src@optional-upgrade.sh
  test/scenarios-bootc/periodics/el94-crel@el94-src@upgrade-fails.sh
  test/scenarios-bootc/periodics/el94-crel@published-images-standard1.sh
  test/scenarios-bootc/periodics/el94-crel@published-images-standard2.sh
  test/scenarios-bootc/periodics/el94-prel@el94-crel@upgrade-ok.sh
  test/scenarios-bootc/presubmits/el94-crel@el94-src@upgrade-ok.sh
  vendor/go.etcd.io/etcd/api/v3/version/version.go
  vendor/go.etcd.io/etcd/client/v3/README.md
  vendor/k8s.io/apiserver/pkg/cel/environment/base.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/cloud-provider/controllers/service/controller.go
  vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/core.go
  vendor/k8s.io/kubernetes/pkg/controlplane/controller/leaderelection/run_with_leaderelection.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#4268 OCPBUGS-45192: Add ipv6 to trusted firewall zone
  docs/config/Containerfile.bootc-rhel9
  docs/contributor/network/host_networking.md
  docs/user/howto_firewall.md
  scripts/devenv-builder/configure-vm.sh
  test/bin/scenario.sh
  test/image-blueprints-bootc/layer1-base/group2/rhel94-bootc-crel-optionals.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel94-bootc-crel.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel94-bootc-prel.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel94-bootc-yminus2.containerfile
  test/image-blueprints-bootc/layer2-source/group1/cos9-bootc-source.containerfile
  test/image-blueprints-bootc/layer2-source/group1/rhel94-bootc-source-base.containerfile
  test/image-blueprints-bootc/layer2-source/group1/rhel94-bootc-source.containerfile
  test/image-blueprints/layer1-base/group2/rhel94-microshift-yminus2.toml
  test/image-blueprints/layer1-base/group3/rhel94-microshift-previous-minor.toml
  test/image-blueprints/layer1-base/group4/rhel94-crel-with-optionals.toml
  test/image-blueprints/layer1-base/group4/rhel94-crel.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-base.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-fake-next-minor.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-tuned.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-with-optionals.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source.toml
  test/image-blueprints/layer3-periodic/group1/rhel94-source-isolated.toml
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#4269 OCPBUGS-38468: use default route mtu
  pkg/config/ovn/ovn.go
  pkg/util/net.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4280 [release-4.18] USHIFT-5096: Use RC RPMs
  test/bin/common_versions.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4289 NO-ISSUE: fix doc message
  test/suites/standard2/etcd.robot
Labels: lgtm, approved, jira/valid-reference

#4293 OCPBUGS-38468: Revert "use default route mtu"
  pkg/config/ovn/ovn.go
  pkg/util/net.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4298 NO-ISSUE: Use `rpm -q PKG` instead of `rpm -qa | grep PKG`
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#4299 [release-4.18] NO-ISSUE: Use `rpm -q PKG` instead of `rpm -qa | grep PKG`
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4301 [release-4.17] NO-ISSUE: Use `rpm -q PKG` instead of `rpm -qa | grep PKG`
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4295 USHIFT-5101: Move offline tests from periodics to presubmits
  test/scenarios-bootc/presubmits/el95-src@offline.sh
Labels: lgtm, approved, jira/valid-reference

#4306 NO-ISSUE: Relax cri-o versioning requirement before full transition to 1.32
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#4294 USHIFT-5098: Fix container verification procedure to exit on the first error
  Makefile
  okd/src/microshift-okd-multi-build.Containerfile
  scripts/fetch_tools.sh
  scripts/verify/verify-containers.sh
  test/bin/ci_phase_iso_build.sh
  test/bin/pyutils/build_bootc_images.py
  test/bin/pyutils/common.py
  test/image-blueprints-bootc/layer1-base/group2/rhel95-bootc-crel-optionals.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel95-bootc-crel.containerfile
Labels: lgtm, approved, jira/valid-reference

#4251 USHIFT-4925: Service startup time data collecting
  pkg/cmd/run.go
  pkg/servicemanager/manager.go
  pkg/servicemanager/manager_test.go
  pkg/servicemanager/startuprecorder/startuprecorder.go
Labels: lgtm, approved, jira/valid-reference

#4308 USHIFT-4275: Enable FIPS bootc scenario on rhel95
  test/scenarios-bootc/periodics/el95-src@fips.sh
Labels: lgtm, approved, jira/valid-reference

#4244 USHIFT-4932: TLS config options for api server
  cmd/generate-config/config/config-openapi-spec.json
  docs/user/howto_config.md
  etcd/cmd/microshift-etcd/run.go
  etcd/go.mod
  etcd/vendor/github.com/openshift/library-go/pkg/crypto/OWNERS
  etcd/vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  etcd/vendor/github.com/openshift/library-go/pkg/crypto/rotation.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/apiserver.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
  etcd/vendor/k8s.io/apiserver/pkg/authentication/user/doc.go
  etcd/vendor/k8s.io/apiserver/pkg/authentication/user/user.go
  etcd/vendor/modules.txt
  packaging/microshift/config.yaml
  pkg/config/apiserver.go
  pkg/config/config.go
  pkg/controllers/kube-apiserver.go
  pkg/controllers/kube-controller-manager.go
  pkg/controllers/kube-scheduler.go
  pkg/controllers/openshift-route-controller-manager.go
  pkg/node/kubelet.go
  test/suites/standard1/configuration.robot
Labels: lgtm, approved, jira/valid-reference

#4302 USHIFT-4918 USHIFT-4920: microshift healthcheck - wait for workloads
  go.mod
  packaging/greenboot/functions.sh
  packaging/greenboot/microshift-running-check-gateway-api.sh
  packaging/greenboot/microshift-running-check-multus.sh
  packaging/greenboot/microshift-running-check-olm.sh
  packaging/greenboot/microshift-running-check.sh
  pkg/cmd/healthcheck.go
  pkg/healthcheck/debug_info.go
  pkg/healthcheck/healthcheck.go
  pkg/healthcheck/microshift_core_workloads.go
  pkg/healthcheck/utils.go
  pkg/healthcheck/workloads.go
  pkg/healthcheck/workloads_test.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#4318 USHIFT-5202: Optimize CI runtime for pre-submit jobs to run faster and more balanced
  test/scenarios-bootc/periodics/cos9-src@multi-nic.sh
  test/scenarios-bootc/periodics/cos9-src@optional.sh
  test/scenarios-bootc/periodics/cos9-src@osconfig-cleanup-data.sh
  test/scenarios-bootc/presubmits/cos9-src@auto-recovery.sh
  test/scenarios-bootc/presubmits/cos9-src@backup-and-restore-on-reboot.sh
  test/scenarios-bootc/presubmits/cos9-src@log-scan.sh
  test/scenarios-bootc/presubmits/cos9-src@storage.sh
  test/scenarios/periodics/el94-src@osconfig-cleanup-data.sh
  test/scenarios/periodics/el94-src@osconfig-lifecycle.sh
  test/scenarios/periodics/el94-src@osconfig-misc.sh
  test/scenarios/periodics/el94-src@osconfig.sh
Labels: lgtm, approved, jira/valid-reference

#4325 USHIFT-2911: Enable SELinux tests on bootc CentOS 9 Stream
  test/scenarios-bootc/periodics/el95-crel@published-images-standard1.sh
  test/scenarios-bootc/presubmits/cos9-src@standard-suite1.sh
  test/scenarios-bootc/presubmits/el95-src@standard-suite1.sh
Labels: lgtm, approved, jira/valid-reference

#4328 NO-ISSUE: Fail the bootc image build if all retries for container pull fail
  test/image-blueprints-bootc/layer2-source/group2/rhel95-bootc-source-isolated.containerfile
  test/image-blueprints-bootc/layer2-source/group3/cos9-bootc-source-isolated.containerfile
Labels: lgtm, approved, jira/valid-reference

#4329 USHIFT-5217: when ovn.yaml file empty the default is overridden with nil
  pkg/config/ovn/ovn.go
Labels: lgtm, approved, jira/valid-reference

#4307 [release-4.17] OCPBUGS-46040: Add ipv6 cluster network to firewall
  docs/contributor/network/host_networking.md
  docs/user/howto_firewall.md
  scripts/devenv-builder/configure-vm.sh
  test/bin/scenario.sh
  test/image-blueprints/layer1-base/group2/rhel92-microshift-yminus2.toml
  test/image-blueprints/layer1-base/group2/rhel94-microshift-previous-minor.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-crel.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-base.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-fake-next-minor.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-tuned.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-with-optionals.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source.toml
  test/image-blueprints/layer3-periodic/group1/rhel94-crel-with-optionals.toml
  test/image-blueprints/layer3-periodic/group1/rhel94-source-isolated.toml
  test/image-blueprints/layer5-bootc/group1/cos9-bootc-source.containerfile
  test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source-ostree-parent.containerfile
  test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source.containerfile
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#4332 USHIFT-5214: Switch to using 4.19 engineering candidate packages
  test/bin/common_versions.sh
  test/image-blueprints-bootc/layer1-base/group2/rhel95-bootc-crel-optionals.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel95-bootc-crel.containerfile
Labels: lgtm, approved, jira/valid-reference

#4338 USHIFT-5223: Properly use bootc or rpm-ostree usroverlay command
  test/resources/ostree.resource
  test/suites/greenboot/greenboot.robot
  test/suites/standard2/kustomize.robot
Labels: lgtm, approved, jira/valid-reference

#4347 [release-4.18] USHIFT-5223: Fix greenboot test to properly handle stdout
  test/suites/greenboot/greenboot.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4346 USHIFT-5226: Remove CSI webhook due to deprecation
  assets/components/csi-snapshot-controller/webhook_clusterrole.yaml
  assets/components/csi-snapshot-controller/webhook_clusterrolebinding.yaml
  assets/components/csi-snapshot-controller/webhook_config.yaml
  assets/components/csi-snapshot-controller/webhook_deployment.yaml
  assets/components/csi-snapshot-controller/webhook_service.yaml
  assets/components/csi-snapshot-controller/webhook_serviceaccount.yaml
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  cmd/generate-config/config/config-openapi-spec.json
  docs/user/howto_config.md
  etcd/vendor/github.com/openshift/microshift/pkg/config/storage.go
  okd/src/README.md
  packaging/microshift/config.yaml
  pkg/components/csi-snapshot-controller.go
  pkg/config/config_test.go
  pkg/config/storage.go
  pkg/config/storage_test.go
  pkg/healthcheck/microshift_core_workloads.go
  pkg/healthcheck/workloads_test.go
  scripts/auto-rebase/assets.yaml
  scripts/auto-rebase/rebase.sh
  test/suites/greenboot/greenboot.robot
  test/suites/standard1/configuration.robot
Labels: lgtm, approved, jira/valid-reference

#4341 [release-4.18] OCPBUGS-47463: Raise the default greenboot timeout to 600s
  docs/contributor/greenboot.md
  packaging/greenboot/functions.sh
  test/image-blueprints-bootc/layer1-base/group2/rhel94-bootc-crel-optionals.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel94-bootc-crel.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel94-bootc-prel.containerfile
  test/image-blueprints-bootc/layer2-source/group1/cos9-bootc-source.containerfile
  test/image-blueprints-bootc/layer2-source/group1/rhel94-bootc-source-base.containerfile
  test/image-blueprints-bootc/layer2-source/group1/rhel94-bootc-source.containerfile
  test/image-blueprints-bootc/layer2-source/group2/rhel94-bootc-source-ostree-parent-previous-minor.containerfile
  test/image-blueprints-bootc/layer2-source/group2/rhel94-bootc-source-ostree-parent-yminus2.containerfile
  test/image-blueprints/layer1-base/group2/rhel94-microshift-yminus2.toml
  test/image-blueprints/layer1-base/group3/rhel94-microshift-previous-minor.toml
  test/image-blueprints/layer1-base/group4/rhel94-crel-with-optionals.toml
  test/image-blueprints/layer1-base/group4/rhel94-crel.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-base.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-fake-next-minor.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-tuned.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-with-optionals.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source.toml
  test/image-blueprints/layer3-periodic/group1/rhel94-source-isolated.toml
  test/kickstart-templates/includes/post-greenboot.cfg
  test/kickstart-templates/kickstart-centos.ks.template
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4340 OCPBUGS-47462: Raise the default greenboot timeout to 600s
  docs/contributor/greenboot.md
  packaging/greenboot/functions.sh
  test/image-blueprints-bootc/layer1-base/group2/rhel94-bootc-prel.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel94-bootc-yminus2.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel95-bootc-crel-optionals.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel95-bootc-crel.containerfile
  test/image-blueprints-bootc/layer2-source/group1/cos9-bootc-source.containerfile
  test/image-blueprints-bootc/layer2-source/group1/rhel95-bootc-source-base.containerfile
  test/image-blueprints-bootc/layer2-source/group1/rhel95-bootc-source.containerfile
  test/image-blueprints/layer1-base/group2/rhel94-microshift-yminus2.toml
  test/image-blueprints/layer1-base/group3/rhel94-microshift-previous-minor.toml
  test/image-blueprints/layer1-base/group4/rhel94-crel-with-optionals.toml
  test/image-blueprints/layer1-base/group4/rhel94-crel.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-base.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-fake-next-minor.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-tuned.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-with-optionals.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source.toml
  test/image-blueprints/layer3-periodic/group1/rhel94-source-isolated.toml
  test/kickstart-templates/includes/post-greenboot.cfg
  test/kickstart-templates/kickstart-centos.ks.template
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4348 USHIFT-5228: Use microshift healthcheck for verifying cncf multinode health
  packaging/greenboot/functions.sh
  scripts/multinode/configure-pri.sh
  scripts/multinode/configure-sec.sh
Labels: lgtm, approved, jira/valid-reference
