Repository openshift/microshift, pull requests merged in 2024-01, with the labels that each got.

#2823 [release-4.15] USHIFT-2127: Add tracing to dnf_retry.sh and fix rc logic
  scripts/dnf_retry.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2821 [release-4.15] OCPBUGS-25904: The microshift-cleanup-data script should delete pods from all namesp…
  scripts/microshift-cleanup-data.sh
  test/suites/osconfig/cleanup-data.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2831 [release-4.14] USHIFT-2140: Only install osbuild from COPR on RHEL 9.3
  scripts/image-builder/configure.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2836 USHIFT-2146: redirect kubectl output to a temp file
  test/resources/common.resource
  test/resources/kubeconfig.resource
Labels: lgtm, approved, jira/valid-reference

#2837 USHIFT-2145: look for dependency in rpm repo before trying to use it
  scripts/get-latest-rhocp-repo.sh
Labels: lgtm, approved, jira/valid-reference

#2832 USHIFT-2142: Split standard suite into 2 parts to parallelize its execution
  test/scenarios-periodics/el93-src@standard-suite1.sh
  test/scenarios-periodics/el93-src@standard-suite2.sh
  test/scenarios/el92-src@standard-suite1.sh
  test/scenarios/el92-src@standard-suite2.sh
  test/suites/standard1/configuration.robot
  test/suites/standard1/kustomize.robot
  test/suites/standard1/log-scan.robot
  test/suites/standard1/networking-smoke.robot
  test/suites/standard1/show-config.robot
  test/suites/standard1/validate-certificate-rotation.robot
  test/suites/standard1/validate-selinux-policy.robot
  test/suites/standard1/version.robot
  test/suites/standard2/etcd.robot
  test/suites/standard2/hostname.robot
Labels: lgtm, approved, jira/valid-reference

#2845 [release-4.15] USHIFT-2152: look for dependency in rpm repo before trying to use it
  scripts/devenv-builder/configure-vm.sh
  scripts/get-latest-rhocp-repo.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2851 USHIFT-2157: Upgrade osbuild copr package versions after copr cleanup
  scripts/image-builder/configure.sh
Labels: lgtm, approved, jira/valid-reference

#2853 [release-4.14] USHIFT-2159: Upgrade osbuild copr package versions after copr cleanup
  scripts/image-builder/configure.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2849 [release-4.15] USHIFT-2154: Split standard suite into 2 parts to parallelize its execution
  test/scenarios-periodics/el93-src@standard-suite1.sh
  test/scenarios-periodics/el93-src@standard-suite2.sh
  test/scenarios/el92-src@standard-suite1.sh
  test/scenarios/el92-src@standard-suite2.sh
  test/suites/standard1/configuration.robot
  test/suites/standard1/kustomize.robot
  test/suites/standard1/log-scan.robot
  test/suites/standard1/networking-smoke.robot
  test/suites/standard1/show-config.robot
  test/suites/standard1/validate-selinux-policy.robot
  test/suites/standard1/version.robot
  test/suites/standard2/etcd.robot
  test/suites/standard2/hostname.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2568 USHIFT-1822: scenario and suite for testing rpm-based installation and upgrades
  scripts/verify/verify-rf.sh
  test/README.md
  test/bin/scenario.sh
  test/bin/subscription_manager_register.sh
  test/resources/microshift-rpm.resource
  test/scenario_settings.sh.example
  test/scenarios/el92-prel@upgrade-rpm-ok.sh
  test/scenarios/el92-src@rpm-install.sh
  test/suites/rpm/install-and-upgrade-successful.robot
  test/suites/upgrade/upgrade-rpm-successful.robot
Labels: lgtm, approved, jira/valid-reference

#2857 USHIFT-2160: Retry logic for registry image pull
  test/bin/mirror_registry.sh
Labels: lgtm, approved, jira/valid-reference

#2858 OCPBUGS-21901: increase core dns pod buffersize
  assets/components/openshift-dns/dns/configmap.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#2860 USHIFT-2139: bump sonobuoy version to 0.57.1
  test/scenarios-periodics/el92-src@cncf-conformance.sh
Labels: lgtm, approved, jira/valid-reference

#2866 USHIFT-2169: -f option to build_images.sh does not require a parameter
  test/bin/build_images.sh
Labels: lgtm, approved, jira/valid-reference

#2878 USHIFT-2105: Temporarily disable flaky tests
  test/suites/standard1/log-scan.robot
  test/suites/standard1/networking-smoke.robot
Labels: lgtm, approved, jira/valid-reference

#2880 USHIFT-2167: Ignore origin/ dir for security scans
  .snyk
Labels: lgtm, approved, jira/valid-reference

#2859 USHIFT-2131: Add registry mirror configuration to kickstart-liveimg
  test/bin/build_images.sh
  test/bin/common.sh
  test/bin/mirror_registry.sh
  test/kickstart-templates/kickstart-liveimg.ks.template
Labels: lgtm, approved, jira/valid-reference

#2879 USHIFT-2184: Retry compose start
  test/bin/build_images.sh
Labels: lgtm, approved, jira/valid-reference

#2887 USHIFT-2191: force versions in rpm install test
  test/resources/microshift-rpm.resource
  test/suites/rpm/install-and-upgrade-successful.robot
Labels: lgtm, approved, jira/valid-reference

#2891 USHIFT-2105: cert rotation test wait for greenboot
  test/suites/standard1/validate-certificate-rotation.robot
Labels: lgtm, approved, jira/valid-reference

#2885 OCPBUGS-23336: Check AdvertiseAddress configured in NICs
  pkg/config/config.go
  pkg/config/config_test.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#2897 USHIFT-2131: Fix dnf download for rhocp repos
  test/bin/build_images.sh
Labels: lgtm, approved, jira/valid-reference

#2873 USHIFT-2183: Make sos report collection more robust in scenario.sh
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#2905 USHIFT-2157: Update osbuild packages from copr after previous version cleanup
  scripts/image-builder/configure.sh
Labels: lgtm, approved, jira/valid-reference

#2895 [release-4.15] USHIFT-2187: Fix image mirroring for previous version
  test/bin/build_images.sh
  test/bin/common.sh
  test/bin/mirror_registry.sh
  test/kickstart-templates/kickstart-liveimg.ks.template
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2907 USHIFT-2204: add script to tag stable releases
  scripts/release-notes/tag_stable_releases.py
Labels: lgtm, approved, jira/valid-reference

#2904 USHIFT-2201: Update golang to 1.21.3
  Makefile
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#2865 [release-4.14] USHIFT-2164: scenario and suite for testing rpm-based installation and upgrades
  scripts/verify/verify-rf.sh
  test/README.md
  test/bin/scenario.sh
  test/bin/subscription_manager_register.sh
  test/resources/microshift-host.resource
  test/resources/microshift-rpm.resource
  test/scenario_settings.sh.example
  test/scenarios/el92-prel@upgrade-rpm-ok.sh
  test/scenarios/el92-src@rpm-install.sh
  test/suites/rpm/install-and-upgrade-successful.robot
  test/suites/upgrade/upgrade-rpm-successful.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2850 USHIFT-1848: add periodic test scenario for the standard tests on rpm-based system
  test/resources/selinux.py
  test/resources/selinux.resource
  test/scenarios-periodics/el92-src@rpm-standard1.sh
  test/scenarios-periodics/el92-src@rpm-standard2.sh
Labels: lgtm, approved, jira/valid-reference

#2915 USHIFT-2211 Bump golangci-lint version
  scripts/fetch_tools.sh
Labels: lgtm, approved

#2789 OCPBUGS-22216: Make lvmo version visible to users via configmap
  assets/components/lvms/topolvm-configmap_lvms-version.yaml
  docs/contributor/storage/default_csi_plugin.md
  docs/user/debugging_tips.md
  pkg/components/storage.go
  scripts/auto-rebase/lvms_assets.yaml
  scripts/auto-rebase/rebase-lvms.sh
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2902 USHIFT-2200: Fix configure-vm.sh to work in standalone mode and on CentOS
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#2910 USHIFT-2209: Add kickstart include functionality to the test framework
  test/bin/scenario.sh
  test/kickstart-templates/includes/main-liveimg.cfg
  test/kickstart-templates/includes/main-network.cfg
  test/kickstart-templates/includes/main-ostree.cfg
  test/kickstart-templates/includes/main-prologue.cfg
  test/kickstart-templates/includes/post-containers.cfg
  test/kickstart-templates/includes/post-microshift.cfg
  test/kickstart-templates/includes/post-network.cfg
  test/kickstart-templates/includes/post-system.cfg
  test/kickstart-templates/kickstart-liveimg.ks.template
  test/kickstart-templates/kickstart-offline.ks.template
  test/kickstart-templates/kickstart.ks.template
Labels: lgtm, approved, jira/valid-reference

#2919 USHIFT-2213: wrong namespace in docs
  docs/user/debugging_tips.md
Labels: lgtm, approved, jira/valid-reference

#2924 USHIFT-2214: Add missing dependency of microshift-olm on microshift package
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#2927 USHIFT-2157: Stop using copr repos as a source of osbuild RPM packages
  scripts/image-builder/configure.sh
Labels: lgtm, approved, jira/valid-reference

#2933 [release-4.14] USHIFT-2159: Stop using copr repos as a source of osbuild RPM packages
  scripts/image-builder/configure.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2934 USHIFT-2230: OLM release info files are no longer included in the base release-info RPM package
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#2939 USHIFT-2233: Use openshift-marketplace ns for OLM Catalogs
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-namespace.yaml
  scripts/auto-rebase/rebase.sh
  test/assets/olm/catalog-source.yaml
  test/assets/olm/subscription-cert-manager.yaml
  test/suites/optional/olm.robot
Labels: lgtm, approved, jira/valid-reference

#2951 USHIFT-2242: add option to build_images.sh to skip log collection step
  test/bin/build_images.sh
Labels: lgtm, approved, jira/valid-reference
