Repository openshift/microshift, pull requests merged in 2024-07, with the labels that each got.

#3463 NO-ISSUE: microshift-test-agent improvements
  test/agent/microshift-test-agent.service
  test/agent/microshift-test-agent.sh
Labels: lgtm, approved, jira/valid-reference

#3513 [release-4.16] OCPBUGS-35814: Fix CRI-O version to match Kubernetes version
  packaging/rpm/microshift.spec
  scripts/devenv-builder/configure-vm.sh
  scripts/get-latest-rhocp-repo.sh
  scripts/image-builder/build.sh
  scripts/image-builder/config/rhocp.toml.template
  test/bin/build_images.sh
  test/bin/get_rel_version_repo.sh
  test/bin/pyutils/build_bootc_images.py
  test/bin/scenario.sh
  test/bootc-sources/microshift_repo_config.sh.template
  test/kickstart-templates/includes/post-cos9rpm.cfg
  test/package-sources/microshift-crel.toml
  test/package-sources/microshift-prel.toml
  test/package-sources/rhocp-y.toml
  test/package-sources/rhocp-y1.toml
  test/scenarios/el94-src@rpm-install.sh
  test/suites/rpm/install-and-upgrade-successful.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3562 USHIFT-3511: enable FIPs tests for 4.17
  test/scenarios-periodics/el94-src@fips-rpm.sh
  test/scenarios-periodics/el94-src@fips.sh
Labels: lgtm, approved, jira/valid-reference

#3568 [release-4.16] NO-ISSUE: Set static CRI-O ver for 4.15 and 4.14 images; don't use cache
  test/bin/ci_phase_iso_build.sh
  test/image-blueprints/layer1-base/group2/rhel92-microshift-previous-minor.toml
  test/image-blueprints/layer1-base/group2/rhel92-microshift-yminus2.toml
  test/image-blueprints/layer1-base/group2/rhel93-microshift-previous-minor.toml
  test/image-blueprints/layer1-base/group2/rhel93-microshift-yminus2.toml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3570 [release-4.15] OCPBUGS-36423: Fix crio version to match Kubernetes' version
  packaging/rpm/microshift.spec
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3569 USHIFT-3725: Fix repository package check in bootc image build
  test/bin/pyutils/build_bootc_images.py
Labels: lgtm, approved, jira/valid-reference

#3579 USHIFT-3000: Configure router to support ipv6 single/dual stack
  assets/components/openshift-router/deployment.yaml
  pkg/components/controllers.go
  pkg/config/config.go
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#3595 USHIFT-3734: Avoid using build image dnf wrapper script
  Makefile
  packaging/images/Containerfile.rpm-builder
Labels: lgtm, approved, jira/valid-reference

#3585 USHIFT-3730: Introduce common versions file for image builds
  scripts/image-builder/cleanup.sh
  test/bin/build_bootc_images.sh
  test/bin/build_images.sh
  test/bin/cleanup_hypervisor.sh
  test/bin/common.sh
  test/bin/common_versions.sh
  test/bin/get_latest_rpm_version.sh
  test/bin/get_rel_version_repo.sh
  test/bin/pyutils/build_bootc_images.py
  test/bin/pyutils/common.py
  test/bin/scenario.sh
  test/package-sources/microshift-crel.toml
  test/package-sources/microshift-prel.toml
  test/scenarios-upgrades/el92-prel@el94-crel@upgrade-ok.sh
  test/scenarios-upgrades/el92-prel@el94-src@upgrade-fails-and-rolls-back.sh
  test/scenarios-upgrades/el92-prel@el94-src@upgrade-ok.sh
  test/scenarios-upgrades/el92-yminus2@el94-crel@upgrade-ok.sh
  test/scenarios-upgrades/el93-prel@el94-crel@upgrade-ok.sh
  test/scenarios-upgrades/el93-prel@el94-src@upgrade-ok.sh
  test/scenarios-upgrades/el93-yminus2@el94-crel@upgrade-ok.sh
  test/scenarios-upgrades/el93-yminus2@el94-src@upgrade-ok.sh
  test/scenarios/el92-prel@el94-src@upgrade-ok.sh
  test/scenarios/el92-yminus2@el94-src@upgrade-ok.sh
  test/scenarios/el93-prel@el94-src@upgrade-ok.sh
  test/scenarios/el94-src@rpm-install.sh
  test/suites/rpm/install-and-upgrade-successful.robot
Labels: lgtm, approved, jira/valid-reference

#3594 [release-4.16] USHIFT-3730: Introduce common versions file for image builds
  scripts/image-builder/cleanup.sh
  test/bin/build_bootc_images.sh
  test/bin/build_images.sh
  test/bin/cleanup_hypervisor.sh
  test/bin/common.sh
  test/bin/common_versions.sh
  test/bin/get_latest_rpm_version.sh
  test/bin/pyutils/build_bootc_images.py
  test/bin/pyutils/common.py
  test/bin/scenario.sh
  test/package-sources/microshift-crel.toml
  test/package-sources/microshift-prel.toml
  test/scenarios-upgrades/el92-prel@el94-crel@upgrade-ok.sh
  test/scenarios-upgrades/el92-prel@el94-src@upgrade-fails-and-rolls-back.sh
  test/scenarios-upgrades/el92-prel@el94-src@upgrade-ok.sh
  test/scenarios-upgrades/el92-yminus2@el94-crel@upgrade-ok.sh
  test/scenarios-upgrades/el93-prel@el94-crel@upgrade-ok.sh
  test/scenarios-upgrades/el93-prel@el94-src@upgrade-ok.sh
  test/scenarios-upgrades/el93-yminus2@el94-crel@upgrade-ok.sh
  test/scenarios-upgrades/el93-yminus2@el94-src@upgrade-ok.sh
  test/scenarios/el92-prel@el94-src@upgrade-ok.sh
  test/scenarios/el92-yminus2@el94-src@upgrade-ok.sh
  test/scenarios/el93-prel@el94-src@upgrade-ok.sh
  test/scenarios/el94-src@rpm-install.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3591 USHIFT-3733: add management annotation to topolvm pods
  assets/components/lvms/topolvm-controller_deployment.yaml
  assets/components/lvms/topolvm-node_daemonset.yaml
Labels: lgtm, approved, jira/valid-reference

#3592 USHIFT-3732: Remove invalid images & scenarios such as rhel{92,93} x 4.{16,17}
  test/image-blueprints/layer1-base/group2/rhel92-microshift-previous-minor.image-installer
  test/image-blueprints/layer1-base/group2/rhel92-microshift-previous-minor.toml
  test/image-blueprints/layer1-base/group2/rhel93-microshift-previous-minor.image-installer
  test/image-blueprints/layer1-base/group2/rhel94-microshift-previous-minor.image-installer
  test/image-blueprints/layer1-base/group2/rhel94-microshift-previous-minor.toml
  test/image-blueprints/layer2-presubmit/group1/rhel-9.2-microshift-source-aux.alias
  test/image-blueprints/layer2-presubmit/group1/rhel92-crel.toml
  test/image-blueprints/layer2-presubmit/group1/rhel92-source-base.toml
  test/image-blueprints/layer2-presubmit/group1/rhel92-source-fake-next-minor.toml
  test/image-blueprints/layer2-presubmit/group1/rhel92-source.toml
  test/image-blueprints/layer3-periodic/group1/rhel92-crel-with-optionals.toml
  test/image-blueprints/layer3-periodic/group1/rhel92-source-with-optionals.toml
  test/image-blueprints/layer3-periodic/group1/rhel93-crel.toml
  test/image-blueprints/layer3-periodic/group1/rhel93-source.toml
  test/image-blueprints/layer4-ext/group1/rhel92_microshift-ext.image-installer
  test/image-blueprints/layer4-ext/group1/rhel93_microshift-ext.image-installer
  test/image-blueprints/layer4-ext/group1/rhel93_microshift-ext.toml
  test/image-blueprints/layer4-ext/group1/rhel94_microshift-ext.image-installer
  test/image-blueprints/layer4-ext/group1/rhel94_microshift-ext.toml
  test/scenarios-upgrades/el92-crel@el94-src@optional-upgrade.sh
  test/scenarios-upgrades/el93-prel@el94-crel@upgrade-ok.sh
  test/scenarios-upgrades/el93-prel@el94-src@upgrade-ok.sh
  test/scenarios-upgrades/el94-prel@el94-crel@upgrade-ok.sh
  test/scenarios-upgrades/el94-prel@el94-src@upgrade-fails-and-rolls-back.sh
  test/scenarios-upgrades/el94-prel@el94-src@upgrade-ok.sh
  test/scenarios/el93-prel@el94-src@upgrade-ok.sh
  test/scenarios/el94-crel@el94-src@upgrade-ok.sh
  test/scenarios/el94-prel@el94-src@upgrade-ok.sh
Labels: lgtm, approved, jira/valid-reference

#3602 USHIFT-3736: Force NM configuration to allow ipv6
  packaging/NetworkManager.conf.d/10-microshift-ignore-devices.conf
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#3601 [release-4.16] Remove invalid images & scenarios such as rhel{92,93} x 4.16
  test/image-blueprints/layer2-presubmit/group1/rhel-9.2-microshift-source-aux.alias
  test/image-blueprints/layer2-presubmit/group1/rhel92-crel.toml
  test/image-blueprints/layer2-presubmit/group1/rhel92-source-base.toml
  test/image-blueprints/layer2-presubmit/group1/rhel92-source-fake-next-minor.toml
  test/image-blueprints/layer2-presubmit/group1/rhel92-source.toml
  test/image-blueprints/layer3-periodic/group1/rhel92-crel-with-optionals.toml
  test/image-blueprints/layer3-periodic/group1/rhel92-source-with-optionals.toml
  test/image-blueprints/layer3-periodic/group1/rhel93-crel.toml
  test/image-blueprints/layer3-periodic/group1/rhel93-source.toml
  test/image-blueprints/layer4-ext/group1/rhel92_microshift-ext.image-installer
  test/image-blueprints/layer4-ext/group1/rhel93_microshift-ext.image-installer
  test/image-blueprints/layer4-ext/group1/rhel93_microshift-ext.toml
  test/image-blueprints/layer4-ext/group1/rhel94_microshift-ext.image-installer
  test/image-blueprints/layer4-ext/group1/rhel94_microshift-ext.toml
  test/scenarios-upgrades/el92-crel@el94-src@optional-upgrade.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#3521 USHIFT-3473: Add validations for network ipv4/ipv6 stacks
  etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/network.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/network.go
Labels: lgtm, approved, jira/valid-reference

#3596 USHIFT-2925: Start using hypervisor container registry for ostreecontainer in kickstart
  scripts/image-builder/mirror-images.sh
  test/bin/mirror_registry.sh
  test/bin/pyutils/build_bootc_images.py
  test/bin/scenario.sh
  test/kickstart-templates/includes/main-ostreecontainer.cfg
Labels: lgtm, approved, jira/valid-reference

#3593 OCPBUGS-36587: Filter ip family in router service controller
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/loadbalancerservice/controller.go
  pkg/loadbalancerservice/router.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#3610 [release-4.16] USHIFT-3745: Remove bootc-related functionality from 4.16 test harness
  test/bin/build_bootc_images.sh
  test/bin/ci_phase_iso_build.sh
  test/bin/common.sh
  test/bin/pyutils/build_bootc_images.py
  test/bin/pyutils/common.py
  test/bin/scenario.sh
  test/bootc-sources/microshift_repo_config.sh.template
  test/image-blueprints/layer5-bootc/group0/rhel94-bootc-base.containerfile
  test/image-blueprints/layer5-bootc/group1/centos9-bootc.image-bootc
  test/image-blueprints/layer5-bootc/group1/cos9-bootc-source.containerfile
  test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source.containerfile
  test/image-blueprints/layer5-bootc/group1/rhel94-bootc.image-bootc
  test/image-blueprints/layer5-bootc/group2/cos9-bootc-source-optionals.containerfile
  test/image-blueprints/layer5-bootc/group2/rhel94-bootc-source-optionals.containerfile
  test/kickstart-templates/includes/main-ostreecontainer.cfg
  test/kickstart-templates/includes/main-prologue.cfg
  test/kickstart-templates/includes/post-bootc-wa.cfg
  test/kickstart-templates/kickstart-bootc.ks.template
  test/scenarios-bootc/cos9-src@backup-and-restore-on-reboot.sh
  test/scenarios-bootc/cos9-src@backups.sh
  test/scenarios-bootc/cos9-src@greenboot.sh
  test/scenarios-bootc/cos9-src@log-scan.sh
  test/scenarios-bootc/cos9-src@multi-nic.sh
  test/scenarios-bootc/cos9-src@optional.sh
  test/scenarios-bootc/cos9-src@osconfig-cleanup-data.sh
  test/scenarios-bootc/cos9-src@osconfig-lifecycle.sh
  test/scenarios-bootc/cos9-src@osconfig-misc.sh
  test/scenarios-bootc/cos9-src@standard-suite2.sh
  test/scenarios-bootc/cos9-src@storage.sh
  test/scenarios-bootc/el94-src@backup-and-restore-on-reboot.sh
  test/scenarios-bootc/el94-src@backups.sh
  test/scenarios-bootc/el94-src@greenboot.sh
  test/scenarios-bootc/el94-src@log-scan.sh
  test/scenarios-bootc/el94-src@multi-nic.sh
  test/scenarios-bootc/el94-src@optional.sh
  test/scenarios-bootc/el94-src@osconfig-cleanup-data.sh
  test/scenarios-bootc/el94-src@osconfig-lifecycle.sh
  test/scenarios-bootc/el94-src@osconfig-misc.sh
  test/scenarios-bootc/el94-src@standard-suite2.sh
  test/scenarios-bootc/el94-src@storage.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3615 USHIFT-3503: Properly apply greenboot timeout increase in blueprints and container files
  test/image-blueprints/layer1-base/group2/rhel92-microshift-yminus2.toml
  test/image-blueprints/layer1-base/group2/rhel93-microshift-yminus2.toml
  test/image-blueprints/layer1-base/group2/rhel94-microshift-previous-minor.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-crel.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-base.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-fake-next-minor.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-with-optionals.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source.toml
  test/image-blueprints/layer3-periodic/group1/rhel94-crel-with-optionals.toml
  test/image-blueprints/layer3-periodic/group1/rhel94-source-isolated.toml
  test/image-blueprints/layer3-periodic/group1/rhel94-source-with-optionals.toml
  test/image-blueprints/layer5-bootc/group1/cos9-bootc-source.containerfile
  test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source.containerfile
  test/kickstart-templates/includes/post-greenboot.cfg
  test/kickstart-templates/includes/post-system.cfg
  test/kickstart-templates/kickstart-centos.ks.template
  test/resources/libostree.py
Labels: lgtm, approved, jira/valid-reference

#3608 USHIFT-3742: test if all the running pods are annotated for workload partitioning
  test/resources/oc.resource
  test/suites/standard2/workload-partitioning.robot
Labels: lgtm, approved, jira/valid-reference

#3607 USHIFT-3740: ovnk configuration changes for ipv6
  assets/components/ovn/common/configmap.yaml
  assets/components/ovn/single-node/master/daemonset.yaml
Labels: lgtm, approved, jira/valid-reference

#3625 USHIFT-3749: Prerequisites for ostree-to-bootc upgrade tests
  test/agent/microshift-test-agent.sh
  test/image-blueprints/layer1-base/group2/rhel94-microshift-previous-minor.toml
  test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source.containerfile
  test/resources/ostree-data.resource
  test/suites/upgrade/upgrade-successful.robot
Labels: lgtm, approved, jira/valid-reference

#3522 USHIFT-3459: Passthrough kubelet config from microshift config
  assets/core/kubelet.yaml
  cmd/generate-config/config/config-openapi-spec.json
  docs/user/howto_config.md
  packaging/microshift/config.yaml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/node/kubelet.go
  pkg/node/kubelet_test.go
Labels: lgtm, approved, jira/valid-reference

#3626 USHIFT-3752: Skip node reboot test in conformance
  origin/skip.txt
Labels: lgtm, approved, jira/valid-reference

#3616 NO-ISSUE: Move upgrade tests back to periodics
  test/scenarios-periodics/el92-yminus2@el94-crel@upgrade-ok.sh
  test/scenarios-periodics/el93-yminus2@el94-crel@upgrade-ok.sh
  test/scenarios-periodics/el93-yminus2@el94-src@upgrade-ok.sh
  test/scenarios-periodics/el94-crel@el94-src@optional-upgrade.sh
  test/scenarios-periodics/el94-crel@el94-src@upgrade-fails.sh
  test/scenarios-periodics/el94-crel@el94-src@upgrade-ok.sh
  test/scenarios-periodics/el94-prel@el94-crel@upgrade-ok.sh
  test/scenarios-periodics/el94-prel@el94-src@upgrade-fails-and-rolls-back.sh
  test/scenarios-periodics/el94-prel@el94-src@upgrade-ok.sh
  test/scenarios-periodics/el94-src@upgrade-fails-cannot-backup.sh
Labels: lgtm, approved, jira/valid-reference

#3632 NO-ISSUE: rebase-main-4.17.0-0.nightly-2024-07-14-213604_amd64-2024-07-14_arm64-2024-07-14
  Makefile.kube_git.var
  Makefile.version.aarch64.var
  Makefile.version.x86_64.var
  assets/optional/multus/release-multus-aarch64.json
  assets/optional/multus/release-multus-x86_64.json
  assets/optional/operator-lifecycle-manager/release-olm-aarch64.json
  assets/optional/operator-lifecycle-manager/release-olm-x86_64.json
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  etcd/go.mod
  etcd/go.sum
  etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
  etcd/vendor/modules.txt
  go.mod
  go.sum
  packaging/crio.conf.d/10-microshift_amd64.conf
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/commits.txt
  scripts/auto-rebase/last_rebase.sh
  scripts/auto-rebase/rebase.sh
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#3636 USHIFT-3761: Default to ipv6 config values when node ip is ipv6
  pkg/config/config.go
Labels: lgtm, approved, jira/valid-reference

#3633 USHIFT-3749: Add subscription-manager to the base ostree image to enable DNF install in containers
  test/image-blueprints/layer1-base/group2/rhel94-microshift-previous-minor.toml
Labels: lgtm, approved, jira/valid-reference

#3647 USHIFT-3761: Set default networks separately
  etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
  pkg/config/config.go
Labels: lgtm, approved, jira/valid-reference

#3635 USHIFT-3476: Test harness ipv6 adaptations
  scripts/devenv-builder/manage-vm.sh
  test/assets/ipv6-network.xml
  test/bin/common.sh
  test/bin/manage_hypervisor_config.sh
  test/bin/scenario.sh
  test/bin/start_webserver.sh
  test/kickstart-templates/includes/post-network.cfg
  test/suites/greenboot/greenboot.robot
Labels: lgtm, approved, jira/valid-reference

#3652 USHIFT-3483: Add ipv6 helpers to test framework
  test/resources/libipv6.py
  test/resources/microshift-network.resource
Labels: lgtm, approved, jira/valid-reference

#3609 USHIFT-3478: Configuration adaptations for dual stack
  etcd/vendor/github.com/openshift/microshift/pkg/config/apiserver.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
  pkg/components/render.go
  pkg/config/apiserver.go
  pkg/config/config.go
  pkg/controllers/kube-apiserver.go
  pkg/controllers/kube-controller-manager.go
  pkg/controllers/kube-controller-manager_test.go
  pkg/node/netconfig.go
Labels: lgtm, approved, jira/valid-reference

#3667 USHIFT-3773: Skip 2 node sig-architecture conformance test
  origin/skip.txt
Labels: lgtm, approved, jira/valid-reference

#3654 NO-ISSUE: Missing persistent journal on 1st boot when installing using rhel94 iso
  test/bin/scenario.sh
  test/kickstart-templates/includes/post-system.cfg
  test/scenarios/el92-yminus2@el94-src@upgrade-ok.sh
Labels: lgtm, approved, jira/valid-reference

#3627 NO-ISSUE: Fix common versions script not to produce errors for non-existent repos
  test/bin/common_versions.sh
Labels: lgtm, approved, jira/valid-reference

#3657 USHIFT-3770: Add service to cleanup stale kubelet files on boot
  packaging/rpm/microshift.spec
  packaging/tuned/microshift-cleanup-kubelet.service
  scripts/microshift-cleanup-data.sh
Labels: lgtm, approved, jira/valid-reference

#3658 USHIFT-3001: Add initial RF ipv6 tests
  test/assets/ipv6-network.xml
  test/bin/scenario.sh
  test/kickstart-templates/includes/post-containers.cfg
  test/resources/kubeconfig.resource
  test/resources/microshift-network.resource
  test/scenarios/el94-src@ipv6.sh
  test/suites/ipv6/singlestack.robot
Labels: lgtm, approved, jira/valid-reference

#3677 NO-ISSUE: Skip topolvm deletion check for crel upgrades
  test/suites/upgrade/upgrade-successful.robot
Labels: lgtm, approved, jira/valid-reference

#3675 USHIFT-2193: docs: corrects and adjusts rebase docs for LVMS
  docs/contributor/rebase.md
Labels: lgtm, approved, jira/valid-reference

#3571 USHIFT-3462: `microshift-baseline` TuneD profile
  packaging/rpm/make-rpm.sh
  packaging/rpm/microshift.spec
  packaging/systemd/microshift.service
  packaging/tuned/profile/script.sh
  packaging/tuned/profile/tuned.conf
  packaging/tuned/profile/variables.conf
  scripts/image-builder/cleanup.sh
  scripts/image-builder/configure.sh
  test/assets/tuned/pod.yaml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-tuned.toml
  test/kickstart-templates/includes/post-microshift.cfg
  test/scenarios/el94-src@low-latency.sh
  test/suites/tuned/profile.robot
Labels: lgtm, approved, jira/valid-reference

#3655 USHIFT-3465: Add high-performance CRI-O runtime and RuntimeClass
  packaging/crio.conf.d/05-high-performance-runtime.conf
  packaging/rpm/microshift.spec
  packaging/tuned/runtime-class/kustomization.yaml
  packaging/tuned/runtime-class/runtime-class.yaml
  test/assets/tuned/pod.yaml
  test/suites/tuned/profile.robot
Labels: lgtm, approved, jira/valid-reference

#3653 USHIFT-3748: Check for oc utility on hypervisor host, install with fetch_tools.sh
  scripts/fetch_tools.sh
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#3641 [release-4.16] USHIFT-3503: Properly apply greenboot timeout increase in blueprints and container files
  test/bin/common_versions.sh
  test/bin/scenario.sh
  test/image-blueprints/layer1-base/group2/rhel92-microshift-previous-minor.toml
  test/image-blueprints/layer1-base/group2/rhel92-microshift-yminus2.toml
  test/image-blueprints/layer1-base/group2/rhel93-microshift-previous-minor.toml
  test/image-blueprints/layer1-base/group2/rhel93-microshift-yminus2.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-crel.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-base.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-fake-next-minor.toml
  test/image-blueprints/layer2-presubmit/group1/rhel94-source.toml
  test/image-blueprints/layer3-periodic/group1/rhel94-crel-with-optionals.toml
  test/image-blueprints/layer3-periodic/group1/rhel94-source-isolated.toml
  test/image-blueprints/layer3-periodic/group1/rhel94-source-with-optionals.toml
  test/kickstart-templates/includes/post-greenboot.cfg
  test/kickstart-templates/includes/post-system.cfg
  test/kickstart-templates/kickstart-centos.ks.template
  test/resources/libostree.py
  test/scenarios-periodics/el92-prel@el94-crel@upgrade-ok.sh
  test/scenarios-periodics/el92-prel@el94-src@upgrade-fails-and-rolls-back.sh
  test/scenarios-periodics/el92-prel@el94-src@upgrade-ok.sh
  test/scenarios-periodics/el92-yminus2@el94-crel@upgrade-ok.sh
  test/scenarios-periodics/el93-prel@el94-crel@upgrade-ok.sh
  test/scenarios-periodics/el93-prel@el94-src@upgrade-ok.sh
  test/scenarios-periodics/el93-yminus2@el94-crel@upgrade-ok.sh
  test/scenarios-periodics/el93-yminus2@el94-src@upgrade-ok.sh
  test/scenarios-periodics/el94-crel@el94-src@optional-upgrade.sh
  test/scenarios-periodics/el94-crel@el94-src@upgrade-fails.sh
  test/scenarios-periodics/el94-crel@el94-src@upgrade-ok.sh
  test/scenarios-periodics/el94-src@upgrade-fails-cannot-backup.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3676 USHIFT-3479: ipFamilyPolicy adjustments and ovnk restart on dual stack migration
  assets/components/openshift-router/service-cloud.yaml
  assets/components/openshift-router/service-internal.yaml
  assets/components/ovn/single-node/master/daemonset.yaml
  pkg/components/render.go
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#3684 USHIFT-3503: Attempt to gracefully destroy a VM before forceful shutdown
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#3672 USHIFT-1545: Full VM name validation
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#3688 USHIFT-2928: Remove /var/run symlink creation workaround from bootc container files
  test/image-blueprints/layer5-bootc/group1/cos9-bootc-source.containerfile
  test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source.containerfile
Labels: lgtm, approved, jira/valid-reference

#3689 USHIFT-3126: Use RHEL 9 version of bootc-image-builder
  test/bin/pyutils/build_bootc_images.py
Labels: lgtm, approved, jira/valid-reference

#3634 USHIFT-3749: Implement ostree-to-bootc image basic upgrade tests
  test/bin/pyutils/build_bootc_images.py
  test/image-blueprints/layer5-bootc/group0/rhel94-ostree-microshift-previous-minor.container-encapsulate
  test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source-ostree-parent.containerfile
  test/resources/libostree.py
  test/resources/microshift-host.resource
  test/resources/ostree.resource
  test/scenarios-bootc/el94-prel@el94-src@upgrade-ostree2bootc-ok.sh
  test/scenarios-periodics/el94-crel@el94-src@upgrade-ok.sh
  test/suites/upgrade/upgrade-successful-bootc.robot
Labels: lgtm, approved, jira/valid-reference

#3656 USHIFT-3463: Add microshift-tuned daemon for unattended TuneD profile activation
  packaging/rpm/microshift.spec
  packaging/tuned/microshift-tuned.py
  packaging/tuned/microshift-tuned.service
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-tuned.toml
  test/resources/microshift-host.resource
  test/resources/microshift-process.resource
  test/resources/systemd.resource
  test/scenarios/el94-src@low-latency.sh
  test/suites/tuned/microshift-tuned.robot
  test/suites/tuned/profile.robot
Labels: lgtm, approved, jira/valid-reference
