Repository openshift/microshift, pull requests merged in 2024-09, with the labels that each got.

#3837 USHIFT-4121 USHIFT-4123: Skip sig-ci tests, revert ovnk image
  assets/release/release-x86_64.json
  origin/skip.txt
Labels: lgtm, approved, jira/valid-reference

#3792 USHIFT-3778: Drop-in configuration directory
  docs/user/howto_config.md
  packaging/rpm/microshift.spec
  pkg/config/config_test.go
  pkg/config/files.go
  test/resources/microshift-config.resource
  test/suites/greenboot/greenboot.robot
  test/suites/ipv6/dualstack.robot
  test/suites/network/multi-nic.robot
  test/suites/network/offline.robot
  test/suites/standard1/configuration.robot
  test/suites/standard1/kustomize.robot
  test/suites/standard1/router.robot
  test/suites/standard1/show-config.robot
  test/suites/standard2/etcd.robot
  test/suites/standard2/validate-custom-certificates.robot
  test/suites/tuned/workload-partitioning.robot
Labels: lgtm, approved, jira/valid-reference

#3844 USHIFT-4073: Add multi-arch image build section to the docs
  docs/contributor/image_mode.md
Labels: lgtm, approved, jira/valid-reference

#3749 USHIFT-4025: Implement MicroShift image mode container build procedure
  packaging/imagemode/Containerfile.repobase
  packaging/imagemode/Containerfile.repourl
  packaging/imagemode/Containerfile.rhocp
  packaging/imagemode/Makefile
  packaging/imagemode/README.md
  packaging/imagemode/systemd/microshift-make-rshared.service
Labels: lgtm, approved, jira/valid-reference

#3867 USHIFT-4059: Add crio metrics config to ansible scripts
  ansible/roles/install-microshift/defaults/main.yml
  ansible/roles/install-microshift/files/01-crio-metrics.conf
  ansible/roles/install-microshift/tasks/main.yml
Labels: lgtm, approved, jira/valid-reference

#3874 USHIFT-4279: Remove the unnecessary openssl image dependency
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
Labels: lgtm, approved, jira/valid-reference

#3887 NO-ISSUE: Make Containerfile.repobase self contained to be used in build pipelines
  packaging/imagemode/Containerfile.repobase
Labels: lgtm, approved, jira/valid-reference

#3873 NO-ISSUE: Fix manage_hypervisor_config.sh script to finish cleanup procedure
  test/bin/manage_hypervisor_config.sh
Labels: lgtm, approved, jira/valid-reference

#3894 [release-4.17] USHIFT-4326: Remove the unnecessary openssl image dependency
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3838 USHIFT-4119: Add bootc FIPS tests to MicroShift periodics CI on CentOS 9 Stream
  test/image-blueprints/layer5-bootc/group1/cos9-bootc-source.containerfile
  test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source.containerfile
  test/image-blueprints/layer5-bootc/group2/cos9-bootc-source-fips.containerfile
  test/image-blueprints/layer5-bootc/group2/rhel94-bootc-source-fips.containerfile
  test/kickstart-templates/includes/post-fips.cfg
  test/scenarios-bootc/periodics/cos9-src@fips.sh
  test/scenarios-bootc/periodics/cos9-src@greenboot.sh
  test/scenarios-bootc/periodics/el94-src@fips.sh.disabled
  test/scenarios-bootc/periodics/el94-src@greenboot.sh
  test/suites/fips/validate-fips.robot
Labels: lgtm, approved, jira/valid-reference

#3901 USHIFT-4052: Upgrade CRI-O version dependency to 1.31.0
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#3794 USHIFT-3323: Merge boot and run phases in CI - PHASE 1
  test/bin/ci_phase_boot_and_test.sh
  test/bin/ci_phase_iso_boot.sh
  test/bin/ci_phase_test.sh
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#3886 OCPBUGS-41510: Avoid link local ipv6 addresses in mdns
  pkg/mdns/controller.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#3913 USHIFT-4333: Declare openvswitch3.3 package as obsolete to allow seemless upgrade to openvswitch3.4
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#3920 [release-4.17] USHIFT-4338: Declare openvswitch3.3 package as obsolete to allow seemless upgrade to openvswitch3.4
  packaging/rpm/microshift.spec
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3883 USHIFT-4128: Add ipv6 dual stack scenario to bootc iso tests
  test/scenarios-bootc/presubmits/el94-src@dual-stack.sh
Labels: lgtm, approved, jira/valid-reference

#3938 USHIFT-4358: Fix greenboot's healthcheck handling when config is missing
  packaging/greenboot/functions.sh
Labels: lgtm, approved, jira/valid-reference

#3861 USHIFT-4134: test agent: make sure cleanup activities run to completion
  test/agent/microshift-test-agent.service
  test/agent/microshift-test-agent.sh
Labels: lgtm, approved, jira/valid-reference

#3830 USHIFT-4335 USHIFT-4354 USHIFT-4356: build runnable microshift-okd bootc container
  .dockerignore
  okd/src/README.md
  okd/src/configure.sh
  okd/src/create_repos.sh
  okd/src/microshift-okd-multi-build.Containerfile
  okd/src/use_okd_assets.sh
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#3941 Rebase lvms quay.io lvms dev lvms4 lvms operator bundle v4.17.0 41
  assets/components/lvms/lvm.topolvm.io_lvmclusters.yaml
  assets/components/lvms/lvm.topolvm.io_lvmvolumegroups.yaml
  assets/components/lvms/lvms-operator_apps_v1_deployment.yaml
  assets/components/lvms/topolvm-configmap_lvms-version.yaml
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  scripts/auto-rebase/last_lvms_rebase.sh
  scripts/auto-rebase/rebase_job_entrypoint.sh
Labels: lgtm, approved

#3911 USHIFT-4385: Add devenv instructions on mounting shared directory
  Makefile
  docs/contributor/devenv_setup.md
  scripts/fetch_tools.sh
Labels: lgtm, approved, jira/valid-reference

#3953 USHIFT-4520: Exit with non-zero status from onerror kickstart handler
  test/kickstart-templates/includes/onerror-logs.cfg
Labels: lgtm, approved, jira/valid-reference

#3921 USHIFT-4336: Implement embedded container build support in bootc tests
  test/bin/pyutils/build_bootc_images.py
  test/image-blueprints/layer5-bootc/group2/cos9-bootc-source-isolated.containerfile
  test/image-blueprints/layer5-bootc/group2/microshift-imagestore-config.sh.template
  test/image-blueprints/layer5-bootc/group2/rhel94-bootc-source-isolated.containerfile
  test/scenarios-bootc/periodics/cos9-src@isolated-net.sh
  test/scenarios-bootc/periodics/el94-src@isolated-net.sh
Labels: lgtm, approved, jira/valid-reference

#3960 NO-ISSUE: Enable 4.18 crel images
  test/bin/common_versions.sh
Labels: lgtm, approved, jira/valid-reference

#3962 [release-4.17] NO-ISSUE: Update 4.17 crel to RC
  test/bin/common_versions.sh
Labels: lgtm, approved, cherry-pick-approved, staff-eng-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#3961 USHIFT-4524: Update Go version in configure-vm.sh and microshift.spec during rebase
  scripts/auto-rebase/rebase_job_entrypoint.sh
Labels: lgtm, approved, jira/valid-reference

#3946 USHIFT-3779: Check if nginx is running in scenario.sh and build_images.sh
  test/bin/build_images.sh
  test/bin/pyutils/build_bootc_images.py
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#3914 USHIFT-4278: Specify default value for .storage.optionalCsiComponents that is an accepted value
  cmd/generate-config/config/config-openapi-spec.json
  etcd/vendor/github.com/openshift/microshift/pkg/config/storage.go
  packaging/microshift/config.yaml
  pkg/config/storage.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#3927 USHIFT-4115: Manifest deletion
  docs/user/howto_config.md
  etcd/vendor/github.com/openshift/microshift/pkg/config/manifests.go
  pkg/config/manifests.go
  pkg/kustomize/apply.go
  pkg/kustomize/kustomize.go
  test/scenarios-bootc/presubmits/cos9-src@standard-suite1.sh
  test/scenarios-bootc/presubmits/el94-src@standard-suite1.sh
  test/scenarios/periodics/cos9-src@rpm-standard1.sh
  test/scenarios/periodics/el94-src@rpm-standard1.sh
  test/scenarios/presubmits/el94-src@standard-suite1.sh
  test/suites/selinux/validate-selinux-policy.robot
  test/suites/standard1/kustomize.robot
Labels: lgtm, approved, jira/valid-reference

#3853 USHIFT-4342: Add flannel resource as optional CNI
  Makefile
  assets/optional/flannel/00-namespace.yaml
  assets/optional/flannel/01-service-account.yaml
  assets/optional/flannel/02-cluster-role.yaml
  assets/optional/flannel/03-cluster-role-binding.yaml
  assets/optional/flannel/04-configmap.yaml
  assets/optional/flannel/05-daemonset.yaml
  assets/optional/flannel/kustomization.aarch64.yaml
  assets/optional/flannel/kustomization.x86_64.yaml
  assets/optional/flannel/kustomization.yaml
  assets/optional/flannel/release-flannel-aarch64.json
  assets/optional/flannel/release-flannel-x86_64.json
  assets/optional/kube-proxy/00-namespace.yaml
  assets/optional/kube-proxy/01-service-account.yaml
  assets/optional/kube-proxy/02-cluster-role.yaml
  assets/optional/kube-proxy/03-cluster-role-binding.yaml
  assets/optional/kube-proxy/04-configmap.yaml
  assets/optional/kube-proxy/05-daemonset.yaml
  assets/optional/kube-proxy/kustomization.aarch64.yaml
  assets/optional/kube-proxy/kustomization.x86_64.yaml
  assets/optional/kube-proxy/kustomization.yaml
  assets/optional/kube-proxy/release-kube-proxy-aarch64.json
  assets/optional/kube-proxy/release-kube-proxy-x86_64.json
  cmd/generate-config/config/config-openapi-spec.json
  docs/user/howto_config.md
  packaging/flannel/00-disableDefaultCNI.yaml
  packaging/flannel/microshift-flannel.service
  packaging/microshift/config.yaml
  packaging/rpm/make-rpm.sh
  packaging/rpm/microshift.spec
  pkg/components/networking.go
  pkg/config/config.go
  pkg/config/network.go
  pkg/config/network_test.go
  scripts/auto-rebase/assets.yaml
Labels: lgtm, approved, jira/valid-reference

#3984 USHIFT-3175: Reduce skip list for conformance
  origin/skip.txt
Labels: lgtm, approved, jira/valid-reference

#3983 NO-ISSUE: Add an option to reuse mirror registry
  test/bin/mirror_registry.sh
Labels: lgtm, approved, jira/valid-reference

#3976 USHIFT-4127: Refactor bootc RPM repository configuration
  test/bin/pyutils/build_bootc_images.py
  test/image-blueprints/layer5-bootc/group1/cos9-bootc-source.containerfile
  test/image-blueprints/layer5-bootc/group1/microshift_repo_config.sh.template
  test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source.containerfile
  test/image-blueprints/layer5-bootc/group1/rhel94-ostree-microshift-previous-minor.container-encapsulate
  test/image-blueprints/layer5-bootc/group2/cos9-bootc-source-optionals.containerfile
  test/image-blueprints/layer5-bootc/group2/rhel94-bootc-source-fake-next-minor.containerfile
  test/image-blueprints/layer5-bootc/group2/rhel94-bootc-source-optionals.containerfile
  test/image-blueprints/layer5-bootc/group2/rhel94-bootc-source-ostree-parent.containerfile
  test/package-sources-bootc/microshift-base.repo
  test/package-sources-bootc/microshift-centos9-nfv.repo
  test/package-sources-bootc/microshift-crel.repo
  test/package-sources-bootc/microshift-fake-next-minor.repo
  test/package-sources-bootc/microshift-fast-datapath-rhel9.repo
  test/package-sources-bootc/microshift-local.repo
  test/package-sources-bootc/microshift-prel.repo
  test/package-sources-bootc/microshift-rhocp-y.repo
  test/package-sources-bootc/microshift-rhocp-y1.repo
  test/package-sources-bootc/microshift-rhocp-y2.repo
Labels: lgtm, approved, jira/valid-reference

#3998 NO-ISSUE: rebase-main-4.18.0-0.nightly-2024-09-29-150556_amd64-2024-09-29_arm64-2024-09-29
  Makefile.kube_git.var
  Makefile.version.aarch64.var
  Makefile.version.x86_64.var
  assets/controllers/kube-controller-manager/defaultconfig.yaml
  assets/optional/multus/release-multus-aarch64.json
  assets/optional/multus/release-multus-x86_64.json
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-catalogsources.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-clusterserviceversions.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-installplans.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-olmconfigs.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-operatorconditions.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-operatorgroups.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-operators.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-subscriptions.crd.yaml
  assets/optional/operator-lifecycle-manager/kustomization.aarch64.yaml
  assets/optional/operator-lifecycle-manager/kustomization.x86_64.yaml
  assets/optional/operator-lifecycle-manager/release-olm-aarch64.json
  assets/optional/operator-lifecycle-manager/release-olm-x86_64.json
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  etcd/go.mod
  etcd/go.sum
  etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/network.go
  etcd/vendor/modules.txt
  go.mod
  go.sum
  packaging/crio.conf.d/10-microshift_amd64.conf
  pkg/controllers/kube-controller-manager_test.go
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/commits.txt
  scripts/auto-rebase/last_rebase.sh
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding/binder.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding/fake_binder.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding/volume_binding.go
  vendor/k8s.io/kubernetes/pkg/volume/util/util.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference
