Repository openshift/microshift, pull requests merged in 2024-10, with the labels that each got.

#4003 NO-ISSUE: USHIFT_USER should have sudo access without password
  test/README.md
Labels: lgtm, approved, jira/valid-reference

#4004 NO-ISSUE: Separate bootc containerfile to be downloadable in docs
  docs/config/Containerfile.bootc-rhel9
  docs/contributor/image_mode.md
Labels: lgtm, approved, jira/valid-reference

#4009 Rebase lvms registry.redhat.io lvms4 lvms operator bundle v4.17.0 43
  assets/components/lvms/lvms-operator_apps_v1_deployment.yaml
  assets/components/lvms/topolvm-configmap_lvms-version.yaml
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  scripts/auto-rebase/last_lvms_rebase.sh
  scripts/auto-rebase/rebase_job_entrypoint.sh
Labels: lgtm, approved

#4010 NO-ISSUE: Skip HAProxy multinode schedule conformance test
  origin/skip.txt
Labels: lgtm, approved, jira/valid-reference

#4019 NO-ISSUE: Rebase lvms registry.redhat.io lvms4 lvms operator bundle v4.17.0 43
  assets/components/lvms/lvm.topolvm.io_lvmclusters.yaml
  assets/components/lvms/lvm.topolvm.io_lvmvolumegroups.yaml
  assets/components/lvms/lvms-operator_apps_v1_deployment.yaml
  assets/components/lvms/topolvm-configmap_lvms-version.yaml
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  scripts/auto-rebase/last_lvms_rebase.sh
  scripts/auto-rebase/rebase_job_entrypoint.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4023 NO-ISSUE: Add temp skips until 1.31 rebase
  origin/skip.txt
Labels: lgtm, approved, jira/valid-reference

#3997 USHIFT-4547: Add timeout and retries to ISO downloads when building images
  scripts/image-builder/configure.sh
  test/bin/build_images.sh
Labels: lgtm, approved, jira/valid-reference

#4030 NO-ISSUE: Add avahi-tools requirement for router smoke test
  test/README.md
Labels: lgtm, approved, jira/valid-reference

#3999 USHIFT-4541: improve slave NIC detection for router exposed IPs
  pkg/config/config.go
Labels: lgtm, approved, jira/valid-reference

#4008 USHIFT-4534: Add rebase capabilities for gateway api
  assets/optional/gateway-api/00-openshift_gateway_api_namespace.yaml
  assets/optional/gateway-api/02-gatewayclass.yaml
  assets/optional/gateway-api/02-istio.yaml
  assets/optional/gateway-api/kustomization.yaml
  scripts/auto-rebase/assets.yaml
  scripts/auto-rebase/ossm_assets.yaml
  scripts/auto-rebase/presubmit.py
  scripts/auto-rebase/rebase_gateway_api.sh
Labels: lgtm, approved, jira/valid-reference

#4032 [release-4.17] NO-ISSUE: Bump dev-env's Go ver to 1.22.5
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4034 USHIFT-4343: Add test scenario for flannel CNI plugin
  Makefile
  test/bin/ci_phase_iso_build.sh
  test/image-blueprints/layer5-bootc/group2/cos9-bootc-source-flannel.containerfile
  test/scenarios-bootc/periodics/cos9-src@flannel.sh
Labels: lgtm, approved, jira/valid-reference

#3975 USHIFT-4116: Auto recovery: backup
  pkg/admin/autorecovery/backup.go
  pkg/admin/data/data_manager.go
  pkg/admin/data/types.go
  pkg/admin/prerun/prerun.go
  pkg/admin/prerun/system.go
  pkg/admin/prerun/version.go
  pkg/cmd/admin.go
  test/scenarios-bootc/presubmits/cos9-src@auto-recovery.sh
  test/scenarios-bootc/presubmits/el94-src@auto-recovery.sh
  test/scenarios/periodics/el94-src@auto-recovery-rpm.sh
  test/suites/backup/auto-recovery.robot
Labels: lgtm, approved, jira/valid-reference

#4048 USHIFT-4349: Fixed --osinfo=generic warning
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#4056 USHIFT-4684: Optimize microshift-test-agent code to avoid race conditions
  test/agent/microshift-test-agent.service
  test/agent/microshift-test-agent.sh
Labels: lgtm, approved, jira/valid-reference

#4062 USHIFT-4127: Add bootc package to yminus2 ostree image for upgrade scenarios to work
  test/image-blueprints/layer1-base/group2/rhel94-microshift-yminus2.toml
Labels: lgtm, approved, jira/valid-reference

#4057 USHIFT-4567: Remove 1.31 temp skipped conformance tests
  origin/skip.txt
Labels: lgtm, approved, jira/valid-reference

#4058 USHIFT-4685: Skip unsupported multus conformance tests
  origin/skip.txt
Labels: lgtm, approved, jira/valid-reference

#4065 NO-ISSUE: Add error message for AWS CLI commands instead of silent exit
  test/bin/manage_build_cache.sh
Labels: lgtm, approved, jira/valid-reference

#4060 USHIFT-4686: Add greenboot healthcheck after reboot on ostree system
  test/suites/standard1/kustomize.robot
Labels: lgtm, approved, jira/valid-reference

#4075 [release-4.17] Fix microshift-test-agent race conditions
  test/agent/microshift-test-agent.service
  test/agent/microshift-test-agent.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#4016 [release-4.17] USHIFT-4694: update common_versions.sh
  test/bin/common_versions.sh
  test/package-sources/rhocp-y.toml
  test/package-sources/rhocp-y1.toml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4080 USHIFT-4704: Port bootc build procedure to directly use mirror registry instead of local storage
  scripts/image-builder/mirror-images.sh
  test/README.md
  test/bin/ci_phase_boot_and_test.sh
  test/bin/common.sh
  test/bin/mirror_registry.sh
  test/bin/pyutils/build_bootc_images.py
  test/bin/scenario.sh
  test/kickstart-templates/includes/post-containers.cfg
  test/scenarios-bootc/periodics/cos9-src@isolated-net.sh
  test/scenarios-bootc/periodics/el94-prel@el94-src@upgrade-ostree2bootc-ok.sh
  test/scenarios-bootc/periodics/el94-src@isolated-net.sh
  test/scenarios-bootc/presubmits/el94-src@downgrade-block.sh
  test/scenarios/presubmits/el94-src@ipv6.sh
Labels: lgtm, approved, jira/valid-reference

#4085 [release-4.16] USHIFT-4707: Add greenboot healthcheck after reboot on ostree system
  test/suites/standard1/kustomize.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4086 [release-4.17] USHIFT-4706: Add greenboot healthcheck after reboot on ostree system
  test/suites/standard1/kustomize.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4079 USHIFT-4702: Add terminationMessagePolicy to multus containers
  assets/optional/multus/06-daemonset.yaml
  assets/optional/multus/07-daemonset-dhcp.yaml
Labels: lgtm, approved, jira/valid-reference

#4061 USHIFT-4117: Auto Recovery: Restore
  pkg/admin/autorecovery/backup.go
  pkg/admin/autorecovery/restore.go
  pkg/admin/autorecovery/state.go
  pkg/admin/autorecovery/state_test.go
  pkg/admin/autorecovery/storage.go
  pkg/admin/autorecovery/storage_test.go
  pkg/admin/data/atomic_dir_copy.go
  pkg/admin/data/data_manager.go
  pkg/admin/data/types.go
  pkg/admin/prerun/system.go
  pkg/cmd/admin.go
  pkg/util/util.go
  test/suites/backup/auto-recovery.robot
Labels: lgtm, approved, jira/valid-reference

#4093 NO-ISSUE: Use /run/cni/bin location for flannel cni
  assets/optional/flannel/05-daemonset.yaml
Labels: lgtm, approved, jira/valid-reference

#4092 USHIFT-4712: Fix tests and node configuration for CNCF conformance
  scripts/multinode/configure-pri.sh
  scripts/multinode/configure-sec.sh
  test/scenarios/periodics/el94-src@cncf-conformance.sh
Labels: lgtm, approved, jira/valid-reference

#4066 USHIFT-4565: Gateway API rpm
  assets/optional/gateway-api/00-extensions.istio.io_wasmplugins.yaml
  assets/optional/gateway-api/00-gateway.networking.k8s.io_crds.yaml
  assets/optional/gateway-api/00-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  assets/optional/gateway-api/00-networking.istio.io_destinationrules.yaml
  assets/optional/gateway-api/00-networking.istio.io_envoyfilters.yaml
  assets/optional/gateway-api/00-networking.istio.io_gateways.yaml
  assets/optional/gateway-api/00-networking.istio.io_proxyconfigs.yaml
  assets/optional/gateway-api/00-networking.istio.io_serviceentries.yaml
  assets/optional/gateway-api/00-networking.istio.io_sidecars.yaml
  assets/optional/gateway-api/00-networking.istio.io_virtualservices.yaml
  assets/optional/gateway-api/00-networking.istio.io_workloadentries.yaml
  assets/optional/gateway-api/00-networking.istio.io_workloadgroups.yaml
  assets/optional/gateway-api/00-sailoperator.io_istiocnis.yaml
  assets/optional/gateway-api/00-sailoperator.io_istiorevisions.yaml
  assets/optional/gateway-api/00-sailoperator.io_istios.yaml
  assets/optional/gateway-api/00-sailoperator.io_remoteistios.yaml
  assets/optional/gateway-api/00-security.istio.io_authorizationpolicies.yaml
  assets/optional/gateway-api/00-security.istio.io_peerauthentications.yaml
  assets/optional/gateway-api/00-security.istio.io_requestauthentications.yaml
  assets/optional/gateway-api/00-telemetry.istio.io_telemetries.yaml
  assets/optional/gateway-api/01-servicemesh-operator3-metrics-service_v1_service.yaml
  assets/optional/gateway-api/01-servicemesh-operator3_rbac.authorization.k8s.io_v1_clusterrole.yaml
  assets/optional/gateway-api/01-servicemesh-operator3_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  assets/optional/gateway-api/01-servicemesh-operator3_rbac.authorization.k8s.io_v1_role.yaml
  assets/optional/gateway-api/01-servicemesh-operator3_rbac.authorization.k8s.io_v1_rolebinding.yaml
  assets/optional/gateway-api/01-servicemesh-operator3_v1_serviceaccount.yaml
  assets/optional/gateway-api/02-istio.yaml
  assets/optional/gateway-api/03-servicemesh-operator3_apps_v1_deployment.yaml
  assets/optional/gateway-api/kustomization.aarch64.yaml
  assets/optional/gateway-api/kustomization.x86_64.yaml
  assets/optional/gateway-api/kustomization.yaml
  packaging/greenboot/microshift-running-check-gateway-api.sh
  packaging/rpm/microshift.spec
  scripts/auto-rebase/last_rebase_gateway_api.sh
  scripts/auto-rebase/ossm_assets.yaml
  scripts/auto-rebase/rebase_gateway_api.sh
Labels: lgtm, approved, jira/valid-reference

#4091 USHIFT-4118: Documentation for auto-recovery
  docs/user/autorecovery.md
Labels: lgtm, approved, jira/valid-reference

#4018 USHIFT-4350: Create script for creation of AWS stack
  scripts/aws/cf-gen.yaml
  scripts/aws/manage_aws_stack.sh
Labels: lgtm, approved, jira/valid-reference

#4017 USHIFT-4129: Update common_versions.sh with 4.17 repos
  test/bin/common_versions.sh
  test/package-sources/rhocp-y.toml
  test/package-sources/rhocp-y1.toml
  test/scenarios/presubmits/el94-src@rpm-install.sh
Labels: lgtm, approved, jira/valid-reference

#4102 USHIFT-4712: CNCF scenario: check failed tests
  test/scenarios/periodics/el94-src@cncf-conformance.sh
Labels: lgtm, approved, jira/valid-reference

#4103 [release-4.17] USHIFT-4714: Fix CNCF conformance periodics issues
  scripts/multinode/configure-pri.sh
  scripts/multinode/configure-sec.sh
  test/scenarios/periodics/el94-src@cncf-conformance.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4090 USHIFT-2927: Remove fstab workaround in kickstart
  test/kickstart-templates/includes/post-bootc-wa.cfg
  test/kickstart-templates/kickstart-bootc.ks.template
Labels: lgtm, approved, jira/valid-reference

#4099 NO-ISSUE: Move kustomize.robot to standard-suite2
  test/suites/standard2/kustomize.robot
Labels: lgtm, approved, jira/valid-reference

#4101 USHIFT-4705: Check disk space before backing up / restoring
  pkg/admin/autorecovery/restore.go
  pkg/admin/data/data_manager.go
  pkg/admin/data/disk_space.go
Labels: lgtm, approved, jira/valid-reference

#4104 USHIFT-4715: Add gateway-api-release-info RPM
  assets/optional/gateway-api/release-gateway-api-aarch64.json
  assets/optional/gateway-api/release-gateway-api-x86_64.json
  packaging/rpm/microshift.spec
  scripts/auto-rebase/ossm_assets.yaml
  scripts/auto-rebase/rebase_gateway_api.sh
Labels: lgtm, approved, jira/valid-reference

#4076 USHIFT-4536: Add Gateway API tests
  test/assets/gateway-api/gateway.yaml.template
  test/assets/gateway-api/http-route.yaml.template
  test/image-blueprints/layer2-presubmit/group1/rhel94-source-with-optionals.toml
  test/image-blueprints/layer3-periodic/group1/rhel94-crel-with-optionals.toml
  test/image-blueprints/layer3-periodic/group1/rhel94-source-with-optionals.toml
  test/image-blueprints/layer5-bootc/group2/cos9-bootc-source-optionals.containerfile
  test/image-blueprints/layer5-bootc/group2/rhel94-bootc-source-optionals.containerfile
  test/suites/optional/gateway-api.robot
Labels: lgtm, approved, jira/valid-reference

#4105 NO-ISSUE: Remove microshift-gateway-api from rhel94-crel-with-optionals.toml until the package is published on mirror
  test/image-blueprints/layer3-periodic/group1/rhel94-crel-with-optionals.toml
Labels: lgtm, approved, jira/valid-reference

#4118 USHIFT-4724: Isolated tests must not have access to mirror registry
  test/image-blueprints/layer3-periodic/group1/rhel94-source-isolated.toml
  test/image-blueprints/layer5-bootc/group2/cos9-bootc-source-isolated.containerfile
  test/image-blueprints/layer5-bootc/group2/rhel94-bootc-source-isolated.containerfile
  test/kickstart-templates/kickstart-bootc-isolated.ks.template
  test/kickstart-templates/kickstart-isolated.ks.template
  test/scenarios-bootc/periodics/cos9-src@isolated-net.sh
  test/scenarios-bootc/periodics/el94-src@isolated-net.sh
  test/scenarios/periodics/el94-src@isolated-net.sh
  test/suites/network/isolated-network.robot
Labels: lgtm, approved, jira/valid-reference
