Repository openshift/microshift, pull requests merged in 2025-09, with the labels that each got.

#5405 [release-4.20] USHIFT-6086: Disable CentOS images and scenarios in 4.20 branch
  test/image-blueprints-bootc/README.md
  test/image-blueprints-bootc/layer1-base/group2/centos9-bootc.image-bootc
  test/image-blueprints-bootc/layer2-presubmit/group1/cos9-bootc-source.containerfile
  test/image-blueprints-bootc/layer3-periodic/group3/cos9-bootc-source-isolated.containerfile
  test/image-blueprints-bootc/layer3-periodic/group3/cos9-bootc-source-kindnet.containerfile
  test/image-blueprints-bootc/layer3-periodic/group3/cos9-bootc-source-optionals.containerfile
  test/kickstart-templates/includes/post-cos9rpm.cfg
  test/kickstart-templates/kickstart-centos.ks.template
  test/package-sources-bootc/microshift-centos9-nfv.repo
  test/scenarios-bootc/periodics/cos9-src@greenboot.sh
  test/scenarios-bootc/periodics/cos9-src@isolated-net.sh
  test/scenarios-bootc/periodics/cos9-src@kindnet.sh
  test/scenarios-bootc/periodics/cos9-src@multi-nic.sh
  test/scenarios-bootc/periodics/cos9-src@optional.sh
  test/scenarios-bootc/presubmits/cos9-src@standard-suite1.sh
  test/scenarios-bootc/presubmits/cos9-src@standard-suite2.sh
Labels: lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#5409 [release-4.16] USHIFT-6086: Disable CentOS images and scenarios in 4.16 branch
  test/image-blueprints/layer1-base/group1/centos9.image-fetcher
  test/kickstart-templates/includes/post-cos9rpm.cfg
  test/kickstart-templates/kickstart-centos.ks.template
  test/scenarios-periodics/cos9-src@rpm-standard1.sh
  test/scenarios-periodics/cos9-src@rpm-standard2.sh
Labels: lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#5411 USHIFT-6088: Add verified label to rebase
  scripts/auto-rebase/rebase.py
Labels: lgtm, approved, jira/valid-reference, verified

#5365 USHIFT-5983: Update scenario.sh script to run gingko tests
  scripts/fetch_tools.sh
  test/bin/ci_phase_boot_and_test.sh
  test/bin/common.sh
  test/bin/scenario.sh
  test/scenarios-bootc/releases/el96-lrel@ginkgo-tests.sh
  test/scenarios/releases/el96-lrel@ginkgo-tests.sh
Labels: lgtm, approved, jira/valid-reference, verified

#5424 USHIFT-6094: Ansible Add NVIDIA GPU support
  ansible/README.md
  ansible/roles/nvidia-gpu-setup/README.md
  ansible/roles/nvidia-gpu-setup/defaults/main.yml
  ansible/roles/nvidia-gpu-setup/tasks/main.yml
  ansible/roles/nvidia-gpu-test/defaults/main.yml
  ansible/roles/nvidia-gpu-test/tasks/main.yml
  ansible/roles/nvidia-gpu-test/templates/gpu-test-workload.yaml.j2
  ansible/setup-node.yml
  ansible/vars/all.yml
Labels: lgtm, approved, jira/valid-reference, verified

#5438 USHIFT-5548: Exclude telemetry from community builds
  Makefile
  packaging/rpm/make-rpm.sh
  packaging/rpm/microshift.spec
  test/bin/build_rpms.sh
Labels: lgtm, approved, jira/valid-reference, verified

#5445 USHIFT-6035: Switch to 4.20-rc packages in common_versions.sh
  test/bin/common_versions.sh
  test/scenarios-bootc/periodics/el96-crel@brew-standard1.sh
  test/scenarios-bootc/periodics/el96-crel@brew-standard2.sh
Labels: lgtm, approved, jira/valid-reference, verified

#5459 USHIFT-6107: Increase the vm size for the storage cases to pass
  test/scenarios-bootc/releases/el96-lrel@ginkgo-tests.sh
  test/scenarios/releases/el96-lrel@ginkgo-tests.sh
Labels: lgtm, approved, jira/valid-reference, verified

#5463 TRT-2071: updating skips for pending test renames
  origin/skip.txt
Labels: lgtm, approved, jira/valid-reference, verified

#5460 USHIFT-5992: Update README.md to have the latest information
  scripts/advisory_publication/README.md
Labels: lgtm, approved, jira/valid-reference, verified

#5464 USHIFT-5911: Refactor configure-vm.sh script
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference, verified

#5492 [release-4.20] USHIFT-5983: Update scenario.sh script to run gingko tests
  scripts/fetch_tools.sh
  test/bin/ci_phase_boot_and_test.sh
  test/bin/common.sh
  test/bin/scenario.sh
  test/scenarios-bootc/releases/el96-lrel@ginkgo-tests.sh
  test/scenarios/releases/el96-lrel@ginkgo-tests.sh
Labels: lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#5497 NO-ISSUE: rebase-main-4.21.0-0.nightly-2025-09-18-193221_amd64-2025-09-18_arm64-2025-09-16
  Makefile.kube_git.var
  Makefile.version.aarch64.var
  Makefile.version.x86_64.var
  assets/components/multus/kustomization.aarch64.yaml
  assets/components/multus/kustomization.x86_64.yaml
  assets/components/multus/release-multus-aarch64.json
  assets/components/multus/release-multus-x86_64.json
  assets/controllers/kube-controller-manager/defaultconfig.yaml
  assets/optional/kube-proxy/kustomization.aarch64.yaml
  assets/optional/kube-proxy/kustomization.x86_64.yaml
  assets/optional/kube-proxy/release-kube-proxy-aarch64.json
  assets/optional/kube-proxy/release-kube-proxy-x86_64.json
  assets/optional/operator-lifecycle-manager/kustomization.aarch64.yaml
  assets/optional/operator-lifecycle-manager/kustomization.x86_64.yaml
  assets/optional/operator-lifecycle-manager/release-olm-aarch64.json
  assets/optional/operator-lifecycle-manager/release-olm-x86_64.json
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  deps/github.com/openshift/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/etcd3/etcd3retry/retry_etcdclient.go
  deps/github.com/openshift/kubernetes/test/e2e/storage/testsuites/volume_modify.go
  go.mod
  go.sum
  packaging/crio.conf.d/10-microshift_amd64.conf
  packaging/crio.conf.d/10-microshift_arm64.conf
  pkg/controllers/kube-controller-manager_test.go
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/commits.txt
  scripts/auto-rebase/last_rebase.sh
  vendor/github.com/openshift/cluster-policy-controller/pkg/security/controller/namespace_scc_allocation_controller.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/etcd3retry/retry_etcdclient.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference, verified

#5507 [release-4.20] USHIFT-6035: Update rc as latest release type in common_versions
  test/bin/common_versions.sh
Labels: lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#5517 USHIFT-6176: Remove nightly brew references and images
  test/bin/build_images.sh
  test/bin/common_versions.sh
  test/bin/manage_brew_rpms.sh
  test/bin/pyutils/build_bootc_images.py
  test/image-blueprints-bootc/layer1-base/group2/rhel96-bootc-brew-nightly-with-optional.containerfile
  test/image-blueprints/layer1-base/group4/rhel96-brew-nightly-with-optionals.toml
Labels: lgtm, approved, jira/valid-reference, verified

#5528 NO-ISSUE: Fix brew dependency in image blueprints
  test/image-blueprints/layer2-presubmit/group1/rhel96-lrel-optionals-tuned.toml
Labels: lgtm, approved, jira/valid-reference, verified

#5355 USHIFT-5925: Cert manager auto rebase
  assets/optional/cert-manager/manager/images.yaml
  assets/optional/cert-manager/manager/kustomization.yaml
  scripts/auto-rebase/assets_cert_manager.yaml
  scripts/auto-rebase/rebase.py
  scripts/auto-rebase/rebase_cert_manager.sh
  scripts/auto-rebase/rebase_job_entrypoint.sh
  scripts/fetch_tools.sh
Labels: lgtm, approved, jira/valid-reference, verified

#5509 USHIFT-5548 Disable telemetry for community builds
  Makefile
  packaging/rpm/make-rpm.sh
  packaging/rpm/microshift.spec
  pkg/config/config.go
  pkg/controllers/telemetry.go
  pkg/version/version.go
Labels: lgtm, approved, verified

#5320 USHIFT-5572: Add HTTP01 ACME test for cert-manager
  test/assets/cert-manager/pebble-server.yaml
  test/suites/optional/cert-manager.robot
Labels: lgtm, approved, jira/valid-reference, verified

#5530 USHIFT-6103: Add standard scenario bootc tests on RHEL 10
  packaging/rpm/microshift.spec
  test/image-blueprints-bootc/layer1-base/group1/rhel100-test-agent.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel100-bootc.image-bootc
  test/image-blueprints-bootc/layer2-presubmit/group1/rhel100-bootc-source.containerfile
  test/scenarios-bootc/periodics/el100-src@standard-suite1.sh
  test/scenarios-bootc/periodics/el100-src@standard-suite2.sh
Labels: lgtm, approved, jira/valid-reference, verified

#5544 USHIFT-5864: Reenable offline AI Model Serving test
  test/image-blueprints-bootc/layer3-periodic/group1/rhel96-bootc-source-ai-model-serving.containerfile
  test/scenarios-bootc/periodics/el96-src@ai-model-serving-offline.sh
  test/suites/ai-model-serving/ai-model-serving-offline.robot
Labels: lgtm, approved, jira/valid-reference, verified
