Repository openshift/microshift, pull requests merged in 2025-04, with the labels that each got.

#4748 USHIFT-5541: Increase timeout for CatalogSource & add extra logging
  test/bin/scenario.sh
  test/kickstart-templates/includes/main-prologue.cfg
  test/suites/optional/olm.robot
Labels: lgtm, approved, jira/valid-reference

#4749 USHIFT-5543: Create observability data dir before service starts
  packaging/observability/microshift-observability.service
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#4738 ShiftWeek: Etcd to Kine replacement in OKD
  okd/src/etcd/README.md
  okd/src/etcd/microshift-etcd-postgres.sh
  okd/src/etcd/microshift-etcd-sqlite.sh
Labels: lgtm, approved

#4742 OCPBUGS-52420: Fix container file documentation with correct image embedding commands
  docs/config/Containerfile.bootc-embedded-rhel9
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4739 [release-4.18] OCPBUGS-53421: Backport bootc embedded image upgrade adjustments
  docs/config/Containerfile.bootc-embedded-rhel9
  docs/config/Containerfile.bootc-rhel9
  docs/contributor/image_mode.md
  test/bin/pyutils/build_bootc_images.py
  test/image-blueprints-bootc/layer1-base/group2/microshift-copy-images.conf.template
  test/image-blueprints-bootc/layer1-base/group2/microshift-copy-images.sh.template
  test/image-blueprints-bootc/layer1-base/group2/rhel94-bootc-crel-isolated.containerfile
  test/image-blueprints-bootc/layer2-source/group2/microshift-imagestore-config.sh.template
  test/image-blueprints-bootc/layer2-source/group2/rhel94-bootc-source-isolated.containerfile
  test/image-blueprints-bootc/layer2-source/group3/cos9-bootc-source-isolated.containerfile
  test/scenarios-bootc/periodics/el94-crel@el94-src@upgrade-fails-isolated.sh
  test/scenarios-bootc/presubmits/el94-crel@el94-src@upgrade-ok-isolated.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4751 OCPBUGS-54239: Add hostname package dependency to microshift RPM
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4752 [release-4.18] OCPBUGS-54448: Add hostname package dependency to microshift RPM
  packaging/rpm/microshift.spec
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4764 USHIFT-5559: Loosen the relationship between microshift and m-observability services
  packaging/observability/microshift-observability.service
Labels: lgtm, approved, jira/valid-reference

#4746 USHIFT-3845: Crio uses crun as a default runtime
  packaging/crio.conf.d/00-crio-crun.conf
  packaging/crio.conf.d/10-microshift_amd64.conf
  packaging/crio.conf.d/10-microshift_arm64.conf
  packaging/rpm/microshift.spec
  scripts/devenv-builder/configure-vm.sh
  test/image-blueprints-bootc/layer2-source/group1/cos9-bootc-source.containerfile
  test/kickstart-templates/includes/post-cos9rpm.cfg
  test/suites/standard2/configuration.robot
Labels: lgtm, approved, jira/valid-reference

#4765 USHIFT-5533: Switch to using immutable filesystem for installing systemd drop-ins
  docs/config/Containerfile.bootc-embedded-rhel9
  docs/config/Containerfile.bootc-rhel9
  docs/contributor/image_mode.md
  okd/src/microshift-okd-multi-build.Containerfile
  okd/src/microshift-okd-run.Containerfile
  packaging/imagemode/Containerfile.repobase
  packaging/imagemode/Containerfile.repourl
  packaging/imagemode/Containerfile.rhocp
  test/image-blueprints-bootc/layer1-base/group2/rhel96-bootc-crel-isolated.containerfile
  test/image-blueprints-bootc/layer2-source/group1/rhel96-bootc-source.containerfile
  test/image-blueprints-bootc/layer2-source/group2/rhel96-bootc-source-ai-model-serving.containerfile
  test/image-blueprints-bootc/layer2-source/group2/rhel96-bootc-source-isolated.containerfile
  test/image-blueprints-bootc/layer2-source/group3/cos9-bootc-source-isolated.containerfile
  test/kickstart-templates/includes/post-bootc-container-tweaks.cfg
Labels: lgtm, approved, jira/valid-reference

#4697 OCPBUGS-51365: Move Multus manifests from RPM to embedded assets & run kustomizer standalone
  assets/components/multus/00-namespace.yaml
  assets/components/multus/01-crd-networkattachmentdefinition.yaml
  assets/components/multus/02-service-account.yaml
  assets/components/multus/03-cluster-role.yaml
  assets/components/multus/04-cluster-role-binding.yaml
  assets/components/multus/05-configmap.yaml
  assets/components/multus/06-daemonset.yaml
  assets/components/multus/07-daemonset-dhcp.yaml
  assets/components/multus/kustomization.aarch64.yaml
  assets/components/multus/kustomization.x86_64.yaml
  assets/components/multus/kustomization.yaml
  assets/components/multus/release-multus-aarch64.json
  assets/components/multus/release-multus-x86_64.json
  cmd/generate-config/config/config-openapi-spec.json
  docs/user/howto_config.md
  packaging/microshift/config.yaml
  packaging/microshift/dropins/enable-multus.yaml
  packaging/rpm/microshift.spec
  pkg/assets/crd.go
  pkg/cmd/run.go
  pkg/components/components.go
  pkg/components/networking.go
  pkg/config/config.go
  pkg/config/network.go
  pkg/kustomize/kustomize.go
  scripts/auto-rebase/assets.yaml
  scripts/auto-rebase/rebase.sh
  test/suites/upgrade/upgrade-multus.robot
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4732 USHIFT-5529: Restructure bootc image build by separating pre-submits and periodics
  test/bin/ci_phase_iso_build.sh
  test/image-blueprints-bootc/layer2-presubmit/group1/cos9-bootc-source.containerfile
  test/image-blueprints-bootc/layer2-presubmit/group1/microshift-ovsdb-ownership.conf.template
  test/image-blueprints-bootc/layer2-presubmit/group1/rhel96-bootc-source-base.containerfile
  test/image-blueprints-bootc/layer2-presubmit/group1/rhel96-bootc-source.containerfile
  test/image-blueprints-bootc/layer2-presubmit/group2/rhel96-bootc-source-aux.containerfile
  test/image-blueprints-bootc/layer2-presubmit/group2/rhel96-bootc-source-fake-next-minor.containerfile
  test/image-blueprints-bootc/layer2-presubmit/group2/rhel96-bootc-source-fips.containerfile
  test/image-blueprints-bootc/layer2-presubmit/group2/rhel96-bootc-source-optionals.containerfile
  test/image-blueprints-bootc/layer2-presubmit/group3/cos9-bootc-source-fips.containerfile
  test/image-blueprints-bootc/layer2-presubmit/group3/cos9-bootc-source-flannel.containerfile
  test/image-blueprints-bootc/layer2-presubmit/group3/cos9-bootc-source-isolated.containerfile
  test/image-blueprints-bootc/layer2-presubmit/group3/cos9-bootc-source-optionals.containerfile
  test/image-blueprints-bootc/layer3-periodic/group1/ai-model-serving-test-data.sh.template
  test/image-blueprints-bootc/layer3-periodic/group1/rhel96-bootc-source-ai-model-serving.containerfile
  test/image-blueprints-bootc/layer3-periodic/group1/rhel96-bootc-source-isolated.containerfile
  test/image-blueprints-bootc/layer3-periodic/group2/rhel96-bootc-source-ai-model-serving.image-bootc
  test/image-blueprints-bootc/layer3-periodic/group2/rhel96-bootc-source-isolated.image-bootc
  test/scenarios-bootc/periodics/el96-crel@el96-src@upgrade-ok-isolated.sh
  test/scenarios-bootc/periodics/el96-src@ai-model-serving-offline.sh
  test/scenarios-bootc/periodics/el96-src@offline.sh
Labels: lgtm, approved, jira/valid-reference

#4754 USHIFT-5519: Add microshift_version to telemetry
  pkg/admin/autorecovery/backup.go
  pkg/admin/prerun/version.go
  pkg/controllers/telemetry.go
  pkg/telemetry/gather.go
  pkg/telemetry/telemetry.go
  pkg/util/util.go
Labels: lgtm, approved, jira/valid-reference

#4770 USHIFT-5523: Add summary line to junit files
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#4767 OCPBUGS-52420: Add embedded containerfile to packaging/imagemode
  packaging/imagemode/Containerfile-embedded.repobase
  packaging/imagemode/Makefile
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4778 USHIFT-5569: Fix advisory publication report
  scripts/advisory_publication/advisory_publication_report.py
Labels: lgtm, approved, jira/valid-reference

#4779 USHIFT-5576: Improve deprecation notice in greenboot/functions.sh
  packaging/greenboot/functions.sh
Labels: lgtm, approved, jira/valid-reference

#4736 USHIFT-4537: introduce topolvm to upstream
  Makefile
  assets/optional/topolvm/01-namespace.yaml
  assets/optional/topolvm/02-cert-manager.yaml
  assets/optional/topolvm/03-topolvm.yaml
  assets/optional/topolvm/kustomization.yaml
  okd/src/microshift-okd-multi-build.Containerfile
  okd/storage/README.md
  okd/storage/hostpath/00-psql-namespace.yaml
  okd/storage/hostpath/01-pv-volume.yaml
  okd/storage/hostpath/02-pvc-volume.yaml
  okd/storage/hostpath/03-psql-service.yaml
  okd/storage/hostpath/04-psql-deployment.yaml
  okd/storage/hostpath/kustomization.yaml
  okd/storage/topolvm/example-psql/01-psql-namespace.yaml
  okd/storage/topolvm/example-psql/02-pvc-volume.yaml
  okd/storage/topolvm/example-psql/03-psql-service.yaml
  okd/storage/topolvm/example-psql/04-psql-deployment.yaml
  okd/storage/topolvm/prepare_topolvm_manifests.sh
  packaging/microshift/dropins/disable-storage-csi.yaml
  packaging/rpm/make-rpm.sh
  packaging/rpm/microshift.spec
  scripts/auto-rebase/assets.yaml
  test/bin/build_rpms.sh
Labels: lgtm, approved, jira/valid-reference

#4718 USHIFT-5461: Implement S3 caching for container images in layer1
  test/bin/ci_phase_iso_build.sh
  test/bin/manage_build_cache.sh
  test/bin/mirror_registry.sh
  test/bin/pyutils/build_bootc_images.py
Labels: lgtm, approved, jira/valid-reference

#4768 USHIFT-5518: Add telemetry proxy settings and tests
  cmd/generate-config/config/config-openapi-spec.json
  docs/user/howto_config.md
  packaging/microshift/config.yaml
  pkg/config/config.go
  pkg/config/telemetry.go
  pkg/controllers/telemetry.go
  pkg/telemetry/telemetry.go
  pkg/telemetry/telemetry_test.go
  test/resources/ProxyLibrary.py
  test/suites/telemetry/telemetry.robot
Labels: lgtm, approved, jira/valid-reference

#4790 NO-ISSUE: Skip LoadBalancer test
  origin/skip.txt
Labels: lgtm, approved, jira/valid-reference

#4700 [release-4.15] OCPBUGS-54714: Upgrade openvswitch package version to 3.3
  packaging/rpm/microshift.spec
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4791 USHIFT-5580: Use CentOS base image for RHEL 9.6 ISO creation until GA
  test/bin/pyutils/build_bootc_images.py
  test/bin/pyutils/common.py
  test/image-blueprints-bootc/layer1-base/group1/rhel96-test-agent.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel96-bootc.image-bootc
  test/scenarios-bootc/periodics/el96-crel@brew-standard1.sh
  test/scenarios-bootc/presubmits/el96-src@standard-suite1.sh
Labels: lgtm, approved, jira/valid-reference

#4777 USHIFT-5529: Move bootc layer2-presubmit/group3 to periodics
  test/image-blueprints-bootc/README.md
  test/image-blueprints-bootc/layer3-periodic/group3/cos9-bootc-source-fips.containerfile
  test/image-blueprints-bootc/layer3-periodic/group3/cos9-bootc-source-flannel.containerfile
  test/image-blueprints-bootc/layer3-periodic/group3/cos9-bootc-source-isolated.containerfile
  test/image-blueprints-bootc/layer3-periodic/group3/cos9-bootc-source-optionals.containerfile
  test/scenarios-bootc/periodics/cos9-src@flannel.sh
Labels: lgtm, approved, jira/valid-reference

#4757 USHIFT-5400 add observability profiles
  packaging/observability/opentelemetry-collector-large.yaml
  packaging/observability/opentelemetry-collector-medium.yaml
  packaging/observability/opentelemetry-collector-small.yaml
Labels: lgtm, approved

#4803 USHIFT-5400: Minor fixes to example OTEL profiles
  packaging/observability/opentelemetry-collector-large.yaml
  packaging/observability/opentelemetry-collector-small.yaml
Labels: lgtm, approved, jira/valid-reference

#4782 USHIFT-5568: Split AI Model Serving manifest
  assets/optional/ai-model-serving/kserve/kustomization.yaml
  assets/optional/ai-model-serving/kustomization.yaml
  assets/optional/ai-model-serving/runtimes/kustomization.yaml
  docs/user/ai_model_serving.md
  packaging/rpm/microshift.spec
  scripts/auto-rebase/assets_ai_model_serving.yaml
  scripts/ci-ai-model-serving/tests/06-test-vllm.sh
  test/image-blueprints-bootc/layer3-periodic/group1/ai-model-serving-test-data.sh.template
  test/suites/ai-model-serving/ai-model-serving-offline.robot
  test/suites/ai-model-serving/ai-model-serving-online.robot
Labels: lgtm, approved, jira/valid-reference

#4792 USHIFT-5530: Revert "Temporarily disable el94-to-el96 bootc upgrade tests"
  test/scenarios-bootc/periodics/el94-prel@el96-crel@upgrade-ok.sh
  test/scenarios-bootc/periodics/el94-prel@el96-src@upgrade-fails-and-rolls-back.sh
  test/scenarios-bootc/periodics/el94-prel@el96-src@upgrade-ostree2bootc-ok.sh
  test/scenarios-bootc/periodics/el94-yminus2@el96-src@upgrade-ostree2bootc-ok.sh
  test/scenarios-bootc/presubmits/el94-prel@el96-src@upgrade-ok.sh
  test/scenarios-bootc/presubmits/el94-yminus2@el96-src@upgrade-ok.sh
Labels: lgtm, approved, jira/valid-reference

#4807 USHIFT-5593: Revert bootc image builder to non-eus rhel9
  test/bin/pyutils/build_bootc_images.py
Labels: lgtm, approved, jira/valid-reference

#4780 USHIFT-5561: Introduce e2e scenarios for telemetry
  cmd/generate-config/config/config-openapi-spec.json
  docs/user/howto_config.md
  packaging/microshift/config.yaml
  pkg/config/telemetry.go
  pkg/telemetry/telemetry.go
  test/bin/ci_phase_boot_and_test.sh
  test/bin/manage_prometheus.sh
  test/resources/microshift-host.resource
  test/resources/prometheus.py
  test/scenarios-bootc/periodics/el96-src@telemetry.sh
  test/suites/osconfig/clusterid.robot
  test/suites/telemetry/telemetry.robot
Labels: lgtm, approved, jira/valid-reference

#4812 [release-4.17] NO-ISSUE: Remove failed rebase log
  rebase_sh.log
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4821 USHIFT-5621: qemu-ga tweaks: add timeouts, increase read file buffer, use subprocess lib
  test/bin/scenario.sh
  test/resources/qemu-guest-agent.py
Labels: lgtm, approved, jira/valid-reference

#4806 USHIFT-5571: Remove observability preset that enables the service automatically
  packaging/observability/90-enable-microshift-observability.preset
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#4824 NO-ISSUE: Relax requirements for observability line count tests
  test/suites/optional/observability.robot
Labels: lgtm, approved, jira/valid-reference

#4804 USHIFT-5544: OTEL/observability: scrape Pods' metrics
  docs/user/ai_model_serving.md
  packaging/observability/opentelemetry-collector-large.yaml
Labels: lgtm, approved, jira/valid-reference

#4820 USHIFT-5624: Rebase AI Model Serving to use RHOAI 2.19
  assets/optional/ai-model-serving/kserve/configmap/inferenceservice.yaml
  assets/optional/ai-model-serving/kserve/inferenceservice-config-microshift-patch.yaml
  assets/optional/ai-model-serving/kserve/overlays/odh/inferenceservice-config-patch.yaml
  assets/optional/ai-model-serving/kserve/overlays/odh/params.env
  assets/optional/ai-model-serving/release-ai-model-serving-x86_64.json
  assets/optional/ai-model-serving/runtimes/kustomization.x86_64.yaml
  assets/optional/ai-model-serving/runtimes/vllm-gaudi.yaml
  assets/optional/ai-model-serving/runtimes/vllm-rocm.yaml
  scripts/auto-rebase/last_rebase_ai_model_serving.sh
  scripts/auto-rebase/rebase-lvms.sh
  scripts/auto-rebase/rebase.sh
  scripts/auto-rebase/rebase_ai_model_serving.sh
  scripts/auto-rebase/rebase_gateway_api.sh
Labels: lgtm, approved, jira/valid-reference

#4726 USHIFT-5531: Auto-rebase procedure with flannel and kube-proxy image update
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#4837 NO-ISSUE: Fix vllm cuda image after RHOAI 2.19
  scripts/ci-ai-model-serving/tests/06-test-vllm.sh
Labels: lgtm, approved, jira/valid-reference

#4838 NO-ISSUE: temporary disable for crel tests in 4.19+
  test/scenarios-bootc/periodics/el96-crel@brew-standard1.sh.disabled
  test/scenarios-bootc/periodics/el96-crel@brew-standard2.sh.disabled
  test/scenarios-bootc/periodics/el96-crel@optional-sigstore.sh.disabled
  test/scenarios/periodics/el94-crel@optional-sigstore.sh.disabled
Labels: lgtm, approved, jira/valid-reference
