Repository openshift/microshift, pull requests merged in 2025-05, with the labels that each got.

#4860 NO-ISSUE: Bring back rhoai 2.19
  assets/optional/ai-model-serving/kserve/configmap/inferenceservice.yaml
  assets/optional/ai-model-serving/kserve/inferenceservice-config-microshift-patch.yaml
  assets/optional/ai-model-serving/kserve/overlays/odh/inferenceservice-config-patch.yaml
  assets/optional/ai-model-serving/kserve/overlays/odh/params.env
  assets/optional/ai-model-serving/release-ai-model-serving-x86_64.json
  assets/optional/ai-model-serving/runtimes/kustomization.x86_64.yaml
  assets/optional/ai-model-serving/runtimes/vllm-gaudi.yaml
  assets/optional/ai-model-serving/runtimes/vllm-rocm.yaml
  scripts/auto-rebase/last_rebase_ai_model_serving.sh
  scripts/auto-rebase/rebase_job_entrypoint.sh
Labels: lgtm, approved, jira/valid-reference

#4863 USHIFT-5578: remove upstream/okd directory
  README.md
  okd/gh-workflows/README.md
  okd/gh-workflows/build-upstream-rpms-only.png
  okd/gh-workflows/microshift-build-example.yaml
  okd/gh-workflows/run-in-bootc-container.png
  okd/src/README.md
  okd/src/configure.sh
  okd/src/create_repos.sh
  okd/src/etcd/README.md
  okd/src/etcd/microshift-etcd-postgres.sh
  okd/src/etcd/microshift-etcd-sqlite.sh
  okd/src/microshift-okd-build-rpms.Containerfile
  okd/src/microshift-okd-multi-build.Containerfile
  okd/src/microshift-okd-run.Containerfile
  okd/src/use_okd_assets.sh
  okd/storage/README.md
  okd/storage/hostpath/00-psql-namespace.yaml
  okd/storage/hostpath/01-pv-volume.yaml
  okd/storage/hostpath/02-pvc-volume.yaml
  okd/storage/hostpath/03-psql-service.yaml
  okd/storage/hostpath/04-psql-deployment.yaml
  okd/storage/hostpath/kustomization.yaml
  okd/storage/topolvm/example-psql/01-psql-namespace.yaml
  okd/storage/topolvm/example-psql/02-pvc-volume.yaml
  okd/storage/topolvm/example-psql/03-psql-service.yaml
  okd/storage/topolvm/example-psql/04-psql-deployment.yaml
  okd/storage/topolvm/prepare_topolvm_manifests.sh
Labels: lgtm, approved, jira/valid-reference

#4866 [release-4.19] NO-ISSUE: Bring back rhoai 2.19
  assets/optional/ai-model-serving/kserve/configmap/inferenceservice.yaml
  assets/optional/ai-model-serving/kserve/inferenceservice-config-microshift-patch.yaml
  assets/optional/ai-model-serving/kserve/overlays/odh/inferenceservice-config-patch.yaml
  assets/optional/ai-model-serving/kserve/overlays/odh/params.env
  assets/optional/ai-model-serving/release-ai-model-serving-x86_64.json
  assets/optional/ai-model-serving/runtimes/kustomization.x86_64.yaml
  assets/optional/ai-model-serving/runtimes/vllm-gaudi.yaml
  assets/optional/ai-model-serving/runtimes/vllm-rocm.yaml
  scripts/auto-rebase/last_rebase_ai_model_serving.sh
  scripts/auto-rebase/rebase_job_entrypoint.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4825 USHIFT-5369: Add 2 RF Observability test cases
  test/assets/observability/otel_config.yaml
  test/bin/ci_phase_boot_and_test.sh
  test/bin/manage_loki.sh
  test/bin/manage_prometheus.sh
  test/bin/scenario.sh
  test/resources/journalctl.py
  test/resources/loki.py
  test/resources/prometheus.py
  test/scenarios-bootc/periodics/cos9-src@optional.sh
  test/scenarios-bootc/presubmits/el96-src@optional.sh
  test/scenarios/periodics/el94-src@optional.sh
  test/suites/optional/observability.robot
Labels: lgtm, approved, jira/valid-reference

#4743 Add Fault Tests
  test/bin/stress_testing.sh
  test/resources/fault-test-messages.yaml
  test/resources/fault-tests.resource
  test/resources/kubeconfig.resource
  test/resources/microshift-host.resource
  test/resources/oc.resource
  test/scenarios-bootc/periodics/el96-src@fault-tests.sh
  test/suites/fault-tests/outages.robot
  test/suites/standard2/configuration.robot
  test/suites/standard2/tls-configuration.robot
Labels: lgtm, approved

#4813 USHIFT-5528: Add new option to scenario.sh to target any given VM
  test/bin/scenario.sh
  test/scenario_settings.sh.example
Labels: lgtm, approved, jira/valid-reference

#4870 USHIFT-5712: Snyk fixes
  pkg/cmd/init.go
  pkg/controllers/kube-controller-manager.go
  pkg/controllers/kube-controller-manager_test.go
  pkg/controllers/kube-scheduler.go
  pkg/util/net.go
Labels: lgtm, approved, jira/valid-reference

#4874 USHIFT-5528: Add documentation on how to target any given VM
  test/README.md
Labels: lgtm, approved, jira/valid-reference

#4823 Configure internal RHEL 9.6 repos for osbuild.
  scripts/devenv-builder/configure-composer.sh
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved

#4769 USHIFT-2575: add 2 telemetry test cases
  test/bin/ci_phase_boot_and_test.sh
  test/resources/observability.resource
  test/resources/prometheus.py
  test/suites/optional/observability.robot
  test/suites/telemetry/telemetry.robot
Labels: lgtm, approved, jira/valid-reference

#4887 [release-4.19] USHIFT-2575: add 2 telemetry test cases
  test/bin/ci_phase_boot_and_test.sh
  test/resources/observability.resource
  test/resources/prometheus.py
  test/suites/optional/observability.robot
  test/suites/telemetry/telemetry.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4889 USHIFT-5660: Ingress access logging implementation and tests
  assets/components/openshift-router/configmap-accesslog.yaml
  assets/components/openshift-router/deployment.yaml
  cmd/generate-config/config/config-openapi-spec.json
  docs/user/howto_config.md
  packaging/microshift/config.yaml
  pkg/components/controllers.go
  pkg/config/config.go
  pkg/config/ingress.go
  scripts/auto-rebase/assets.yaml
  scripts/auto-rebase/manifests_patches/010-ingress-deployment-clientCA.patch
  scripts/auto-rebase/manifests_patches/011-ingress-deployment-access-logging.patch
  scripts/verify/verify-rf.sh
  test/assets/network/router-error-configmap.yaml
  test/suites/standard1/router.robot
Labels: lgtm, approved, jira/valid-reference

#4899 USHIFT-5638: Start using sonobuoy v0.57.3
  test/bin/common_versions.sh
  test/scenarios-bootc/periodics/el96-src@cncf-conformance.sh
  test/scenarios/periodics/el94-src@cncf-conformance.sh
Labels: lgtm, approved, jira/valid-reference

#4915 USHIFT-5741: Add syslog configuration to ingress access logging
  assets/components/openshift-router/deployment.yaml
  cmd/generate-config/config/config-openapi-spec.json
  docs/user/howto_config.md
  etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/ingress.go
  etcd/vendor/github.com/openshift/microshift/pkg/util/net.go
  packaging/microshift/config.yaml
  pkg/components/controllers.go
  pkg/config/config.go
  pkg/config/ingress.go
  scripts/auto-rebase/manifests_patches/011-ingress-deployment-access-logging.patch
  test/scenarios-bootc/presubmits/el96-src@router.sh
  test/scenarios/presubmits/el94-src@router.sh
  test/suites/router/router.robot
Labels: lgtm, approved, jira/valid-reference

#4924 USHIFT-5763: file naming issue in config-operator scc
  scripts/auto-rebase/assets.yaml
Labels: lgtm, approved, jira/valid-reference

#4913 OCPBUGS-56260: bump to openvswitch version 3.5
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4936 USHIFT-5772: explicitly specify kernel path when running virt-install
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#4937 [release-4.19] USHIFT-5773: explicitly specify kernel path when running virt-install
  test/bin/scenario.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4938 OCPBUGS-56497: Avoid port collisions in prometheus/loki RF
  test/bin/manage_loki.sh
  test/bin/manage_prometheus.sh
  test/resources/observability.resource
  test/scenarios-bootc/periodics/cos9-src@optional.sh
  test/scenarios-bootc/presubmits/el96-src@optional.sh
  test/scenarios/periodics/el94-src@optional.sh
  test/suites/optional/observability.robot
  test/suites/telemetry/telemetry.robot
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4929 [release-4.19] NO-ISSUE: Update common_versions.sh -> RC
  test/bin/common_versions.sh
  test/resources/journalctl.py
  test/scenarios-bootc/periodics/el96-crel@published-images-standard1.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4930 NO-ISSUE: Update common_versions.sh -> RC
  test/bin/common_versions.sh
  test/resources/journalctl.py
  test/scenarios-bootc/periodics/el96-crel@published-images-standard1.sh
Labels: lgtm, approved, jira/valid-reference

#4946 [release-4.19] USHIFT-5775: TLS config RF test: skip cipher if not available
  test/suites/standard2/configuration.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4903 OCPBUGS-56157: Use large OTEL config example as default + descriptions tweaks
  packaging/observability/opentelemetry-collector-large.yaml
  packaging/observability/opentelemetry-collector-medium.yaml
  packaging/observability/opentelemetry-collector-small.yaml
  packaging/observability/opentelemetry-collector.yaml
  packaging/rpm/microshift.spec
  test/suites/optional/observability.robot
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4927 USHIFT-5480: Rebase RHOAI to 2.20
  assets/optional/ai-model-serving/kserve/inferenceservice-config-microshift-patch.yaml
  assets/optional/ai-model-serving/kserve/overlays/odh/inferenceservice-config-patch.yaml
  assets/optional/ai-model-serving/kserve/overlays/odh/params.env
  assets/optional/ai-model-serving/kserve/rbac/role.yaml
  assets/optional/ai-model-serving/release-ai-model-serving-x86_64.json
  assets/optional/ai-model-serving/runtimes/kustomization.x86_64.yaml
  scripts/auto-rebase/last_rebase_ai_model_serving.sh
  scripts/auto-rebase/rebase_ai_model_serving.sh
  scripts/auto-rebase/rebase_job_entrypoint.sh
  test/suites/ai-model-serving/ai-model-serving-offline.robot
Labels: lgtm, approved, jira/valid-reference

#4955 NO-ISSUE: Remove fixed node port from hello-microshift service in RF
  test/resources/microshift-network.resource
  test/suites/network/multi-nic.robot
Labels: lgtm, approved, jira/valid-reference

#4958 USHIFT-5778: Fix ordering in router security RF tests
  test/suites/router/router.robot
Labels: lgtm, approved, jira/valid-reference

#4968 [release-4.19] USHIFT-5778: Stop excluding router security tests
  test/suites/standard1/router.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4974 [release-4.18] NO-ISSUE: cncf - skip test that frequently gets stuck
  test/scenarios-bootc/periodics/el94-src@cncf-conformance.sh
  test/scenarios/periodics/el94-src@cncf-conformance.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
