Repository openshift/microshift, pull requests merged in 2025-02, with the labels that each got.

#4494 NO-ISSUE: okd: Add read permission to /etc/shadow
  okd/src/microshift-okd-multi-build.Containerfile
Labels: lgtm, approved, jira/valid-reference

#4508 NO-ISSUE: rebase-main-4.19.0-0.nightly-2025-01-30-091858_amd64-2025-01-30_arm64-2025-02-03
  Makefile.version.aarch64.var
  assets/core/kubelet.yaml
  assets/optional/multus/release-multus-aarch64.json
  assets/optional/operator-lifecycle-manager/release-olm-aarch64.json
  assets/release/release-aarch64.json
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/last_rebase.sh
  scripts/auto-rebase/rebase.sh
Labels: lgtm, approved, jira/valid-reference

#4449 USHIFT-5342: Extra debug for CNCF scenarios
  test/scenarios-bootc/periodics/el95-src@cncf-conformance.sh
  test/scenarios/periodics/el94-src@cncf-conformance.sh
Labels: lgtm, approved, jira/valid-reference

#4479 USHIFT-2596: improve TLS config cipher RF test cases
  test/resources/microshift-config.resource
  test/suites/standard1/show-config.robot
  test/suites/standard2/configuration.robot
Labels: lgtm, approved, jira/valid-reference

#4505 USHIFT-5359: Remove conformance skips for 1.32
  origin/skip.txt
Labels: lgtm, approved, jira/valid-reference

#4516 USHIFT-5350: Enable public Quay repository creation on push
  test/bin/mirror_registry.sh
Labels: lgtm, approved, jira/valid-reference

#4504 OCPBUGS-48163: Atomic nodename file
  pkg/admin/autorecovery/state.go
  pkg/admin/data/atomic_dir_copy.go
  pkg/config/node.go
  pkg/util/util.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4483 USHIFT-5281: Implement MicroShift CI image build rules and docs
  packaging/images/Containerfile.ci-brew
  packaging/images/Makefile
  packaging/images/README.md
Labels: lgtm, approved, jira/valid-reference

#4522 NO-ISSUE: skip tls 1.2 cipher configuration tests
  test/suites/standard2/configuration.robot
Labels: lgtm, approved, jira/valid-reference

#4523 USHIFT-5367: Increase the max_connections setting of Postgres to improve mirror registry stability
  test/bin/mirror_registry.sh
Labels: lgtm, approved, jira/valid-reference

#4534 USHIFT-5293: Early quit for microshift greenboot scripts
  packaging/greenboot/functions.sh
  packaging/greenboot/microshift-running-check-gateway-api.sh
  packaging/greenboot/microshift-running-check-multus.sh
  packaging/greenboot/microshift-running-check-olm.sh
  packaging/greenboot/microshift-running-check.sh
Labels: lgtm, approved, jira/valid-reference

#4535 [release-4.18] USHIFT-5379: Early quit for microshift greenboot scripts
  packaging/greenboot/functions.sh
  packaging/greenboot/microshift-running-check-gateway-api.sh
  packaging/greenboot/microshift-running-check-multus.sh
  packaging/greenboot/microshift-running-check-olm.sh
  packaging/greenboot/microshift-running-check.sh
Labels: lgtm, approved, cherry-pick-approved, staff-eng-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4531 USHIFT-5352: Use EUS bootc base images and prevent unintended OS version upgrade
  docs/config/Containerfile.bootc-rhel9
  docs/contributor/image_mode.md
  packaging/imagemode/Containerfile.repobase
  packaging/imagemode/Containerfile.repourl
  packaging/imagemode/Containerfile.rhocp
  packaging/imagemode/Makefile
  packaging/imagemode/README.md
  test/image-blueprints-bootc/layer1-base/group1/rhel94-bootc-base.containerfile
  test/image-blueprints-bootc/layer1-base/group1/rhel94-test-agent.containerfile
  test/scenarios-bootc-containers/presubmits/el95-src@standard-suite1.sh
  test/scenarios-bootc/periodics/el94-crel@published-images-standard1.sh
  test/scenarios-bootc/periodics/el94-crel@published-images-standard2.sh
  test/scenarios-bootc/periodics/el95-crel@optional-sigstore.sh
  test/scenarios-bootc/presubmits/cos9-src@standard-suite1.sh
  test/scenarios-bootc/presubmits/el95-src@standard-suite1.sh
  test/scenarios/periodics/el94-crel@optional-sigstore.sh
  test/scenarios/periodics/el94-src@rpm-standard1.sh
  test/scenarios/presubmits/el94-src@standard-suite1.sh
  test/suites/standard1/version.robot
Labels: lgtm, approved, jira/valid-reference

#4541 NO-ISSUE: Update RPM descriptions to mention bootc containerfiles
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#4539 USHIFT-5201: Add new RPM with AI Model Serving for MicroShift
  packaging/greenboot/microshift-running-check-ai-model-serving.sh
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#4548 USHIFT-5391: Add systemd-resolved to the bootc optionals image
  test/image-blueprints-bootc/layer2-source/group2/rhel95-bootc-source-optionals.containerfile
  test/image-blueprints-bootc/layer2-source/group3/cos9-bootc-source-optionals.containerfile
Labels: lgtm, approved, jira/valid-reference

#4542 [release-4.18] USHIFT-5352: Use EUS bootc base images and prevent unintended OS version upgrade
  docs/config/Containerfile.bootc-rhel9
  docs/contributor/image_mode.md
  packaging/imagemode/Containerfile.repobase
  packaging/imagemode/Containerfile.repourl
  packaging/imagemode/Containerfile.rhocp
  packaging/imagemode/Makefile
  packaging/imagemode/README.md
  test/image-blueprints-bootc/layer1-base/group1/rhel94-bootc-base.containerfile
  test/image-blueprints-bootc/layer1-base/group1/rhel94-test-agent.containerfile
  test/scenarios-bootc-containers/presubmits/el94-src@standard-suite1.sh
  test/scenarios-bootc/periodics/el94-crel@published-images-standard1.sh
  test/scenarios-bootc/presubmits/cos9-src@standard-suite1.sh
  test/scenarios-bootc/presubmits/el94-src@standard-suite1.sh
  test/scenarios/periodics/el94-crel@optional-sigstore.sh
  test/scenarios/periodics/el94-src@rpm-standard1.sh
  test/scenarios/presubmits/el94-src@standard-suite1.sh
  test/suites/standard1/version.robot
Labels: lgtm, approved, cherry-pick-approved, staff-eng-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4553 USHIFT-5391: Add systemd-resolved to bootc source images
  test/image-blueprints-bootc/layer2-source/group1/cos9-bootc-source.containerfile
  test/image-blueprints-bootc/layer2-source/group1/rhel95-bootc-source.containerfile
  test/image-blueprints-bootc/layer2-source/group2/rhel95-bootc-source-optionals.containerfile
  test/image-blueprints-bootc/layer2-source/group3/cos9-bootc-source-optionals.containerfile
Labels: lgtm, approved, jira/valid-reference

#4555 [release-4.17] USHIFT-5391: Add systemd-resolved to source bootc images
  test/image-blueprints/layer5-bootc/group1/cos9-bootc-source.containerfile
  test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source-ostree-parent.containerfile
  test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source.containerfile
  test/suites/osconfig/systemd-resolved.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4556 USHIFT-5391: Optimize systemd-resolved package uninstallation
  test/suites/osconfig/systemd-resolved.robot
Labels: lgtm, approved, jira/valid-reference

#4554 [release-4.18] USHIFT-5391: Add systemd-resolved to bootc source images
  test/image-blueprints-bootc/layer2-source/group1/cos9-bootc-source.containerfile
  test/image-blueprints-bootc/layer2-source/group1/rhel94-bootc-source.containerfile
  test/suites/osconfig/systemd-resolved.robot
Labels: lgtm, approved, cherry-pick-approved, staff-eng-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4571 USHIFT-5402: Test harness VM IP address robustness
  scripts/devenv-builder/manage-vm.sh
  test/bin/scenario.sh
  test/scenarios-bootc/presubmits/el95-src@dual-stack.sh
Labels: lgtm, approved, jira/valid-reference

#4565 [release-4.14] USHIFT-4867: error in microshift RF tests randomize parameter
  test/run.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4563 [release-4.15] USHIFT-4867: error in microshift RF tests randomize parameter
  test/run.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4569 NO-ISSUE: Enable flannel RPM build by default in build_rpms.sh
  test/bin/build_rpms.sh
  test/bin/ci_phase_iso_build.sh
Labels: lgtm, approved, jira/valid-reference

#4596 OCPBUGS-51184: Remove MicroShift Greenboot Fail Marker on first check start
  packaging/greenboot/functions.sh
  packaging/greenboot/microshift-running-check.sh
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4586 USHIFT-5402: Handle DUID in ipv6 test harness
  test/kickstart-templates/includes/post-network.cfg
Labels: lgtm, approved, jira/valid-reference

#4593 USHIFT-5378: Reenable TLS 1.2 tests
  test/suites/standard2/configuration.robot
Labels: lgtm, approved, jira/valid-reference

#4594 [release-4.18] USHIFT-5435: Handle DUID for ipv6 CI tests
  scripts/devenv-builder/manage-vm.sh
  test/bin/scenario.sh
  test/kickstart-templates/includes/post-network.cfg
  test/scenarios-bootc/presubmits/el94-src@dual-stack.sh
Labels: lgtm, approved, cherry-pick-approved, staff-eng-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4572 USHIFT-5281: Implement brew configuration and package management procedures
  packaging/images/Containerfile.ci-brew
  packaging/images/Makefile
  packaging/images/README.md
  scripts/fetch_tools.sh
  test/bin/build_rpms.sh
  test/bin/ci_phase_iso_build.sh
  test/bin/common.sh
  test/bin/manage_brew_rpms.sh
  test/bin/manage_build_cache.sh
  test/bin/pyutils/build_bootc_images.py
  test/image-blueprints-bootc/layer1-base/group2/rhel95-bootc-brew.containerfile
  test/package-sources-bootc/microshift-brew.repo
  test/scenarios-bootc/periodics/el95-crel@brew-standard1.sh
  test/scenarios-bootc/periodics/el95-crel@brew-standard2.sh
Labels: lgtm, approved, jira/valid-reference

#4600 USHIFT-5401: Add telemetry configuration parameters
  cmd/generate-config/config/config-openapi-spec.json
  docs/user/howto_config.md
  packaging/microshift/config.yaml
  pkg/config/config.go
  pkg/config/telemetry.go
  test/kickstart-templates/includes/post-microshift.cfg
Labels: lgtm, approved, jira/valid-reference

#4602 OCPBUGS-51186: skip installing ai-model and low-latency optional RPMs
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4604 USHIFT-5288: Mirroring of images in CI should be performed for the current platform only
  scripts/mirror-images.sh
  test/bin/pyutils/build_bootc_images.py
  test/bin/pyutils/common.py
Labels: lgtm, approved, jira/valid-reference

#4611 OCPBUGS-51366: Sort interfaces by index
  pkg/util/net.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference
