Repository openshift/microshift, pull requests merged in 2025-06, with the labels that each got.

#4931 USHIFT-5714 update lvm-o bundle to the 4.18.2-2 in prep for 4.19.
  assets/components/lvms/lvm.topolvm.io_lvmclusters.yaml
  assets/components/lvms/lvm.topolvm.io_lvmvolumegroupnodestatuses.yaml
  assets/components/lvms/lvm.topolvm.io_lvmvolumegroups.yaml
  assets/components/lvms/lvms-operator_rbac.authorization.k8s.io_v1_clusterrole.yaml
  assets/components/lvms/topolvm-configmap_lvms-version.yaml
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  scripts/auto-rebase/last_lvms_rebase.sh
Labels: lgtm, approved

#4994 NO-ISSUE: rebase-main-4.20.0-0.nightly-2025-05-29-041615_amd64-2025-05-29_arm64-2025-06-01
  Makefile.kube_git.var
  Makefile.version.aarch64.var
  Makefile.version.x86_64.var
  assets/components/multus/kustomization.aarch64.yaml
  assets/components/multus/kustomization.x86_64.yaml
  assets/components/multus/release-multus-aarch64.json
  assets/components/multus/release-multus-x86_64.json
  assets/crd/0000_03_config-operator_01_securitycontextconstraints.crd.yaml
  assets/optional/kube-proxy/kustomization.aarch64.yaml
  assets/optional/kube-proxy/kustomization.x86_64.yaml
  assets/optional/kube-proxy/release-kube-proxy-aarch64.json
  assets/optional/kube-proxy/release-kube-proxy-x86_64.json
  assets/optional/operator-lifecycle-manager/0000_50_olm_00-catalogsources.crd.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_01-networkpolicies.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_02-olm-operator.serviceaccount.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_03-olmconfig.yaml
  assets/optional/operator-lifecycle-manager/0000_50_olm_03-services.yaml
  assets/optional/operator-lifecycle-manager/kustomization.aarch64.yaml
  assets/optional/operator-lifecycle-manager/kustomization.x86_64.yaml
  assets/optional/operator-lifecycle-manager/kustomization.yaml
  assets/optional/operator-lifecycle-manager/release-olm-aarch64.json
  assets/optional/operator-lifecycle-manager/release-olm-x86_64.json
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  etcd/go.mod
  etcd/go.sum
  etcd/vendor/k8s.io/client-go/util/cert/cert.go
  etcd/vendor/modules.txt
  go.mod
  go.sum
  packaging/crio.conf.d/10-microshift_amd64.conf
  packaging/crio.conf.d/10-microshift_arm64.conf
  scripts/auto-rebase/assets.yaml
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/commits.txt
  scripts/auto-rebase/last_rebase.sh
  test/bin/common_versions.sh
  vendor/k8s.io/apiserver/pkg/server/options/serving_with_loopback.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/watcher.go
  vendor/k8s.io/client-go/util/cert/cert.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/filters/apirequestcount/deprecated.go
  vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
  vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/node_expander.go
  vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go
  vendor/k8s.io/kubernetes/pkg/volume/util/resize_util.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#5000 USHIFT-5774: skip checking non-core pods from being annotated
  test/suites/tuned/workload-partitioning.robot
Labels: lgtm, approved, jira/valid-reference

#5018 NO-ISSUE: Add teardown for "Router Disabled" test
  test/suites/router/router.robot
Labels: lgtm, approved, jira/valid-reference

#4998 USHIFT-5816: SubMgr: register force & get 'status' output
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#5023 [release-4.19] NO-ISSUE: Bump kubelet
  scripts/multinode/configure-sec.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#5024 NO-ISSUE: Fix initial ref for upgrade-ostree2bootc test
  test/bin/subscription_manager_register.sh
  test/scenarios-bootc/periodics/el96-prel@el96-src@upgrade-ostree2bootc-ok.sh
Labels: lgtm, approved, jira/valid-reference

#5054 USHIFT-5820: Bump cri-o version to 1.33.0
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#5053 USHIFT-5817: RHEL 9.6 upgrade scenarios
  test/image-blueprints-bootc/layer1-base/group2/rhel96-bootc-prel.containerfile
  test/scenarios-bootc/periodics/el96-prel@el96-crel@upgrade-ok.sh
  test/scenarios-bootc/periodics/el96-prel@el96-src@upgrade-fails-and-rolls-back.sh
  test/scenarios-bootc/presubmits/el94-prel@el96-src@upgrade-ok.sh
  test/scenarios-bootc/presubmits/el96-prel@el96-src@upgrade-ok.sh
Labels: lgtm, approved, jira/valid-reference

#5085 [release-4.19] OCPBUGS-57789: Fix signature checking in CI hypervisor
  test/bin/mirror_registry.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4900 USHIFT-5397: [QE] Replace MicroShift build images phase with dev scripts
  test/bin/build_rpms.sh
  test/bin/manage_brew_rpms.sh
Labels: lgtm, approved, jira/valid-reference

#5076 [release-4.19] USHIFT-5627: Start using 4.19 released repos in common_versions.sh
  test/bin/common_versions.sh
  test/scenarios-bootc/periodics/el96-crel@brew-standard1.sh
  test/scenarios-bootc/periodics/el96-crel@brew-standard2.sh
  test/scenarios-bootc/periodics/el96-crel@optional-sigstore.sh
  test/scenarios/periodics/el94-crel@optional-sigstore.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#5098 NO-ISSUE: rebase-main-4.20.0-0.nightly-2025-06-20-214016_amd64-2025-06-20_arm64-2025-06-23
  Makefile.kube_git.var
  Makefile.version.aarch64.var
  Makefile.version.x86_64.var
  assets/components/multus/kustomization.aarch64.yaml
  assets/components/multus/kustomization.x86_64.yaml
  assets/components/multus/release-multus-aarch64.json
  assets/components/multus/release-multus-x86_64.json
  assets/controllers/kube-apiserver/defaultconfig.yaml
  assets/optional/kube-proxy/kustomization.aarch64.yaml
  assets/optional/kube-proxy/kustomization.x86_64.yaml
  assets/optional/kube-proxy/release-kube-proxy-aarch64.json
  assets/optional/kube-proxy/release-kube-proxy-x86_64.json
  assets/optional/operator-lifecycle-manager/kustomization.aarch64.yaml
  assets/optional/operator-lifecycle-manager/kustomization.x86_64.yaml
  assets/optional/operator-lifecycle-manager/release-olm-aarch64.json
  assets/optional/operator-lifecycle-manager/release-olm-x86_64.json
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  deps/github.com/openshift/kubernetes/openshift-hack/cmd/k8s-tests-ext/disabled_tests.go
  deps/github.com/openshift/kubernetes/openshift-hack/cmd/k8s-tests-ext/k8s-tests.go
  deps/github.com/openshift/kubernetes/staging/src/k8s.io/apimachinery/third_party/forked/golang/json/fields.go
  deps/github.com/openshift/kubernetes/staging/src/k8s.io/client-go/third_party/forked/golang/template/exec.go
  deps/github.com/openshift/kubernetes/staging/src/k8s.io/client-go/third_party/forked/golang/template/funcs.go
  deps/github.com/openshift/kubernetes/staging/src/k8s.io/code-generator/third_party/forked/golang/reflect/type.go
  deps/github.com/openshift/kubernetes/test/e2e/common/node/security_context.go
  etcd/go.mod
  etcd/go.sum
  etcd/vendor/github.com/openshift/build-machinery-go/.ci-operator.yaml
  etcd/vendor/github.com/openshift/build-machinery-go/Dockerfile.commitchecker
  etcd/vendor/github.com/openshift/build-machinery-go/make/targets/golang/verify-update.mk
  etcd/vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yq.mk
  etcd/vendor/github.com/openshift/microshift/pkg/config/ingress.go
  etcd/vendor/github.com/openshift/microshift/pkg/config/node.go
  etcd/vendor/github.com/openshift/microshift/pkg/util/cryptomaterial/trustupdates.go
  etcd/vendor/github.com/openshift/microshift/pkg/util/net.go
  etcd/vendor/github.com/openshift/microshift/pkg/util/util.go
  etcd/vendor/k8s.io/apimachinery/third_party/forked/golang/json/fields.go
  etcd/vendor/k8s.io/client-go/third_party/forked/golang/template/exec.go
  etcd/vendor/k8s.io/client-go/third_party/forked/golang/template/funcs.go
  etcd/vendor/modules.txt
  go.mod
  go.sum
  packaging/crio.conf.d/10-microshift_amd64.conf
  packaging/crio.conf.d/10-microshift_arm64.conf
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/commits.txt
  scripts/auto-rebase/last_rebase.sh
  scripts/auto-rebase/rebase.sh
  vendor/github.com/openshift/build-machinery-go/.ci-operator.yaml
  vendor/github.com/openshift/build-machinery-go/Dockerfile.commitchecker
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/verify-update.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yq.mk
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#5107 [release-4.18] OCPBUGS-58139: Upgrade openvswitch package to 3.5.
  packaging/rpm/microshift.spec
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
