Repository openshift/microshift, pull requests merged in 2025-07, with the labels that each got.

#5120 OCPBUGS-57777: Change poll interval for first metrics send
  pkg/controllers/telemetry.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#5119 [release-4.18] NO-ISSUE: Add timeout limits to isolated-network tests
  test/suites/network/isolated-network.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#5117 NO-ISSUE: Add timeout limits to isolated-network tests
  test/suites/network/isolated-network.robot
Labels: lgtm, approved, jira/valid-reference

#5074 USHIFT-5805: Add zstd:chunked demonstrator script
  scripts/verify/verify-py.sh
  scripts/zstd/images.py
  scripts/zstd/summary.sh
Labels: lgtm, approved, jira/valid-reference

#5124 USHIFT-5794: Improvements to Generic Device Plugin configuration
  cmd/generate-config/config/config-openapi-spec.json
  docs/user/howto_config.md
  packaging/microshift/config.yaml
  pkg/config/gdp.go
  pkg/config/gdp_test.go
  pkg/gdp/gdp.go
Labels: lgtm, approved, jira/valid-reference

#5142 USHIFT-5864: Disable ai-model-serving-offline scenario until crio 1.33 is supported
  test/scenarios-bootc/periodics/el96-src@ai-model-serving-offline.sh.disabled
Labels: lgtm, approved, jira/valid-reference

#5144 [release-4.18] USHIFT-5527: Revert Skip 'default config' test on crel
  test/scenarios-bootc/periodics/el94-crel@published-images-standard2.sh
  test/suites/standard2/configuration.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#5145 [release-4.19] USHIFT-5879: Renable default config test on for the current release
  test/scenarios-bootc/periodics/el96-crel@published-images-standard2.sh
  test/suites/standard2/configuration.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#5143 USHIFT-5526: Renable default config test on for the current release
  test/scenarios-bootc/periodics/el96-crel@published-images-standard2.sh
  test/suites/standard2/configuration.robot
Labels: lgtm, approved, jira/valid-reference

#5155 [release-4.18] OCPBUGS-58442: Fix subscription-manager registration command not to use sudo directly
  test/bin/subscription_manager_register.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#5159 [release-4.14] OCPBUGS-58447: Fix subscription-manager registration command not to use sudo directly
  test/bin/subscription_manager_register.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#5160 USHIFT-5620: Create scripts for testing NVIDIA Device Plugin
  scripts/ci-ai-model-serving/setup/00-debug.sh
  scripts/ci-ai-model-serving/setup/02-nvidia-driver.sh
  scripts/ci-ai-model-serving/setup/03-nvidia-container-toolkit.sh
  scripts/ci-ai-model-serving/setup/04-nvidia-device-plugin.sh
  scripts/ci-ai-model-serving/setup/05-debug.sh
  scripts/ci-ai-model-serving/tests/01-verify-nvidia-gpu.sh
  scripts/ci-ai-model-serving/tests/02-wait-for-greenboot.sh
  scripts/ci-ai-model-serving/tests/03-get-kubeconfig.sh
  scripts/ci-ai-model-serving/tests/04-verify-device-plugin.sh
  scripts/ci-ai-model-serving/tests/05-test-cuda-vector-add.sh
  scripts/ci-nvidia-device-plugin/1-setup.sh
  scripts/ci-nvidia-device-plugin/2-reboot.sh
  scripts/ci-nvidia-device-plugin/3-test.sh
  scripts/ci-nvidia-device-plugin/setup/00-debug.sh
  scripts/ci-nvidia-device-plugin/setup/01-microshift.sh
  scripts/ci-nvidia-device-plugin/setup/02-nvidia-driver.sh
  scripts/ci-nvidia-device-plugin/setup/03-nvidia-container-toolkit.sh
  scripts/ci-nvidia-device-plugin/setup/04-nvidia-device-plugin.sh
  scripts/ci-nvidia-device-plugin/setup/05-debug.sh
  scripts/ci-nvidia-device-plugin/tests/01-verify-nvidia-gpu.sh
  scripts/ci-nvidia-device-plugin/tests/02-wait-for-greenboot.sh
  scripts/ci-nvidia-device-plugin/tests/03-get-kubeconfig.sh
  scripts/ci-nvidia-device-plugin/tests/04-verify-device-plugin.sh
  scripts/ci-nvidia-device-plugin/tests/05-test-cuda-vector-add.sh
Labels: lgtm, approved, jira/valid-reference

#5167 USHIFT-5897: Observability test: remove debug exporter and journal log matching
  test/assets/observability/otel_config.yaml
  test/suites/optional/observability.robot
Labels: lgtm, approved, jira/valid-reference

#5168 USHIFT-5818: Generic Device Plugin - fixes for periodic jobs
  test/image-blueprints-bootc/layer2-presubmit/group2/rhel96-bootc-source-optionals.containerfile
  test/image-blueprints-bootc/layer3-periodic/group3/cos9-bootc-source-optionals.containerfile
  test/scenarios/periodics/el96-src@optional.sh
  test/suites/optional/generic-device-plugin.robot
Labels: lgtm, approved, jira/valid-reference

#5169 USHIFT-5898: Improve GDP config validation
  cmd/generate-config/config/config-openapi-spec.json
  packaging/microshift/config.yaml
  pkg/config/gdp.go
  pkg/config/gdp_test.go
Labels: lgtm, approved, jira/valid-reference

#5183 [release-4.19] NO-ISSUE: Bump CNCF K8s ver to 1.32.6
  scripts/multinode/configure-sec.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#5199 USHIFT-5907: Add MicroShift version to artifacts
  scripts/ci-ai-model-serving/setup/01-microshift.sh
  scripts/ci-nvidia-device-plugin/setup/01-microshift.sh
Labels: lgtm, approved, jira/valid-reference

#5203 NO-ISSUE: kindnet: Add plugin dir for crio config
  packaging/crio.conf.d/13-microshift-kindnet.conf
Labels: lgtm, approved, jira/valid-reference

#5162 USHIFT-5894: Add ostree and bootc images based on brew RPMs to cache
  test/bin/build_images.sh
  test/bin/build_rpms.sh
  test/bin/common_versions.sh
  test/bin/pyutils/build_bootc_images.py
  test/image-blueprints-bootc/layer1-base/group2/rhel96-bootc-brew-ec-with-optional.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel96-bootc-brew-nightly-with-optional.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel96-bootc-brew-rc-with-optional.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel96-bootc-brew-y0-with-optional.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel96-bootc-brew-y1-with-optional.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel96-bootc-brew-y2-with-optional.containerfile
  test/image-blueprints/layer1-base/group2/rhel94-brew-y2-with-optionals.toml
  test/image-blueprints/layer1-base/group3/rhel96-brew-y1-with-optionals.toml
  test/image-blueprints/layer1-base/group4/rhel96-brew-ec-with-optionals.toml
  test/image-blueprints/layer1-base/group4/rhel96-brew-nightly-with-optionals.toml
  test/image-blueprints/layer1-base/group4/rhel96-brew-rc-with-optionals.toml
  test/image-blueprints/layer1-base/group4/rhel96-brew-y0-with-optionals.toml
  test/package-sources/microshift-brew.toml
Labels: lgtm, approved, jira/valid-reference

#5217 NO-ISSUE: rebase-release-4.19-4.19.0-0.nightly-2025-07-16-160211_amd64-2025-07-16_arm64-2025-07-16
  Makefile.version.aarch64.var
  Makefile.version.x86_64.var
  assets/components/multus/release-multus-aarch64.json
  assets/components/multus/release-multus-x86_64.json
  assets/optional/kube-proxy/release-kube-proxy-aarch64.json
  assets/optional/kube-proxy/release-kube-proxy-x86_64.json
  assets/optional/operator-lifecycle-manager/kustomization.aarch64.yaml
  assets/optional/operator-lifecycle-manager/kustomization.x86_64.yaml
  assets/optional/operator-lifecycle-manager/release-olm-aarch64.json
  assets/optional/operator-lifecycle-manager/release-olm-x86_64.json
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  pkg/cmd/init.go
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/commits.txt
  scripts/auto-rebase/last_rebase.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#5215 USHIFT-5904: Change USBID to string for easier usage and (de)serialization
  cmd/generate-config/config/config-openapi-spec.json
  docs/user/howto_config.md
  packaging/microshift/config.yaml
  pkg/config/gdp.go
  pkg/config/gdp_test.go
Labels: lgtm, approved, jira/valid-reference

#5153 USHIFT-5896: Add missing rpms for optional ostree and bootc images
  scripts/verify/verify-containers.sh
  test/bin/common.sh
  test/image-blueprints-bootc/layer1-base/group2/rhel94-bootc-brew-y2-with-optional.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel94-bootc-yminus2.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel96-bootc-brew-ec-with-optional.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel96-bootc-brew-nightly-with-optional.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel96-bootc-brew-rc-with-optional.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel96-bootc-brew-y0-with-optional.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel96-bootc-brew-y1-with-optional.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel96-bootc-brew.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel96-bootc-crel-isolated.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel96-bootc-crel-optionals.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel96-bootc-crel.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel96-bootc-prel.containerfile
  test/image-blueprints-bootc/layer2-presubmit/group1/cos9-bootc-source.containerfile
  test/image-blueprints-bootc/layer2-presubmit/group1/rhel96-bootc-source-base.containerfile
  test/image-blueprints-bootc/layer2-presubmit/group1/rhel96-bootc-source.containerfile
  test/image-blueprints-bootc/layer2-presubmit/group2/rhel96-bootc-source-fake-next-minor.containerfile
  test/image-blueprints-bootc/layer2-presubmit/group2/rhel96-bootc-source-optionals.containerfile
  test/image-blueprints-bootc/layer3-periodic/group1/rhel96-bootc-source-ai-model-serving.containerfile
  test/image-blueprints-bootc/layer3-periodic/group3/cos9-bootc-source-kindnet.containerfile
  test/image-blueprints-bootc/layer3-periodic/group3/cos9-bootc-source-optionals.containerfile
  test/image-blueprints/layer1-base/group2/rhel94-brew-y2-with-optionals.toml
  test/image-blueprints/layer1-base/group2/rhel94-microshift-yminus2.toml
  test/image-blueprints/layer1-base/group3/rhel96-brew-y1-with-optionals.toml
  test/image-blueprints/layer1-base/group3/rhel96-microshift-previous-minor.toml
  test/image-blueprints/layer1-base/group4/rhel96-brew-ec-with-optionals.toml
  test/image-blueprints/layer1-base/group4/rhel96-brew-nightly-with-optionals.toml
  test/image-blueprints/layer1-base/group4/rhel96-brew-rc-with-optionals.toml
  test/image-blueprints/layer1-base/group4/rhel96-brew-y0-with-optionals.toml
  test/image-blueprints/layer1-base/group4/rhel96-crel-with-optionals.toml
  test/image-blueprints/layer1-base/group4/rhel96-crel.toml
  test/image-blueprints/layer2-presubmit/group1/rhel96-source-base.toml
  test/image-blueprints/layer2-presubmit/group1/rhel96-source-tuned.toml
  test/image-blueprints/layer2-presubmit/group1/rhel96-source-with-optionals.toml
  test/image-blueprints/layer2-presubmit/group1/rhel96-source.toml
  test/image-blueprints/layer3-periodic/group1/rhel96-source-isolated.toml
  test/suites/standard2/configuration.robot
Labels: lgtm, approved, jira/valid-reference

#5041 USHIFT-5563: introduce cert-manager operator manifests
  assets/optional/cert-manager/crd/bases/certificaterequests.cert-manager.io-crd.yaml
  assets/optional/cert-manager/crd/bases/certificates.cert-manager.io-crd.yaml
  assets/optional/cert-manager/crd/bases/challenges.acme.cert-manager.io-crd.yaml
  assets/optional/cert-manager/crd/bases/clusterissuers.cert-manager.io-crd.yaml
  assets/optional/cert-manager/crd/bases/config.openshift.io_certmanagers.yaml
  assets/optional/cert-manager/crd/bases/issuers.cert-manager.io-crd.yaml
  assets/optional/cert-manager/crd/bases/operator.openshift.io_certmanagers.yaml
  assets/optional/cert-manager/crd/bases/operator.openshift.io_istiocsrs.yaml
  assets/optional/cert-manager/crd/bases/orders.acme.cert-manager.io-crd.yaml
  assets/optional/cert-manager/crd/kustomization.yaml
  assets/optional/cert-manager/crd/kustomizeconfig.yaml
  assets/optional/cert-manager/crd/patches/cainjection_in_certmanagers.yaml
  assets/optional/cert-manager/crd/patches/webhook_in_certmanagers.yaml
  assets/optional/cert-manager/kustomization.yaml
  assets/optional/cert-manager/manager/kustomization.yaml
  assets/optional/cert-manager/manager/manager.yaml
  assets/optional/cert-manager/rbac/auth_proxy_client_clusterrole.yaml
  assets/optional/cert-manager/rbac/auth_proxy_role.yaml
  assets/optional/cert-manager/rbac/auth_proxy_role_binding.yaml
  assets/optional/cert-manager/rbac/auth_proxy_service.yaml
  assets/optional/cert-manager/rbac/certmanager_editor_role.yaml
  assets/optional/cert-manager/rbac/certmanager_viewer_role.yaml
  assets/optional/cert-manager/rbac/kustomization.yaml
  assets/optional/cert-manager/rbac/leader_election_role.yaml
  assets/optional/cert-manager/rbac/leader_election_role_binding.yaml
  assets/optional/cert-manager/rbac/role.yaml
  assets/optional/cert-manager/rbac/role_binding.yaml
  assets/optional/cert-manager/rbac/service_account.yaml
  assets/optional/cert-manager/release-cert-manager-aarch64.json
  assets/optional/cert-manager/release-cert-manager-x86_64.json
  packaging/rpm/microshift.spec
  scripts/auto-rebase/assets_cert_manager.yaml
  scripts/auto-rebase/presubmit.py
  test/bin/common.sh
  test/suites/optional/cert-manager.robot
Labels: lgtm, approved, jira/valid-reference

#5246 NO-ISSUE: improve crio crun runtime check
  test/suites/standard2/configuration.robot
Labels: lgtm, approved, jira/valid-reference

#5247 USHIFT-5921: cert-manager greenboot deployment healthcheck
  packaging/greenboot/microshift-running-check-cert-manager.sh
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#5252 NO-ISSUE: OLM & Gateway API tests: add debug log in case of failure
  test/suites/optional/gateway-api.robot
  test/suites/optional/generic-device-plugin.robot
  test/suites/optional/olm.robot
Labels: lgtm, approved, jira/valid-reference

#5236 [release-4.19] USHIFT-5915: Automate kubelet version update for CNCF
  scripts/auto-rebase/rebase.sh
  scripts/multinode/configure-sec.sh
Labels: lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#5245 USHIFT-5920: Optimize CRI-O dropins
  packaging/crio.conf.d/10-microshift_amd64.conf
  packaging/crio.conf.d/10-microshift_arm64.conf
  packaging/crio.conf.d/10-microshift_base.conf
  packaging/crio.conf.d/11-microshift-ovn.conf
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference
