Repository openshift/microshift, pull requests merged in 2025-01, with the labels that each got.

#4379 THEEDGE-4109: Explictly disable IPv4 in anaconda for IPv6 single stack scenarios
  test/bin/scenario.sh
  test/kickstart-templates/includes/main-network.cfg
  test/scenarios-bootc/presubmits/el95-src@ipv6.sh
  test/scenarios/presubmits/el94-src@ipv6.sh
Labels: lgtm, approved, jira/valid-reference

#4339 USHIFT-5202: Add elapsed timestamps for python shell commands
  test/bin/pyutils/build_bootc_images.py
  test/bin/pyutils/common.py
Labels: lgtm, approved, jira/valid-reference

#4397 USHIFT-5272: Reorganize test/assets directory into sub-folders
  test/assets/hello/hello-microshift-ingress.yaml
  test/assets/hello/hello-microshift-service-ipv6.yaml
  test/assets/hello/hello-microshift-service.yaml
  test/assets/hello/hello-microshift.yaml
  test/assets/network/dual-stack-network.xml
  test/assets/network/ipv6-network.xml
  test/assets/network/isolated-lb-service.yaml
  test/assets/network/isolated-network.xml
  test/assets/network/multus-network.xml
  test/assets/storage/lvmd.yaml
  test/assets/storage/snapshot.yaml
  test/assets/storage/storage-class-thin.yaml
  test/assets/storage/volume-snapshot-class.yaml
  test/assets/topolvm-to-lvms-diff.yaml
  test/bin/manage_hypervisor_config.sh
  test/resources/microshift-config.resource
  test/resources/microshift-network.resource
  test/suites/ipv6/dualstack.robot
  test/suites/network/isolated-network.robot
  test/suites/network/offline.robot
  test/suites/standard1/networking-smoke.robot
  test/suites/storage/snapshot.robot
Labels: lgtm, approved, jira/valid-reference

#4402 OCPBUGS-44695: Port mirror registry to use Quay
  docs/contributor/howto_quay_build.md
  scripts/devenv-builder/configure-composer.sh
  test/assets/network/isolated-netfilter.xml
  test/assets/network/isolated-network.xml
  test/assets/quay/config.yaml.template
  test/assets/quay/user_dump.sql.template
  test/bin/common.sh
  test/bin/manage_hypervisor_config.sh
  test/bin/manage_webserver.sh
  test/bin/mirror_registry.sh
  test/bin/pyutils/build_bootc_images.py
  test/bin/pyutils/common.py
  test/bin/scenario.sh
  test/kickstart-templates/includes/post-containers.cfg
  test/kickstart-templates/kickstart-bootc-isolated.ks.template
  test/scenarios-bootc/periodics/cos9-src@isolated-net.sh
  test/scenarios-bootc/periodics/el95-src@isolated-net.sh
  test/scenarios-bootc/presubmits/el95-src@ipv6.sh
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4220 USHIFT-4277: Small fixes including update for beta mirror changes
  ansible/roles/add-kubelet-logging/tasks/main.yml
  ansible/roles/create-service-account/tasks/main.yml
  ansible/roles/create-vm/defaults/main.yml
  ansible/roles/install-logging-exporters/defaults/main.yml
  ansible/roles/install-microshift/defaults/main.yml
  ansible/roles/install-microshift/files/01-crio-metrics.conf
  ansible/roles/manage-repos/defaults/main.yml
  ansible/roles/manage-repos/tasks/create-mirrors.yaml
  ansible/roles/manage-repos/tasks/main.yml
  ansible/roles/manage-repos/templates/ocpbeta.repo.j2
  ansible/roles/microshift-start/files/ready.sh
  ansible/roles/microshift-start/tasks/main.yml
Labels: lgtm, approved, jira/valid-reference

#4388 NO-ISSUE: okd: Add step to embed all component images to final image
  okd/src/README.md
  okd/src/microshift-okd-multi-build.Containerfile
Labels: lgtm, approved, jira/valid-reference

#4414 NO-ISSUE: Fix hadolint errors in OKD container file
  okd/src/microshift-okd-multi-build.Containerfile
Labels: lgtm, approved, jira/valid-reference

#4403 USHIFT-5280: microshift healthcheck - include timeout duration in the logs
  pkg/healthcheck/service.go
  pkg/healthcheck/workloads.go
Labels: lgtm, approved, jira/valid-reference

#4400 NO-ISSUE: update TraceAll loglevel to 10
  pkg/config/debugging.go
  pkg/config/debugging_test.go
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#4413 OCPBUGS-44695: Optimize Quay configuration procedure
  scripts/devenv-builder/cleanup-composer.sh
  test/assets/quay/config.yaml.template
  test/assets/quay/user_dump.sql.template
  test/bin/mirror_registry.sh
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4387 USHIFT-5286: Update image mode document with bootc image builder (BIB)
  docs/contributor/image_mode.md
Labels: lgtm, approved, jira/valid-reference

#4435 NO-ISSUE: Rebase 4.15 + increase healthcheck timeout to 600s
  Makefile.version.aarch64.var
  Makefile.version.x86_64.var
  assets/optional/operator-lifecycle-manager/kustomization.aarch64.yaml
  assets/optional/operator-lifecycle-manager/kustomization.x86_64.yaml
  assets/optional/operator-lifecycle-manager/release-olm-aarch64.json
  assets/optional/operator-lifecycle-manager/release-olm-x86_64.json
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  docs/contributor/greenboot.md
  packaging/greenboot/functions.sh
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/commits.txt
  scripts/auto-rebase/last_rebase.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4426 OCPBUGS-44695: Add signature copy and verification support when working with local Quay registry
  test/assets/kustomizations/base/pod-base.yaml
  test/assets/reboot/pod-with-pvc.yaml
  test/bin/mirror_registry.sh
  test/bin/pyutils/build_bootc_images.py
  test/bin/scenario.sh
  test/kickstart-templates/includes/post-containers-sigstore.cfg
  test/kickstart-templates/includes/post-containers.cfg
  test/kickstart-templates/kickstart-bootc.ks.template
  test/kickstart-templates/kickstart-centos.ks.template
  test/kickstart-templates/kickstart-liveimg.ks.template
  test/kickstart-templates/kickstart.ks.template
  test/scenarios-bootc/periodics/cos9-src@optional.sh
  test/scenarios-bootc/periodics/el94-prel@el95-crel@upgrade-ok.sh
  test/scenarios-bootc/periodics/el94-prel@el95-src@upgrade-fails-and-rolls-back.sh
  test/scenarios-bootc/periodics/el94-prel@el95-src@upgrade-ostree2bootc-ok.sh
  test/scenarios-bootc/periodics/el94-yminus2@el95-src@upgrade-ostree2bootc-ok.sh
  test/scenarios-bootc/periodics/el95-crel@el95-src@optional-upgrade.sh
  test/scenarios-bootc/periodics/el95-crel@el95-src@upgrade-fails.sh
  test/scenarios-bootc/periodics/el95-src@upgrade-fails-cannot-backup.sh
  test/scenarios-bootc/presubmits/el94-prel@el95-src@upgrade-ok.sh
  test/scenarios-bootc/presubmits/el94-yminus2@el95-src@upgrade-ok.sh
  test/scenarios-bootc/presubmits/el95-base@el95-src@upgrade-ok.sh
  test/scenarios-bootc/presubmits/el95-crel@el95-src@upgrade-ok.sh
  test/scenarios-bootc/presubmits/el95-src@downgrade-block.sh
  test/scenarios-bootc/presubmits/el95-src@optional.sh
  test/scenarios-bootc/presubmits/el95-src@upgrade-fails-on-1st-boot-but-recovers-on-2nd.sh
  test/scenarios-bootc/presubmits/el95-src@upgrade-fails.sh
  test/scenarios/periodics/el94-src@optional.sh
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4430 [release-4.18] OCPBUGS-48577: Enable sigstore-based verification in MicroShift CI
  docs/contributor/howto_quay_build.md
  scripts/devenv-builder/cleanup-composer.sh
  scripts/devenv-builder/configure-composer.sh
  test/assets/isolated-netfilter.xml
  test/assets/isolated-network.xml
  test/assets/kustomizations/base/pod-base.yaml
  test/assets/quay/config.yaml.template
  test/assets/reboot/pod-with-pvc.yaml
  test/bin/common.sh
  test/bin/manage_hypervisor_config.sh
  test/bin/manage_webserver.sh
  test/bin/mirror_registry.sh
  test/bin/pyutils/build_bootc_images.py
  test/bin/pyutils/common.py
  test/bin/scenario.sh
  test/kickstart-templates/includes/post-containers-sigstore.cfg
  test/kickstart-templates/includes/post-containers.cfg
  test/kickstart-templates/kickstart-bootc-isolated.ks.template
  test/kickstart-templates/kickstart-bootc.ks.template
  test/kickstart-templates/kickstart-centos.ks.template
  test/kickstart-templates/kickstart-liveimg.ks.template
  test/kickstart-templates/kickstart.ks.template
  test/scenarios-bootc/periodics/cos9-src@isolated-net.sh
  test/scenarios-bootc/periodics/el94-crel@el94-src@optional-upgrade.sh
  test/scenarios-bootc/periodics/el94-crel@el94-src@upgrade-fails.sh
  test/scenarios-bootc/periodics/el94-prel@el94-crel@upgrade-ok.sh
  test/scenarios-bootc/periodics/el94-prel@el94-src@upgrade-fails-and-rolls-back.sh
  test/scenarios-bootc/periodics/el94-prel@el94-src@upgrade-ostree2bootc-ok.sh
  test/scenarios-bootc/periodics/el94-src@isolated-net.sh
  test/scenarios-bootc/periodics/el94-src@upgrade-fails-cannot-backup.sh
  test/scenarios-bootc/periodics/el94-yminus2@el94-src@upgrade-ostree2bootc-ok.sh
  test/scenarios-bootc/presubmits/cos9-src@optional.sh
  test/scenarios-bootc/presubmits/el94-base@el94-src@upgrade-ok.sh
  test/scenarios-bootc/presubmits/el94-crel@el94-src@upgrade-ok.sh
  test/scenarios-bootc/presubmits/el94-prel@el94-src@upgrade-ok.sh
  test/scenarios-bootc/presubmits/el94-src@downgrade-block.sh
  test/scenarios-bootc/presubmits/el94-src@ipv6.sh
  test/scenarios-bootc/presubmits/el94-src@optional.sh
  test/scenarios-bootc/presubmits/el94-src@upgrade-fails-on-1st-boot-but-recovers-on-2nd.sh
  test/scenarios-bootc/presubmits/el94-src@upgrade-fails.sh
  test/scenarios-bootc/presubmits/el94-yminus2@el94-src@upgrade-ok.sh
  test/scenarios/periodics/el94-src@optional.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4437 USHIFT-4288: Update greenboot.mds with healthcheck
  docs/config/busybox_running_check.sh
  docs/contributor/greenboot.md
  docs/user/greenboot.md
Labels: lgtm, approved, jira/valid-reference

#4425 USHIFT-4926: Gantt chart generator script for MicroShift startup data
  scripts/startup-graph/graph_gen.py
  scripts/startup-graph/requirements.txt
  scripts/startup-graph/startup_graph.sh
Labels: lgtm, approved, jira/valid-reference

#4427 OCPBUGS-48110: Update router cluster roles
  assets/components/openshift-router/cluster-role-aggregate-admin-route.yaml
  assets/components/openshift-router/cluster-role-aggregate-edit-route.yaml
  assets/components/openshift-router/cluster-role-system-router.yaml
  pkg/components/controllers.go
  scripts/auto-rebase/assets.yaml
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#4445 [release-4.18] USHIFT-5294: Disable image sigstore verification until a solution for rebase is found
  test/bin/scenario.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4446 USHIFT-5295: Add trace log when service terminated abruptly
  pkg/servicemanager/manager.go
Labels: lgtm, approved, jira/valid-reference

#4315 OCPBUGS-38468: use default route mtu
  pkg/components/networking.go
  pkg/config/ovn/ovn.go
  pkg/config/ovn/ovn_test.go
  pkg/util/net.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4436 [release-4.18] USHIFT-5291: Remove CSI webhook due to deprecation
  assets/components/csi-snapshot-controller/webhook_clusterrole.yaml
  assets/components/csi-snapshot-controller/webhook_clusterrolebinding.yaml
  assets/components/csi-snapshot-controller/webhook_config.yaml
  assets/components/csi-snapshot-controller/webhook_deployment.yaml
  assets/components/csi-snapshot-controller/webhook_service.yaml
  assets/components/csi-snapshot-controller/webhook_serviceaccount.yaml
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  cmd/generate-config/config/config-openapi-spec.json
  docs/user/howto_config.md
  etcd/vendor/github.com/openshift/microshift/pkg/config/storage.go
  okd/src/README.md
  packaging/greenboot/microshift-running-check.sh
  packaging/microshift/config.yaml
  pkg/assets/scheme.go
  pkg/components/csi-snapshot-controller.go
  pkg/config/config_test.go
  pkg/config/storage.go
  pkg/config/storage_test.go
  scripts/auto-rebase/assets.yaml
  scripts/auto-rebase/rebase.sh
  test/assets/csi-webhook-deletion-diff.yaml
  test/suites/standard1/configuration.robot
  test/suites/upgrade/upgrade-successful.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4447 [release-4.17] OCPBUGS-48742: Raise the default greenboot timeout to 600s
  docs/contributor/greenboot.md
  packaging/greenboot/functions.sh
  test/image-blueprints/layer5-bootc/group1/cos9-bootc-source.containerfile
  test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source-ostree-parent.containerfile
  test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source.containerfile
  test/kickstart-templates/includes/post-greenboot.cfg
  test/kickstart-templates/kickstart-centos.ks.template
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4448 [release-4.16] OCPBUGS-48743: Raise the default greenboot timeout to 600s
  docs/contributor/greenboot.md
  packaging/greenboot/functions.sh
  test/kickstart-templates/includes/post-greenboot.cfg
  test/kickstart-templates/kickstart-centos.ks.template
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4441 USHIFT-5273: Start using EUS repositories in CI on EUS operating systems
  scripts/devenv-builder/cleanup-composer.sh
  scripts/devenv-builder/configure-composer.sh
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#4450 USHIFT-5226 : Delete CSI Webhook on start up
  pkg/assets/scheme.go
  pkg/components/csi-snapshot-controller.go
  test/assets/storage/csi-webhook-deletion-diff.yaml
  test/suites/upgrade/upgrade-successful.robot
Labels: lgtm, approved

#4451 OCPBUGS-48735: Fix default cipher suites when using TLS 1.2
  etcd/vendor/github.com/openshift/microshift/pkg/config/apiserver.go
  pkg/config/apiserver.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4463 [release-4.18] USHIFT-5291: Fix CNCF post CSI Webhook removal
  scripts/multinode/configure-sec.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4460 USHIFT-5296: Stabilize auto-recovery-extra test cases for QE env
  test/assets/auto-recovery/10-auto-recovery.conf
  test/assets/auto-recovery/red-script.sh
Labels: lgtm, approved, jira/valid-reference

#4439 USHIFT-5282: Fix default config + test
  cmd/generate-config/config/config-openapi-spec.json
  cmd/generate-config/parser.go
  docs/user/howto_config.md
  packaging/microshift/config.yaml
  pkg/config/ingress.go
  test/suites/standard1/hostname.robot
  test/suites/standard1/kustomize.robot
  test/suites/standard2/configuration.robot
Labels: lgtm, approved, jira/valid-reference

#4487 NO-ISSUE: Rebalance standard scenarios: move etcd to standard1 & skip default cfg test for crel
  test/scenarios-bootc/periodics/el95-crel@published-images-standard2.sh
  test/suites/standard1/etcd.robot
  test/suites/standard2/configuration.robot
Labels: lgtm, approved, jira/valid-reference

#4481 USHIFT-4726: Attempt console login in offline tests
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#4478 [release-4.18] USHIFT-5294: Enable sigstore verification for selected scenarios
  test/bin/scenario.sh
  test/scenarios-bootc/periodics/el94-crel@el94-src@optional-upgrade.sh
  test/scenarios-bootc/periodics/el94-crel@el94-src@upgrade-fails.sh
  test/scenarios-bootc/periodics/el94-crel@optional-sigstore.sh
  test/scenarios-bootc/periodics/el94-crel@published-images-standard1.sh
  test/scenarios-bootc/periodics/el94-crel@published-images-standard2.sh
  test/scenarios-bootc/periodics/el94-prel@el94-crel@upgrade-ok.sh
  test/scenarios-bootc/periodics/el94-prel@el94-src@upgrade-fails-and-rolls-back.sh
  test/scenarios-bootc/periodics/el94-prel@el94-src@upgrade-ostree2bootc-ok.sh
  test/scenarios-bootc/periodics/el94-src@upgrade-fails-cannot-backup.sh
  test/scenarios-bootc/periodics/el94-yminus2@el94-src@upgrade-ostree2bootc-ok.sh
  test/scenarios-bootc/presubmits/cos9-src@optional.sh
  test/scenarios-bootc/presubmits/el94-base@el94-src@upgrade-ok.sh
  test/scenarios-bootc/presubmits/el94-crel@el94-src@upgrade-ok.sh
  test/scenarios-bootc/presubmits/el94-prel@el94-src@upgrade-ok.sh
  test/scenarios-bootc/presubmits/el94-src@downgrade-block.sh
  test/scenarios-bootc/presubmits/el94-src@optional.sh
  test/scenarios-bootc/presubmits/el94-src@upgrade-fails-on-1st-boot-but-recovers-on-2nd.sh
  test/scenarios-bootc/presubmits/el94-src@upgrade-fails.sh
  test/scenarios-bootc/presubmits/el94-yminus2@el94-src@upgrade-ok.sh
  test/scenarios/periodics/el94-crel@optional-sigstore.sh
  test/scenarios/periodics/el94-src@optional.sh
  test/suites/standard1/containers-policy.robot
  test/suites/standard2/containers-policy.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
