Repository openshift/microshift, pull requests merged in 2025-03, with the labels that each got.

#4538 USHIFT-5381: Check microshift.service for all healthchecks
  pkg/healthcheck/healthcheck.go
  test/suites/optional/healthchecks-disabled-service.robot
Labels: lgtm, approved, jira/valid-reference

#4625 Rebase main 4.19.0 0.nightly 2025 02 28 132549 amd64 2025 02 28 arm64 2025 03 02
  Makefile.kube_git.var
  Makefile.version.aarch64.var
  Makefile.version.x86_64.var
  assets/controllers/kube-apiserver/defaultconfig.yaml
  assets/optional/multus/kustomization.x86_64.yaml
  assets/optional/multus/release-multus-aarch64.json
  assets/optional/multus/release-multus-x86_64.json
  assets/optional/operator-lifecycle-manager/kustomization.aarch64.yaml
  assets/optional/operator-lifecycle-manager/kustomization.x86_64.yaml
  assets/optional/operator-lifecycle-manager/release-olm-aarch64.json
  assets/optional/operator-lifecycle-manager/release-olm-x86_64.json
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  etcd/go.mod
  etcd/go.sum
  etcd/vendor/github.com/golang-jwt/jwt/v4/parser.go
  etcd/vendor/github.com/openshift/microshift/pkg/util/net.go
  etcd/vendor/go.etcd.io/etcd/api/v3/version/version.go
  etcd/vendor/go.etcd.io/etcd/client/v3/lease.go
  etcd/vendor/go.etcd.io/etcd/server/v3/embed/etcd.go
  etcd/vendor/go.etcd.io/etcd/server/v3/embed/serve.go
  etcd/vendor/go.etcd.io/etcd/server/v3/etcdserver/server.go
  etcd/vendor/go.etcd.io/etcd/server/v3/mvcc/key_index.go
  etcd/vendor/go.etcd.io/etcd/server/v3/mvcc/kvstore.go
  etcd/vendor/modules.txt
  go.mod
  go.sum
  packaging/crio.conf.d/10-microshift_amd64.conf
  packaging/crio.conf.d/10-microshift_arm64.conf
  scripts/auto-rebase/changelog.txt
  scripts/auto-rebase/commits.txt
  scripts/auto-rebase/last_rebase.sh
  scripts/auto-rebase/rebase.sh
  vendor/go.etcd.io/etcd/api/v3/version/version.go
  vendor/go.etcd.io/etcd/client/v3/lease.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/node/restrict_extreme_worker_latency_profile.go
  vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/node/validate_node_config.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, tide/merge-method-squash, jira/valid-bug

#4615 USHIFT-5456: add optional-skipped-rpms option to configure-vm
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#4629 [release-4.18] OCPBUGS-52206: Sort interfaces by index
  pkg/util/net.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#4626 [release-4.18] USHIFT-4902: change 4.18 repository to rhocp
  test/bin/common_versions.sh
  test/scenarios-bootc/periodics/el94-crel@published-images-standard1.sh.disabled
  test/scenarios-bootc/periodics/el94-crel@published-images-standard2.sh.disabled
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4636 NO-ISSUE: Fix typo in scenario.sh script
  test/bin/scenario.sh
Labels: lgtm, approved, jira/valid-reference

#4633 [release-4.17] USHIFT-5471: Update footperf CPU configuration
  scripts/ci-footprint-and-performance/setup/001-configure-wp-lowlat.sh
  scripts/ci-footprint-and-performance/setup/021-install-kernel-rt.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4634 USHIFT-5471: Update footperf CPU configuration
  scripts/ci-footprint-and-performance/setup/001-configure-wp-lowlat.sh
  scripts/ci-footprint-and-performance/setup/021-install-kernel-rt.sh
Labels: lgtm, approved, jira/valid-reference

#4630 [release-4.18] USHIFT-5471: Update footperf CPU configuration
  scripts/ci-footprint-and-performance/setup/001-configure-wp-lowlat.sh
  scripts/ci-footprint-and-performance/setup/021-install-kernel-rt.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4632 USHIFT-5373: Replace GenerateUniqueTempPath by Go library functions
  pkg/admin/autorecovery/state.go
  pkg/admin/data/atomic_dir_copy.go
  pkg/config/node.go
  pkg/util/util.go
Labels: lgtm, approved, jira/valid-reference

#4635 USHIFT-5375: Document embedding container images in bootc builds
  docs/config/Containerfile.bootc-embedded-rhel9
  docs/config/Containerfile.bootc-rhel9
  docs/contributor/image_mode.md
  packaging/imagemode/Containerfile.repobase
  packaging/imagemode/Containerfile.repourl
  packaging/imagemode/Containerfile.rhocp
Labels: lgtm, approved, jira/valid-reference

#4661 USHIFT-5457: Bump multinode test kubelet to 1.32.2
  scripts/multinode/configure-sec.sh
Labels: lgtm, approved, jira/valid-reference

#4614 USHIFT-5338: AI Model Serving Offline Sanity Test
  assets/optional/ai-model-serving/kserve/inferenceservice-config-microshift-patch.yaml
  assets/optional/ai-model-serving/kserve/kustomization.yaml
  test/bin/pyutils/build_bootc_images.py
  test/image-blueprints-bootc/layer2-source/group2/ai-model-serving-test-data.sh.template
  test/image-blueprints-bootc/layer2-source/group2/rhel96-bootc-source-ai-model-serving.containerfile
  test/image-blueprints-bootc/layer2-source/group3/rhel96-bootc-source-ai-model-serving.image-bootc
  test/resources/offline.resource
  test/scenarios-bootc/presubmits/el95-src@ai-model-serving.sh
  test/suites/ai-model-serving/Containerfile
  test/suites/ai-model-serving/ai-model-serving.robot
  test/suites/network/offline.robot
Labels: lgtm, approved, jira/valid-reference

#4660 USHIFT-5348: Add option to build single image in build_bootc_images.py
  test/bin/pyutils/build_bootc_images.py
Labels: lgtm, approved, jira/valid-reference

#4474 USHIFT-5344: introduce ingress security customizations
  assets/components/openshift-router/deployment.yaml
  cmd/generate-config/config/config-openapi-spec.json
  docs/user/howto_config.md
  packaging/microshift/config.yaml
  pkg/components/controllers.go
  pkg/config/config.go
  pkg/config/ingress.go
  scripts/auto-rebase/manifests_patches/010-ingress-deployment-clientCA.patch
  scripts/auto-rebase/rebase.sh
  test/suites/standard1/router.robot
Labels: lgtm, approved, jira/valid-reference

#4670 USHIFT-5489: Refactor configure-composer.sh script to be modular
  scripts/devenv-builder/configure-composer.sh
Labels: lgtm, approved, jira/valid-reference

#4659 USHIFT-5339: Test AI Model Serving with NVIDIA GPU
  scripts/ci-ai-model-serving/1-setup.sh
  scripts/ci-ai-model-serving/2-reboot.sh
  scripts/ci-ai-model-serving/3-test.sh
  scripts/ci-ai-model-serving/setup/00-debug.sh
  scripts/ci-ai-model-serving/setup/01-microshift.sh
  scripts/ci-ai-model-serving/setup/02-nvidia-driver.sh
  scripts/ci-ai-model-serving/setup/03-nvidia-container-toolkit.sh
  scripts/ci-ai-model-serving/setup/04-nvidia-device-plugin.sh
  scripts/ci-ai-model-serving/setup/05-debug.sh
  scripts/ci-ai-model-serving/tests/01-verify-nvidia-gpu.sh
  scripts/ci-ai-model-serving/tests/02-wait-for-greenboot.sh
  scripts/ci-ai-model-serving/tests/03-get-kubeconfig.sh
  scripts/ci-ai-model-serving/tests/04-verify-device-plugin.sh
  scripts/ci-ai-model-serving/tests/05-test-cuda-vector-add.sh
  scripts/ci-ai-model-serving/tests/06-test-vllm.sh
  scripts/ci-ai-model-serving/tests/vllm-image/Containerfile
  scripts/ci-ai-model-serving/tests/vllm-image/download_model.py
  scripts/devenv-builder/configure-vm.sh
Labels: lgtm, approved, jira/valid-reference

#4672 USHIFT-5459: Ensure same kubelet version across nodes in cncf tests
  scripts/multinode/configure-sec.sh
Labels: lgtm, approved, jira/valid-reference

#4671 OCPBUGS-52420: Bootc images to use the /usr read-only storage for preloaded container images
  docs/config/Containerfile.bootc-embedded-rhel9
  docs/config/Containerfile.bootc-rhel9
  test/image-blueprints-bootc/layer2-source/group2/microshift-imagestore-config.service.template
  test/image-blueprints-bootc/layer2-source/group2/microshift-imagestore-config.sh.template
  test/image-blueprints-bootc/layer2-source/group2/rhel96-bootc-source-ai-model-serving.containerfile
  test/image-blueprints-bootc/layer2-source/group2/rhel96-bootc-source-isolated.containerfile
  test/image-blueprints-bootc/layer2-source/group3/cos9-bootc-source-isolated.containerfile
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4677 [release-4.18] USHIFT-5458: Sync kubelet version with apiserver for cncf conformance
  scripts/multinode/configure-sec.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4674 USHIFT-5406: Optimize mirror images operation for repetitive runs
  scripts/mirror-images.sh
  test/bin/mirror_registry.sh
Labels: lgtm, approved, jira/valid-reference

#4687 USHIFT-5339: Don't match ARM64 when instance type starts with 'g'
  scripts/aws/manage_aws_stack.sh
Labels: lgtm, approved, jira/valid-reference

#4690 USHIFT-5491: Temporarily disable router security options tests
  test/suites/standard1/router.robot
Labels: lgtm, approved, jira/valid-reference

#4663 USHIFT-5298: Metrics collection
  pkg/controllers/telemetry.go
  pkg/node/kubelet.go
  pkg/telemetry/gather.go
  pkg/telemetry/telemetry.go
  test/kickstart-templates/includes/post-containers.cfg
Labels: lgtm, approved, jira/valid-reference

#4691 [release-4.18] OCPBUGS-53026: Fix default config
  cmd/generate-config/config/config-openapi-spec.json
  cmd/generate-config/parser.go
  docs/user/howto_config.md
  packaging/microshift/config.yaml
  pkg/config/ingress.go
  test/suites/standard1/hostname.robot
  test/suites/standard1/kustomize.robot
  test/suites/standard2/configuration.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4676 USHIFT-2911: Enable SELinux tests in standard suite for bootc images
  test/scenarios-bootc/periodics/el96-crel@brew-standard1.sh
  test/scenarios-bootc/periodics/el96-crel@published-images-standard1.sh
  test/scenarios-bootc/periodics/el96-crel@published-images-standard2.sh
  test/scenarios-bootc/presubmits/el96-src@standard-suite1.sh
  test/scenarios/periodics/el94-src@rpm-standard1.sh
Labels: lgtm, approved, jira/valid-reference

#4688 USHIFT-5492: Auto-detect disconnected env to disable telemetry
  pkg/controllers/telemetry.go
  pkg/util/net.go
Labels: lgtm, approved, jira/valid-reference

#4692 USHIFT-5108: Update cri-o to 1.32 in rpm spec
  packaging/rpm/microshift.spec
Labels: lgtm, approved, jira/valid-reference

#4694 USHIFT-3132: Remove the container layer workaround when building RHEL ISO
  test/image-blueprints-bootc/layer1-base/group1/rhel94-bootc-base.containerfile
  test/image-blueprints-bootc/layer1-base/group1/rhel96-bootc-base.containerfile
  test/image-blueprints-bootc/layer1-base/group2/rhel94-bootc.image-bootc
  test/image-blueprints-bootc/layer1-base/group2/rhel96-bootc.image-bootc
Labels: lgtm, approved, jira/valid-reference

#4678 USHIFT-5472: Bootc image embedding using release info RPMs
  test/bin/pyutils/build_bootc_images.py
  test/image-blueprints-bootc/layer2-source/group2/rhel96-bootc-source-ai-model-serving.containerfile
  test/image-blueprints-bootc/layer2-source/group2/rhel96-bootc-source-isolated.containerfile
  test/image-blueprints-bootc/layer2-source/group3/cos9-bootc-source-isolated.containerfile
Labels: lgtm, approved, jira/valid-reference

#4686 USHIFT-5371: Enable nightly rebase for RHOAI
  assets/optional/ai-model-serving/kserve/configmap/inferenceservice.yaml
  assets/optional/ai-model-serving/kserve/crd/full/serving.kserve.io_inferencegraphs.yaml
  assets/optional/ai-model-serving/kserve/crd/full/serving.kserve.io_inferenceservices.yaml
  assets/optional/ai-model-serving/kserve/default/manager_auth_proxy_patch.yaml
  assets/optional/ai-model-serving/kserve/inferenceservice-config-microshift-patch.yaml
  assets/optional/ai-model-serving/kserve/manager/manager.yaml
  assets/optional/ai-model-serving/kserve/overlays/odh/inferenceservice-config-patch.yaml
  assets/optional/ai-model-serving/kserve/overlays/odh/kustomization.yaml
  assets/optional/ai-model-serving/kserve/overlays/odh/params.env
  assets/optional/ai-model-serving/kserve/rbac/role.yaml
  assets/optional/ai-model-serving/kserve/webhook/manifests.yaml
  assets/optional/ai-model-serving/release-ai-model-serving-x86_64.json
  assets/optional/ai-model-serving/runtimes/kustomization.x86_64.yaml
  scripts/auto-rebase/assets_ai_model_serving.yaml
  scripts/auto-rebase/last_rebase_ai_model_serving.sh
  scripts/auto-rebase/rebase.py
  scripts/auto-rebase/rebase_ai_model_serving.sh
  scripts/auto-rebase/rebase_job_entrypoint.sh
Labels: lgtm, approved, jira/valid-reference

#4699 [release-4.18] USHIFT-4882: Re-enable standard tests for bootc images published in the public registry
  test/scenarios-bootc/periodics/el94-crel@published-images-standard1.sh
  test/scenarios-bootc/periodics/el94-crel@published-images-standard2.sh
  test/suites/standard2/configuration.robot
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4712 USHIFT-5530: Temporarily disable el94-to-el96 bootc upgrade tests
  test/scenarios-bootc/periodics/el94-prel@el96-crel@upgrade-ok.sh.disabled
  test/scenarios-bootc/periodics/el94-prel@el96-src@upgrade-fails-and-rolls-back.sh.disabled
  test/scenarios-bootc/periodics/el94-prel@el96-src@upgrade-ostree2bootc-ok.sh.disabled
  test/scenarios-bootc/periodics/el94-yminus2@el96-src@upgrade-ostree2bootc-ok.sh.disabled
  test/scenarios-bootc/presubmits/el94-prel@el96-src@upgrade-ok.sh.disabled
  test/scenarios-bootc/presubmits/el94-yminus2@el96-src@upgrade-ok.sh.disabled
Labels: lgtm, approved, jira/valid-reference

#4711 USHIFT-5475: Add multi-arch build functionality to CI brew image
  packaging/images/Makefile
  packaging/images/README.md
Labels: lgtm, approved, jira/valid-reference

#4703 USHIFT-4882: Bootc published image standard tests can now use public registry when available
  test/scenarios-bootc/periodics/el96-crel@published-images-standard1.sh
  test/scenarios-bootc/periodics/el96-crel@published-images-standard2.sh
Labels: lgtm, approved, jira/valid-reference

#4710 OCPBUGS-51329: Use specific arch manifest instead of manifest list for LVMS Operator
  assets/components/lvms/lvms-operator_apps_v1_deployment.yaml
  assets/release/release-aarch64.json
  assets/release/release-x86_64.json
  scripts/auto-rebase/rebase-lvms.sh
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#4715 NO-ISSUE: Update flannel and kube-proxy images to latest one
  assets/optional/flannel/kustomization.aarch64.yaml
  assets/optional/flannel/kustomization.x86_64.yaml
  assets/optional/flannel/release-flannel-aarch64.json
  assets/optional/flannel/release-flannel-x86_64.json
  assets/optional/kube-proxy/kustomization.aarch64.yaml
  assets/optional/kube-proxy/kustomization.x86_64.yaml
  assets/optional/kube-proxy/release-kube-proxy-aarch64.json
  assets/optional/kube-proxy/release-kube-proxy-x86_64.json
Labels: lgtm, approved, jira/valid-reference

#4662 USHIFT-5079: Add online AI Model Serving RF test
  scripts/devenv-builder/configure-composer.sh
  test/assets/ai-model-serving/ovms-query-preparation.sh
  test/assets/ai-model-serving/ovms-resources.yaml
  test/image-blueprints-bootc/layer2-source/group2/rhel96-bootc-source-optionals.containerfile
  test/image-blueprints-bootc/layer2-source/group3/rhel96-bootc-source-ai-model-serving.image-bootc
  test/resources/common.resource
  test/resources/kubeconfig.resource
  test/resources/microshift-host.resource
  test/scenarios-bootc/presubmits/el96-src@ai-model-serving-offline.sh
  test/scenarios-bootc/presubmits/el96-src@ai-model-serving-online.sh
  test/suites/ai-model-serving/ai-model-serving-offline.robot
  test/suites/ai-model-serving/ai-model-serving-online.robot
Labels: lgtm, approved, jira/valid-reference

#4713 USHIFT-5399: Add RF tests for telemetry
  pkg/controllers/telemetry.go
  test/suites/standard2/telemetry.robot
Labels: lgtm, approved, jira/valid-reference

#4673 USHIFT-5473: Doc for AI Model Serving
  docs/user/ai_model_serving.md
Labels: lgtm, approved, jira/valid-reference

#4717 NO-ISSUE: Temporary skip for telemetry tests
  test/suites/standard2/telemetry.robot
Labels: lgtm, approved, jira/valid-reference

#4716 USHIFT-4902: Update common_versions.sh
  test/bin/common_versions.sh
Labels: lgtm, approved, jira/valid-reference

#4679 USHIFT-5490: Implement bootc embedded image upgrade workaround and tests
  docs/config/Containerfile.bootc-embedded-rhel9
  docs/config/Containerfile.bootc-rhel9
  docs/contributor/image_mode.md
  test/image-blueprints-bootc/layer1-base/group2/microshift-copy-images.conf.template
  test/image-blueprints-bootc/layer1-base/group2/microshift-copy-images.sh.template
  test/image-blueprints-bootc/layer1-base/group2/rhel96-bootc-crel-isolated.containerfile
  test/image-blueprints-bootc/layer2-source/group2/rhel96-bootc-source-ai-model-serving.containerfile
  test/image-blueprints-bootc/layer2-source/group2/rhel96-bootc-source-isolated.containerfile
  test/image-blueprints-bootc/layer2-source/group3/cos9-bootc-source-isolated.containerfile
  test/scenarios-bootc/periodics/el96-crel@el96-src@upgrade-fails-isolated.sh
  test/scenarios-bootc/presubmits/el96-crel@el96-src@upgrade-ok-isolated.sh
Labels: lgtm, approved, jira/valid-reference

#4733 [release-4.15] USHIFT-3270: Increase dnf low-bitrate timeout
  test/resources/microshift-rpm.resource
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#4281 TRACING-4752: Add OpenTelemetry-Collector as optional sub-package
  assets/optional/observability/00-namespace.yaml
  assets/optional/observability/01-service-account.yaml
  assets/optional/observability/02-cluster-role.yaml
  assets/optional/observability/03-cluster-role-binding.yaml
  assets/optional/observability/kustomization.yaml
  etcd/vendor/github.com/openshift/microshift/pkg/config/kubeconfig.go
  packaging/observability/90-enable-microshift-observability.preset
  packaging/observability/microshift-observability.service
  packaging/observability/opentelemetry-collector.yaml
  packaging/rpm/microshift.spec
  pkg/cmd/init.go
  pkg/config/kubeconfig.go
  scripts/auto-rebase/assets.yaml
  test/image-blueprints-bootc/layer2-source/group2/rhel96-bootc-source-optionals.containerfile
  test/image-blueprints-bootc/layer2-source/group3/cos9-bootc-source-optionals.containerfile
  test/resources/journalctl.py
  test/suites/optional/observability.robot
Labels: lgtm, approved, jira/valid-reference
